export declare enum EListItemCommentsStateTypes {
    "SET_ERROR_INFO" = "SET_ERROR_INFO",
    "SET_LIST_ITEM_COMMENTS" = "SET_LIST_ITEM_COMMENTS",
    "SET_IS_LOADING" = "SET_IS_LOADING",
    "SET_IS_SCROLLING" = "SET_IS_SCROLLING",
    "SET_DATA_PAGE_INFO" = "SET_DATA_PAGE_INFO",
    "SET_COMMENT_ACTION" = "SET_COMMENT_ACTION",
    "SET_ADD_COMMENT" = "SET_ADD_COMMENT",
    "SET_SELECTED_COMMENT" = "SET_SELECTED_COMMENT"
}
//# sourceMappingURL=EListItemCommentsStateTypes.d.ts.map