declare var define: any;

define([], () => {
  return {
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  "Save": "Spare",
  "Cancel": "Aflyse",
  "SiteBreadcrumbLabel": "Hjemmeside breadcrumb",
  "ListViewGroupEmptyLabel": "Tom",
  "WebPartTitlePlaceholder": "Titel på webdel",
  "WebPartTitleLabel": "Tilføje en titel",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "I et par sekunder",
    "L_RelativeDateTime_AFewSeconds": "Et par sekunder siden",
    "L_RelativeDateTime_AboutAMinuteFuture": "I ca. et minut",
    "L_RelativeDateTime_AboutAMinute": "Omkring et minut siden",
    "L_RelativeDateTime_XMinutesFuture": "I {0} minut||I {0} minutter",
    "L_RelativeDateTime_XMinutes": "{0} minut siden||{0} minutter siden",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "I omkring en time",
    "L_RelativeDateTime_AboutAnHour": "For en time siden",
    "L_RelativeDateTime_Tomorrow": "Morgen",
    "L_RelativeDateTime_Yesterday": "Går",
    "L_RelativeDateTime_TomorrowAndTime": "I morgen på {0}",
    "L_RelativeDateTime_YesterdayAndTime": "I går på {0}",
    "L_RelativeDateTime_XHoursFuture": "I {0} time||I {0} timer",
    "L_RelativeDateTime_XHours": "{0} time siden||{0} timer siden",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} på {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} dag fra nu||{0} dage fra nu",
    "L_RelativeDateTime_XDays": "{0} dag siden||{0} dage siden",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Dag"
  },
  "SendEmailTo": "Send en mail til {0}",
  "StartChatWith": "Start en chat med {0}",
  "Contact": "Kontakt",
  "UpdateProfile": "Opdater din profil",
  "TaxonomyPickerNoTerms": "Ordsæt indeholder ingen betingelser",
  "TaxonomyPickerExpandTitle": "Udvid Dette ordsæt",
  "TaxonomyPickerMenuTermSet": "Menu for ordsæt",
  "TaxonomyPickerInLabel": "I",
  "TaxonomyPickerTermSetLabel": "Ordsæt",
  "TaxonomyPickerTermsNotFound": "De næste markerede ord blev ikke fundet i ordbanken: {0}",
  "TaxonomyPickerInvalidTerms": "Ret ugyldige ord: {0}",
  "peoplePickerComponentTooltipMessage": "Folk Picker",
  "peoplePickerComponentErrorMessage": "Påkrævet felt",
  "peoplePickerSuggestionsHeaderText": "Foreslåede personer",
  "peoplePickerLoadingText": "Indlæsning",
  "PeoplePickerSearchText": "Henter brugere",
  "PeoplePickerGroupNotFound": "Gruppen blev ikke fundet.",
  "genericNoResultsFoundText": "Der blev ikke fundet nogen resultater",
  "ListItemPickerSelectValue": "Vælg værdi",
  "ListItemAttachmentsActionDeleteIconTitle": "Slette",
  "ListItemAttachmentsactionDeleteTitle": "Slette",
  "ListItemAttachmentsfileDeletedMsg": "Fil, {0} slettet",
  "ListItemAttachmentsfileDeleteError": "Fejl ved sletning af fil: {0}, årsag {1}",
  "ListItemAttachmentserrorLoadAttachments": "Fejl ved vedhæftet fil til indlæsning af listeelement, årsag: {0}",
  "ListItemAttachmentsconfirmDelete": "Er du sikker på, at du vil sende den vedhæftede fil {0} til webstedets papirkurv?",
  "ListItemAttachmentsdialogTitle": "Vedhæftet listeelement",
  "ListItemAttachmentsdialogOKbuttonLabel": "Ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Annullere",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Slette",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Tilføj vedhæftet fil",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Tilføj vedhæftet fil",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Filen {0} ikke vedhæftet, årsag: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Tilføj vedhæftet fil",
  "ListItemAttachmentsloadingMessage": "Uploader fil...",
  "ListItemAttachmentslPlaceHolderIconText": "Vedhæftet listeelement",
  "ListItemAttachmentslPlaceHolderDescription": "Tilføj vedhæftet fil",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Tilføj",
  "mapsErrorMessage": "Der opstod en fejl under indlæsning af kortet",
  "mapsLoadingText": "Indlæsning",
  "mapsSearchButtonText": "Søg",
  "mapsTitlePrefix": "Kort over",
  "ListViewFilterLabel": "Filtrere listen",
  "HeaderNormalText": "Normal tekst",
  "HeaderH2": "Overskrift 2",
  "HeaderH3": "Overskrift 3",
  "HeaderH4": "Overskrift 4",
  "HeaderBlockQuote": "Citat",
  "AlignLeft": "Venstrejusteret",
  "AlignCenter": "Midte",
  "AlignRight": "Juster til højre",
  "AlignJustify": "Retfærdiggøre",
  "ListBullet": "Punktopstilling",
  "ListNumbered": "Opstilling",
  "StyleTitle": "Stil",
  "BoldTitle": "Fed (Ctrl + B)",
  "ItalicTitle": "Kursiv (Ctrl + I)",
  "UnderlineTitle": "Understregning (CTRL + U)",
  "AlignTitle": "Justere",
  "ListTitle": "Liste",
  "LinkTitle": "Hyperlink",
  "ImageTitle": "Billede",
  "MoreTitle": "Mere",
  "FormattingPaneTitle": "Tekstformatering",
  "CloseButton": "Tæt",
  "InsertLinkTitle": "Indsæt kæde",
  "InsertImageTitle": "Indsæt billede",
  "AddressFieldLabel": "Adresse",
  "TextToDisplayLabel": "Tekst, som skal vises",
  "SaveButtonLabel": "Gemme",
  "CancelButtonLabel": "Annullere",
  "RemoveLinkLabel": "Fjern link",
  "ParagraphSectionTitle": "Stk",
  "HyperlinkSectionTitle": "Hyperlink",
  "UndoTitle": "Fortryd (CTRL + Z)",
  "RedoTitle": "Annuller Fortryd (CTRL + Y)",
  "ClearFormattingTitle": "Ryd al formatering",
  "FontStyleTitle": "Typografi",
  "FontSizeTitle": "Skriftstørrelse",
  "StrikethroughTitle": "Gennemstregning",
  "SuperscriptTitle": "Hævet skrift",
  "SubscriptTitle": "Sænket skrift",
  "FontColorLabel": "Skriftfarve",
  "AutomaticFontColor": "Automatisk",
  "HighlightColorLabel": "Fremhæv farve",
  "NoColorHighlightColor": "Ingen farve",
  "IncreaseIndentTitle": "Forøg indrykning",
  "DecreaseIndentTitle": "Formindsk indrykning",
  "ThemeColorsGroupName": "Temafarver",
  "HighlightColorsGroupName": "Fremhæv farver",
  "StandardColorsGroupName": "Standard farver",
  "CustomColorsGroupName": "Brugerdefinerede farver",
  "ThemeColorDarker": "Temaet er mørkere",
  "ThemeColorDark": "Temaet mørk",
  "ThemeColorDarkAlt": "Tema mørk suppleant",
  "ThemeColorPrimary": "Temaet Primary",
  "ThemeColorSecondary": "Theme Secondary",
  "ThemeColorTertiary": "Neutral tertiær",
  "ThemeColorNeutralSecondary": "Neutral sekundær",
  "ThemeColorNeutralPrimaryAlt": "Neutral primær suppleant",
  "ThemeColorNeutralPrimary": "Neutral primær",
  "ThemeColorNeutralDark": "Neutral mørk",
  "HighlightColorYellow": "Gul",
  "HighlightColorGreen": "Grøn",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Blå",
  "HighlightColorRed": "Rød",
  "HighlightColorDarkblue": "Mørkeblå",
  "HighlightColorTeal": "Krikand",
  "HighlightColorDarkgreen": "Mørkegrøn",
  "HighlightColorPurple": "Lilla",
  "HighlightColorMaroon": "Maron",
  "HighlightColorGold": "Guld",
  "HighlightColorDarkgrey": "Mørkegrå",
  "HighlightColorGrey": "Grå",
  "HighlightColorBlack": "Sort",
  "StandardColorDarkred": "Mørkerød",
  "StandardColorRed": "Rød",
  "StandardColorOrange": "Appelsin",
  "StandardColorYellow": "Gul",
  "StandardColorLightgreen": "Lysegrøn",
  "StandardColorGreen": "Grøn",
  "StandardColorLightblue": "Lyseblå",
  "StandardColorBlue": "Blå",
  "StandardColorDarkblue": "Mørkeblå",
  "StandardColorPurple": "Lilla",
  "DatePickerMonthLongJanuary": "Januar",
  "DatePickerMonthShortJanuary": "Jan",
  "DatePickerMonthLongFebruary": "Februar",
  "DatePickerMonthShortFebruary": "Feb",
  "DatePickerMonthLongMarch": "Marts",
  "DatePickerMonthShortMarch": "Mar",
  "DatePickerMonthLongApril": "April",
  "DatePickerMonthShortApril": "Apr",
  "DatePickerMonthLongMay": "Maj",
  "DatePickerMonthShortMay": "Maj",
  "DatePickerMonthLongJune": "Juni",
  "DatePickerMonthShortJune": "Jun",
  "DatePickerMonthLongJuly": "Juli",
  "DatePickerMonthShortJuly": "Jul",
  "DatePickerMonthLongAugust": "August",
  "DatePickerMonthShortAugust": "Aug",
  "DatePickerMonthLongSeptember": "September",
  "DatePickerMonthShortSeptember": "Sep",
  "DatePickerMonthLongOctober": "Oktober",
  "DatePickerMonthShortOctober": "Okt",
  "DatePickerMonthLongNovember": "November",
  "DatePickerMonthShortNovember": "Nov",
  "DatePickerMonthLongDecember": "December",
  "DatePickerMonthShortDecember": "Dec",
  "DatePickerDayLongSunday": "Søndag",
  "DatePickerDayShortSunday": "Søn",
  "DatePickerDayLongMonday": "Mandag",
  "DatePickerDayShortMonday": "Man",
  "DatePickerDayLongTuesday": "Tirsdag",
  "DatePickerDayShortTuesday": "Tir",
  "DatePickerDayLongWednesday": "Onsdag",
  "DatePickerDayShortWednesday": "Ons",
  "DatePickerDayLongThursday": "Torsdag",
  "DatePickerDayShortThursday": "Tor",
  "DatePickerDayLongFriday": "Fredag",
  "DatePickerDayShortFriday": "Fre",
  "DatePickerDayLongSaturday": "Lørdag",
  "DatePickerDayShortSaturday": "Lør",
  "DatePickerGoToToday": "Gå til i dag",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Dato",
  "DateTimePickerTime": "Tid",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Forkert time værdi",
  "DateTimePickerMinuteValueInvalid": "Forkert minutværdi",
  "DateTimePickerSecondValueInvalid": "Forkert anden værdi",
  "DateTimePickerTextErrorMessage": "Angiv en gyldig dato",
  "AddFileButtonLabel": "Tilføj fil",
  "AddImageButtonLabel": "Tilføj billede",
  "AriaCellValue": "{0} kolonne, {1}",
  "FilePickerCancelButtonLabel": "Annullere",
  "CantValidateValidationMessage": "Vi kunne ikke bekræfte dette link. Kontroller linket, og prøv igen.",
  "ChangeFileLinkLabel": "Ændre fil",
  "ChangeImageLinkLabel": "Skift billede",
  "ChooseFileLinkLabel": "Vælg fil",
  "ChooseImageLinkLabel": "Vælg billede",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Du er ansvarlig for at respektere andres rettigheder, herunder ophavsret.",
  "CreativeCommonsMessage": "Disse resultater er tagget med Creative Commons-licenser. Gennemgå licenserne for at sikre, at du overholder.",
  "DateFormat": "MM/DD/ÅÅÅÅ hh: mm A",
  "DocumentLabelTemplate": "{0}, dokument, ændret {1}, redigeret af {2}, privat",
  "DocumentLibraries": "Dokumentbiblioteker",
  "EditedByNamePlate": "redigeret af ",
  "EmptyFileSize": "0 byte",
  "FilePickerHeader": "Filvælger",
  "FileSizeField": "Filstørrelse",
  "FolderAltText": "Mappe",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, mappe, ændret {1}, redigeret af {2}, {3} elementer, privat",
  "FromLinkLinkLabel": "Fra et link",
  "ImageAltText": ". {0} billede",
  "ImageAriaLabelTemplate": ". {0} billede",
  "ImageLayoutPlaceholderText": "Layout",
  "ImageSizePlaceholderText": "Billedstørrelse",
  "ItemChildCountField": "Antal underordnede elementer",
  "LayoutOptionAll": "Alle",
  "LayoutOptionSquare": "Firkant",
  "LayoutOptionTall": "Høj",
  "LayoutOptionWide": "Bred",
  "LearnMoreLink": "Lær mere.",
  "LicenseOptionAll": "Alle",
  "LicenseOptionAny": "Kun Creative Commons",
  "LicensePlaceholderText": "Licens",
  "LinkFileInstructions": "Indsætte et link til en fil i OneDrive for Business eller SharePoint Online",
  "LinkHeader": "Fra et link",
  "LinkImageInstructions": "Indsætte et link til et billede i OneDrive for Business eller SharePoint Online",
  "ListLayoutAriaLabel": "Indstillinger for visning. {0} {1}.",
  "ListLayoutCompact": "Kompakt visning",
  "ListLayoutCompactDescription": "Få vist elementer og detaljer på en kompakt liste",
  "ListLayoutList": "Listevisning",
  "ListLayoutListDescrition": "Få vist elementer og detaljer på en liste",
  "ListLayoutTile": "Flise udsigt",
  "ListLayoutTileDescription": "Få vist elementer med felt eksempler",
  "ListOptionsAlt": "Indstillinger for visning. {0} valgt.",
  "ListOptionsTitle": "Åbne menuen visningsindstillinger",
  "Loading": "Indlæsning...",
  "ModifiedByField": "Modificeret af",
  "ModifiedField": "Dato for ændring",
  "NameField": "Navn",
  "No": "Nej",
  "ProvidedValueIsInvalid": "Den leverede værdi er ugyldig",
  "NoExternalLinksValidationMessage": "Vi understøtter kun sammenkædning med filer i din egen organisation.",
  "NoImageValidationMessage": "Dette er ikke et link til en filtype, vi understøtter. Du kan kun linke til et billede.",
  "NoRecentFiles": "Ingen nylige filer",
  "NoRecentFilesDescription": "Prøv at vælge en fil fra dit website, eller upload en fra din enhed.",
  "NoResultsBadEnglish": "Der er ikke fundet noget resultat. Prøv at ændre filtreringsindstillingerne",
  "ODModifiedField": "Ændret",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, ændret {2}, redigeret af {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Dette element er fra dit OneDrive-websted. Filer og mapper i OneDrive er private, medmindre du deler dem. Har du delt denne fil med dit webstedsmedlemmer, så de kan dgang det?",
  "OneDriveConfirmDialogTitle": "Bare tjekker...",
  "OneDriveEmptyFolderAlt": "Tom mappe",
  "OneDriveEmptyFolderDescription": "Hvis du vil tilføje filer, skal du gå til dit OneDrive. Du kan også føje filer til denne mappe ved hjælp af OneDrive-appen til din computer.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Denne mappe er tom",
  "OneDriveRootFolderName": "Filer",
  "OpenButtonLabel": "Åbne",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Billeder og filer, der leveres af din organisation",
  "PoweredByBing": "Drevet af Bing",
  "RecentDocumentsHeader": "Seneste dokumenter",
  "RecentImagesHeader": "Seneste billeder",
  "RecentLinkLabel": "Seneste",
  "SearchBoxPlaceholder": "Websøgning",
  "SearchResultAlt": "Billed resultat for {0}.",
  "SearchResultAriaLabel": "Tryk på ENTER for at åbne billedkilden i en ny fane.",
  "Selected": "Valgte",
  "SharingField": "Deling",
  "SharingPrivate": "Privat",
  "SharingShared": "Delt",
  "SiteLinkLabel": "Websted",
  "SizeOptionAll": "Alle",
  "SizeOptionExtraLarge": "Ekstra stor",
  "SizeOptionLarge": "Store",
  "SizeOptionMedium": "Medium",
  "SizeOptionSmall": "Lille",
  "SizeUnit": [
    "Byte",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "F.eks",
    "Yb"
  ],
  "SorryWebSearch": "Denne funktion er desværre ikke implementeret i dette eksempel, fordi den kræver en Bing API-nøgle.",
  "SortedAscending": "Sorteret A til å",
  "SortedDescending": "Sorteret Z til en",
  "TypeAriaLabel": "Kolonne handlinger for filtype, skal du trykke på for at sortere efter filtype",
  "UploadFileHeader": "Overfør fil",
  "UploadImageHeader": "Upload billede",
  "UploadLinkLabel": "Uploade",
  "WebSearchLinkLabel": "Websøgning",
  "StockImagesLinkLabel": "Stock-billeder",
  "StockImagesHeader": "Stock-billeder",
  "Yes": "Ja",
  "NewFolderNamePlaceholder": "Angiv mappenavnet",
  "FolderFilterBoxPlaceholder": "Filtrere mapper efter navn",
  "FolderExplorerLoading": "Indlæser mapper...",
  "FolderExplorerNoItems": "Denne mappe har ingen undermapper.",
  "NewFolderIncorrectSymbolsError": "Indtast et navn, der ikke indeholder nogen af disse tegn: \" * : < > ? /  |.",
  "SomethingWentWrong": "Noget gik galt",
  "SelectedLabel": "Valgt",
  "SelectIcon": "Vælg ikon",
  "TreeViewExpandTitle": "Udvid dette element",
  "TreeViewCollapseTitle": "Skjul dette element",
  "CollectionDataEmptyFields": "Der blev ikke angivet felter for indsamlingsdataene.",
  "CollectionDataEmptyValue": "Ingen data i din samling.",
  "CollectionAddRowButtonLabel": "Føje data til samlingen",
  "CollectionDeleteRowButtonLabel": "Slet den aktuelle række",
  "CollectionSaveAndAddButtonLabel": "Tilføje og gemme",
  "CollectionDataItemShowErrorsLabel": "Vis rækkefejl",
  "CollectionDataItemFieldRequiredLabel": "Feltet er påkrævet.",
  "CollectionDataItemMissingFields": "Fields kollektionen er tom!",
  "InvalidUrlError": "Den angivne URL-adresse er ugyldig",
  "CollectionDataSearch": "Søge",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "indlæse dine teams",
  "MyTeamsMessageError": "Noget gik galt, mens du indlæser dine teams, kan du prøve senere eller opdatere browser",
  "MyTeamsNoTeamsMessage": "Du har ingen hold.",
  "MyTeamsTeamChannelPublicMessage": "Offentlige kanaler",
  "MyTeamsTeamChannelTypeMessage": "Private kanaler",
  "TeamChannelPickerFontIconFavoriteText": "Favorit",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Privat kanal",
  "TeamChannelPickerSugestionHeaderText": "Foreslåede teamkanaler",
  "TeamPickerButtonRemoveTitle": "fjerne",
  "TeamPickernoResultsFoundText": "Der blev ikke fundet nogen teams",
  "TeamPickerSugestionsHeaderText": "Foreslåede teams",
  "TeamsChannelPickerButtonRemoveTitle": "fjerne",
  "TeamsChannelPickerNoresultsFoundText": "Der blev ikke fundet nogen kanaler",
  "ViewMore": "Se mere",
  "DynamicFormLoading": "Pålæsning...",
  "DynamicFormPleaseWait": "Vent venligst...",
  "DynamicFormRequiredErrorMessage": "Du kan ikke lade det være tomt.",
  "DynamicFormTermPanelTitle": "Vælg ord",
  "DynamicFormEnterURLPlaceholder": "Angiv en URL-adresse",
  "DynamicFormEnterDescriptionPlaceholder": "Alternativ tekst",
  "DynamicFormDialogValidationErrorTitle": "Valideringsfejl",
  "DynamicFormDialogValidationErrorMessage": "Der er valideringsfejl. Ret dem venligst før du gemmer.",
  "DynamicFormNumberValueMustBeGreaterThan": "Værdien skal være større end {0}",
  "DynamicFormNumberValueMustBeBetween": "Værdien skal være mellem {0} og {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Værdien skal være lavere end {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Brug denne placering:",
  "ListItemCommentDIalogDeleteSubText": "Er du sikker på, at du vil slette denne kommentar?",
  "ListItemCommentsDialogDeleteTitle": "Bekræft kommentar til sletning",
  "ListItemCommentsLabel": "Kommentarer",
  "ListItemCommentsNoCommentsLabel": "No comments",
  "OrgAssetsLinkLabel": "Din organisation",
  "MyTeamsMessageDontHaveTeams": "You don't have any teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Indtast et udtryk, du vil tagge",
  "ModernTaxonomyPickerTreeTitleSingle": "Vælg et tag",
  "ModernTaxonomyPickerTreeTitleMulti": "Vælg et eller flere tags",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Tilføj tag",
  "ModernTaxonomyPickerApplyButtonText": "Brug",
  "ModernTaxonomyPickerCancelButtonText": "Annuller",
  "ModernTaxonomyPickerLoadMoreText": "Lær mere",
  "ModernTaxonomyPickerRemoveButtonText": "Slet",
  "ModernTaxonomyPickerPanelCloseButtonText": "Luk",
  "ModernTaxonomyPickerNoResultsFound": "Ingen resultater fundet",
  "ModernTaxonomyPickerSuggestionInLabel": "i",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
