declare var define: any;

define([], () => {
  return {
    TermSertNaviagtionErrorMessage: "TermSet not found",
    TermSetNavigationNoTerms: "No terms defined",
    "Save": "Lagre",
    "Cancel": "Avbryt",
    "SiteBreadcrumbLabel": "Brødsmule på nettstedet",
    "ListViewGroupEmptyLabel": "Tom",
    "WebPartTitlePlaceholder": "Webdel-tittel",
    "WebPartTitleLabel": "Legg til en tittel",
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Om noen få sekunder",
      "L_RelativeDateTime_AFewSeconds": "Et par sekunder siden",
      "L_RelativeDateTime_AboutAMinuteFuture": "Om omtrent ett minutt",
      "L_RelativeDateTime_AboutAMinute": "For ett minutt siden",
      "L_RelativeDateTime_XMinutesFuture": "Om {0} minutt||Om {0} minutter",
      "L_RelativeDateTime_XMinutes": "{0} minutt siden||{0} minutter siden",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Om en time",
      "L_RelativeDateTime_AboutAnHour": "For en time siden",
      "L_RelativeDateTime_Tomorrow": "Morgen",
      "L_RelativeDateTime_Yesterday": "Går",
      "L_RelativeDateTime_TomorrowAndTime": "I morgen kl {0}",
      "L_RelativeDateTime_YesterdayAndTime": "I går på {0}",
      "L_RelativeDateTime_XHoursFuture": "Om {0} time||Om {0} timer",
      "L_RelativeDateTime_XHours": "{0} time siden||{0} timer siden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
      "L_RelativeDateTime_DayAndTime": "{0} {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dag fra nå||{0} dager fra nå",
      "L_RelativeDateTime_XDays": "{0} dag siden||{0} dager siden",
      "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
      "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
      "L_RelativeDateTime_Today": "Dag"
    },
    "SendEmailTo": "Send en e-post til {0}",
    "StartChatWith": "Start en chat med {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Oppdater profilen",
    "TaxonomyPickerNoTerms": "Termsettet inneholder ingen termer",
    "TaxonomyPickerExpandTitle": "Utvid termsettet",
    "TaxonomyPickerMenuTermSet": "Meny for termsett",
    "TaxonomyPickerInLabel": "I",
    "TaxonomyPickerTermSetLabel": "Termsett",
    "TaxonomyPickerTermsNotFound": "Finner ikke de neste valgte termene i termlageret: {0}",
    "TaxonomyPickerInvalidTerms": "Reparer ugyldig(e) term(er): {0}",
    "peoplePickerComponentTooltipMessage": "Personvelger",
    "peoplePickerComponentErrorMessage": "Obligatorisk felt",
    "peoplePickerSuggestionsHeaderText": "Foreslåtte personer",
    "peoplePickerLoadingText": "Laster",
    "PeoplePickerSearchText": "Henter brukere",
    "PeoplePickerGroupNotFound": "Finner ikke gruppen.",
    "genericNoResultsFoundText": "Ingen resultater funnet",
    "ListItemPickerSelectValue": "Velg verdi",
    "ListItemAttachmentsActionDeleteIconTitle": "Slett",
    "ListItemAttachmentsactionDeleteTitle": "Slett",
    "ListItemAttachmentsfileDeletedMsg": "Fil {0} slettet",
    "ListItemAttachmentsfileDeleteError": "Feil ved sletting av fil: {0}, årsak {1}",
    "ListItemAttachmentserrorLoadAttachments": "Feil ved lasting av vedlegg til listeelement, årsak: {0}",
    "ListItemAttachmentsconfirmDelete": "Er du sikker på at du vil sende vedlegget {0} til papirkurven for området?",
    "ListItemAttachmentsdialogTitle": "Vedlegg til listeelement",
    "ListItemAttachmentsdialogOKbuttonLabel": "ok",
    "ListItemAttachmentsdialogCancelButtonLabel": "Avbryt",
    "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Slett",
    "ListItemAttachmentsuploadAttachmentDialogTitle": "Legg til vedlegg",
    "ListItemAttachmentsuploadAttachmentButtonLabel": "Legg til vedlegg",
    "ListItemAttachmentsuploadAttachmentErrorMsg": "Filen {0} ikke vedlagt, grunn: {1}",
    "ListItemAttachmentsCommandBarAddAttachmentLabel": "Legg til vedlegg",
    "ListItemAttachmentsloadingMessage": "Laster opp fil...",
    "ListItemAttachmentslPlaceHolderIconText": "Vedlegg til listeelement",
    "ListItemAttachmentslPlaceHolderDescription": "Vennligst legg til vedlegg",
    "ListItemAttachmentslPlaceHolderButtonLabel": "Legg til",
    "mapsErrorMessage": "Det oppstod en feil under lasting av kartet",
    "mapsLoadingText": "Laster",
    "mapsSearchButtonText": "Søk",
    "mapsTitlePrefix": "Kart over",
    "ListViewFilterLabel": "Filtrer listen",
    "HeaderNormalText": "Vanlig tekst",
    "HeaderH2": "Overskrift 2",
    "HeaderH3": "Overskrift 3",
    "HeaderH4": "Overskrift 4",
    "HeaderBlockQuote": "Sitat",
    "AlignLeft": "Juster venstre",
    "AlignCenter": "Midtstill",
    "AlignRight": "Juster høyre",
    "AlignJustify": "Blokkjuster",
    "ListBullet": "Punktliste",
    "ListNumbered": "Nummerert liste",
    "StyleTitle": "Stil",
    "BoldTitle": "Fet (Ctrl + B)",
    "ItalicTitle": "Kursiv (Ctrl + I)",
    "UnderlineTitle": "Understreking (Ctrl + U)",
    "AlignTitle": "Juster",
    "ListTitle": "Liste",
    "LinkTitle": "Hyperkobling",
    "ImageTitle": "Bilde",
    "MoreTitle": "Mer",
    "FormattingPaneTitle": "Tekstformatering",
    "CloseButton": "Lukk",
    "InsertLinkTitle": "Sett inn kobling",
    "InsertImageTitle": "Sett inn bilde",
    "AddressFieldLabel": "Adresse",
    "TextToDisplayLabel": "Tekst som skal vises",
    "SaveButtonLabel": "Lagre",
    "CancelButtonLabel": "Avbryt",
    "RemoveLinkLabel": "Fjern kobling",
    "ParagraphSectionTitle": "Avsnitt",
    "HyperlinkSectionTitle": "Hyperkobling",
    "UndoTitle": "Angre (Ctrl + Z)",
    "RedoTitle": "Gjør om (CTRL + Y)",
    "ClearFormattingTitle": "Fjern all formatering",
    "FontStyleTitle": "Skriftstil",
    "FontSizeTitle": "Skriftstørrelse",
    "StrikethroughTitle": "Gjennomstreking",
    "SuperscriptTitle": "Hevet skrift",
    "SubscriptTitle": "Senket skrift",
    "FontColorLabel": "Skriftfarge",
    "AutomaticFontColor": "Automatisk",
    "HighlightColorLabel": "Uthevingsfarge",
    "NoColorHighlightColor": "Ingen farge",
    "IncreaseIndentTitle": "Øk innrykk",
    "DecreaseIndentTitle": "Reduser innrykk",
    "ThemeColorsGroupName": "Temafarger",
    "HighlightColorsGroupName": "Utheve farger",
    "StandardColorsGroupName": "Standard farger",
    "CustomColorsGroupName": "Egendefinerte farger",
    "ThemeColorDarker": "Tema mørkere",
    "ThemeColorDark": "Tema mørk",
    "ThemeColorDarkAlt": "Tema mørk alternativ",
    "ThemeColorPrimary": "Primærtema",
    "ThemeColorSecondary": "Sekundærtema",
    "ThemeColorTertiary": "Nøytral tertiær",
    "ThemeColorNeutralSecondary": "Nøytral sekundær",
    "ThemeColorNeutralPrimaryAlt": "Nøytral primær alternativ",
    "ThemeColorNeutralPrimary": "Nøytral primær",
    "ThemeColorNeutralDark": "Nøytral mørk",
    "HighlightColorYellow": "Gul",
    "HighlightColorGreen": "Grønn",
    "HighlightColorAqua": "Aqua",
    "HighlightColorMagenta": "Magenta",
    "HighlightColorBlue": "Blå",
    "HighlightColorRed": "Rød",
    "HighlightColorDarkblue": "Mørkeblå",
    "HighlightColorTeal": "Teal",
    "HighlightColorDarkgreen": "Mørkegrønne",
    "HighlightColorPurple": "Lilla",
    "HighlightColorMaroon": "Rødbrun",
    "HighlightColorGold": "Gull",
    "HighlightColorDarkgrey": "Mørk grå",
    "HighlightColorGrey": "Grå",
    "HighlightColorBlack": "Svart",
    "StandardColorDarkred": "Mørk rød",
    "StandardColorRed": "Rød",
    "StandardColorOrange": "Oransje",
    "StandardColorYellow": "Gul",
    "StandardColorLightgreen": "Lys grønn",
    "StandardColorGreen": "Grønn",
    "StandardColorLightblue": "Lys blå",
    "StandardColorBlue": "Blå",
    "StandardColorDarkblue": "Mørkeblå",
    "StandardColorPurple": "Lilla",
    "DatePickerMonthLongJanuary": "Januar",
    "DatePickerMonthShortJanuary": "Jan",
    "DatePickerMonthLongFebruary": "Februar",
    "DatePickerMonthShortFebruary": "Feb",
    "DatePickerMonthLongMarch": "Mars",
    "DatePickerMonthShortMarch": "Mar",
    "DatePickerMonthLongApril": "April",
    "DatePickerMonthShortApril": "April",
    "DatePickerMonthLongMay": "Mai",
    "DatePickerMonthShortMay": "Mai",
    "DatePickerMonthLongJune": "Juni",
    "DatePickerMonthShortJune": "Juni",
    "DatePickerMonthLongJuly": "Juli",
    "DatePickerMonthShortJuly": "Juli",
    "DatePickerMonthLongAugust": "August",
    "DatePickerMonthShortAugust": "Aug",
    "DatePickerMonthLongSeptember": "September",
    "DatePickerMonthShortSeptember": "Sept",
    "DatePickerMonthLongOctober": "Oktober",
    "DatePickerMonthShortOctober": "Okt",
    "DatePickerMonthLongNovember": "November",
    "DatePickerMonthShortNovember": "Nov",
    "DatePickerMonthLongDecember": "Desember",
    "DatePickerMonthShortDecember": "Des",
    "DatePickerDayLongSunday": "Søndag",
    "DatePickerDayShortSunday": "Sø.",
    "DatePickerDayLongMonday": "Mandag",
    "DatePickerDayShortMonday": "Ma.",
    "DatePickerDayLongTuesday": "Tirsdag",
    "DatePickerDayShortTuesday": "Ti.",
    "DatePickerDayLongWednesday": "Onsdag",
    "DatePickerDayShortWednesday": "On.",
    "DatePickerDayLongThursday": "Torsdag",
    "DatePickerDayShortThursday": "To.",
    "DatePickerDayLongFriday": "Fredag",
    "DatePickerDayShortFriday": "Fr.",
    "DatePickerDayLongSaturday": "Lørdag",
    "DatePickerDayShortSaturday": "Lø.",
    "DatePickerGoToToday": "I dag",
    "DatePickerIsRequiredErrorMessage": "",
    "DatePickerInvalidInputErrorMessage": "",
    "DatePickerIsOutOfBoundsErrorMessage": "",
    "DateTimePickerDate": "Dato",
    "DateTimePickerTime": "Tid",
    "DateTimePickerTimeSeparator": ":",
    "DateTimePickerHourValueInvalid": "Feil timeverdi",
    "DateTimePickerMinuteValueInvalid": "Feil minuttverdi",
    "DateTimePickerSecondValueInvalid": "Feil sekundverdi",
    "DateTimePickerTextErrorMessage": "Angi en gyldig dato",
    "AddFileButtonLabel": "Legg til fil",
    "AddImageButtonLabel": "Legg til bilde",
    "AriaCellValue": "{0} kolonne {1}",
    "FilePickerCancelButtonLabel": "Avbryt",
    "CantValidateValidationMessage": "Vi kunne ikke bekrefte denne koblingen. Kontroller koblingen og prøv på nytt.",
    "ChangeFileLinkLabel": "Endre fil",
    "ChangeImageLinkLabel": "Endre bilde",
    "ChooseFileLinkLabel": "Velg fil",
    "ChooseImageLinkLabel": "Velg bilde",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "Du er ansvarlig for å respektere andres rettigheter, inkludert opphavsrett.",
    "CreativeCommonsMessage": "Disse resultatene er merket med Creative Commons-lisenser. Se gjennom lisensene for å sikre at du overholder dem.",
    "DateFormat": "MM/DD/åååå hh: mm A",
    "DocumentLabelTemplate": "{0}, dokument, endret {1}, redigert av {2}, privat",
    "DocumentLibraries": "Dokumentbiblioteker",
    "EditedByNamePlate": "redigert av ",
    "EmptyFileSize": "0 byte",
    "FilePickerHeader": "Filvelger",
    "FileSizeField": "Filstørrelse",
    "FolderAltText": "Mappe",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    "FolderLabelTemplate": "{0}, mappe, endret {1}, redigert av {2}, {3} elementer, privat",
    "FromLinkLinkLabel": "Fra en kobling",
    "ImageAltText": ". {0} bilde",
    "ImageAriaLabelTemplate": ". {0} bilde",
    "ImageLayoutPlaceholderText": "Oppsett",
    "ImageSizePlaceholderText": "Bildestørrelse",
    "ItemChildCountField": "Antall underordnede elementer",
    "LayoutOptionAll": "Alle",
    "LayoutOptionSquare": "Kvadratisk",
    "LayoutOptionTall": "Høy",
    "LayoutOptionWide": "Bred",
    "LearnMoreLink": "få mer informasjon.",
    "LicenseOptionAll": "Alle",
    "LicenseOptionAny": "Kun Creative Commons",
    "LicensePlaceholderText": "Lisens",
    "LinkFileInstructions": "Lim inn en kobling til en fil i OneDrive for Business eller SharePoint Online",
    "LinkHeader": "Fra en kobling",
    "LinkImageInstructions": "Lim inn en kobling til et bilde i OneDrive for Business eller SharePoint Online",
    "ListLayoutAriaLabel": "Vis alternativer. {0} {1}.",
    "ListLayoutCompact": "Kompakt visning",
    "ListLayoutCompactDescription": "Vis elementer og detaljer i en kompakt liste",
    "ListLayoutList": "Listevisning",
    "ListLayoutListDescrition": "Vis elementer og detaljer i en liste",
    "ListLayoutTile": "Flisvisning",
    "ListLayoutTileDescription": "Vis elementer med forhåndsvisninger av fliser",
    "ListOptionsAlt": "Vis alternativer. {0} valgt.",
    "ListOptionsTitle": "Åpne menyen for visningsalternativer",
    "Loading": "Laster...",
    "ModifiedByField": "Endret av",
    "ModifiedField": "Endret dato",
    "NameField": "navn",
    "No": "nei",
    "ProvidedValueIsInvalid": "Angitt verdi er ugyldig",
    "NoExternalLinksValidationMessage": "Vi støtter bare kobling til filer i din egen organisasjon.",
    "NoImageValidationMessage": "Dette er ikke en kobling til en filtype vi støtter. Du kan bare koble til et bilde.",
    "NoRecentFiles": "Ingen nylige filer",
    "NoRecentFilesDescription": "Prøv å velge en fil fra nettstedet ditt, eller Last opp en fra enheten din.",
    "NoResultsBadEnglish": "Det finnes ingen resultater. Prøv å endre filteralternativene",
    "ODModifiedField": "Endret",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0}, {1}, modifisert {2}, redigert av {3}, {4}, {5}",
    "OneDriveConfirmDialogBody": "Dette elementet er fra OneDrive-webområdet. Filer og mapper i OneDrive er private med mindre du deler dem. Har du delt denne filen med område medlemmene slik at de kan tilgangen den?",
    "OneDriveConfirmDialogTitle": "Bare sjekker...",
    "OneDriveEmptyFolderAlt": "Tøm mappe",
    "OneDriveEmptyFolderDescription": "Hvis du vil legge til filer, går du til OneDrive. Du kan også legge til filer i denne mappen ved hjelp av OneDrive-appen for datamaskinen.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "Denne mappen er tom",
    "OneDriveRootFolderName": "Filer",
    "OpenButtonLabel": "Åpne",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "Bilder og filer fra organisasjonen",
    "PoweredByBing": "Drevet av Bing",
    "RecentDocumentsHeader": "Nylig brukte dokumenter",
    "RecentImagesHeader": "Nylige bilder",
    "RecentLinkLabel": "Siste",
    "SearchBoxPlaceholder": "Søk på weben",
    "SearchResultAlt": "Bilderesultat for {0}.",
    "SearchResultAriaLabel": "Trykk på Enter for å åpne bildekilden i en ny fane.",
    "Selected": "Valgte",
    "SharingField": "Deler",
    "SharingPrivate": "Privat",
    "SharingShared": "Delte",
    "SiteLinkLabel": "Nettstedet",
    "SizeOptionAll": "Alle",
    "SizeOptionExtraLarge": "Ekstra stor",
    "SizeOptionLarge": "Stor",
    "SizeOptionMedium": "Middels",
    "SizeOptionSmall": "Liten",
    "SizeUnit": [
      "Byte",
      "Kb",
      "Mb",
      "Gb",
      "Tb",
      "Pb",
      "Eb",
      "Zb",
      "Yb"
    ],
    "SorryWebSearch": "Beklager, denne funksjonen er ikke implementert i dette eksemplet, fordi det krever en Bing API-nøkkel.",
    "SortedAscending": "Sortert A til å",
    "SortedDescending": "Sortert Å til A",
    "TypeAriaLabel": "Kolonneoperasjoner for filtype, trykk for å sortere etter filtype",
    "UploadFileHeader": "Last opp fil",
    "UploadImageHeader": "Last opp bilde",
    "UploadLinkLabel": "Last opp",
    "WebSearchLinkLabel": "Søk på weben",
    "StockImagesLinkLabel": "Arkivbilder",
    "StockImagesHeader": "Arkivbilder",
    "Yes": "ja",
    "NewFolderNamePlaceholder": "Skriv inn mappenavnet",
    "FolderFilterBoxPlaceholder": "Filtrer mapper etter navn",
    "FolderExplorerLoading": "Laster inn mapper...",
    "FolderExplorerNoItems": "Denne mappen har ingen undermapper.",
    "NewFolderIncorrectSymbolsError": "Skriv inn et navn som ikke inneholder noen av disse tegnene: \" * : < > ? /  |.",
    "SomethingWentWrong": "Noe gikk galt",
    "SelectedLabel": "Valgt",
    "SelectIcon": "Velg ikon",
    "TreeViewExpandTitle": "Utvid dette elementet",
    "TreeViewCollapseTitle": "Skjul dette elementet",
    "CollectionDataEmptyFields": "Det ble ikke angitt noen felt for innsamlingsdataene.",
    "CollectionDataEmptyValue": "Ingen data i samlingen din.",
    "CollectionAddRowButtonLabel": "Legg til data i samlingen",
    "CollectionDeleteRowButtonLabel": "Slett gjeldende rad",
    "CollectionSaveAndAddButtonLabel": "Legg til og lagre",
    "CollectionDataItemShowErrorsLabel": "Vis radfeil",
    "CollectionDataItemFieldRequiredLabel": "Feltet er obligatorisk.",
    "CollectionDataItemMissingFields": "Feltsamlingen er tom.",
    "InvalidUrlError": "Den angitte URL-adressen er ikke gyldig",
    "CollectionDataSearch": "Søk",
    "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
    "MyTeamsLoadingMessage": "laste inn teamene dine",
    "MyTeamsMessageError": "Noe gikk galt mens du lastet inn teamene dine, prøv senere eller oppdater nettleseren",
    "MyTeamsNoTeamsMessage": "Du har ingen team",
    "MyTeamsTeamChannelPublicMessage": "Offentlige kanaler",
    "MyTeamsTeamChannelTypeMessage": "Private kanaler",
    "TeamChannelPickerFontIconFavoriteText": "Favoritt",
    "TeamChannelPickerFontIconPrivateChannelTitle": "Privat kanal",
    "TeamChannelPickerSugestionHeaderText": "Foreslåtte teamkanaler",
    "TeamPickerButtonRemoveTitle": "fjern",
    "TeamPickernoResultsFoundText": "Finner ingen team",
    "TeamPickerSugestionsHeaderText": "Foreslåtte team",
    "TeamsChannelPickerButtonRemoveTitle": "fjern",
    "TeamsChannelPickerNoresultsFoundText": "Finner ingen kanaler",
    "ViewMore": "Vis mer",
    "DynamicFormLoading": "Laster...",
    "DynamicFormPleaseWait": "Vent...",
    "DynamicFormRequiredErrorMessage": "Du kan ikke la dette stå tomt.",
    "DynamicFormTermPanelTitle": "Velg term",
    "DynamicFormEnterURLPlaceholder": "Skriv inn en URL-adresse",
    "DynamicFormEnterDescriptionPlaceholder": "Alternativ tekst",
    "DynamicFormDialogValidationErrorTitle": "Valideringsfeil",
    "DynamicFormDialogValidationErrorMessage": "Det er valideringsfeil, vennligst fiks dem før du lagrer.",
    "DynamicFormNumberValueMustBeGreaterThan": "Verdien må være større enn {0}",
    "DynamicFormNumberValueMustBeBetween": "Verdien må være mellom {0} og {1}",
    "DynamicFormNumberValueMustBeLowerThan": "Verdien må være lavere enn {0}",
    "DynamicFormChooseFileLabel": "File",
    "DynamicFormChooseFileButtonText": "Select file",
    "DynamicFormRequiredFileMessage": "File is required.",
    "customDisplayName": "Bruk denne plasseringen:",
    "ListItemCommentDIalogDeleteSubText": "Er du sikker på at du vil slette denne kommentaren?",
    "ListItemCommentsDialogDeleteTitle": "Bekreft sletting av kommentar",
    "ListItemCommentsLabel": "Kommentarer",
    "ListItemCommentsNoCommentsLabel": "Det finnes ingen kommentarer",
    "OrgAssetsLinkLabel": "Egen organisasjon",
    "MyTeamsMessageDontHaveTeams": "Du har ingen team",
    "ModernTaxonomyPickerDefaultPlaceHolder": "Skriv inn termen som skal merkes",
    "ModernTaxonomyPickerTreeTitleSingle": "Velg et merke",
    "ModernTaxonomyPickerTreeTitleMulti": "Velg ett eller flere merker",
    "ModernTaxonomyPickerAddTagButtonTooltip": "Legg til merke",
    "ModernTaxonomyPickerApplyButtonText": "Bruk",
    "ModernTaxonomyPickerCancelButtonText": "Avbryt",
    "ModernTaxonomyPickerLoadMoreText": "Last inn mer",
    "ModernTaxonomyPickerRemoveButtonText": "Fjern",
    "ModernTaxonomyPickerPanelCloseButtonText": "Lukk",
    "ModernTaxonomyPickerNoResultsFound": "Ingen resultater funnet",
    "ModernTaxonomyPickerSuggestionInLabel": "i",

    "ModernAudioPlay": "Play",
    "ModernAudioPause": "Pause",
    "ModernAudioIncVol": "Increase Volume",
    "ModernAudioDecVol": "Decrease Volume",
    "ModernAudioMute": "Mute",

    "ProgressStepsIndicatorNoSteps": "No steps",

    "UploadFilesButtonLabel": "Add",
    "UpLoadFilesDeleteButtonLabel": "Delete",
    "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
    "UpLoadFilesSelectAllLabel": "Select all",
    "UploadFilesUploadButtonLabel": "Upload",
  };
});
