declare var define: any;

define([], () => {
  return {
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  "Save": "Spara",
  "Cancel": "Avbryt",
  "SiteBreadcrumbLabel": "Brödsmulemeny",
  "ListViewGroupEmptyLabel": "Tom",
  "WebPartTitlePlaceholder": "Webbdelstitel",
  "WebPartTitleLabel": "Ange titel",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Om några sekunder",
    "L_RelativeDateTime_AFewSeconds": "För några sekunder sedan",
    "L_RelativeDateTime_AboutAMinuteFuture": "Om ungefär en minut",
    "L_RelativeDateTime_AboutAMinute": "För ungefär en minut sedan",
    "L_RelativeDateTime_XMinutesFuture": "Om {0} minut||Om {0} minuter",
    "L_RelativeDateTime_XMinutes": "För {0} minut sedan||För {0} minuter sedan",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Om ungefär en timme",
    "L_RelativeDateTime_AboutAnHour": "För ungefär en timme sedan",
    "L_RelativeDateTime_Tomorrow": "Imorgon",
    "L_RelativeDateTime_Yesterday": "Igår",
    "L_RelativeDateTime_TomorrowAndTime": "Imorgon vid {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Igår vid {0}",
    "L_RelativeDateTime_XHoursFuture": "Om {0} timme||Om {0} timmar",
    "L_RelativeDateTime_XHours": "För {0} timme sedan||För {0} timmar sedan",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} på {1}",
    "L_RelativeDateTime_XDaysFuture": "Om {0} dag||Om {0} dagar",
    "L_RelativeDateTime_XDays": "För {0} dag sedan||För {0} dagar sedan",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Idag"
  },
  "SendEmailTo": "Skicka epost till {0}",
  "StartChatWith": "Börja en konversation med {0}",
  "Contact": "Kontakt",
  "UpdateProfile": "Uppdatera din profil",
  "TaxonomyPickerNoTerms": "Termuppsättningen innehåller inga termer",
  "TaxonomyPickerExpandTitle": "Expandera termuppsättningen",
  "TaxonomyPickerMenuTermSet": "Meny för termuppsättning",
  "TaxonomyPickerInLabel": "I",
  "TaxonomyPickerTermSetLabel": "Termuppsättning",
  "TaxonomyPickerTermsNotFound": "Det gick inte att hitta nästa valda term i termarkivet: {0}",
  "TaxonomyPickerInvalidTerms": "Åtgärda ogiltiga termer: {0}",
  "peoplePickerComponentTooltipMessage": "Personväljare",
  "peoplePickerComponentErrorMessage": "Obligatoriskt fält",
  "peoplePickerSuggestionsHeaderText": "Föreslagna personer",
  "peoplePickerLoadingText": "Laddar",
  "PeoplePickerSearchText": "Hämtar användare",
  "PeoplePickerGroupNotFound": "Gruppen kunde inte hittas.",
  "genericNoResultsFoundText": "Inga sökträffar",
  "ListItemPickerSelectValue": "Ange ett värde",
  "ListItemAttachmentsActionDeleteIconTitle": "Ta bort",
  "ListItemAttachmentsactionDeleteTitle": "Ta bort",
  "ListItemAttachmentsfileDeletedMsg": "Filen {0} raderades",
  "ListItemAttachmentsfileDeleteError": "Fel vid radering av fil: {0}, orsak {1}",
  "ListItemAttachmentserrorLoadAttachments": "Fel vid laddning av bilaga, orsak: {0}",
  "ListItemAttachmentsconfirmDelete": "Vill du verkligen flytta bilagan {0} till papperskorgen?",
  "ListItemAttachmentsdialogTitle": "Bilaga",
  "ListItemAttachmentsdialogOKbuttonLabel": "Ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Avbryt",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Ta bort",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Lägg till bilaga",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Lägg till bilaga",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Filen {0} kunde inte bifogas, orsak: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Lägg till bilaga",
  "ListItemAttachmentsloadingMessage": "Laddar upp filen...",
  "ListItemAttachmentslPlaceHolderIconText": "Bilaga",
  "ListItemAttachmentslPlaceHolderDescription": "Lägg till en bilaga",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Lägg till",
  "mapsErrorMessage": "Ett fel uppstod vid laddning av kartan",
  "mapsLoadingText": "Laddar",
  "mapsSearchButtonText": "Sök",
  "mapsTitlePrefix": "Karta över",
  "ListViewFilterLabel": "Filtrera listan",
  "HeaderNormalText": "Normal",
  "HeaderH2": "Rubrik 2",
  "HeaderH3": "Rubrik 3",
  "HeaderH4": "Rubrik 4",
  "HeaderBlockQuote": "Citat",
  "AlignLeft": "Vänsterjustera",
  "AlignCenter": "Centrera",
  "AlignRight": "Högerjustera",
  "AlignJustify": "Justera",
  "ListBullet": "Punktlista",
  "ListNumbered": "Numrerad lista",
  "StyleTitle": "Stil",
  "BoldTitle": "Fet (Ctrl+B)",
  "ItalicTitle": "Kursiv (Ctrl+I)",
  "UnderlineTitle": "Understruken (Ctrl+U)",
  "AlignTitle": "Justera",
  "ListTitle": "Lista",
  "LinkTitle": "Hyperlänk",
  "ImageTitle": "Bild",
  "MoreTitle": "Mer",
  "FormattingPaneTitle": "Textformatering",
  "CloseButton": "Stäng",
  "InsertLinkTitle": "Infoga länk",
  "InsertImageTitle": "Infoga bild",
  "AddressFieldLabel": "Adress",
  "TextToDisplayLabel": "Visningstext",
  "SaveButtonLabel": "Spara",
  "CancelButtonLabel": "Avbryt",
  "RemoveLinkLabel": "Ta bort länk",
  "ParagraphSectionTitle": "Stycke",
  "HyperlinkSectionTitle": "Hyperlänk",
  "UndoTitle": "Ångra (Ctrl+Z)",
  "RedoTitle": "Upprepa (Ctrl + Y)",
  "ClearFormattingTitle": "Rensa all formatering",
  "FontStyleTitle": "Teckensnitt",
  "FontSizeTitle": "Teckenstorlek ",
  "StrikethroughTitle": "Genomstruken",
  "SuperscriptTitle": "Upphöjt",
  "SubscriptTitle": "Nedsänkt",
  "FontColorLabel": "Teckenfärg",
  "AutomaticFontColor": "Automatisk",
  "HighlightColorLabel": "Markeringsfärg",
  "NoColorHighlightColor": "Ingen färg",
  "IncreaseIndentTitle": "Öka indrag",
  "DecreaseIndentTitle": "Minska indrag",
  "ThemeColorsGroupName": "Temafärger",
  "HighlightColorsGroupName": "Markeringsfärger",
  "StandardColorsGroupName": "Standardfärger",
  "CustomColorsGroupName": "Anpassade färger",
  "ThemeColorDarker": "Mörkare tema",
  "ThemeColorDark": "Mörkt tema",
  "ThemeColorDarkAlt": "Mörkt alternativt tema",
  "ThemeColorPrimary": "Primärt tema",
  "ThemeColorSecondary": "Andrahandstema",
  "ThemeColorTertiary": "Neutralt tredjeval",
  "ThemeColorNeutralSecondary": "Neutralt andrahandsval",
  "ThemeColorNeutralPrimaryAlt": "Neutralt primärt alternativ",
  "ThemeColorNeutralPrimary": "Neutralt primärt",
  "ThemeColorNeutralDark": "Neutralt mörkt",
  "HighlightColorYellow": "Gul",
  "HighlightColorGreen": "Grön",
  "HighlightColorAqua": "Cyan",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Blå",
  "HighlightColorRed": "Röd",
  "HighlightColorDarkblue": "Mörkblå",
  "HighlightColorTeal": "Teal",
  "HighlightColorDarkgreen": "Mörkgrön",
  "HighlightColorPurple": "Lila",
  "HighlightColorMaroon": "Vinröd",
  "HighlightColorGold": "Guld",
  "HighlightColorDarkgrey": "Mörkgrå",
  "HighlightColorGrey": "Grå",
  "HighlightColorBlack": "Svart",
  "StandardColorDarkred": "Mörkröd",
  "StandardColorRed": "Röd",
  "StandardColorOrange": "Orange",
  "StandardColorYellow": "Gul",
  "StandardColorLightgreen": "Ljusgrön",
  "StandardColorGreen": "Grön",
  "StandardColorLightblue": "Ljusblå",
  "StandardColorBlue": "Blå",
  "StandardColorDarkblue": "Mörkblå",
  "StandardColorPurple": "Lila",
  "DatePickerMonthLongJanuary": "januari",
  "DatePickerMonthShortJanuary": "jan",
  "DatePickerMonthLongFebruary": "februari",
  "DatePickerMonthShortFebruary": "feb",
  "DatePickerMonthLongMarch": "mars",
  "DatePickerMonthShortMarch": "mar",
  "DatePickerMonthLongApril": "april",
  "DatePickerMonthShortApril": "apr",
  "DatePickerMonthLongMay": "maj",
  "DatePickerMonthShortMay": "maj",
  "DatePickerMonthLongJune": "juni",
  "DatePickerMonthShortJune": "jun",
  "DatePickerMonthLongJuly": "juli",
  "DatePickerMonthShortJuly": "jul",
  "DatePickerMonthLongAugust": "augusti",
  "DatePickerMonthShortAugust": "aug",
  "DatePickerMonthLongSeptember": "september",
  "DatePickerMonthShortSeptember": "sep",
  "DatePickerMonthLongOctober": "oktober",
  "DatePickerMonthShortOctober": "okt",
  "DatePickerMonthLongNovember": "november",
  "DatePickerMonthShortNovember": "nov",
  "DatePickerMonthLongDecember": "december",
  "DatePickerMonthShortDecember": "dec",
  "DatePickerDayLongSunday": "söndag",
  "DatePickerDayShortSunday": "sön",
  "DatePickerDayLongMonday": "måndag",
  "DatePickerDayShortMonday": "mån",
  "DatePickerDayLongTuesday": "tisdag",
  "DatePickerDayShortTuesday": "tis",
  "DatePickerDayLongWednesday": "onsdag",
  "DatePickerDayShortWednesday": "ons",
  "DatePickerDayLongThursday": "torsdag",
  "DatePickerDayShortThursday": "tor",
  "DatePickerDayLongFriday": "fredag",
  "DatePickerDayShortFriday": "fre",
  "DatePickerDayLongSaturday": "lördag",
  "DatePickerDayShortSaturday": "lör",
  "DatePickerGoToToday": "Idag",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Datum",
  "DateTimePickerTime": "Tid",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Felaktigt timvärde",
  "DateTimePickerMinuteValueInvalid": "Felaktigt minutvärde",
  "DateTimePickerSecondValueInvalid": "Felaktigt andra värde",
  "DateTimePickerTextErrorMessage": "Ange ett giltigt datum",
  "AddFileButtonLabel": "Lägg till fil",
  "AddImageButtonLabel": "Lägg till bild",
  "AriaCellValue": "{0} kolumn {1}",
  "FilePickerCancelButtonLabel": "Avbryt",
  "CantValidateValidationMessage": "Vi kunde inte verifiera den här länken. Vänligen kontrollera länken och försök igen.",
  "ChangeFileLinkLabel": "Ändra fil",
  "ChangeImageLinkLabel": "Ändra bild",
  "ChooseFileLinkLabel": "Välj Arkiv",
  "ChooseImageLinkLabel": "Välj bild",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Du är ansvarig för att respektera andras rättigheter, inklusive upphovsrätt.",
  "CreativeCommonsMessage": "Dessa resultat är märkta med Creative Commons-licenser. Granska licenserna för att säkerställa att du följer dem.",
  "DateFormat": "ÅÅÅÅ-MM-DD HH: mm A",
  "DocumentLabelTemplate": "{0}, dokument, ändrad {1}, redigerad av {2}, privat",
  "DocumentLibraries": "Dokumentbibliotek",
  "EditedByNamePlate": "redigerad av ",
  "EmptyFileSize": "0 byte",
  "FilePickerHeader": "Filväljare",
  "FileSizeField": "Filstorlek",
  "FolderAltText": "Mappen",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, mapp, ändrad {1}, redigerad av {2}, {3} objekt, privat",
  "FromLinkLinkLabel": "Från en länk",
  "ImageAltText": ". {0} bild",
  "ImageAriaLabelTemplate": ". {0} bild",
  "ImageLayoutPlaceholderText": "Layout",
  "ImageSizePlaceholderText": "Bildstorlek",
  "ItemChildCountField": "Antal underordnade objekt",
  "LayoutOptionAll": "Alla",
  "LayoutOptionSquare": "Kvadrat",
  "LayoutOptionTall": "Hög",
  "LayoutOptionWide": "Bred",
  "LearnMoreLink": "Lära dig mer.",
  "LicenseOptionAll": "Alla",
  "LicenseOptionAny": "Endast Creative Commons",
  "LicensePlaceholderText": "Licens",
  "LinkFileInstructions": "Klistra in en länk till en fil i OneDrive för företag eller SharePoint Online",
  "LinkHeader": "Från en länk",
  "LinkImageInstructions": "Klistra in en länk till en bild i OneDrive för företag eller SharePoint Online",
  "ListLayoutAriaLabel": "Visa alternativ. {0} {1}.",
  "ListLayoutCompact": "Kompakt lista",
  "ListLayoutCompactDescription": "Visa objekt och information i en kompakt lista",
  "ListLayoutList": "Lista",
  "ListLayoutListDescrition": "Visa objekt och information i en lista",
  "ListLayoutTile": "Paneler",
  "ListLayoutTileDescription": "Visa förhandsgranskningar av objekt sida vid sida",
  "ListOptionsAlt": "Visa alternativ. {0} valt.",
  "ListOptionsTitle": "Öppna menyn Visa alternativ",
  "Loading": "Laddar...",
  "ModifiedByField": "Ändrades av",
  "ModifiedField": "Ändrat datum",
  "NameField": "Namn",
  "No": "Nej",
  "ProvidedValueIsInvalid": "Det angivna värdet är inte giltigt",
  "NoExternalLinksValidationMessage": "Vi stöder bara länkning till filer i din egen organisation.",
  "NoImageValidationMessage": "Detta är inte en länk till en filtyp som stöds. Du kan endast länka till en bild.",
  "NoRecentFiles": "Inga senaste filer",
  "NoRecentFilesDescription": "Prova att välja en fil från din webbplats eller ladda upp en från din enhet.",
  "NoResultsBadEnglish": "Det finns inget resultat hittades. Försök att ändra filteralternativen",
  "ODModifiedField": "Ändrade",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, ändrad {2}, redigerad av {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Det här objektet är från din OneDrive-webbplats. Filer och mappar på OneDrive är privata om du inte delar dem. Har du delat denna fil med dina webbplatsmedlemmar så att de kan komma åt dem?",
  "OneDriveConfirmDialogTitle": "Kontrollerar...",
  "OneDriveEmptyFolderAlt": "Tom mapp",
  "OneDriveEmptyFolderDescription": "Om du vill lägga till filer går du till OneDrive. Du kan också lägga till filer i den här mappen med hjälp av OneDrive-appen för datorn.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Den här mappen är tom",
  "OneDriveRootFolderName": "Filer",
  "OpenButtonLabel": "Öppna",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Bilder och filer som tillhandahålls av din organisation",
  "PoweredByBing": "Drivs av Bing",
  "RecentDocumentsHeader": "Senaste dokument",
  "RecentImagesHeader": "Senaste bilder",
  "RecentLinkLabel": "Senaste",
  "SearchBoxPlaceholder": "Webbsökning",
  "SearchResultAlt": "Bildresultat för {0}.",
  "SearchResultAriaLabel": "Tryck på RETUR för att öppna bildkällan i en ny flik.",
  "Selected": "Markerade",
  "SharingField": "Dela",
  "SharingPrivate": "Privat",
  "SharingShared": "Delade",
  "SiteLinkLabel": "Webbplats",
  "SizeOptionAll": "Alla",
  "SizeOptionExtraLarge": "Extra stor",
  "SizeOptionLarge": "Stora",
  "SizeOptionMedium": "Medium",
  "SizeOptionSmall": "Liten",
  "SizeUnit": [
    "Byte",
    "kB",
    "MB",
    "GB",
    "TB",
    "PB",
    "EB",
    "ZB",
    "YB"
  ],
  "SorryWebSearch": "Den här funktionen implementeras inte i det här exemplet eftersom den kräver en API-nyckel för Bing.",
  "SortedAscending": "Sortera stigande A till Ö",
  "SortedDescending": "Sortera fallande Ö till A",
  "TypeAriaLabel": "Kolumn åtgärder för filtyp, tryck för att sortera efter filtyp",
  "UploadFileHeader": "Ladda upp fil",
  "UploadImageHeader": "Ladda upp bild",
  "UploadLinkLabel": "Uppladdning",
  "WebSearchLinkLabel": "Webbsökning",
  "StockImagesLinkLabel": "Stockbilder",
  "StockImagesHeader": "Stockbilder",
  "Yes": "Ja",
  "NewFolderNamePlaceholder": "Ange mappnamnet",
  "FolderFilterBoxPlaceholder": "Filtrera mappar efter namn",
  "FolderExplorerLoading": "Läser in mappar...",
  "FolderExplorerNoItems": "Den här mappen har inga undermappar.",
  "NewFolderIncorrectSymbolsError": "Ange ett namn som inte innehåller något av följande tecken: \" * : < > ? /  |.",
  "SomethingWentWrong": "Något gick fel",
  "SelectedLabel": "Vald",
  "SelectIcon": "Välj ikon",
  "TreeViewExpandTitle": "Expandera det här objektet",
  "TreeViewCollapseTitle": "Komprimera det här objektet",
  "CollectionDataEmptyFields": "Inga fält angavs för insamlingsdata.",
  "CollectionDataEmptyValue": "Inga data i din samling.",
  "CollectionAddRowButtonLabel": "Lägg till data i samlingen",
  "CollectionDeleteRowButtonLabel": "Ta bort den aktuella raden",
  "CollectionSaveAndAddButtonLabel": "Lägg till och spara",
  "CollectionDataItemShowErrorsLabel": "Visa radfel",
  "CollectionDataItemFieldRequiredLabel": "Fältet krävs.",
  "CollectionDataItemMissingFields": "Fältsamlingen är tom!",
  "InvalidUrlError": "Den angivna webbadressen är inte giltig",
  "CollectionDataSearch": "Sök",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "Läser in dina team",
  "MyTeamsMessageError": "Något gick fel när dina teams lästes in, försök senare eller uppdatera webbläsaren",
  "MyTeamsNoTeamsMessage": "Du har inga team.",
  "MyTeamsTeamChannelPublicMessage": "Offentliga kanaler",
  "MyTeamsTeamChannelTypeMessage": "Privata kanaler",
  "TeamChannelPickerFontIconFavoriteText": "Favorit",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Privat kanal",
  "TeamChannelPickerSugestionHeaderText": "Föreslagna teamkanaler",
  "TeamPickerButtonRemoveTitle": "avlägsna",
  "TeamPickernoResultsFoundText": "Inga team hittades",
  "TeamPickerSugestionsHeaderText": "Föreslagna team",
  "TeamsChannelPickerButtonRemoveTitle": "ta bort",
  "TeamsChannelPickerNoresultsFoundText": "Inga kanaler hittades",
  "ViewMore": "Visa mer",
  "DynamicFormLoading": "Laddar...",
  "DynamicFormPleaseWait": "Vänta...",
  "DynamicFormRequiredErrorMessage": "Du kan inte lämna det här tomt.",
  "DynamicFormTermPanelTitle": "Välj term",
  "DynamicFormEnterURLPlaceholder": "Ange en webbadress",
  "DynamicFormEnterDescriptionPlaceholder": "Alternativ text",
  "DynamicFormDialogValidationErrorTitle": "Valideringsfel",
  "DynamicFormDialogValidationErrorMessage": "Det finns valideringsfel, åtgärda dem innan du sparar.",
  "DynamicFormNumberValueMustBeGreaterThan": "Värdet måste vara större än {0}",
  "DynamicFormNumberValueMustBeBetween": "Värdet måste vara mellan {0} och {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Värdet måste vara lägre än {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Använd den här platsen:",
  "ListItemCommentDIalogDeleteSubText": "Vill du ta bort den här kommentaren?",
  "ListItemCommentsDialogDeleteTitle": "Bekräfta ta bort kommentar",
  "ListItemCommentsLabel": "Kommentarer",
  "ListItemCommentsNoCommentsLabel": "Det finns inga kommentarer",
  "OrgAssetsLinkLabel": "Din organisation",
  "MyTeamsMessageDontHaveTeams": "Du har inga teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Ange en term som du vill tagga",
  "ModernTaxonomyPickerTreeTitleSingle": "Välj en tagg",
  "ModernTaxonomyPickerTreeTitleMulti": "Välj en eller flera taggar",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Lägg till tagg",
  "ModernTaxonomyPickerApplyButtonText": "Använd",
  "ModernTaxonomyPickerCancelButtonText": "Avbryt",
  "ModernTaxonomyPickerLoadMoreText": "Läs in mer",
  "ModernTaxonomyPickerRemoveButtonText": "Ta bort",
  "ModernTaxonomyPickerPanelCloseButtonText": "Stäng",
  "ModernTaxonomyPickerNoResultsFound": "Inga resultat hittades",
  "ModernTaxonomyPickerSuggestionInLabel": "i",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
