require("./LinkFilePickerTab.module.css");
var styles = {
    filePicker: 'filePicker_f92cbf76',
    tabsContainer: 'tabsContainer_f92cbf76',
    tabContainer: 'tabContainer_f92cbf76',
    nav: 'nav_f92cbf76',
    tabHeaderContainer: 'tabHeaderContainer_f92cbf76',
    breadcrumbNav: 'breadcrumbNav_f92cbf76',
    breadcrumbNavItem: 'breadcrumbNavItem_f92cbf76',
    tab: 'tab_f92cbf76',
    tabOffset: 'tabOffset_f92cbf76',
    tabFiles: 'tabFiles_f92cbf76',
    scrollablePaneWrapper: 'scrollablePaneWrapper_f92cbf76',
    actionButtonsContainer: 'actionButtonsContainer_f92cbf76',
    actionButtons: 'actionButtons_f92cbf76',
    actionButton: 'actionButton_f92cbf76',
    tabHeader: 'tabHeader_f92cbf76',
    selectedTab: 'selectedTab_f92cbf76',
    header: 'header_f92cbf76',
    xlg: 'xlg_f92cbf76',
    xxlg: 'xxlg_f92cbf76',
    xxxlg: 'xxxlg_f92cbf76',
    xxxxlg: 'xxxxlg_f92cbf76',
    itemPickerTopBar: 'itemPickerTopBar_f92cbf76',
    commandBarNoChevron: 'commandBarNoChevron_f92cbf76',
    fileItem: 'fileItem_f92cbf76',
    folderItem: 'folderItem_f92cbf76',
    fileTypeIcon: 'fileTypeIcon_f92cbf76',
    fileTypeIconIcon: 'fileTypeIconIcon_f92cbf76',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_f92cbf76',
    iconColumnHeader: 'iconColumnHeader_f92cbf76',
    fileRow: 'fileRow_f92cbf76',
    folderRow: 'folderRow_f92cbf76',
    emptyFolder: 'emptyFolder_f92cbf76',
    emptyFolderImage: 'emptyFolderImage_f92cbf76',
    emptyFolderImageTag: 'emptyFolderImageTag_f92cbf76',
    emptyFolderTitle: 'emptyFolderTitle_f92cbf76',
    emptyFolderSubText: 'emptyFolderSubText_f92cbf76',
    emptyFolderMobile: 'emptyFolderMobile_f92cbf76',
    emptyFolderPc: 'emptyFolderPc_f92cbf76',
    emptyFolderIcon: 'emptyFolderIcon_f92cbf76',
    linkTextField: 'linkTextField_f92cbf76',
    localTabSinglePreview: 'localTabSinglePreview_f92cbf76',
    localTabSinglePreviewImage: 'localTabSinglePreviewImage_f92cbf76'
};
export default styles;
//# sourceMappingURL=LinkFilePickerTab.module.scss.js.map