require("./ControlsTest.module.css");
var styles = {
    controlsTest: 'controlsTest_f9492e6d',
    instruction: 'instruction_f9492e6d',
    'ms-motion-slideLeftIn': 'ms-motion-slideLeftIn_f9492e6d',
    'ms-motion-fadeIn': 'ms-motion-fadeIn_f9492e6d',
    'ms-motion-slideRightIn': 'ms-motion-slideRightIn_f9492e6d',
    container: 'container_f9492e6d',
    toggleFilter: 'toggleFilter_f9492e6d',
    controlFiltersContainer: 'controlFiltersContainer_f9492e6d',
    row: 'row_f9492e6d',
    listItem: 'listItem_f9492e6d',
    button: 'button_f9492e6d',
    label: 'label_f9492e6d',
    siteBreadcrumb: 'siteBreadcrumb_f9492e6d',
    carouselContent: 'carouselContent_f9492e6d',
    carouselButtonsContainer: 'carouselButtonsContainer_f9492e6d',
    carouselImageContent: 'carouselImageContent_f9492e6d',
    listViewWrapper: 'listViewWrapper_f9492e6d',
    dialogContainer: 'dialogContainer_f9492e6d',
    dialogContent: 'dialogContent_f9492e6d',
    dialogFooter: 'dialogFooter_f9492e6d',
    loader: 'loader_f9492e6d',
    'ms-motion-fadeOut': 'ms-motion-fadeOut_f9492e6d',
    'ms-motion-scaleDownIn': 'ms-motion-scaleDownIn_f9492e6d',
    'ms-motion-scaleDownOut': 'ms-motion-scaleDownOut_f9492e6d',
    'ms-motion-slideLeftOut': 'ms-motion-slideLeftOut_f9492e6d',
    'ms-motion-slideRightOut': 'ms-motion-slideRightOut_f9492e6d',
    'ms-motion-slideUpOut': 'ms-motion-slideUpOut_f9492e6d',
    'ms-motion-slideDownOut': 'ms-motion-slideDownOut_f9492e6d',
    'ms-motion-slideUpIn': 'ms-motion-slideUpIn_f9492e6d',
    'ms-motion-slideDownIn': 'ms-motion-slideDownIn_f9492e6d'
};
export default styles;
//# sourceMappingURL=ControlsTest.module.scss.js.map