import * as React from 'react';
export declare const DOCICONURL_XLSX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/xlsx.png";
export declare const DOCICONURL_DOCX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/docx.png";
export declare const DOCICONURL_PPTX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/pptx.png";
export declare const DOCICONURL_MPPX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/mpp.png";
export declare const DOCICONURL_PHOTO = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/photo.png";
export declare const DOCICONURL_PDF = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/pdf.png";
export declare const DOCICONURL_TXT = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/txt.png";
export declare const DOCICONURL_EMAIL = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/email.png";
export declare const DOCICONURL_CSV = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/csv.png";
export declare const DOCICONURL_ONE = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/one.png";
export declare const DOCICONURL_VSDX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/vsdx.png";
export declare const DOCICONURL_VSSX = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/vssx.png";
export declare const DOCICONURL_PUB = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/pub.png";
export declare const DOCICONURL_ACCDB = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/accdb.png";
export declare const DOCICONURL_ZIP = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/zip.png";
export declare const DOCICONURL_GENERIC = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/genericfile.png";
export declare const DOCICONURL_CODE = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/code.png";
export declare const DOCICONURL_HTML = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/html.png";
export declare const DOCICONURL_XML = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/xml.png";
export declare const DOCICONURL_SPO = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/spo.png";
export declare const DOCICONURL_VIDEO = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/video.png";
export declare const DOCICONURL_AUDIO = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/audio.png";
export declare const DOCICONURL_FOLDER = "https://static2.sharepointonline.com/files/fabric/assets/item-types/96/folder.png";
export declare const useUtils: () => {
    b64toBlob: (b64Data: any, contentType: string, sliceSize?: number) => Promise<Blob>;
    blobToBase64: (blob: Blob) => Promise<string>;
    getMentionCharIndex: (text: string, mentionDenotationChars: any, isolateChar: string) => any;
    hasValidChars: (text: string, allowedChars: any) => any;
    hasValidMentionCharIndex: (mentionCharIndex: number, text: string, isolateChar?: string, textPrefix?: string) => boolean;
    GetFileImageUrl: (file: string) => string;
    getShortName: (name: string) => string;
    isOndrive: (name: string) => Promise<boolean>;
    formatFileSize: (bytes: number, decimalPoint: number) => string;
    getFolderIcon: () => string;
    trimBeginDoubleSlash: (value: string) => string;
    checkIfCursorIsInsideContainer: (event: React.MouseEvent<HTMLDivElement>, containerRef: HTMLDivElement) => boolean;
    centerElement: (container: HTMLElement, elementToCenter: HTMLElement) => {
        left: number;
        top: number;
    };
    getScrollPosition: (_dataListContainerRef: {
        scrollTop: any;
        scrollHeight: any;
        clientHeight: any;
    }) => number;
    getInitials: (name: string) => string;
    getBase64Image: (img: any) => string;
    parseHtmlString: (htmlString: string) => string;
    getFileExtension: (fileName: string) => string;
};
//# sourceMappingURL=useUtils.d.ts.map