declare var define: any;

define([], () => {
  return {
    "Save": "Uložit",
    "Cancel": "Zrušit",
    'SiteBreadcrumbLabel': 'Menu',
    'ListViewGroupEmptyLabel': 'Prázdné',
    'WebPartTitlePlaceholder': 'Název webové části',
    'WebPartTitleLabel': 'Přidat název',
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Za několik vteřin",
      "L_RelativeDateTime_AFewSeconds": "Před pár vteřinami",
      "L_RelativeDateTime_AboutAMinuteFuture": "Asi za minutu",
      "L_RelativeDateTime_AboutAMinute": "Asi před minutou",
      "L_RelativeDateTime_XMinutesFuture": "Za {0} minuty||Za {0} minut",
      "L_RelativeDateTime_XMinutes": "{0} před minutou||{0} minutami",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Asi za hodinu",
      "L_RelativeDateTime_AboutAnHour": "Asi před hodinou",
      "L_RelativeDateTime_Tomorrow": "Zítra",
      "L_RelativeDateTime_Yesterday": "Včera",
      "L_RelativeDateTime_TomorrowAndTime": "Zítra v {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Včera v {0}",
      "L_RelativeDateTime_XHoursFuture": "Za {0} hodinu||V {0} hodin",
      "L_RelativeDateTime_XHours": "{0} před hodinou||{0} hodin před",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} v {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} den od teď||{0} dní od teď",
      "L_RelativeDateTime_XDays": "{0} před dnem||{0} dny před",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Dnes"
    },
    "SendEmailTo": "Odeslat e-mail {0}",
    "StartChatWith": "Zahájit chat s {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Aktualizujte svůj profil",

    "TaxonomyPickerNoTerms": "Množina neobsahuje žádné výrazy",
    "TaxonomyPickerExpandTitle": "Rozbalit tuto množinu výrazů",
    "TaxonomyPickerMenuTermSet": "Menu pro množinu výrazů",
    "TaxonomyPickerInLabel": "v",
    "TaxonomyPickerTermSetLabel": "Množina výrazů",
    "TaxonomyPickerTermsNotFound": "Následující vybrané výrazy nebyly nalezeny: {0}",
    "TaxonomyPickerInvalidTerms": "Opravte neplatné výrazy: {0}",

    "peoplePickerComponentTooltipMessage": "Výběr uživatelů",
    "peoplePickerComponentErrorMessage": "Povinné pole",
    "peoplePickerSuggestionsHeaderText": 'Navrhovaní lidé',
    "peoplePickerLoadingText": 'Načítání',
    "PeoplePickerSearchText": 'Načítání uživatelů',
    "PeoplePickerGroupNotFound": "Skupina nebyla nalezena.",

    "genericNoResultsFoundText": 'Žádné výsledky',

    "ListItemPickerSelectValue": 'Vyberte hodnotu',
    "ListItemAttachmentsActionDeleteIconTitle": 'Odstranit',
    "ListItemAttachmentsactionDeleteTitle": 'Odstranit',
    "ListItemAttachmentsfileDeletedMsg": 'Soubor {0} odstraněn',
    "ListItemAttachmentsfileDeleteError": 'Chyba odstraňování souboru: {0}, důvod {1}',
    "ListItemAttachmentserrorLoadAttachments": 'Chyba při načítání přílohy položky seznamu, důvod: {0}',
    "ListItemAttachmentsconfirmDelete": 'Opravdu chcete odeslat přílohu {0} do koše webu?',
    "ListItemAttachmentsdialogTitle": 'Příloha položky seznamu',
    "ListItemAttachmentsdialogOKbuttonLabel": 'OK',
    "ListItemAttachmentsdialogCancelButtonLabel": 'Zrušit',
    "ListItemAttachmentsdialogOKbuttonLabelOnDelete": 'Odstranit',
    "ListItemAttachmentsuploadAttachmentDialogTitle": 'Přidat přílohu',
    "ListItemAttachmentsuploadAttachmentButtonLabel": 'Přidat přílohu',
    "ListItemAttachmentsuploadAttachmentErrorMsg": 'Soubor {0} nebyl přiložen, důvod: {1}',
    "ListItemAttachmentsCommandBarAddAttachmentLabel": 'Přidat přílohu',
    "ListItemAttachmentsloadingMessage": 'Nahrávání souboru ...',
    "ListItemAttachmentslPlaceHolderIconText": 'Příloha položky seznamu',
    "ListItemAttachmentslPlaceHolderDescription": 'Prosíme, přidejte přílohu',
    "ListItemAttachmentslPlaceHolderButtonLabel": 'Přidat',

    "mapsErrorMessage": 'Při načítání mapy došlo k chybě',
    "mapsLoadingText": 'Načítání',
    "mapsSearchButtonText": 'Hledat',
    "mapsTitlePrefix": 'Mapa',

    "ListViewFilterLabel": "Filtrovat seznam",

    "HeaderNormalText": "Normální text",
    "HeaderH2": "Nadpis 1",
    "HeaderH3": "Nadpis 2",
    "HeaderH4": "Nadpis 3",
    "HeaderBlockQuote": "Citace",
    "AlignLeft": "Zarovnat vlevo",
    "AlignCenter": "Zarovnat na střed",
    "AlignRight": "Zarovnat vpravo",
    "AlignJustify": "Přizpůsobit",
    "ListBullet": "Seznam s odrážkami",
    "ListNumbered": "Číslovaný seznam",
    "StyleTitle": "Styl",
    "BoldTitle": "Tučné (Ctrl+B)",
    "ItalicTitle": "Kurzíva (Ctrl+I)",
    "UnderlineTitle": "Podtržení (Ctrl+U)",
    "AlignTitle": "Zarovnat",
    "ListTitle": "Seznam",
    "LinkTitle": "Odkaz",
    "ImageTitle": "Obrázek",
    "MoreTitle": "Více",
    "FormattingPaneTitle": "Formátování textu",
    "CloseButton": "Zavřít",
    "InsertLinkTitle": "Vložit odkaz",
    "InsertImageTitle": "Vložit obrázek",
    "AddressFieldLabel": "URL adresa",
    "TextToDisplayLabel": "Text k zobrazení",
    "SaveButtonLabel": "Uložit",
    "CancelButtonLabel": "Zrušit",
    "RemoveLinkLabel": "Odstranit odkaz",
    "ParagraphSectionTitle": "Odstavec",
    "HyperlinkSectionTitle": "Hyperlink",
    "UndoTitle": "Zpět (Ctrl+Z)",
    "RedoTitle": "Opakovat (Ctrl+Y)",
    "ClearFormattingTitle": "Odstranit veškeré formátování",
    "FontStyleTitle": "Styl písma",
    "FontSizeTitle": "Velikost písma",
    "StrikethroughTitle": "Přeškrtnuté",
    "SuperscriptTitle": "Horní index",
    "SubscriptTitle": "Dolní index",
    "FontColorLabel": "Barva písma",
    "AutomaticFontColor": "Automatická",
    "HighlightColorLabel": "Barva zvýraznění",
    "NoColorHighlightColor": "Žádná barva",
    "IncreaseIndentTitle": "Zvětšit odsazení",
    "DecreaseIndentTitle": "Změnšit odsazení",
    "ThemeColorsGroupName": "Barvy motivu",
    "HighlightColorsGroupName": "Barvy zvýraznění",
    "StandardColorsGroupName": "Standartní barvy",
    "CustomColorsGroupName": "Vlastní barvy",
    "ThemeColorDarker": "Tmavší",
    "ThemeColorDark": "Tmavý",
    "ThemeColorDarkAlt": "Alternativní tmavý",
    "ThemeColorPrimary": "Primární",
    "ThemeColorSecondary": "Sekundární",
    "ThemeColorTertiary": "Ostatní",
    "ThemeColorNeutralSecondary": "Neutralní sekundární",
    "ThemeColorNeutralPrimaryAlt": "Neutrální alternativní primární",
    "ThemeColorNeutralPrimary": "Neutrální primární",
    "ThemeColorNeutralDark": "Neutrální tmavý",
    "HighlightColorYellow": "Žlutá",
    "HighlightColorGreen": "Zelená",
    "HighlightColorAqua": "Bleděmodrá",
    "HighlightColorMagenta": "Purpurová",
    "HighlightColorBlue": "Modrá",
    "HighlightColorRed": "Červená",
    "HighlightColorDarkblue": "Tmavomodrá",
    "HighlightColorTeal": "Zelenomodrá",
    "HighlightColorDarkgreen": "Tmavězelená",
    "HighlightColorPurple": "Fialová",
    "HighlightColorMaroon": "Kaštanově hnědá",
    "HighlightColorGold": "Zlatá",
    "HighlightColorDarkgrey": "Tmavěšedá",
    "HighlightColorGrey": "Šedá",
    "HighlightColorBlack": "Černá",
    "StandardColorDarkred": "Tmavěčervená",
    "StandardColorRed": "Červená",
    "StandardColorOrange": "Oranžová",
    "StandardColorYellow": "Žlutá",
    "StandardColorLightgreen": "Světlezelená",
    "StandardColorGreen": "Zelená",
    "StandardColorLightblue": "Světlemodrá",
    "StandardColorBlue": "Modrá",
    "StandardColorDarkblue": "Tmavěmodrá",
    "StandardColorPurple": "Fialová",

    "DatePickerMonthLongJanuary": "leden",
    "DatePickerMonthShortJanuary": "led",
    "DatePickerMonthLongFebruary": "únor",
    "DatePickerMonthShortFebruary": "úno",
    "DatePickerMonthLongMarch": "březen",
    "DatePickerMonthShortMarch": "bře",
    "DatePickerMonthLongApril": "duben",
    "DatePickerMonthShortApril": "dub",
    "DatePickerMonthLongMay": "květen",
    "DatePickerMonthShortMay": "kvě",
    "DatePickerMonthLongJune": "červen",
    "DatePickerMonthShortJune": "čvn",
    "DatePickerMonthLongJuly": "červenec",
    "DatePickerMonthShortJuly": "čvc",
    "DatePickerMonthLongAugust": "srpen",
    "DatePickerMonthShortAugust": "srp",
    "DatePickerMonthLongSeptember": "září",
    "DatePickerMonthShortSeptember": "zář",
    "DatePickerMonthLongOctober": "říjen",
    "DatePickerMonthShortOctober": "říj",
    "DatePickerMonthLongNovember": "listopad",
    "DatePickerMonthShortNovember": "lis",
    "DatePickerMonthLongDecember": "prosinec",
    "DatePickerMonthShortDecember": "pro",
    "DatePickerDayLongSunday": "neděle",
    "DatePickerDayShortSunday": "ne",
    "DatePickerDayLongMonday": "pondělí",
    "DatePickerDayShortMonday": "po",
    "DatePickerDayLongTuesday": "úterý",
    "DatePickerDayShortTuesday": "út",
    "DatePickerDayLongWednesday": "středa",
    "DatePickerDayShortWednesday": "st",
    "DatePickerDayLongThursday": "čtvrtek",
    "DatePickerDayShortThursday": "čt",
    "DatePickerDayLongFriday": "pátek",
    "DatePickerDayShortFriday": "pá",
    "DatePickerDayLongSaturday": "sobota",
    "DatePickerDayShortSaturday": "so",
    "DatePickerGoToToday": "Dnes",
    "DatePickerIsRequiredErrorMessage": "Povinné pole",
    "DatePickerInvalidInputErrorMessage": "Neplatné zadání",
    "DatePickerIsOutOfBoundsErrorMessage": "Hodnota mimo povolený rozsah",
    "DateTimePickerDate": "Datum",
    "DateTimePickerTime": "Čas",
    "DateTimePickerTimeSeparator": ":",
    "DateTimePickerHourValueInvalid": "Neplatná hodnota hodin",
    "DateTimePickerMinuteValueInvalid": "Neplatná hodnota minut",
    "DateTimePickerSecondValueInvalid": "Neplatná hodnota vteřin",
    "DateTimePickerTextErrorMessage":"Zadejte platné datum",

    "AddFileButtonLabel": "Přidat soubor",
    "AddImageButtonLabel": "Přidat obrázek",
    "AriaCellValue": "{0} sloupec, {1}",
    "FilePickerCancelButtonLabel": "Zrušit",
    "CantValidateValidationMessage": "Odkaz se nepodařilo ověřit. Zkontrolujte odkaz a zkuste provést znovu.",
    "ChangeFileLinkLabel": "Změnit soubor",
    "ChangeImageLinkLabel": "Změnit obrázek",
    "ChooseFileLinkLabel": "Vybrat soubor",
    "ChooseImageLinkLabel": "Vybrat obrázek",
    "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    "CopyrightWarning": "Jste odpovědný(á) za respektování práv ostatních, včetně práv autorských.",
    "CreativeCommonsMessage": "Tyto výsledky jsou označeny licencí Creative Commons. Zkontrolujte a zajistěte, že jste v souladu s touto licencí.",
    "DateFormat": "dd.MM.yyyy HH:mm A",
    "DocumentLabelTemplate": "{0}, dokument, upravený {1}, upravil {2}, soukromý",
    "DocumentLibraries": "Knihovny dokumentů",
    "EditedByNamePlate": "upravil ",
    "EmptyFileSize": "0 bajtů",
    "FilePickerHeader": "Výběr souboru",
    "FileSizeField": "Velikost souboru",
    "FolderAltText": "Složka",
    "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    "FolderIconUrl": "https://modernb.akamai.odsp.cdn.office.net/files/fabric-cdn-prod_20210703.001/assets/item-types/20/folder.svg",
    "FolderLabelTemplate": "{0}, složka, upravená {1}, upravil {2}, {3} položek, soukromá",
    "FromLinkLinkLabel": "Z odkazu",
    "ImageAltText": ".{0} obrázek",
    "ImageAriaLabelTemplate": ".{0} obrázek",
    "ImageLayoutPlaceholderText": "Rozložení",
    "ImageSizePlaceholderText": "Velikost obrázku",
    "ItemChildCountField": "Počet podřízených položek",
    "LayoutOptionAll": "Vše",
    "LayoutOptionSquare": "Čtverec",
    "LayoutOptionTall": "Vysoký",
    "LayoutOptionWide": "Široký",
    "LearnMoreLink": "Zjistit víc.",
    "LicenseOptionAll": "Vše",
    "LicenseOptionAny": "Pouze Creative Commons",
    "LicensePlaceholderText": "Licence",
    "LinkFileInstructions": "Přidat odkaz na soubor uložený ve službě OneDrive for Business nebo SharePoint Online",
    "LinkHeader": "Z odkazu",
    "LinkImageInstructions": "Přidat odkaz na obrázek uložený ve službě OneDrive for Business nebo SharePoint Online",
    "ListLayoutAriaLabel": "Možnosti zobrazení. {0}  {1} .",
    "ListLayoutCompact": "Kompaktní seznam",
    "ListLayoutCompactDescription": "Zobrazit položky a podrobnosti v kompaktním seznamu",
    "ListLayoutList": "Seznam",
    "ListLayoutListDescrition": "Zobrazení položek a podrobností v seznamu",
    "ListLayoutTile": "Dlaždice",
    "ListLayoutTileDescription": "Zobrazení položek s náhledy v dlaždicích",
    "ListOptionsAlt": "Možnosti zobrazení. {0}  vybráno .",
    "ListOptionsTitle": "Otevřit možnosti zobrazení",
    "Loading": "Načítání...",
    "ModifiedByField": "Upraveno",
    "ModifiedField": "Datum úpravy",
    "NameField": "Název",
    "No": "Ne",
    "ProvidedValueIsInvalid": "Poskytnutá hodnota je neplatná",
    "NoExternalLinksValidationMessage": "Odkazování na soubory je podporováno pouze v rámci Vaší organizace.",
    "NoImageValidationMessage": "Toto není odkaz na soubor, který je podporován. Lze vložit pouze odkaz na obrázek.",
    "NoRecentFiles": "Žádné nedávné soubory",
    "NoRecentFilesDescription": "Zkuste vybrat soubor z vašeho webu, nebo jej nahrajte z vašeho zařízení.",
    "NoResultsBadEnglish": "Neexistují výsledky hledání. Zkuste změnit parametry filtru.",
    "ODModifiedField": "Upraveno",
    "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    "ODRowArialLabelTemplate": "{0}, {1}, upraveno {2}, upravil {3}, {4}, {5}",
    "OneDriveConfirmDialogBody": "Tato položka je ve Vašem OneDrive. Soubory a složky na OneDrive jsou soukromé, dokud je nesdílíte. Sdíleli jste tento soubor se členy Vašeho webu, aby k němu měli přístup?",
    "OneDriveConfirmDialogTitle": "Kontrola...",
    "OneDriveEmptyFolderAlt": "Prázdná složka",
    "OneDriveEmptyFolderDescription": "Pro přidání souborů přejděte na váš OneDrive. Do této složky můžete nahrát soubory také s použitím aplikace OneDrive pro váš počítač.",
    "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    "OneDriveEmptyFolderTitle": "Tato složka je prázdná",
    "OneDriveRootFolderName": "Soubory",
    "OpenButtonLabel": "Otevřít",
    "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    "OrgAssetsTabLabel": "Obrázky a soubory ve vaší organizaci",
    "PoweredByBing": "Spravované Bingem",
    "RecentDocumentsHeader": "Nedávné dokumenty",
    "RecentImagesHeader": "Nedávné obrázky",
    "RecentLinkLabel": "Nedávné",
    "SearchBoxPlaceholder": "Hledání na webu",
    "SearchResultAlt": "Výsledky obrázků pro {0}.",
    "SearchResultAriaLabel": "Stiskněte Enter pro otevření obrázku na nové záložce.",
    "Selected": "vybráno",
    "SharingField": "Sdílení",
    "SharingPrivate": "Soukromý",
    "SharingShared": "Sdílený",
    "SiteLinkLabel": "Web",
    "SizeOptionAll": "Vše",
    "SizeOptionExtraLarge": "Extra velký",
    "SizeOptionLarge": "Velký",
    "SizeOptionMedium": "Střední",
    "SizeOptionSmall": "Malý",
    "SizeUnit": [
      "bajty",
      "kB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    "SorryWebSearch": "Omlouváme se, tato funkce není implementovaná, jelikož by to vyžadovalo Bing API klíč.",
    "SortedAscending": "Řazení vzestupně (A do Z)",
    "SortedDescending": "Řazení sestupně (Z do A)",
    "TypeAriaLabel": "Operace sloupce Typ souboru, klikněte pro řazení podle typu souboru",
    "UploadFileHeader": "Nahrát soubor",
    "UploadImageHeader": "Nahrát obrázek",
    "UploadLinkLabel": "Nahrát",
    "WebSearchLinkLabel": "Hledání na webu",
    "StockImagesLinkLabel": "Skladové obrázky",
    "StockImagesHeader": "Skladové obrázky",
    "Yes": "Ano",

    "NewFolderNamePlaceholder": "Zadejte název složky",
    "FolderFilterBoxPlaceholder": "Filtrovat složky podle názvu",
    "FolderExplorerLoading": "Načítání složek...",
    "FolderExplorerNoItems": "Tato složka neobsahuje žádné podsložky.",
    "NewFolderIncorrectSymbolsError": "Zadejte název, který neobsahuje žádný z těchto znaků: \" * : < > ? / \ |.",
    "SomethingWentWrong": "Něco se pokazilo",
    "SelectedLabel": "Vybráno",
    "SelectIcon": "Vybrat ikonu",

    "TreeViewExpandTitle": "Rozbalit položku",
    "TreeViewCollapseTitle": "Sbalit položku",

    "CollectionDataEmptyFields": "Pro kolekci nebyla definována žádná pole.",
    "CollectionDataEmptyValue": "Kolekce neobsahuje data.",
    "CollectionAddRowButtonLabel": "Přidat data do kolekce",
    "CollectionDeleteRowButtonLabel": "Odstranit aktuální řádek",
    "CollectionSaveAndAddButtonLabel": "Přidat a uložit",
    "CollectionDataItemShowErrorsLabel": "Zobrazit chyby řádku",
    "CollectionDataItemFieldRequiredLabel": "Pole je povinné.",
    "CollectionDataItemMissingFields": "Kolekce polí je prázdná!",
    "InvalidUrlError": "Zapsaná URL adresa je neplatná",
    "CollectionDataSearch": "Hledat",
    "CollectionDataMinimumUsersDefaultMessage": "Minmální počet uživatelů k výběru je {0}",

    "MyTeamsLoadingMessage": "načítání vašich týmů",
    "MyTeamsMessageError": "Při načítání vašich týmu došlo k chybě. Opakujte akci později, nebo proveďte obnovení stránky v prohlížeči (F5)",
    "MyTeamsNoTeamsMessage": "Nemáte žádné týmy",
    "MyTeamsTeamChannelPublicMessage": "Veřejné kanály",
    "MyTeamsTeamChannelTypeMessage": "Privátní kanály",
    "TeamChannelPickerFontIconFavoriteText": "Oblíbené",
    "TeamChannelPickerFontIconPrivateChannelTitle": "Privátní kanál",
    "TeamChannelPickerSugestionHeaderText": "Doporučené kanály",
    "TeamPickerButtonRemoveTitle": "odstranit",
    "TeamPickernoResultsFoundText": "Týmy nenalezeny",
    "TeamPickerSugestionsHeaderText": "Doporučené týmy",
    "TeamsChannelPickerButtonRemoveTitle": "odstranit",
    "TeamsChannelPickerNoresultsFoundText": "Kanály nenalezeny",

    "ViewMore": "Zobrazit více",

    "DynamicFormLoading": "Načítání...",
    "DynamicFormPleaseWait": "Počkejte...",
    "DynamicFormRequiredErrorMessage": "Toto pole nemůže zůstat prázdné.",
    "DynamicFormTermPanelTitle": "Vybrat výraz",
    "DynamicFormEnterURLPlaceholder": "Zadejte URL",
    "DynamicFormEnterDescriptionPlaceholder": "Alternativní popis",
    "DynamicFormDialogValidationErrorTitle": "Chyba validace",
    "DynamicFormDialogValidationErrorMessage": "Formulář obsahuje chyby validace. Před uložením je potřeba tyto chyby odstranit.",
    "DynamicFormNumberValueMustBeGreaterThan": "Hodnota musí být větší než {0}",
    "DynamicFormNumberValueMustBeBetween": "Hodnota musí být mezi {0} a {1}",
    "DynamicFormNumberValueMustBeLowerThan": "Hodnota musí být menší než {0}",
    "customDisplayName": "Použít toto umístění:",
    "ListItemCommentDIalogDeleteSubText": "Opravdu chcete odstranit tento komentář?",
    "ListItemCommentsDialogDeleteTitle": "Potvrdit odstranění komentáře",
    "ListItemCommentsLabel": "Komentáře",
    "ListItemCommentsNoCommentsLabel": "Žádné komentáře",
    "OrgAssetsLinkLabel": "Vaše organizace",

    "ModernTaxonomyPickerDefaultPlaceHolder": "Zapište výraz pro označení",
    "ModernTaxonomyPickerTreeTitleSingle": "Vybrat výraz",
    "ModernTaxonomyPickerTreeTitleMulti": "Vyberte jeden nebo více výrazů",
    "ModernTaxonomyPickerAddTagButtonTooltip": "Přidat výraz",
    "ModernTaxonomyPickerApplyButtonText": "Použít",
    "ModernTaxonomyPickerCancelButtonText": "Zrušit",
    "ModernTaxonomyPickerLoadMoreText": "Načíst více",
    "ModernTaxonomyPickerRemoveButtonText": "Odstranit",
    "ModernTaxonomyPickerPanelCloseButtonText": "Zavřít",
    "ModernTaxonomyPickerNoResultsFound": "Žádné výsledky",
    "ModernTaxonomyPickerSuggestionInLabel": "v",

    "ModernAudioPlay": "Přehrát",
    "ModernAudioPause": "Pozastavit",
    "ModernAudioIncVol": "Přidat hlasitost",
    "ModernAudioDecVol": "Ubrat hlasitost",
    "ModernAudioMute": "Ztlumit",

    "ProgressStepsIndicatorNoSteps": "Žádné kroky",
    "TermSertNaviagtionErrorMessage": "Výraz nebyl nalezen",
    "TermSetNavigationNoTerms": "Výrazy nejsou definovány",

    "UploadFilesButtonLabel": "Přidat",
    "UpLoadFilesDeleteButtonLabel": "Odstranit",
    "UpLoadFilesDragDropLabel": "Přetáhněte soubory sem, nebo klikněte na tlačítko Přidat",
    "UpLoadFilesSelectAllLabel": "Vybrat vše",
    "UploadFilesUploadButtonLabel": "Nahrát",
};
});
