declare var define: any;

define([], () => {
  return {
    Save: "Uložit",
    Cancel: "Zrušit",

    SiteBreadcrumbLabel: "Navigace na webu",

    ListViewGroupEmptyLabel: "Prázdné",

    WebPartTitlePlaceholder: "Název webové části",
    WebPartTitleLabel: "Přidat název",

    DateTime: {
      L_RelativeDateTime_AFewSecondsFuture: "Za pár sekund",
      L_RelativeDateTime_AFewSeconds: "Před pár sekundami",
      L_RelativeDateTime_AboutAMinuteFuture: "Za zhruba minutu",
      L_RelativeDateTime_AboutAMinute: "Před zhruba minutou",
      L_RelativeDateTime_XMinutesFuture: "Za {0} minutu||Za {0} minut",
      L_RelativeDateTime_XMinutes: "Před {0} minutou||Před {0} minutami",
      L_RelativeDateTime_XMinutesFutureIntervals: "1||2-",
      L_RelativeDateTime_XMinutesIntervals: "1||2-",
      L_RelativeDateTime_AboutAnHourFuture: "Za zhruba hodinu",
      L_RelativeDateTime_AboutAnHour: "Před zhruba hodinou",
      L_RelativeDateTime_Tomorrow: "Zítra",
      L_RelativeDateTime_Yesterday: "Včera",
      L_RelativeDateTime_TomorrowAndTime: "Zítra v {0}",
      L_RelativeDateTime_YesterdayAndTime: "Včera v {0}",
      L_RelativeDateTime_XHoursFuture: "Za {0} hodinu||Za {0} hodin",
      L_RelativeDateTime_XHours: "Před {0} hodinou||Před {0} hodinami",
      L_RelativeDateTime_XHoursFutureIntervals: "1||2-",
      L_RelativeDateTime_XHoursIntervals: "1||2-",
      L_RelativeDateTime_DayAndTime: "{0} v {1}",
      L_RelativeDateTime_XDaysFuture: "Za {0} den||Za {0} dnů",
      L_RelativeDateTime_XDays: "Před {0} dnem||Před {0} dny",
      L_RelativeDateTime_XDaysFutureIntervals: "1||2-",
      L_RelativeDateTime_XDaysIntervals: "1||2-",
      L_RelativeDateTime_Today: "Dnes",
    },
    SendEmailTo: "Poslat e-mail na adresu {0}",
    StartChatWith: "Spustit chat s {0}",
    Contact: "Kontakt",
    UpdateProfile: "Aktualizovat profil",

    TaxonomyPickerNoTerms: "Sada termínů neobsahuje žádné termíny",
    TaxonomyPickerExpandTitle: "Rozbalit tuto sadu termínů",
    TaxonomyPickerMenuTermSet: "Nabídka sady termínů",
    TaxonomyPickerInLabel: "v",
    TaxonomyPickerTermSetLabel: "Sada termínů",
    TaxonomyPickerTermsNotFound: "Následující vybraný(é) termín(y) nebyly nalezeny v úložišti termínů: {0}",
    TaxonomyPickerInvalidTerms: "Opravte neplatné termíny: {0}",

    peoplePickerComponentTooltipMessage: "Výběr uživatelů",
    peoplePickerComponentErrorMessage: "Povinné pole",
    peoplePickerSuggestionsHeaderText: "Navrhovaní uživatelé",
    peoplePickerLoadingText: "Načítání",
    PeoplePickerSearchText: "Hledání uživatelů",
    PeoplePickerGroupNotFound: "Skupinu se nepodařilo najít.",

    genericNoResultsFoundText: "Nebyly nalezeny žádné výsledky",

    ListItemPickerSelectValue: "Vybrat hodnotu",

    ListItemAttachmentsActionDeleteIconTitle: "Odstranit",
    ListItemAttachmentsactionDeleteTitle: "Odstranit",
    ListItemAttachmentsfileDeletedMsg: "Soubor {0} odstraněn",
    ListItemAttachmentsfileDeleteError: "Chyba při odstraňování souboru: {0}, důvod {1}",
    ListItemAttachmentserrorLoadAttachments:
      "Chyba při načítání příloh položky seznamu, důvod: {0}",
    ListItemAttachmentsconfirmDelete:
      "Opravdu chcete poslat přílohu {0} do koše webu?",
    ListItemAttachmentsdialogTitle: "Příloha položky seznamu",
    ListItemAttachmentsdialogOKbuttonLabel: "OK",
    ListItemAttachmentsdialogCancelButtonLabel: "Zrušit",
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: "Odstranit",
    ListItemAttachmentsuploadAttachmentDialogTitle: "Přidat přílohu",
    ListItemAttachmentsuploadAttachmentButtonLabel: "Přidat přílohu",
    ListItemAttachmentsuploadAttachmentErrorMsg:
      "Soubor {0} nebyl přiložen, důvod: {1}",
    ListItemAttachmentsCommandBarAddAttachmentLabel: "Přidat přílohu",
    ListItemAttachmentsloadingMessage: "Nahrávám soubor...",
    ListItemAttachmentslPlaceHolderIconText: "Příloha položky seznamu",
    ListItemAttachmentslPlaceHolderDescription: "Přidat přílohu",
    ListItemAttachmentslPlaceHolderButtonLabel: "Přidat",

    mapsErrorMessage: "Při načítání mapy došlo k chybě",
    mapsLoadingText: "Načítání",
    mapsSearchButtonText: "Hledat",
    mapsTitlePrefix: "Mapa:",

    ListViewFilterLabel: "Filtrovat seznam",

    HeaderNormalText: "Normální text",
    HeaderH2: "Nadpis 2",
    HeaderH3: "Nadpis 3",
    HeaderH4: "Nadpis 4",
    HeaderBlockQuote: "Citace",
    HeaderMonospaced: "Neproporcionální",
    AlignLeft: "Zarovnat vlevo",
    AlignCenter: "Zarovnat na střed",
    AlignRight: "Zarovnat vpravo",
    AlignJustify: "Do bloku",
    ListBullet: "Odrážkový seznam",
    ListNumbered: "Číslovaný seznam",
    StyleTitle: "Styl",
    BoldTitle: "Tučné (Ctrl+B)",
    ItalicTitle: "Kurzíva (Ctrl+I)",
    UnderlineTitle: "Podtržené (Ctrl+U)",
    AlignTitle: "Zarovnání",
    ListTitle: "Seznam",
    LinkTitle: "Hypertextový odkaz",
    ImageTitle: "Obrázek",
    MoreTitle: "Více",
    FormattingPaneTitle: "Formátování textu",
    CloseButton: "Zavřít",
    InsertLinkTitle: "Vložit odkaz",
    InsertImageTitle: "Vložit obrázek",
    AddressFieldLabel: "Adresa",
    TextToDisplayLabel: "Zobrazovaný text",
    SaveButtonLabel: "Uložit",
    CancelButtonLabel: "Zrušit",
    RemoveLinkLabel: "Odebrat odkaz",
    ParagraphSectionTitle: "Odstavec",
    HyperlinkSectionTitle: "Hypertextový odkaz",
    UndoTitle: "Zpět (Ctrl+Z)",
    RedoTitle: "Znovu (Ctrl+Y)",
    ClearFormattingTitle: "Vymazat veškeré formátování",
    FontStyleTitle: "Styl písma",
    FontSizeTitle: "Velikost písma",
    StrikethroughTitle: "Přeškrtnuté",
    SuperscriptTitle: "Horní index",
    SubscriptTitle: "Dolní index",
    FontColorLabel: "Barva písma",
    AutomaticFontColor: "Automatická",
    HighlightColorLabel: "Barva zvýraznění",
    NoColorHighlightColor: "Bez barvy",
    IncreaseIndentTitle: "Zvětšit odsazení",
    DecreaseIndentTitle: "Zmenšit odsazení",
    ThemeColorsGroupName: "Barvy motivu",
    HighlightColorsGroupName: "Barvy zvýraznění",
    StandardColorsGroupName: "Standardní barvy",
    CustomColorsGroupName: "Vlastní barvy",
    ThemeColorDarker: "Tmavší motiv",
    ThemeColorDark: "Tmavý motiv",
    ThemeColorDarkAlt: "Tmavý alternativní motiv",
    ThemeColorPrimary: "Primární motiv",
    ThemeColorSecondary: "Sekundární motiv",
    ThemeColorTertiary: "Neutrální terciární",
    ThemeColorNeutralSecondary: "Neutrální sekundární",
    ThemeColorNeutralPrimaryAlt: "Neutrální primární alternativa",
    ThemeColorNeutralPrimary: "Neutrální primární",
    ThemeColorNeutralDark: "Neutrální tmavá",
    HighlightColorYellow: "Žlutá",
    HighlightColorGreen: "Zelená",
    HighlightColorAqua: "Tyrkysová",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Modrá",
    HighlightColorRed: "Červená",
    HighlightColorDarkblue: "Tmavě modrá",
    HighlightColorTeal: "Modrozelená",
    HighlightColorDarkgreen: "Tmavě zelená",
    HighlightColorPurple: "Fialová",
    HighlightColorMaroon: "Vínová",
    HighlightColorGold: "Zlatá",
    HighlightColorDarkgrey: "Tmavě šedá",
    HighlightColorGrey: "Šedá",
    HighlightColorBlack: "Černá",
    StandardColorDarkred: "Tmavě červená",
    StandardColorRed: "Červená",
    StandardColorOrange: "Oranžová",
    StandardColorYellow: "Žlutá",
    StandardColorLightgreen: "Světle zelená",
    StandardColorGreen: "Zelená",
    StandardColorLightblue: "Světle modrá",
    StandardColorBlue: "Modrá",
    StandardColorDarkblue: "Tmavě modrá",
    StandardColorPurple: "Fialová",

    DatePickerMonthLongJanuary: "Leden",
    DatePickerMonthShortJanuary: "Led",
    DatePickerMonthLongFebruary: "Únor",
    DatePickerMonthShortFebruary: "Úno",
    DatePickerMonthLongMarch: "Březen",
    DatePickerMonthShortMarch: "Bře",
    DatePickerMonthLongApril: "Duben",
    DatePickerMonthShortApril: "Dub",
    DatePickerMonthLongMay: "Květen",
    DatePickerMonthShortMay: "Kvě",
    DatePickerMonthLongJune: "Červen",
    DatePickerMonthShortJune: "Čvn",
    DatePickerMonthLongJuly: "Červenec",
    DatePickerMonthShortJuly: "Čvc",
    DatePickerMonthLongAugust: "Srpen",
    DatePickerMonthShortAugust: "Srp",
    DatePickerMonthLongSeptember: "Září",
    DatePickerMonthShortSeptember: "Zář",
    DatePickerMonthLongOctober: "Říjen",
    DatePickerMonthShortOctober: "Říj",
    DatePickerMonthLongNovember: "Listopad",
    DatePickerMonthShortNovember: "Lis",
    DatePickerMonthLongDecember: "Prosinec",
    DatePickerMonthShortDecember: "Pro",
    DatePickerDayLongSunday: "Neděle",
    DatePickerDayShortSunday: "Ne",
    DatePickerDayLongMonday: "Pondělí",
    DatePickerDayShortMonday: "Po",
    DatePickerDayLongTuesday: "Úterý",
    DatePickerDayShortTuesday: "Út",
    DatePickerDayLongWednesday: "Středa",
    DatePickerDayShortWednesday: "St",
    DatePickerDayLongThursday: "Čtvrtek",
    DatePickerDayShortThursday: "Čt",
    DatePickerDayLongFriday: "Pátek",
    DatePickerDayShortFriday: "Pá",
    DatePickerDayLongSaturday: "Sobota",
    DatePickerDayShortSaturday: "So",
    DatePickerGoToToday: "Dnes",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Datum",
    DateTimePickerTime: "Čas",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Nesprávná hodnota hodin",
    DateTimePickerMinuteValueInvalid: "Nesprávná hodnota minut",
    DateTimePickerSecondValueInvalid: "Nesprávná hodnota sekund",
    DateTimePickerTextErrorMessage: "Zadejte platné datum",

    AddFileButtonLabel: "Přidat soubor",
    AddImageButtonLabel: "Přidat obrázek",
    AriaCellValue: "{0} sloupec, {1}",
    FilePickerCancelButtonLabel: "Zrušit",
    CantValidateValidationMessage:
      "Nepodařilo se ověřit tento odkaz. Zkontrolujte prosím odkaz a zkuste to znovu.",
    ChangeFileLinkLabel: "Změnit soubor",
    ChangeImageLinkLabel: "Změnit obrázek",
    ChooseFileLinkLabel: "Vybrat soubor",
    ChooseImageLinkLabel: "Vybrat obrázek",
    CopyrightUrl: "https://www.microsoft.com/cs-cz/legal/copyright/default.aspx",
    CopyrightWarning:
      "Je vaší odpovědností respektovat práva ostatních, včetně autorských práv.",
    CreativeCommonsMessage:
      "Tyto výsledky jsou označeny licencemi Creative Commons. Prostudujte si licence, abyste se ujistili, že splňujete jejich požadavky.",
    DateFormat: "DD.MM.YYYY HH:mm",
    DocumentLabelTemplate:
      "{0}, Dokument, Upraveno {1}, upravil {2}, Soukromé",
    DocumentLibraries: "Knihovny dokumentů",
    EditedByNamePlate: "upravil(a) ",
    EmptyFileSize: "0 bajtů",
    FilePickerHeader: "Výběr souboru",
    FileSizeField: "Velikost souboru",
    FolderAltText: "Složka",
    FolderBackPlate:
      "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate:
      "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl:
      "https://modernb.akamai.odsp.cdn.office.net/files/fabric-cdn-prod_20210703.001/assets/item-types/20/folder.svg",
    FolderLabelTemplate:
      "{0}, Složka, Upraveno {1}, upravil {2}, {3} položek, Soukromé",
    FromLinkLinkLabel: "Z odkazu",
    ImageAltText: ".{0} Obrázek",
    ImageAriaLabelTemplate: ".{0} Obrázek",
    ImageLayoutPlaceholderText: "Rozvržení",
    ImageSizePlaceholderText: "Velikost obrázku",
    ItemChildCountField: "Počet podřízených položek",
    LayoutOptionAll: "Vše",
    LayoutOptionSquare: "Čtvercové",
    LayoutOptionTall: "Vysoké",
    LayoutOptionWide: "Široké",
    LearnMoreLink: "Další informace.",
    LicenseOptionAll: "Vše",
    LicenseOptionAny: "Pouze Creative Commons",
    LicensePlaceholderText: "Licence",
    LinkFileInstructions:
      "Vložte odkaz na soubor v OneDrive pro firmy nebo SharePoint Online",
    LinkHeader: "Z odkazu",
    LinkImageInstructions:
      "Vložte odkaz na obrázek v OneDrive pro firmy nebo SharePoint Online",
    ListLayoutAriaLabel: "Možnosti zobrazení. {0} {1}.",
    ListLayoutCompact: "Kompaktní zobrazení",
    ListLayoutCompactDescription:
      "Zobrazit položky a podrobnosti v kompaktním seznamu",
    ListLayoutList: "Zobrazení seznamu",
    ListLayoutListDescrition:
      "Zobrazit položky a podrobnosti v seznamu",
    ListLayoutTile: "Zobrazení dlaždic",
    ListLayoutTileDescription:
      "Zobrazit položky s náhledy dlaždic",
    ListOptionsAlt: "Možnosti zobrazení. {0} vybráno.",
    ListOptionsTitle: "Otevřít nabídku možností zobrazení",
    Loading: "Načítám...",
    ModifiedByField: "Upravil(a)",
    ModifiedField: "Datum úpravy",
    NameField: "Název",
    No: "Ne",
    ProvidedValueIsInvalid: "Poskytnutá hodnota je neplatná",
    NoExternalLinksValidationMessage:
      "Podporujeme pouze odkazy na soubory ve vaší vlastní organizaci.",
    NoImageValidationMessage:
      "Toto není odkaz na podporovaný typ souboru. Můžete odkazovat pouze na obrázek.",
    NoRecentFiles: "Žádné nedávné soubory",
    NoRecentFilesDescription:
      "Zkuste vybrat soubor z vašeho webu, nebo nahrajte soubor z vašeho zařízení.",
    NoResultsBadEnglish:
      "Nebyly nalezeny žádné výsledky. Zkuste prosím upravit filtrační možnosti.",
    ODModifiedField: "Upraveno",
    ODPhotoIconUrl:
      "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate:
      "{0}, {1}, Upraveno {2}, upravil {3}, {4}, {5}",
    OneDriveConfirmDialogBody:
      "Tato položka pochází z vašeho OneDrivu. Soubory a složky na OneDrivu jsou soukromé, pokud je nesdílíte. Sdíleli jste tento soubor s členy svého webu, aby k němu měli přístup?",
    OneDriveConfirmDialogTitle: "Jen pro ověření...",
    OneDriveEmptyFolderAlt: "Prázdná složka",
    OneDriveEmptyFolderDescription:
      "Chcete-li přidat soubory, přejděte do svého OneDrivu. Soubory můžete do této složky také přidat pomocí aplikace OneDrive pro váš počítač.",
    OneDriveEmptyFolderIconUrl:
      "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Tato složka je prázdná",
    OneDriveRootFolderName: "Soubory",
    OpenButtonLabel: "Otevřít",
    PhotoIconUrl:
      "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Obrázky a soubory poskytované vaší organizací",
    PoweredByBing: "Využívá Bing",
    RecentDocumentsHeader: "Nedávné dokumenty",
    RecentImagesHeader: "Nedávné obrázky",
    RecentLinkLabel: "Nedávné",
    SearchBoxPlaceholder: "Vyhledat na webu",
    SearchResultAlt: "Výsledek obrázku pro {0}.",
    SearchResultAriaLabel:
      "Stiskněte Enter pro otevření zdroje obrázku v nové záložce.",
    Selected: "vybráno",
    SharingField: "Sdílení",
    SharingPrivate: "Soukromé",
    SharingShared: "Sdílené",
    SiteLinkLabel: "Web",
    SizeOptionAll: "Vše",
    SizeOptionExtraLarge: "Extra velké",
    SizeOptionLarge: "Velké",
    SizeOptionMedium: "Střední",
    SizeOptionSmall: "Malé",
    SizeUnit: ["bajtů", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
    SorryWebSearch:
      "Omlouváme se, tato funkce není v této ukázce implementována, protože by vyžadovala Bing API klíč.",
    SortedAscending: "Seřazeno vzestupně",
    SortedDescending: "Seřazeno sestupně",
    TypeAriaLabel:
      "Operace se sloupcem pro typ souboru. Stiskněte pro seřazení podle typu souboru",
    UploadFileHeader: "Nahrát soubor",
    UploadImageHeader: "Nahrát obrázek",
    UploadLinkLabel: "Nahrát",
    WebSearchLinkLabel: "Vyhledat na webu",
    StockImagesLinkLabel: "Ilustrační obrázky",
    StockImagesHeader: "Ilustrační obrázky",
    Yes: "Ano",

    NewFolderNamePlaceholder: "Zadejte název složky",
    FolderFilterBoxPlaceholder: "Filtrovat složky podle názvu",
    FolderExplorerLoading: "Načítám složky...",
    FolderExplorerNoItems: "Tato složka neobsahuje žádné podsložky.",
    NewFolderIncorrectSymbolsError:
      'Zadejte prosím název, který neobsahuje žádné z následujících znaků: " * : < > ? /  |.',
    SomethingWentWrong: "Něco se pokazilo",
    SelectedLabel: "Vybráno",
    SelectIcon: "Vybrat ikonu",

    TreeViewExpandTitle: "Rozbalit tuto položku",
    TreeViewCollapseTitle: "Sbalit tuto položku",

    CollectionDataEmptyFields:
      "Nebylo poskytnuto žádné pole pro data kolekce.",
    CollectionDataEmptyValue: "Ve vaší kolekci nejsou žádná data.",
    CollectionAddRowButtonLabel: "Přidat data do kolekce",
    CollectionDeleteRowButtonLabel: "Odstranit aktuální řádek",
    CollectionSaveAndAddButtonLabel: "Uložit a přidat",
    CollectionDataItemShowErrorsLabel: "Zobrazit chyby v řádku",
    CollectionDataItemFieldRequiredLabel: "Pole je povinné.",
    CollectionDataItemMissingFields: "Kolekce polí je prázdná!",
    InvalidUrlError: "Zadaná adresa URL je neplatná",
    CollectionDataSearch: "Hledat",
    CollectionDataMinimumUsersDefaultMessage:
      "Minimální počet uživatelů k výběru je {0}",
    MyTeamsLoadingMessage: "Načítám vaše týmy",
    MyTeamsMessageError:
      "Při načítání vašich týmů došlo k chybě. Zkuste to prosím později nebo obnovte prohlížeč.",

    MyTeamsNoTeamsMessage: "Nemáte žádné týmy",
    MyTeamsTeamChannelPublicMessage: "Veřejné kanály",
    MyTeamsTeamChannelTypeMessage: "Soukromé kanály",
    TeamChannelPickerFontIconFavoriteText: "Oblíbené",
    TeamChannelPickerFontIconPrivateChannelTitle: "Soukromý kanál",
    TeamChannelPickerSugestionHeaderText: "Navrhované týmové kanály",
    TeamPickerButtonRemoveTitle: "odebrat",
    TeamPickernoResultsFoundText: "Žádné týmy nenalezeny",
    TeamPickerSugestionsHeaderText: "Navrhované týmy",
    TeamsChannelPickerButtonRemoveTitle: "odebrat",
    TeamsChannelPickerNoresultsFoundText: "Žádné kanály nenalezeny",

    ViewMore: "Zobrazit více",

    DynamicFormLoading: "Načítání...",
    DynamicFormPleaseWait: "Čekejte prosím...",
    DynamicFormRequiredErrorMessage: "Toto pole nesmí být prázdné.",
    DynamicFormTermPanelTitle: "Vyberte termín",
    DynamicFormEnterURLPlaceholder: "Zadejte adresu URL",
    DynamicFormEnterDescriptionPlaceholder: "Alternativní text",
    DynamicFormDialogValidationErrorTitle: "Chyba ověření",
    DynamicFormDialogValidationErrorMessage:
      "Vyskytly se chyby ověření, před uložením je prosím opravte.",
    DynamicFormNumberValueMustBeGreaterThan:
      "Hodnota musí být větší než {0}",
    DynamicFormNumberValueMustBeBetween:
      "Hodnota musí být mezi {0} a {1}",
    DynamicFormNumberValueMustBeLowerThan:
      "Hodnota musí být menší než {0}",
    DynamicFormChooseFileLabel: "Soubor",
    DynamicFormChooseFileButtonText: "Vybrat soubor",
    DynamicFormRequiredFileMessage: "Soubor je vyžadován.",
    customDisplayName: "Použít toto umístění:",
    ListItemCommentDIalogDeleteSubText:
      "Opravdu chcete odstranit tento komentář?",
    ListItemCommentsDialogDeleteTitle: "Potvrzení odstranění komentáře",
    ListItemCommentsLabel: "Komentáře",
    ListItemCommentsNoCommentsLabel: "Žádné komentáře",
    OrgAssetsLinkLabel: "Vaše organizace",

    ModernTaxonomyPickerDefaultPlaceHolder: "Zadejte termín k označení",
    ModernTaxonomyPickerTreeTitleSingle: "Vyberte značku",
    ModernTaxonomyPickerTreeTitleMulti: "Vyberte jednu nebo více značek",
    ModernTaxonomyPickerAddTagButtonTooltip: "Přidat značku",
    ModernTaxonomyPickerApplyButtonText: "Použít",
    ModernTaxonomyPickerCancelButtonText: "Zrušit",
    ModernTaxonomyPickerLoadMoreText: "Načíst další",
    ModernTaxonomyPickerRemoveButtonText: "Odebrat",
    ModernTaxonomyPickerPanelCloseButtonText: "Zavřít",
    ModernTaxonomyPickerNoResultsFound: "Nebyly nalezeny žádné výsledky",
    ModernTaxonomyPickerSuggestionInLabel: "v",

    ModernAudioPlay: "Přehrát",
    ModernAudioPause: "Pozastavit",
    ModernAudioIncVol: "Zvýšit hlasitost",
    ModernAudioDecVol: "Snížit hlasitost",
    ModernAudioMute: "Ztišit",

    ProgressStepsIndicatorNoSteps: "Žádné kroky",
    TermSertNaviagtionErrorMessage: "TermSet nebyl nalezen",
    TermSetNavigationNoTerms: "Nejsou definovány žádné termíny",

    UploadFilesButtonLabel: "Přidat",
    UpLoadFilesDeleteButtonLabel: "Odstranit",
    UpLoadFilesDragDropLabel:
      "Přetáhněte sem soubory nebo vyberte tlačítko Přidat soubor",
    UpLoadFilesSelectAllLabel: "Vybrat vše",
    UploadFilesUploadButtonLabel: "Nahrát",

    HoverReactionBarSearchEmojiPlaceholder: "Vyhledat emotikony",
    ImagePickderSelectLabel: "Vybrat obrázek",
    ImagePickerDeleteImageLabel: "Odstranit",
    ImagePickerSelectLabel: "Vybrat",
    ImagePickerCancelLabel: "Zrušit",
    ImagePickerPanelHeaderText:
      "Vyberte prosím obrázek k použití jako miniaturu",
    ImagePickerSharePointTabLabel: "SharePoint",
    ImagePickerOneDriveTabLabel: "OneDrive",
    ImagePickerStockImagesTabLabel: "Ilustrační obrázky",
    ImagePickerUploadTabLabel: "Nahrát",
    ImagePickerDragFilesAccpted:
      "Podporované formáty: .gif, .jpg, .jpeg, .png, .svg",
    ImagePickerDragFilesRejected: "Některé soubory budou odmítnuty",
    ImagePickerDragFilesActive: "Přetáhněte sem obrázky...",
    ImagePickerDragDropText:
      "Přetáhněte sem soubory s obrázky nebo klikněte pro výběr souborů, maximálně lze najednou nahrát 10 souborů",
    ImagePickerUploadLocationLabel: "Vyberte umístění nahrání",
    ImagePickerUploadLocationOndriveLabel: "OneDrive",
    ImagePickerUploadLocationSharePointLabel: "Aktuální web",
    ImagePickerRetryButtonLabel: "Zkusit znovu",
    ImagePickerDeleteLabel: "Odstranit",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "found",
  worldMapLoadintText: "Loading map style…",
  worldMapLocationLabel: "location",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "name",
  worldMapSearchLocations: "Search locations...",
  worldMapTitle: "World Map",
  worldMapZoomContent: "Zoom in",
  worldMapZoomIn: "Zoom in",
  };
});
