declare var define: any;

define([], () => {
  return {
    PeoplePickerGroupNotFound: 'Gruppe konnte nicht gefunden werden.',
    ListViewFilterLabel: 'Filter',

    PeoplePickerSearchText: 'Benutzer werden abgerufen',
    peoplePickerComponentTooltipMessage: 'Benutzerauswahl',
    peoplePickerComponentErrorMessage: 'Pflichtfeld',
    peoplePickerSuggestionsHeaderText: 'Vorgeschlagene Benutzer',
    genericNoResultsFoundText: 'Keine Ergebnisse gefunden',
    peoplePickerLoadingText: 'Laden',

    SiteBreadcrumbLabel: 'Website Brotkrume',
    ListViewGroupEmptyLabel: 'Leer',
    WebPartTitlePlaceholder: 'Webpart Titel',
    WebPartTitleLabel: 'Einen Titel hinzufügen',
    // DateTime: IDateTimeStrings;
    SendEmailTo: 'Sende eine E-Mail an {0}',
    StartChatWith: 'Starte einen Chat mit {0}',
    Contact: 'Kontakt',
    UpdateProfile: 'Aktualisieren Sie Ihr Profil',

    // Taxonomy picker
    TaxonomyPickerNoTerms: 'Ausdruckssatz enthält keine Ausdrücke',
    TaxonomyPickerExpandTitle: 'Diesen Ausdruckssatz erweitern',
    TaxonomyPickerMenuTermSet: 'Ausdruckssatz Menü',
    TaxonomyPickerInLabel: 'in',
    TaxonomyPickerTermSetLabel: 'Ausdruckssatz',

    ListItemPickerSelectValue: 'Wert auswählen',

    ListItemAttachmentsActionDeleteIconTitle: 'Löschen',
    ListItemAttachmentsactionDeleteTitle: 'Löschen',
    ListItemAttachmentsfileDeletedMsg: 'Datei {0} gelöscht',
    ListItemAttachmentsfileDeleteError: 'Fehler beim Löschen der Datei: {0}, Grund: {1}',
    ListItemAttachmentserrorLoadAttachments: 'Fehler beim Laden der Anhänge, Grund: {0}',
    ListItemAttachmentsconfirmDelete: 'Sind Sie sich sicher, dass Sie die Anlage {0} in den Papierkorb der Website verschieben möchten?',
    ListItemAttachmentsdialogTitle: 'Listenelement-Anhang',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Abbrechen',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Löschen',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Anlage hinzufügen',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Anlage hinzufügen',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Die Datei {0} wurde nicht hinzugefügt, Grund: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Anlage hinzufügen',
    ListItemAttachmentsloadingMessage: 'Datei wird hochgeladen ...',
    ListItemAttachmentslPlaceHolderIconText: 'Listenelement-Anhang',
    ListItemAttachmentslPlaceHolderDescription: 'Bitte Anlage hinzufügen',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Hinzufügen',

    // Maps
    mapsErrorMessage: 'Beim Laden der Karte ist ein Fehler aufgetreten',
    mapsLoadingText: 'Laden',
    mapsSearchButtonText: 'Suche',
    mapsTitlePrefix: 'Karte von',

    // RichText
    HeaderNormalText: 'Standardtext',
    HeaderH2: 'Überschrift 1',
    HeaderH3: 'Überschrift 2',
    HeaderH4: 'Überschrift 3',
    HeaderBlockQuote: 'Textzitat',
    AlignLeft: 'Linksbündig',
    AlignCenter: 'Zentrieren',
    AlignRight: 'Rechtsbündig',
    AlignJustify: 'Blocksatz',
    ListBullet: 'Aufzählung',
    ListNumbered: 'Nummerierte Liste',
    StyleTitle: 'Schriftart',
    BoldTitle: 'Fett (Strg+B)',
    ItalicTitle: 'Kursiv (Strg+I)',
    UnderlineTitle: 'Unterstrichen (Strg+U)',
    AlignTitle: 'Ausrichtung',
    ListTitle: 'Liste',
    LinkTitle: 'Hyperlink',
    MoreTitle: 'Mehr',
    FormattingPaneTitle: 'Textformatierung',
    CloseButton: 'Schließen',
    InsertLinkTitle: 'Link einfügen',
    AddressFieldLabel: 'Adresse',
    TextToDisplayLabel: 'Anzuzeigender Text',
    SaveButtonLabel: 'Speichern',
    CancelButtonLabel: 'Abbrechen',
    RemoveLinkLabel: 'Link entfernen',
    ParagraphSectionTitle: 'Absatz',
    HyperlinkSectionTitle: 'Hyperlink',
    UndoTitle: 'Rückgängig (Strg+Z)',
    RedoTitle: 'Wiederholen (Strg+Y)',
    ClearFormattingTitle: 'Alle Formatierungen löschen',
    FontStyleTitle: 'Schriftschnitt',
    FontSizeTitle: 'Schriftgrad',
    StrikethroughTitle: 'Durchgestrichen',
    SuperscriptTitle: 'Hochgestellt',
    SubscriptTitle: 'Tiefgestellt',
    FontColorLabel: 'Schriftfarbe',
    AutomaticFontColor: 'Automatisch',
    HighlightColorLabel: 'Hervorhebungsfarbe',
    NoColorHighlightColor: 'Keine Farbe',
    IncreaseIndentTitle: 'Einzug vergrößern',
    DecreaseIndentTitle: 'Einzug verringern',
    ThemeColorsGroupName: 'Designfarben',
    HighlightColorsGroupName: 'Hervorhebungsfarben',
    StandardColorsGroupName: 'Standardfarben',
    ThemeColorDarker: 'Design dunkler',
    ThemeColorDark: 'Design dunkel',
    ThemeColorDarkAlt: 'Design dunkel alternativ',
    ThemeColorPrimary: 'Design primär',
    ThemeColorSecondary: 'Design sekundär',
    ThemeColorTertiary: 'Design tertiär',
    ThemeColorNeutralSecondary: 'Neutral sekundär',
    ThemeColorNeutralPrimaryAlt: 'Neutral primär alternativ',
    ThemeColorNeutralPrimary: 'Neutral primär',
    ThemeColorNeutralDark: 'Neutral dunkel',
    HighlightColorYellow: 'Gelb',
    HighlightColorGreen: 'Grün',
    HighlightColorAqua: 'Aquamarin',
    HighlightColorMagenta: 'Magenta',
    HighlightColorBlue: 'Blau',
    HighlightColorRed: 'Rot',
    HighlightColorDarkblue: 'Dunkelblau',
    HighlightColorTeal: 'Blaugrün',
    HighlightColorDarkgreen: 'Dunkelgrün',
    HighlightColorPurple: 'Lila',
    HighlightColorMaroon: 'Kastanienbraun',
    HighlightColorGold: 'Gold',
    HighlightColorDarkgrey: 'Dunkelgrau',
    HighlightColorGrey: 'Grau',
    HighlightColorBlack: 'Schwarz',
    StandardColorDarkred: 'Dunkelrot',
    StandardColorRed: 'Rot',
    StandardColorOrange: 'Orange',
    StandardColorYellow: 'Gelb',
    StandardColorLightgreen: 'Hellgrün',
    StandardColorGreen: 'Grün',
    StandardColorLightblue: 'Hellblau',
    StandardColorBlue: 'Blau',
    StandardColorDarkblue: 'Dunkelblau',
    StandardColorPurple: 'Lila',

    // DateTime picker
    DatePickerMonthLongJanuary: 'Januar',
    DatePickerMonthShortJanuary: 'Jan',
    DatePickerMonthLongFebruary: 'Februar',
    DatePickerMonthShortFebruary: 'Feb',
    DatePickerMonthLongMarch: 'März',
    DatePickerMonthShortMarch: 'Mär',
    DatePickerMonthLongApril: 'April',
    DatePickerMonthShortApril: 'Apr',
    DatePickerMonthLongMay: 'Mai',
    DatePickerMonthShortMay: 'Mai',
    DatePickerMonthLongJune: 'Juni',
    DatePickerMonthShortJune: 'Jun',
    DatePickerMonthLongJuly: 'Juli',
    DatePickerMonthShortJuly: 'Jul',
    DatePickerMonthLongAugust: 'August',
    DatePickerMonthShortAugust: 'Aug',
    DatePickerMonthLongSeptember: 'September',
    DatePickerMonthShortSeptember: 'Sep',
    DatePickerMonthLongOctober: 'Oktober',
    DatePickerMonthShortOctober: 'Okt',
    DatePickerMonthLongNovember: 'November',
    DatePickerMonthShortNovember: 'Nov',
    DatePickerMonthLongDecember: 'Dezember',
    DatePickerMonthShortDecember: 'Dez',
    DatePickerDayLongSunday: 'Sonntag',
    DatePickerDayShortSunday: 'So',
    DatePickerDayLongMonday: 'Montag',
    DatePickerDayShortMonday: 'Mo',
    DatePickerDayLongTuesday: 'Dienstag',
    DatePickerDayShortTuesday: 'Di',
    DatePickerDayLongWednesday: 'Mittwoch',
    DatePickerDayShortWednesday: 'Mi',
    DatePickerDayLongThursday: 'Donnerstag',
    DatePickerDayShortThursday: 'Do',
    DatePickerDayLongFriday: 'Freitag',
    DatePickerDayShortFriday: 'Fr',
    DatePickerDayLongSaturday: 'Samstag',
    DatePickerDayShortSaturday: 'Sa',
    DatePickerGoToToday: 'Heute',
    DatePickerIsRequiredErrorMessage: '',
    DatePickerInvalidInputErrorMessage: '',
    DatePickerIsOutOfBoundsErrorMessage: '',
    DateTimePickerDate: 'Datum',
    DateTimePickerTime: 'Uhrzeit',
    DateTimePickerTimeSeparator: ':',
    DateTimePickerHourValueInvalid: 'Falscher Stundenwert',

    DateTime: {
      L_RelativeDateTime_AFewSecondsFuture: 'In wenigen Sekunden',
      L_RelativeDateTime_AFewSeconds: 'Vor wenigen Sekunden',
      L_RelativeDateTime_AboutAMinuteFuture: 'In ungefähr einer Minute',
      L_RelativeDateTime_AboutAMinute: 'Vor ungefähr einer Minute',
      L_RelativeDateTime_XMinutesFuture: 'In {0} Minute||In {0} Minuten',
      L_RelativeDateTime_XMinutes: 'Vor {0} Minute||Vor {0} Minuten',
      L_RelativeDateTime_XMinutesFutureIntervals: '1||2-',
      L_RelativeDateTime_XMinutesIntervals: '1||2-',
      L_RelativeDateTime_AboutAnHourFuture: 'In ungefähr einer Stunde',
      L_RelativeDateTime_AboutAnHour: 'Vor ungefähr einer Stunde',
      L_RelativeDateTime_Tomorrow: 'Morgen',
      L_RelativeDateTime_Yesterday: 'Gestern',
      L_RelativeDateTime_TomorrowAndTime: 'Morgen um {0}',
      L_RelativeDateTime_YesterdayAndTime: 'Gestern um {0}',
      L_RelativeDateTime_XHoursFuture: 'In {0} Stunde||In {0} Stunden',
      L_RelativeDateTime_XHours: 'Vor {0} Stunde||Vor {0} Stunden',
      L_RelativeDateTime_XHoursFutureIntervals: '1||2-',
      L_RelativeDateTime_XHoursIntervals: '1||2-',
      L_RelativeDateTime_DayAndTime: '{0} um {1}',
      L_RelativeDateTime_XDaysFuture: '{0} Tag ab jetzt||{0} Tage ab jetzt',
      L_RelativeDateTime_XDays: 'Vor {0} Tag||Vor {0} Tagen',
      L_RelativeDateTime_XDaysFutureIntervals: '1||2-',
      L_RelativeDateTime_XDaysIntervals: '1||2-',
      L_RelativeDateTime_Today: 'Heute'
    }
  };
});
