declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Website Brotkrume',

    'ListViewGroupEmptyLabel': 'Leer',

    'WebPartTitlePlaceholder': 'Webpart Titel',
    'WebPartTitleLabel': 'Titel hinzufügen',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "In wenigen Sekunden",
      "L_RelativeDateTime_AFewSeconds": "Vor wenigen Sekunden",
      "L_RelativeDateTime_AboutAMinuteFuture": "In ungefähr einer Minute",
      "L_RelativeDateTime_AboutAMinute": "Vor ungefähr einer Minute",
      "L_RelativeDateTime_XMinutesFuture": "In {0} Minute||In {0} Minuten",
      "L_RelativeDateTime_XMinutes": "Vor {0} Minute||Vor {0} Minuten",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "In ungefähr einer Stunde",
      "L_RelativeDateTime_AboutAnHour": "Vor ungefähr einer Stunde",
      "L_RelativeDateTime_Tomorrow": "Morgen",
      "L_RelativeDateTime_Yesterday": "Gestern",
      "L_RelativeDateTime_TomorrowAndTime": "Morgen um {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Gestern um {0}",
      "L_RelativeDateTime_XHoursFuture": "In {0} Stunde||In {0} Stunden",
      "L_RelativeDateTime_XHours": "Vor {0} Stunde||Vor {0} Stunden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} at {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} Tag ab jetzt||{0} Tage ab jetzt",
      "L_RelativeDateTime_XDays": "Vor {0} Tag||Vor {0} Tagen",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Heute"
    },
    "SendEmailTo": "Email senden an {0}",
    "StartChatWith": "Chat starten mit {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Aktualisiere Dein Profil",

    "TaxonomyPickerNoTerms": "Ausdruckssatz enthält keine Ausdrücke",
    "TaxonomyPickerExpandTitle": "Ausdruckssatz erweitern",
    "TaxonomyPickerMenuTermSet": "Ausdruckssatz Menü",
    "TaxonomyPickerInLabel": "in",
    "TaxonomyPickerTermSetLabel": "Ausdruckssatz",

    peoplePickerComponentTooltipMessage: "People Picker",
    peoplePickerComponentErrorMessage: "Benutzerauswahl ist ein Pflichtfeld",
    peoplePickerSuggestionsHeaderText: 'Vorgeschlagene Benutzer',
    peoplePickerLoadingText: 'Laden',
    PeoplePickerSearchText: 'Fetching users',
    PeoplePickerGroupNotFound: "Group could not be found.",

    ListItemPickerSelectValue: 'Wähle Wert',

    mapsErrorMessage: 'Beim Laden von Karten ist ein Fehler aufgetreten',
    mapsLoadingText: 'Laden',
    mapsSearchButtonText: 'Suche',
    mapsTitlePrefix: 'Karte von',

    genericNoResultsFoundText: 'Kein Ergebnis gefunden',

    ListViewFilterLabel: "Filter",

    DatePickerMonthLongJanuary: "January",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "February",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "March",
    DatePickerMonthShortMarch: "Mar",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "May",
    DatePickerMonthShortMay: "May",
    DatePickerMonthLongJune: "June",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "July",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "August",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sept",
    DatePickerMonthLongOctober: "October",
    DatePickerMonthShortOctober: "Oct",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Sunday",
    DatePickerDayShortSunday: "Sun",
    DatePickerDayLongMonday: "Monday",
    DatePickerDayShortMonday: "Mon",
    DatePickerDayLongTuesday: "Tuesday",
    DatePickerDayShortTuesday: "Tue",
    DatePickerDayLongWednesday: "Wednesday",
    DatePickerDayShortWednesday: "Wed",
    DatePickerDayLongThursday: "Thursday",
    DatePickerDayShortThursday: "Thu",
    DatePickerDayLongFriday: "Friday",
    DatePickerDayShortFriday: "Fri",
    DatePickerDayLongSaturday: "Saturday",
    DatePickerDayShortSaturday: "Sat",
    DatePickerGoToToday: "Today",
    DateTimePickerDate: "Date",
    DateTimePickerTime: "Time",
    AMDesignator: "",
    PMDesignator: ""
  };
});
