declare var define: any;

define([], () => {
  return {
    PeoplePickerGroupNotFound: 'Gruppe konnte nicht gefunden werden.',
    ListViewFilterLabel: 'Filter',

    PeoplePickerSearchText: 'Benutzer werden abgerufen',
    peoplePickerComponentTooltipMessage: 'Benutzerauswahl',
    peoplePickerComponentErrorMessage: 'Pflichtfeld',
    peoplePickerSuggestionsHeaderText: 'Vorgeschlagene Benutzer',
    genericNoResultsFoundText: 'Keine Ergebnisse gefunden',
    peoplePickerLoadingText: 'Laden',

    SiteBreadcrumbLabel: 'Website Brotkrume',
    ListViewGroupEmptyLabel: 'Leer',
    WebPartTitlePlaceholder: 'Webpart Titel',
    WebPartTitleLabel: 'Einen Titel hinzufügen',
    // DateTime: IDateTimeStrings;
    SendEmailTo: 'Sende eine E-Mail an {0}',
    StartChatWith: 'Starte einen Chat mit {0}',
    Contact: 'Kontakt',
    UpdateProfile: 'Aktualisieren Sie Ihr Profil',

    // Taxonomy picker
    TaxonomyPickerNoTerms: 'Ausdruckssatz enthält keine Ausdrücke',
    TaxonomyPickerExpandTitle: 'Diesen Ausdruckssatz erweitern',
    TaxonomyPickerMenuTermSet: 'Ausdruckssatz Menü',
    TaxonomyPickerInLabel: 'in',
    TaxonomyPickerTermSetLabel: 'Ausdruckssatz',

    ListItemPickerSelectValue: 'Wert auswählen',

    ListItemAttachmentsActionDeleteIconTitle: 'Löschen',
    ListItemAttachmentsactionDeleteTitle: 'Löschen',
    ListItemAttachmentsfileDeletedMsg: 'Datei {0} gelöscht',
    ListItemAttachmentsfileDeleteError: 'Fehler beim Löschen der Datei: {0}, Grund: {1}',
    ListItemAttachmentserrorLoadAttachments: 'Fehler beim Laden der Anhänge, Grund: {0}',
    ListItemAttachmentsconfirmDelete: 'Sind Sie sich sicher, dass Sie die Anlage {0} in den Papierkorb der Website verschieben möchten?',
    ListItemAttachmentsdialogTitle: 'Listenelement-Anhang',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Abbrechen',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Löschen',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Anlage hinzufügen',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Anlage hinzufügen',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Die Datei {0} wurde nicht hinzugefügt, Grund: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Anlage hinzufügen',
    ListItemAttachmentsloadingMessage: 'Datei wird hochgeladen ...',
    ListItemAttachmentslPlaceHolderIconText: 'Listenelement-Anhang',
    ListItemAttachmentslPlaceHolderDescription: 'Bitte Anlage hinzufügen',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Hinzufügen',

    // Maps
    mapsErrorMessage: 'Beim Laden der Karte ist ein Fehler aufgetreten',
    mapsLoadingText: 'Laden',
    mapsSearchButtonText: 'Suche',
    mapsTitlePrefix: 'Karte von',

    // RichText
    HeaderNormalText: 'Standardtext',
    HeaderH2: 'Überschrift 1',
    HeaderH3: 'Überschrift 2',
    HeaderH4: 'Überschrift 3',
    HeaderBlockQuote: 'Textzitat',
    AlignLeft: 'Linksbündig',
    AlignCenter: 'Zentrieren',
    AlignRight: 'Rechtsbündig',
    AlignJustify: 'Blocksatz',
    ListBullet: 'Aufzählung',
    ListNumbered: 'Nummerierte Liste',
    StyleTitle: 'Schriftart',
    BoldTitle: 'Fett (Strg+B)',
    ItalicTitle: 'Kursiv (Strg+I)',
    UnderlineTitle: 'Unterstrichen (Strg+U)',
    AlignTitle: 'Ausrichtung',
    ListTitle: 'Liste',
    LinkTitle: 'Hyperlink',
    MoreTitle: 'Mehr',
    FormattingPaneTitle: 'Textformatierung',
    CloseButton: 'Schließen',
    InsertLinkTitle: 'Link einfügen',
    AddressFieldLabel: 'Adresse',
    TextToDisplayLabel: 'Anzuzeigender Text',
    SaveButtonLabel: 'Speichern',
    CancelButtonLabel: 'Abbrechen',
    RemoveLinkLabel: 'Link entfernen',
    ParagraphSectionTitle: 'Absatz',
    HyperlinkSectionTitle: 'Hyperlink',
    UndoTitle: 'Rückgängig (Strg+Z)',
    RedoTitle: 'Wiederholen (Strg+Y)',
    ClearFormattingTitle: 'Alle Formatierungen löschen',
    FontStyleTitle: 'Schriftschnitt',
    FontSizeTitle: 'Schriftgrad',
    StrikethroughTitle: 'Durchgestrichen',
    SuperscriptTitle: 'Hochgestellt',
    SubscriptTitle: 'Tiefgestellt',
    FontColorLabel: 'Schriftfarbe',
    AutomaticFontColor: 'Automatisch',
    HighlightColorLabel: 'Hervorhebungsfarbe',
    NoColorHighlightColor: 'Keine Farbe',
    IncreaseIndentTitle: 'Einzug vergrößern',
    DecreaseIndentTitle: 'Einzug verringern',
    ThemeColorsGroupName: 'Designfarben',
    HighlightColorsGroupName: 'Hervorhebungsfarben',
    StandardColorsGroupName: 'Standardfarben',
    ThemeColorDarker: 'Design dunkler',
    ThemeColorDark: 'Design dunkel',
    ThemeColorDarkAlt: 'Design dunkel alternativ',
    ThemeColorPrimary: 'Design primär',
    ThemeColorSecondary: 'Design sekundär',
    ThemeColorTertiary: 'Design tertiär',
    ThemeColorNeutralSecondary: 'Neutral sekundär',
    ThemeColorNeutralPrimaryAlt: 'Neutral primär alternativ',
    ThemeColorNeutralPrimary: 'Neutral primär',
    ThemeColorNeutralDark: 'Neutral dunkel',
    HighlightColorYellow: 'Gelb',
    HighlightColorGreen: 'Grün',
    HighlightColorAqua: 'Aquamarin',
    HighlightColorMagenta: 'Magenta',
    HighlightColorBlue: 'Blau',
    HighlightColorRed: 'Rot',
    HighlightColorDarkblue: 'Dunkelblau',
    HighlightColorTeal: 'Blaugrün',
    HighlightColorDarkgreen: 'Dunkelgrün',
    HighlightColorPurple: 'Lila',
    HighlightColorMaroon: 'Kastanienbraun',
    HighlightColorGold: 'Gold',
    HighlightColorDarkgrey: 'Dunkelgrau',
    HighlightColorGrey: 'Grau',
    HighlightColorBlack: 'Schwarz',
    StandardColorDarkred: 'Dunkelrot',
    StandardColorRed: 'Rot',
    StandardColorOrange: 'Orange',
    StandardColorYellow: 'Gelb',
    StandardColorLightgreen: 'Hellgrün',
    StandardColorGreen: 'Grün',
    StandardColorLightblue: 'Hellblau',
    StandardColorBlue: 'Blau',
    StandardColorDarkblue: 'Dunkelblau',
    StandardColorPurple: 'Lila',

    // DateTime picker
    DatePickerMonthLongJanuary: 'Januar',
    DatePickerMonthShortJanuary: 'Jan',
    DatePickerMonthLongFebruary: 'Februar',
    DatePickerMonthShortFebruary: 'Feb',
    DatePickerMonthLongMarch: 'März',
    DatePickerMonthShortMarch: 'Mär',
    DatePickerMonthLongApril: 'April',
    DatePickerMonthShortApril: 'Apr',
    DatePickerMonthLongMay: 'Mai',
    DatePickerMonthShortMay: 'Mai',
    DatePickerMonthLongJune: 'Juni',
    DatePickerMonthShortJune: 'Jun',
    DatePickerMonthLongJuly: 'Juli',
    DatePickerMonthShortJuly: 'Jul',
    DatePickerMonthLongAugust: 'August',
    DatePickerMonthShortAugust: 'Aug',
    DatePickerMonthLongSeptember: 'September',
    DatePickerMonthShortSeptember: 'Sep',
    DatePickerMonthLongOctober: 'Oktober',
    DatePickerMonthShortOctober: 'Okt',
    DatePickerMonthLongNovember: 'November',
    DatePickerMonthShortNovember: 'Nov',
    DatePickerMonthLongDecember: 'Dezember',
    DatePickerMonthShortDecember: 'Dez',
    DatePickerDayLongSunday: 'Sonntag',
    DatePickerDayShortSunday: 'So',
    DatePickerDayLongMonday: 'Montag',
    DatePickerDayShortMonday: 'Mo',
    DatePickerDayLongTuesday: 'Dienstag',
    DatePickerDayShortTuesday: 'Di',
    DatePickerDayLongWednesday: 'Mittwoch',
    DatePickerDayShortWednesday: 'Mi',
    DatePickerDayLongThursday: 'Donnerstag',
    DatePickerDayShortThursday: 'Do',
    DatePickerDayLongFriday: 'Freitag',
    DatePickerDayShortFriday: 'Fr',
    DatePickerDayLongSaturday: 'Samstag',
    DatePickerDayShortSaturday: 'Sa',
    DatePickerGoToToday: 'Heute',
    DatePickerIsRequiredErrorMessage: '',
    DatePickerInvalidInputErrorMessage: '',
    DatePickerIsOutOfBoundsErrorMessage: '',
    DateTimePickerDate: 'Datum',
    DateTimePickerTime: 'Uhrzeit',
    DateTimePickerTimeSeparator: ':',
    DateTimePickerHourValueInvalid: 'Falscher Stundenwert',

    DateTime: {
      L_RelativeDateTime_AFewSecondsFuture: 'In wenigen Sekunden',
      L_RelativeDateTime_AFewSeconds: 'Vor wenigen Sekunden',
      L_RelativeDateTime_AboutAMinuteFuture: 'In ungefähr einer Minute',
      L_RelativeDateTime_AboutAMinute: 'Vor ungefähr einer Minute',
      L_RelativeDateTime_XMinutesFuture: 'In {0} Minute||In {0} Minuten',
      L_RelativeDateTime_XMinutes: 'Vor {0} Minute||Vor {0} Minuten',
      L_RelativeDateTime_XMinutesFutureIntervals: '1||2-',
      L_RelativeDateTime_XMinutesIntervals: '1||2-',
      L_RelativeDateTime_AboutAnHourFuture: 'In ungefähr einer Stunde',
      L_RelativeDateTime_AboutAnHour: 'Vor ungefähr einer Stunde',
      L_RelativeDateTime_Tomorrow: 'Morgen',
      L_RelativeDateTime_Yesterday: 'Gestern',
      L_RelativeDateTime_TomorrowAndTime: 'Morgen um {0}',
      L_RelativeDateTime_YesterdayAndTime: 'Gestern um {0}',
      L_RelativeDateTime_XHoursFuture: 'In {0} Stunde||In {0} Stunden',
      L_RelativeDateTime_XHours: 'Vor {0} Stunde||Vor {0} Stunden',
      L_RelativeDateTime_XHoursFutureIntervals: '1||2-',
      L_RelativeDateTime_XHoursIntervals: '1||2-',
      L_RelativeDateTime_DayAndTime: '{0} um {1}',
      L_RelativeDateTime_XDaysFuture: '{0} Tag ab jetzt||{0} Tage ab jetzt',
      L_RelativeDateTime_XDays: 'Vor {0} Tag||Vor {0} Tagen',
      L_RelativeDateTime_XDaysFutureIntervals: '1||2-',
      L_RelativeDateTime_XDaysIntervals: '1||2-',
      L_RelativeDateTime_Today: 'Heute'
    },

    AddFileButtonLabel: "Add file",
    AddImageButtonLabel: "Add image",
    AriaCellValue: "{0} column, {1}",
    FilePickerCancelButtonLabel: "Cancel",
    CantValidateValidationMessage: "We couldn't verify this link. Please check the link and try again.",
    ChangeFileLinkLabel: "Change file",
    ChangeImageLinkLabel: "Change image",
    ChooseFileLinkLabel: "Choose file",
    ChooseImageLinkLabel: "Choose image",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    DocumentLibraries: "Document libraries",
    EditedByNamePlate: "edited by ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "File Picker",
    FileSizeField: "File Size",
    FolderAltText: "Folder",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "No",
    ProvidedValueIsInvalid: "Provided value is invalid",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    OneDriveRootFolderName: "Files",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Recent documents",
    RecentImagesHeader: "Recent images",
    RecentLinkLabel: "Recent",
    SearchBoxPlaceholder: "Web search",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    Selected: "selected",
    SharingField: "Sharing",
    SharingPrivate: "Private",
    SharingShared: "Shared",
    SiteLinkLabel: "Site",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Sorry, this function isn't implemented in this sample, because it would require a Bing API key.",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Upload file",
    UploadImageHeader: "Upload image",
    UploadLinkLabel: "Upload",
    WebSearchLinkLabel: "Web search",
    Yes: "Yes"
  };
});
