declare var define: any;

define([], () => {
  return {
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  "Save": "Σώζω",
  "Cancel": "Ακυρώνω",
  "SiteBreadcrumbLabel": "Περιήγηση σε ιστότοπους",
  "ListViewGroupEmptyLabel": "Κενό",
  "WebPartTitlePlaceholder": "Τίτλος τμήματος Web",
  "WebPartTitleLabel": "Προσθήκη τίτλου",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Σε λίγα δευτερόλεπτα",
    "L_RelativeDateTime_AFewSeconds": "Πριν από λίγα δευτερόλεπτα",
    "L_RelativeDateTime_AboutAMinuteFuture": "Σε περίπου ένα λεπτό",
    "L_RelativeDateTime_AboutAMinute": "Πριν ένα λεπτό.",
    "L_RelativeDateTime_XMinutesFuture": "Σε {0} λεπτό||Σε {0} λεπτά",
    "L_RelativeDateTime_XMinutes": "{0} λεπτό πριν||{0} λεπτά πριν",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Σε περίπου μια ώρα",
    "L_RelativeDateTime_AboutAnHour": "Πριν μια ώρα.",
    "L_RelativeDateTime_Tomorrow": "Αύριο",
    "L_RelativeDateTime_Yesterday": "Χθες",
    "L_RelativeDateTime_TomorrowAndTime": "Αύριο στο {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Χθες στο {0}",
    "L_RelativeDateTime_XHoursFuture": "Σε {0} ώρα||Σε {0} ώρες",
    "L_RelativeDateTime_XHours": "{0} ώρα πριν||{0} ώρες πριν",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} στο {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} ημέρα από τώρα||{0} μέρες από τώρα",
    "L_RelativeDateTime_XDays": "πριν από {0} ημέρα||{0} μέρες πριν",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Σήμερα"
  },
  "SendEmailTo": "Στείλτε ένα μήνυμα ηλεκτρονικού ταχυδρομείου στο {0}",
  "StartChatWith": "Έναρξη συνομιλίας με {0}",
  "Contact": "Επαφή",
  "UpdateProfile": "Ενημέρωση του προφίλ σας",
  "TaxonomyPickerNoTerms": "Το σύνολο όρων δεν περιέχει όρους",
  "TaxonomyPickerExpandTitle": "Επέκταση αυτού του συνόλου όρων",
  "TaxonomyPickerMenuTermSet": "Μενού για σύνολο όρων",
  "TaxonomyPickerInLabel": "In",
  "TaxonomyPickerTermSetLabel": "Σύνολο όρων",
  "TaxonomyPickerTermsNotFound": "Δεν ήταν δυνατή η βρείτε τον επόμενο ή τους επόμενους επιλεγμένους περιόδους στο χώρο αποθήκευσης όρων: {0}",
  "TaxonomyPickerInvalidTerms": "Καθορίστε μη έγκυρους όρους: {0}",
  "peoplePickerComponentTooltipMessage": "Ατόμων",
  "peoplePickerComponentErrorMessage": "Απαιτούμενο πεδίο",
  "peoplePickerSuggestionsHeaderText": "Προτεινόμενους ανθρώπους",
  "peoplePickerLoadingText": "Φόρτωση",
  "PeoplePickerSearchText": "Λήψη χρηστών",
  "PeoplePickerGroupNotFound": "Δεν ήταν δυνατή η εύρεση της ομάδας.",
  "genericNoResultsFoundText": "Δεν βρέθηκαν αποτελέσματα",
  "ListItemPickerSelectValue": "Επιλογή τιμής",
  "ListItemAttachmentsActionDeleteIconTitle": "Διαγράψετε",
  "ListItemAttachmentsactionDeleteTitle": "Διαγράψετε",
  "ListItemAttachmentsfileDeletedMsg": "Το αρχείο {0} διαγραφεί",
  "ListItemAttachmentsfileDeleteError": "Σφάλμα κατά τη διαγραφή αρχείου: {0}, αιτία {1}",
  "ListItemAttachmentserrorLoadAttachments": "Σφάλμα κατά την επισύναψη στοιχείου λίστας φόρτωσης, αιτία: {0}",
  "ListItemAttachmentsconfirmDelete": "Είστε βέβαιοι ότι θέλετε να στείλετε το συνημμένο {0} στον κάδο ανακύκλωσης της τοποθεσίας;",
  "ListItemAttachmentsdialogTitle": "Επισύναψη στοιχείου λίστας",
  "ListItemAttachmentsdialogOKbuttonLabel": "Ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Ακυρώσετε",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Διαγράψετε",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Προσθήκη συνημμένου",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Προσθήκη συνημμένου",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Το αρχείο δεν {0} συνημμένο, αιτία: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Προσθήκη συνημμένου",
  "ListItemAttachmentsloadingMessage": "Αποστολή αρχείου...",
  "ListItemAttachmentslPlaceHolderIconText": "Επισύναψη στοιχείου λίστας",
  "ListItemAttachmentslPlaceHolderDescription": "Παρακαλούμε Προσθήκη συνημμένου",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Προσθέσετε",
  "mapsErrorMessage": "Παρουσιάστηκε σφάλμα κατά τη φόρτωση του χάρτη",
  "mapsLoadingText": "Φόρτωση",
  "mapsSearchButtonText": "Αναζήτηση",
  "mapsTitlePrefix": "Χάρτης",
  "ListViewFilterLabel": "Φιλτράρισμα της λίστας",
  "HeaderNormalText": "Κανονικό κείμενο",
  "HeaderH2": "Τομέας 2",
  "HeaderH3": "Τομέας 3",
  "HeaderH4": "Τομέας 4",
  "HeaderBlockQuote": "Ελκυστική φράση",
  "AlignLeft": "Στοίχιση αριστερά",
  "AlignCenter": "Κέντρο",
  "AlignRight": "Στοίχιση δεξιά",
  "AlignJustify": "Δικαιολογήσει",
  "ListBullet": "Λίστα με κουκκίδες",
  "ListNumbered": "Αριθμημένη λίστα",
  "StyleTitle": "Στυλ",
  "BoldTitle": "Έντονη γραφή (CTRL + B)",
  "ItalicTitle": "Πλάγια γραφή (Ctrl + I)",
  "UnderlineTitle": "Υπογράμμιση (CTRL + U)",
  "AlignTitle": "Ευθυγραμμίστε",
  "ListTitle": "Λίστα",
  "LinkTitle": "Υπερ - σύνδεση",
  "ImageTitle": "Εικόνα",
  "MoreTitle": "Περισσότερες",
  "FormattingPaneTitle": "Μορφοποίηση κειμένου",
  "CloseButton": "Κλείσετε",
  "InsertLinkTitle": "Εισαγωγή συνδέσμου",
  "InsertImageTitle": "Εισαγωγή εικόνας",
  "AddressFieldLabel": "Διεύθυνση",
  "TextToDisplayLabel": "Κείμενο προς εμφάνιση",
  "SaveButtonLabel": "Αποθήκευση",
  "CancelButtonLabel": "Ακυρώσετε",
  "RemoveLinkLabel": "Κατάργηση συνδέσμου",
  "ParagraphSectionTitle": "Παράγραφο",
  "HyperlinkSectionTitle": "Υπερ - σύνδεση",
  "UndoTitle": "Αναίρεση (CTRL + Z)",
  "RedoTitle": "Επανάληψη (CTRL + Y)",
  "ClearFormattingTitle": "Απαλοιφή όλων των μορφοποιήσεων",
  "FontStyleTitle": "Στυλ γραμματοσειράς",
  "FontSizeTitle": "Μέγεθος γραμματοσειράς",
  "StrikethroughTitle": "Διακριτή διαγραφή",
  "SuperscriptTitle": "Εκθέτη",
  "SubscriptTitle": "Δείκτης",
  "FontColorLabel": "Χρώμα γραμματοσειράς",
  "AutomaticFontColor": "Αυτόματη",
  "HighlightColorLabel": "Χρώμα επισήμανσης",
  "NoColorHighlightColor": "Χωρίς χρώμα",
  "IncreaseIndentTitle": "Αύξηση εσοχής",
  "DecreaseIndentTitle": "Μείωση εσοχής",
  "ThemeColorsGroupName": "Χρώματα θέματος",
  "HighlightColorsGroupName": "Επισήμανση χρωμάτων",
  "StandardColorsGroupName": "Τυπικά χρώματα",
  "CustomColorsGroupName": "Προσαρμοσμένα χρώματα",
  "ThemeColorDarker": "Πιο σκούρο θέμα",
  "ThemeColorDark": "Θέμα σκούρο",
  "ThemeColorDarkAlt": "Θέμα σκούρο εναλλακτικό",
  "ThemeColorPrimary": "Πρωτεύον θέμα",
  "ThemeColorSecondary": "Θέμα δευτερεύων",
  "ThemeColorTertiary": "Ουδέτερη τριτογενής",
  "ThemeColorNeutralSecondary": "Ουδέτερο δευτερεύον",
  "ThemeColorNeutralPrimaryAlt": "Ουδέτερη κύρια εναλλακτική",
  "ThemeColorNeutralPrimary": "Ουδέτερο πρωτεύον",
  "ThemeColorNeutralDark": "Ουδέτερο σκοτάδι",
  "HighlightColorYellow": "Κίτρινο",
  "HighlightColorGreen": "Πράσινο",
  "HighlightColorAqua": "Ακουά",
  "HighlightColorMagenta": "Ματζέντα",
  "HighlightColorBlue": "Μπλε",
  "HighlightColorRed": "Κόκκινο",
  "HighlightColorDarkblue": "Σκούρο μπλε",
  "HighlightColorTeal": "Κιρκίρι",
  "HighlightColorDarkgreen": "Σκούρο πράσινο",
  "HighlightColorPurple": "Μωβ",
  "HighlightColorMaroon": "Καφέ",
  "HighlightColorGold": "Χρυσό",
  "HighlightColorDarkgrey": "Σκούρο γκρι",
  "HighlightColorGrey": "Γκρι",
  "HighlightColorBlack": "Μαύρο",
  "StandardColorDarkred": "Σκούρο κόκκινο",
  "StandardColorRed": "Κόκκινο",
  "StandardColorOrange": "Πορτοκαλί",
  "StandardColorYellow": "Κίτρινο",
  "StandardColorLightgreen": "Ανοιχτό πράσινο",
  "StandardColorGreen": "Πράσινο",
  "StandardColorLightblue": "Ανοιχτό μπλε",
  "StandardColorBlue": "Μπλε",
  "StandardColorDarkblue": "Σκούρο μπλε",
  "StandardColorPurple": "Μωβ",
  "DatePickerMonthLongJanuary": "Ιανουαρίου",
  "DatePickerMonthShortJanuary": "Ιανουαρίου",
  "DatePickerMonthLongFebruary": "Φεβρουάριος",
  "DatePickerMonthShortFebruary": "Φεβρουαρίου",
  "DatePickerMonthLongMarch": "Μαρτίου",
  "DatePickerMonthShortMarch": "Μαρ",
  "DatePickerMonthLongApril": "Απριλίου",
  "DatePickerMonthShortApril": "Απρ",
  "DatePickerMonthLongMay": "Μπορεί",
  "DatePickerMonthShortMay": "Μπορεί",
  "DatePickerMonthLongJune": "Ιουνίου",
  "DatePickerMonthShortJune": "Ιουνίου",
  "DatePickerMonthLongJuly": "Ιουλίου",
  "DatePickerMonthShortJuly": "Ιουλ",
  "DatePickerMonthLongAugust": "Αυγούστου",
  "DatePickerMonthShortAugust": "Αυγούστου",
  "DatePickerMonthLongSeptember": "Σεπτεμβρίου",
  "DatePickerMonthShortSeptember": "Επτά",
  "DatePickerMonthLongOctober": "Οκτωβρίου",
  "DatePickerMonthShortOctober": "Οκτωβρίου",
  "DatePickerMonthLongNovember": "Νοεμβρίου",
  "DatePickerMonthShortNovember": "Νοεμβρίου",
  "DatePickerMonthLongDecember": "Δεκεμβρίου",
  "DatePickerMonthShortDecember": "Δεκεμβρίου",
  "DatePickerDayLongSunday": "Κυριακή",
  "DatePickerDayShortSunday": "Κυρ",
  "DatePickerDayLongMonday": "Δευτέρα",
  "DatePickerDayShortMonday": "Μου",
  "DatePickerDayLongTuesday": "Τρίτη",
  "DatePickerDayShortTuesday": "Τρί",
  "DatePickerDayLongWednesday": "Τετάρτη",
  "DatePickerDayShortWednesday": "Τετ",
  "DatePickerDayLongThursday": "Πέμπτη",
  "DatePickerDayShortThursday": "Πέμ",
  "DatePickerDayLongFriday": "Παρασκευή",
  "DatePickerDayShortFriday": "Παρ",
  "DatePickerDayLongSaturday": "Σάββατο",
  "DatePickerDayShortSaturday": "Σάβ",
  "DatePickerGoToToday": "Σήμερα",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Ημερομηνία",
  "DateTimePickerTime": "Χρόνο",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Τιμή εσφαλμένης ώρας",
  "DateTimePickerMinuteValueInvalid": "Εσφαλμένη τιμή λεπτού",
  "DateTimePickerSecondValueInvalid": "Εσφαλμένη δεύτερη τιμή",
  "DateTimePickerTextErrorMessage": "Πληκτρολογήστε μια έγκυρη ημερομηνία",
  "AddFileButtonLabel": "Προσθήκη αρχείου",
  "AddImageButtonLabel": "Προσθήκη εικόνας",
  "AriaCellValue": "{0} στήλη, {1}",
  "FilePickerCancelButtonLabel": "Ακυρώσετε",
  "CantValidateValidationMessage": "Δεν μπορέσαμε να επιβεβαιώσουμε αυτή τη σύνδεση. Ελέγξτε τη σύνδεση και προσπαθήστε ξανά.",
  "ChangeFileLinkLabel": "Αλλαγή αρχείου",
  "ChangeImageLinkLabel": "Αλλαγή εικόνας",
  "ChooseFileLinkLabel": "Επιλογή αρχείου",
  "ChooseImageLinkLabel": "Επιλογή εικόνας",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Είστε υπεύθυνοι για τον σεβασμό των δικαιωμάτων των άλλων, συμπεριλαμβανομένων των πνευματικών δικαιωμάτων.",
  "CreativeCommonsMessage": "Αυτά τα αποτελέσματα επισημαίνονται με τις άδειες χρήσης δημιουργικών κοινών. Εξετάστε τις άδειες χρήσης για να διασφαλίσετε ότι συμμορφώνεστε.",
  "DateFormat": "ΜΜ/ηη/εεεε Ωω: λλ α",
  "DocumentLabelTemplate": "{0}, έγγραφο, τροποποιημένο {1}, επεξεργασία από {2}, ιδιωτικό",
  "DocumentLibraries": "Βιβλιοθήκες εγγράφων",
  "EditedByNamePlate": "επεξεργασία από ",
  "EmptyFileSize": "0 byte",
  "FilePickerHeader": "Επιλογή αρχείου",
  "FileSizeField": "Μέγεθος αρχείου",
  "FolderAltText": "Φάκελο",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, φάκελος, τροποποιημένο {1}, επεξεργασία από {2}, {3} στοιχεία, ιδιωτικό",
  "FromLinkLinkLabel": "Από μια σύνδεση",
  "ImageAltText": ". {0} εικόνα",
  "ImageAriaLabelTemplate": ". {0} εικόνα",
  "ImageLayoutPlaceholderText": "Διάταξη",
  "ImageSizePlaceholderText": "Μέγεθος εικόνας",
  "ItemChildCountField": "Καταμέτρηση θυγατρικού στοιχείου",
  "LayoutOptionAll": "Όλα",
  "LayoutOptionSquare": "Πλατεία",
  "LayoutOptionTall": "Ψηλό",
  "LayoutOptionWide": "Ευρύ",
  "LearnMoreLink": "Μάθε περισσότερα.",
  "LicenseOptionAll": "Όλα",
  "LicenseOptionAny": "Μόνο δημιουργικά κοινά",
  "LicensePlaceholderText": "Άδεια",
  "LinkFileInstructions": "Επικολλήστε μια σύνδεση σε ένα αρχείο στο OneDrive για επαγγελματική ή SharePoint Online",
  "LinkHeader": "Από μια σύνδεση",
  "LinkImageInstructions": "Επικόλληση μιας σύνδεσης σε μια εικόνα στο OneDrive για επαγγελματική ή ηλεκτρονική SharePoint",
  "ListLayoutAriaLabel": "Δείτε τις επιλογές. {0} {1}.",
  "ListLayoutCompact": "Συμπαγής προβολή",
  "ListLayoutCompactDescription": "Προβολή στοιχείων και λεπτομερειών σε μια συμπαγή λίστα",
  "ListLayoutList": "Προβολή λίστας",
  "ListLayoutListDescrition": "Προβολή στοιχείων και λεπτομερειών σε μια λίστα",
  "ListLayoutTile": "Προβολή πλακιδίων",
  "ListLayoutTileDescription": "Προβολή στοιχείων με προεπισκοπήσεις πλακιδίων",
  "ListOptionsAlt": "Δείτε τις επιλογές. {0} επιλεγεί.",
  "ListOptionsTitle": "Άνοιγμα του μενού επιλογών προβολής",
  "Loading": "Φόρτωση...",
  "ModifiedByField": "Τροποποιήθηκε από",
  "ModifiedField": "Ημερομηνία τροποποίησης",
  "NameField": "Όνομα",
  "No": "Όχι",
  "ProvidedValueIsInvalid": "Η παρεχόμενη τιμή δεν είναι έγκυρη",
  "NoExternalLinksValidationMessage": "Υποστηρίζουμε μόνο τη σύνδεση με αρχεία του δικού σας οργανισμού.",
  "NoImageValidationMessage": "Αυτή δεν είναι μια σύνδεση με έναν τύπο αρχείου που υποστηρίζουμε. Μπορείτε να συνδέσετε μόνο μια εικόνα.",
  "NoRecentFiles": "Δεν υπάρχουν πρόσφατα αρχεία",
  "NoRecentFilesDescription": "Δοκιμάστε να επιλέξετε ένα αρχείο από τον ιστότοπό σας ή Ανεβάστε ένα από τη συσκευή σας.",
  "NoResultsBadEnglish": "Δεν βρέθηκε αποτέλεσμα. Προσπαθήστε να αλλάξετε τις επιλογές φίλτρου",
  "ODModifiedField": "Τροποποιηθεί",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, τροποποιημένο {2}, επεξεργασία από {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Αυτό το στοιχείο προέρχεται από την τοποθεσία σας στο OneDrive. Τα αρχεία και οι φάκελοι στο OneDrive είναι ιδιωτικά, εκτός εάν τα μοιράζεστε. Έχετε μοιραστεί αυτό το αρχείο με τα μέλη του ιστότοπού σας, ώστε να μπορούν να το κάνουν;",
  "OneDriveConfirmDialogTitle": "Απλά ελέγχω...",
  "OneDriveEmptyFolderAlt": "Κενός φάκελος",
  "OneDriveEmptyFolderDescription": "Για να προσθέσετε αρχεία, μεταβείτε στο OneDrive. Μπορείτε επίσης να προσθέσετε αρχεία σε αυτόν το φάκελο χρησιμοποιώντας την εφαρμογή OneDrive για τον υπολογιστή σας.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Αυτός ο φάκελος είναι κενός",
  "OneDriveRootFolderName": "Αρχεία",
  "OpenButtonLabel": "Ανοίξετε",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Εικόνες και αρχεία που παρέχονται από τον οργανισμό σας",
  "PoweredByBing": "Τροφοδοτείται από το Bing",
  "RecentDocumentsHeader": "Πρόσφατα έγγραφα",
  "RecentImagesHeader": "Πρόσφατες εικόνες",
  "RecentLinkLabel": "Πρόσφατους",
  "SearchBoxPlaceholder": "Αναζήτηση στο Web",
  "SearchResultAlt": "Αποτέλεσμα εικόνας για {0}.",
  "SearchResultAriaLabel": "Πατήστε ENTER για να ανοίξετε την πηγή εικόνας σε μια νέα καρτέλα.",
  "Selected": "Επιλεγμένο",
  "SharingField": "Κοινή χρήση",
  "SharingPrivate": "Ιδιωτικό",
  "SharingShared": "Κοινόχρηστο",
  "SiteLinkLabel": "Τοποθεσία",
  "SizeOptionAll": "Όλα",
  "SizeOptionExtraLarge": "Πολύ μεγάλο",
  "SizeOptionLarge": "Μεγάλο",
  "SizeOptionMedium": "Μεσαία",
  "SizeOptionSmall": "Μικρό",
  "SizeUnit": [
    "Byte",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Π.χ",
    "Yb"
  ],
  "SorryWebSearch": "Λυπούμαστε, αυτή η λειτουργία δεν υλοποιείται σε αυτό το δείγμα, επειδή θα απαιτούσε ένα κλειδί Bing API.",
  "SortedAscending": "Ταξινομημένο α έως ω",
  "SortedDescending": "Ταξινόμηση Z σε A",
  "TypeAriaLabel": "Λειτουργίες στηλών για τον τύπο αρχείου, πατήστε για ταξινόμηση σε τύπο αρχείου",
  "UploadFileHeader": "Αποστολή αρχείου",
  "UploadImageHeader": "Αποστολή εικόνας",
  "UploadLinkLabel": "Φορτώσετε",
  "WebSearchLinkLabel": "Αναζήτηση στο Web",
  "StockImagesLinkLabel": "στοκ φωτογραφίες",
  "StockImagesHeader": "στοκ φωτογραφίες",
  "Yes": "Ναι",
  "NewFolderNamePlaceholder": "Εισαγάγετε το όνομα του φακέλου σας",
  "FolderFilterBoxPlaceholder": "Φιλτράρισμα φακέλων κατά όνομα",
  "FolderExplorerLoading": "Φόρτωση φακέλων...",
  "FolderExplorerNoItems": "Αυτός ο φάκελος δεν έχει υποφακέλους.",
  "NewFolderIncorrectSymbolsError": "Πληκτρολογήστε ένα όνομα που δεν περιλαμβάνει κανέναν από αυτούς τους χαρακτήρες: \" * : < > ; /  |.",
  "SomethingWentWrong": "Κάτι πήγε στραβά.",
  "SelectedLabel": "Επιλεγμένα",
  "SelectIcon": "Επιλογή εικονιδίου",
  "TreeViewExpandTitle": "Ανάπτυξη αυτού του στοιχείου",
  "TreeViewCollapseTitle": "Σύμπτυξη αυτού του στοιχείου",
  "CollectionDataEmptyFields": "Δεν δόθηκαν πεδία για τα δεδομένα συλλογής.",
  "CollectionDataEmptyValue": "Δεν υπάρχουν δεδομένα στη συλλογή σας.",
  "CollectionAddRowButtonLabel": "Προσθήκη δεδομένων στη συλλογή",
  "CollectionDeleteRowButtonLabel": "Διαγραφή της τρέχουσας γραμμής",
  "CollectionSaveAndAddButtonLabel": "Προσθήκη και αποθήκευση",
  "CollectionDataItemShowErrorsLabel": "Εμφάνιση σφαλμάτων γραμμής",
  "CollectionDataItemFieldRequiredLabel": "Απαιτείται πεδίο.",
  "CollectionDataItemMissingFields": "Η συλλογή πεδίων είναι άδεια!",
  "InvalidUrlError": "Η παρεχόμενη διεύθυνση URL δεν είναι έγκυρη",
  "CollectionDataSearch": "Αναζήτηση",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "φόρτωση των ομάδων σας",
  "MyTeamsMessageError": "Κάτι πήγε στραβά κατά τη φόρτωση των ομάδων σας, δοκιμάστε αργότερα ή ανανεώστε το πρόγραμμα περιήγησης",
  "MyTeamsNoTeamsMessage": "Δεν έχεις ομάδες.",
  "MyTeamsTeamChannelPublicMessage": "Δημόσια Κανάλια",
  "MyTeamsTeamChannelTypeMessage": "Ιδιωτικά κανάλια",
  "TeamChannelPickerFontIconFavoriteText": "Αγαπημένος",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Ιδιωτικό κανάλι",
  "TeamChannelPickerSugestionHeaderText": "Προτεινόμενα κανάλια ομάδας",
  "TeamPickerButtonRemoveTitle": "αφαιρώ",
  "TeamPickernoResultsFoundText": "Δεν βρέθηκαν ομάδες",
  "TeamPickerSugestionsHeaderText": "Προτεινόμενες ομάδες",
  "TeamsChannelPickerButtonRemoveTitle": "αφαιρώ",
  "TeamsChannelPickerNoresultsFoundText": "Δεν βρέθηκαν κανάλια",
  "ViewMore": "Δείτε περισσότερα",
  "DynamicFormLoading": "Φόρτωση...",
  "DynamicFormPleaseWait": "Παρακαλώ περίμενε...",
  "DynamicFormRequiredErrorMessage": "Δεν μπορείς να το αφήσεις κενό.",
  "DynamicFormTermPanelTitle": "Επιλογή όρου",
  "DynamicFormEnterURLPlaceholder": "Εισαγωγή διεύθυνσης URL",
  "DynamicFormEnterDescriptionPlaceholder": "Εναλλακτικό κείμενο",
  "DynamicFormDialogValidationErrorTitle": "Σφάλμα επικύρωσης",
  "DynamicFormDialogValidationErrorMessage": "Υπάρχουν σφάλματα επικύρωσης, διορθώστε τα πριν την αποθήκευση.",
  "DynamicFormNumberValueMustBeGreaterThan": "Η τιμή πρέπει να είναι μεγαλύτερη από {0}",
  "DynamicFormNumberValueMustBeBetween": "Η τιμή πρέπει να είναι μεταξύ {0} και {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Η τιμή πρέπει να είναι μικρότερη από {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Χρησιμοποιήστε αυτήν τη θέση:",
  "ListItemCommentDIalogDeleteSubText": "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το σχόλιο;",
  "ListItemCommentsDialogDeleteTitle": "Επιβεβαίωση διαγραφής σχολίου",
  "ListItemCommentsLabel": "Σχόλια",
  "ListItemCommentsNoCommentsLabel": "No comments",
  "OrgAssetsLinkLabel": "Ο οργανισμός σας",
  "MyTeamsMessageDontHaveTeams": "You don't have any teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Εισαγάγετε έναν όρο που θέλετε να προσθέσετε ετικέτα",
  "ModernTaxonomyPickerTreeTitleSingle": "Επιλογή ετικέτας",
  "ModernTaxonomyPickerTreeTitleMulti": "Επιλέξτε μία ή περισσότερες ετικέτες",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Προσθήκη ετικέτας",
  "ModernTaxonomyPickerApplyButtonText": "Χρήση",
  "ModernTaxonomyPickerCancelButtonText": "Ακύρωση",
  "ModernTaxonomyPickerLoadMoreText": "Μάθετε περισσότερα",
  "ModernTaxonomyPickerRemoveButtonText": "Διαγραφή",
  "ModernTaxonomyPickerPanelCloseButtonText": "Κλείσιμο",
  "ModernTaxonomyPickerNoResultsFound": "Δεν βρέθηκαν αποτελέσματα",
  "ModernTaxonomyPickerSuggestionInLabel": "In",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
