declare var define: any;

define([], () => {
  return {
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  "Save": "Tallenna",
  "Cancel": "Peruuta",
  "SiteBreadcrumbLabel": "Sivuston navigointi polku",
  "ListViewGroupEmptyLabel": "Tyhjä",
  "WebPartTitlePlaceholder": "WWW-osan otsikko",
  "WebPartTitleLabel": "Otsikon lisääminen",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Muutamassa sekunnissa",
    "L_RelativeDateTime_AFewSeconds": "Muutama sekunti sitten",
    "L_RelativeDateTime_AboutAMinuteFuture": "Noin minuutissa",
    "L_RelativeDateTime_AboutAMinute": "Noin minuutti sitten",
    "L_RelativeDateTime_XMinutesFuture": "{0} minuutissa||{0} minuutin",
    "L_RelativeDateTime_XMinutes": "{0} minuutti sitten||{0} minuuttia sitten",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
    "L_RelativeDateTime_XMinutesIntervals": "1||2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Noin tunnissa",
    "L_RelativeDateTime_AboutAnHour": "Noin tunti sitten",
    "L_RelativeDateTime_Tomorrow": "Huomenna",
    "L_RelativeDateTime_Yesterday": "Eilen",
    "L_RelativeDateTime_TomorrowAndTime": "Tomorrow yrityksessä {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Eilen klo {0}",
    "L_RelativeDateTime_XHoursFuture": "{0} tunnissa||{0} tunnin aikana",
    "L_RelativeDateTime_XHours": "{0} tunti sitten||{0} tuntia sitten",
    "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
    "L_RelativeDateTime_XHoursIntervals": "1||2-",
    "L_RelativeDateTime_DayAndTime": "{0} oppi laitoksessa {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} päivä nyt||{0} päivää tästä lähtien",
    "L_RelativeDateTime_XDays": "{0} päivä sitten||{0} päivää sitten",
    "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
    "L_RelativeDateTime_XDaysIntervals": "1||2-",
    "L_RelativeDateTime_Today": "Tänään"
  },
  "SendEmailTo": "Lähetä sähkö postia {0}",
  "StartChatWith": "Aloita keskustelu {0}",
  "Contact": "Meihin yhteyttä",
  "UpdateProfile": "Päivitä profiilisi",
  "TaxonomyPickerNoTerms": "Termi joukko ei sisällä mitään termejä",
  "TaxonomyPickerExpandTitle": "Laajenna tämä termi joukko",
  "TaxonomyPickerMenuTermSet": "Termi joukon valikko",
  "TaxonomyPickerInLabel": "Paikassa",
  "TaxonomyPickerTermSetLabel": "Termi joukko",
  "TaxonomyPickerTermsNotFound": "Seuraavia valittuja termejä ei löytynyt termisäilöstä: {0}",
  "TaxonomyPickerInvalidTerms": "Korjaa virheelliset termi(t): {0}",
  "peoplePickerComponentTooltipMessage": "Henkilöiden valitsin",
  "peoplePickerComponentErrorMessage": "Pakollinen kenttä",
  "peoplePickerSuggestionsHeaderText": "Ehdotetut henkilöt",
  "peoplePickerLoadingText": "Lastaus",
  "PeoplePickerSearchText": "Haetaan käyttäjiä",
  "PeoplePickerGroupNotFound": "Ryhmää ei löytynyt.",
  "genericNoResultsFoundText": "Tuloksia ei löytynyt",
  "ListItemPickerSelectValue": "Valitse arvo",
  "ListItemAttachmentsActionDeleteIconTitle": "Poista",
  "ListItemAttachmentsactionDeleteTitle": "Poista",
  "ListItemAttachmentsfileDeletedMsg": "Tiedosto {0} poistettu",
  "ListItemAttachmentsfileDeleteError": "Virhe poistettavan tiedoston kohdalla: {0}, syy {1}",
  "ListItemAttachmentserrorLoadAttachments": "Virhe kuormitus luettelo nimikkeen liite tiedoston syy: {0}",
  "ListItemAttachmentsconfirmDelete": "Haluatko varmasti lähettää liite {0} sivuston roska koriin?",
  "ListItemAttachmentsdialogTitle": "Luettelo kohteen liite",
  "ListItemAttachmentsdialogOKbuttonLabel": "Okei",
  "ListItemAttachmentsdialogCancelButtonLabel": "Peruuta",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Poista",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Lisää liite",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Lisää liite",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Tiedostoa ei {0} liitetty, syy: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Lisää liite",
  "ListItemAttachmentsloadingMessage": "Ladataan tiedostoa...",
  "ListItemAttachmentslPlaceHolderIconText": "Luettelo kohteen liite",
  "ListItemAttachmentslPlaceHolderDescription": "Lisää liite",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Lisää",
  "mapsErrorMessage": "Virhe ladattaessa karttaa",
  "mapsLoadingText": "Lastaus",
  "mapsSearchButtonText": "Etsi",
  "mapsTitlePrefix": "Kartta",
  "ListViewFilterLabel": "Suodata luettelo",
  "HeaderNormalText": "Normaali teksti",
  "HeaderH2": "Otsake 2",
  "HeaderH3": "Otsake 3",
  "HeaderH4": "Otsake 4",
  "HeaderBlockQuote": "Erotettu lainaus",
  "AlignLeft": "Tasaa vasemmalle",
  "AlignCenter": "Keskelle",
  "AlignRight": "Tasaa oikealle",
  "AlignJustify": "Perustella",
  "ListBullet": "Luettelon",
  "ListNumbered": "Numeroitu luettelo",
  "StyleTitle": "Tyyli",
  "BoldTitle": "Lihavoitu (Ctrl + B)",
  "ItalicTitle": "Kursivi (Ctrl + I)",
  "UnderlineTitle": "Alleviivaus (Ctrl + U)",
  "AlignTitle": "Tasaa",
  "ListTitle": "Luettelo",
  "LinkTitle": "Hyperlinkki",
  "ImageTitle": "Kuva",
  "MoreTitle": "Lisää",
  "FormattingPaneTitle": "Tekstin muotoilu",
  "CloseButton": "Lähellä",
  "InsertLinkTitle": "Lisää linkki",
  "InsertImageTitle": "Lisää kuva",
  "AddressFieldLabel": "Osoite",
  "TextToDisplayLabel": "Näytettävä teksti",
  "SaveButtonLabel": "Tallenna",
  "CancelButtonLabel": "Peruuta",
  "RemoveLinkLabel": "Poista linkki",
  "ParagraphSectionTitle": "Kappale",
  "HyperlinkSectionTitle": "Hyperlinkki",
  "UndoTitle": "Kumoa (Ctrl + Z)",
  "RedoTitle": "Tee uudelleen (Ctrl + Y)",
  "ClearFormattingTitle": "Poista kaikki muotoilut",
  "FontStyleTitle": "Fonttityyli",
  "FontSizeTitle": "Fonttikoko",
  "StrikethroughTitle": "Yliviivaus",
  "SuperscriptTitle": "Yläindeksi",
  "SubscriptTitle": "Alaindeksi",
  "FontColorLabel": "Fontin väri",
  "AutomaticFontColor": "Automaattinen",
  "HighlightColorLabel": "Korosta väri",
  "NoColorHighlightColor": "Ei väriä",
  "IncreaseIndentTitle": "Suurenna sisennystä",
  "DecreaseIndentTitle": "Pienennä sisennystä",
  "ThemeColorsGroupName": "Teeman värit",
  "HighlightColorsGroupName": "Korosta värit",
  "StandardColorsGroupName": "Vakiovärit",
  "CustomColorsGroupName": "Mukautetut värit",
  "ThemeColorDarker": "Tummempi teema",
  "ThemeColorDark": "Tumma teema",
  "ThemeColorDarkAlt": "Vaihtoehtoinen tumma teema",
  "ThemeColorPrimary": "Ensisijainen teema",
  "ThemeColorSecondary": "Toissijainen teema",
  "ThemeColorTertiary": "Neutraali tertiääri",
  "ThemeColorNeutralSecondary": "Neutraali toissijainen",
  "ThemeColorNeutralPrimaryAlt": "Neutraali ensisijainen vaihtoehto",
  "ThemeColorNeutralPrimary": "Neutraali ensisijainen",
  "ThemeColorNeutralDark": "Neutraali tumma",
  "HighlightColorYellow": "Keltainen",
  "HighlightColorGreen": "Vihreä",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Sininen",
  "HighlightColorRed": "Punainen",
  "HighlightColorDarkblue": "Tummansininen",
  "HighlightColorTeal": "Sinivihreä",
  "HighlightColorDarkgreen": "Tummanvihreä",
  "HighlightColorPurple": "Violetti",
  "HighlightColorMaroon": "Kastanjanruskea",
  "HighlightColorGold": "Kulta",
  "HighlightColorDarkgrey": "Tummanharmaa",
  "HighlightColorGrey": "Harmaa",
  "HighlightColorBlack": "Musta",
  "StandardColorDarkred": "Tummanpunainen",
  "StandardColorRed": "Punainen",
  "StandardColorOrange": "Oranssi",
  "StandardColorYellow": "Keltainen",
  "StandardColorLightgreen": "Vaaleanvihreä",
  "StandardColorGreen": "Vihreä",
  "StandardColorLightblue": "Vaaleansininen",
  "StandardColorBlue": "Sininen",
  "StandardColorDarkblue": "Tummansininen",
  "StandardColorPurple": "Violetti",
  "DatePickerMonthLongJanuary": "Tammikuu",
  "DatePickerMonthShortJanuary": "Tam",
  "DatePickerMonthLongFebruary": "Helmikuu",
  "DatePickerMonthShortFebruary": "Hel",
  "DatePickerMonthLongMarch": "Maaliskuu",
  "DatePickerMonthShortMarch": "Maal",
  "DatePickerMonthLongApril": "Huhtikuu",
  "DatePickerMonthShortApril": "Huhti",
  "DatePickerMonthLongMay": "Toukokuu",
  "DatePickerMonthShortMay": "Touko",
  "DatePickerMonthLongJune": "Kesäkuu",
  "DatePickerMonthShortJune": "Kesä",
  "DatePickerMonthLongJuly": "Heinäkuu",
  "DatePickerMonthShortJuly": "Heinä",
  "DatePickerMonthLongAugust": "Elokuu",
  "DatePickerMonthShortAugust": "Elo",
  "DatePickerMonthLongSeptember": "Syyskuu",
  "DatePickerMonthShortSeptember": "Syys",
  "DatePickerMonthLongOctober": "Lokakuu",
  "DatePickerMonthShortOctober": "Loka",
  "DatePickerMonthLongNovember": "Marraskuu",
  "DatePickerMonthShortNovember": "Marras",
  "DatePickerMonthLongDecember": "Joulukuu",
  "DatePickerMonthShortDecember": "Joulu",
  "DatePickerDayLongSunday": "Sunnuntai",
  "DatePickerDayShortSunday": "Sun",
  "DatePickerDayLongMonday": "Maanantai",
  "DatePickerDayShortMonday": "Ma",
  "DatePickerDayLongTuesday": "Tiistai",
  "DatePickerDayShortTuesday": "Ti",
  "DatePickerDayLongWednesday": "Keskiviikko",
  "DatePickerDayShortWednesday": "Ke",
  "DatePickerDayLongThursday": "Torstai",
  "DatePickerDayShortThursday": "To",
  "DatePickerDayLongFriday": "Perjantai",
  "DatePickerDayShortFriday": "Pe",
  "DatePickerDayLongSaturday": "Lauantai",
  "DatePickerDayShortSaturday": "La",
  "DatePickerGoToToday": "Tänään",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Päivämäärä",
  "DateTimePickerTime": "Aika",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Virheellinen tuntiarvo",
  "DateTimePickerMinuteValueInvalid": "Virheellinen minuuttiarvo",
  "DateTimePickerSecondValueInvalid": "Virheellinen toinen arvo",
  "DateTimePickerTextErrorMessage": "Anna kelvollinen päivämäärä",
  "AddFileButtonLabel": "Lisää tiedosto",
  "AddImageButtonLabel": "Lisää kuva",
  "AriaCellValue": "{0} sarake, {1}",
  "FilePickerCancelButtonLabel": "Peruuta",
  "CantValidateValidationMessage": "Emme voineet vahvistaa tätä linkkiä. Tarkista linkki ja yritä uudelleen.",
  "ChangeFileLinkLabel": "Muuta tiedosto",
  "ChangeImageLinkLabel": "Vaihda kuva",
  "ChooseFileLinkLabel": "Valitse tiedosto",
  "ChooseImageLinkLabel": "Valitse kuva",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Olet vastuussa muiden oikeuksien, myös tekijänoikeuden, kunnioittamisesta.",
  "CreativeCommonsMessage": "Nämä tulokset on merkitty Creative Commons-lisensseillä. Tarkista käyttöoikeudet, jotta voit varmistaa, että noudatat niitä.",
  "DateFormat": "KK/PP/VVVV hh: mm A",
  "DocumentLabelTemplate": "{0}, asiakirja, muokattu {1}, muokkaaja {2}, Yksityinen",
  "DocumentLibraries": "Asiakirjakirjastot",
  "EditedByNamePlate": "muokkaaja ",
  "EmptyFileSize": "0 tavua",
  "FilePickerHeader": "Tiedoston valitsin",
  "FileSizeField": "Tiedoston koko",
  "FolderAltText": "Kansio",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, kansio, muokattu {1}, muokkaaja {2}, {3} kohteet, Yksityinen",
  "FromLinkLinkLabel": "Linkistä",
  "ImageAltText": ". {0} Kuva",
  "ImageAriaLabelTemplate": ". {0} Kuva",
  "ImageLayoutPlaceholderText": "Asettelu",
  "ImageSizePlaceholderText": "Kuvan koko",
  "ItemChildCountField": "Nimikkeen kohteiden määrä",
  "LayoutOptionAll": "Kaikki",
  "LayoutOptionSquare": "Neliö",
  "LayoutOptionTall": "Pitkä",
  "LayoutOptionWide": "Laaja",
  "LearnMoreLink": "Opi lisää.",
  "LicenseOptionAll": "Kaikki",
  "LicenseOptionAny": "Vain Creative Commons",
  "LicensePlaceholderText": "Lisenssi",
  "LinkFileInstructions": "Liitä linkki tiedostoon OneDrive for Businessissa tai SharePoint Onlinessa",
  "LinkHeader": "Linkistä",
  "LinkImageInstructions": "Liitä linkki kuvaan OneDrive for Businessissa tai SharePoint Onlinessa",
  "ListLayoutAriaLabel": "Näytä valinnat. {0} {1}.",
  "ListLayoutCompact": "Kompakti näkymä",
  "ListLayoutCompactDescription": "Pienikokoisen luettelon kohteiden ja yksityiskohtien tarkasteleminen",
  "ListLayoutList": "Luettelonäkymä",
  "ListLayoutListDescrition": "Luettelon kohteiden ja yksityiskohtien tarkasteleminen",
  "ListLayoutTile": "Ruudukko",
  "ListLayoutTileDescription": "Näytä kohteet, joissa on ruutu esikatseluun",
  "ListOptionsAlt": "Näytä valinnat. {0} valittu.",
  "ListOptionsTitle": "Avaa Näytä valinnat-valikko",
  "Loading": "Lataa...",
  "ModifiedByField": "Muokkaaja",
  "ModifiedField": "Muutettu päivämäärä",
  "NameField": "Nimi",
  "No": "Ei",
  "ProvidedValueIsInvalid": "Annettu arvo ei kelpaa",
  "NoExternalLinksValidationMessage": "Tuemme vain oman organisaatiosi tiedostojen linkittämistä.",
  "NoImageValidationMessage": "Tämä ei ole linkki tiedostotyyppiin, jota tuemme. Voit linkittää vain kuvaan.",
  "NoRecentFiles": "Ei viimeaikaisia tiedostoja",
  "NoRecentFilesDescription": "Valitse tiedosto sivustosta tai lataa se laitteestasi.",
  "NoResultsBadEnglish": "Tuloksia ei löytynyt. Yritä muuttaa suodatusasetuksia",
  "ODModifiedField": "Muutettu",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, muokattu {2}, {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Tämä kohde on OneDrive-sivustosta. OneDriven tiedostot ja kansiot ovat yksityisiä, ellet Jaa niitä. Oletko jakanut tämän tiedoston sivuston jäsenille, jotta he voivat käyttää sitä?",
  "OneDriveConfirmDialogTitle": "Tarkistetaan...",
  "OneDriveEmptyFolderAlt": "Tyhjä kansio",
  "OneDriveEmptyFolderDescription": "Jos haluat lisätä tiedostoja, siirry OneDriveen. Voit myös lisätä tiedostoja tähän kansioon tieto koneen OneDrive-sovelluksen avulla.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Tämä kansio on tyhjä",
  "OneDriveRootFolderName": "Tiedostot",
  "OpenButtonLabel": "Avaa",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Organisaatiosi toimittamat kuvat ja tiedostot",
  "PoweredByBing": "Voimanlähteenä Bing",
  "RecentDocumentsHeader": "Viimeisimmät tiedostot",
  "RecentImagesHeader": "Viimeisimmät kuvat",
  "RecentLinkLabel": "Viimeisimmät",
  "SearchBoxPlaceholder": "Verkkohaku",
  "SearchResultAlt": "Kuvatulos haulle {​​​0}​​​",
  "SearchResultAriaLabel": "Paine ENTER avataksesi kuvan lähteen uudessa välilehdessä.",
  "Selected": "Valittu",
  "SharingField": "Jakaminen",
  "SharingPrivate": "Yksityiset",
  "SharingShared": "Jaettu",
  "SiteLinkLabel": "Sivusto",
  "SizeOptionAll": "Kaikki",
  "SizeOptionExtraLarge": "Erittäin suuri",
  "SizeOptionLarge": "Suuri",
  "SizeOptionMedium": "Keskisuuri",
  "SizeOptionSmall": "Pieni",
  "SizeUnit": [
    "Tavua",
    "KB",
    "MB",
    "GB",
    "TB",
    "PB",
    "EB",
    "ZB",
    "YB"
  ],
  "SorryWebSearch": "Tätä toimintoa ei valitettavasti ole toteutettu tässä esimerkissä, koska se edellyttäisi Bing API-avainta.",
  "SortedAscending": "Lajiteltu A-Z",
  "SortedDescending": "Lajiteltu Z-A",
  "TypeAriaLabel": "Saraketoiminnot tiedostotyypille, lajittele tiedostotyypin mukaan painamalla",
  "UploadFileHeader": "Lataa tiedosto",
  "UploadImageHeader": "Lataa kuva",
  "UploadLinkLabel": "Lataa",
  "WebSearchLinkLabel": "Verkkohaku",
  "StockImagesLinkLabel": "Arkistokuvat",
  "StockImagesHeader": "Arkistokuvat",
  "Yes": "Kyllä",
  "NewFolderNamePlaceholder": "Anna kansion nimi",
  "FolderFilterBoxPlaceholder": "Kansioiden suodattaminen nimen mukaan",
  "FolderExplorerLoading": "Ladataan kansioita...",
  "FolderExplorerNoItems": "Tässä kansiossa ei ole alikansioita.",
  "NewFolderIncorrectSymbolsError": "Kirjoita nimi, joka ei sisällä mitään näistä merkeistä: \" * : < > ? /  |.",
  "SomethingWentWrong": "Jokin meni vikaan.",
  "SelectedLabel": "Valittu",
  "SelectIcon": "Valitse kuvake",
  "TreeViewExpandTitle": "Laajenna tämä kohde",
  "TreeViewCollapseTitle": "Kutista tämä kohde",
  "CollectionDataEmptyFields": "Keräystietoihin ei annettu kenttiä.",
  "CollectionDataEmptyValue": "Kokoelmassa ei ole tietoja.",
  "CollectionAddRowButtonLabel": "Tietojen lisääminen kokoelmaan",
  "CollectionDeleteRowButtonLabel": "Poista nykyinen rivi",
  "CollectionSaveAndAddButtonLabel": "Lisääminen ja tallentaminen",
  "CollectionDataItemShowErrorsLabel": "Näytä rivivirheet",
  "CollectionDataItemFieldRequiredLabel": "Kenttä on pakollinen.",
  "CollectionDataItemMissingFields": "Kenttien kokoelma on tyhjä!",
  "InvalidUrlError": "Annettu URL-osoite ei kelpaa",
  "CollectionDataSearch": "Etsiä",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "Tiimien lataaminen",
  "MyTeamsMessageError": "Jokin meni vikaan ladattaessa tiimejäsi, kokeile myöhemmin tai päivitä selain",
  "MyTeamsNoTeamsMessage": "Sinulla ei ole yhtään tiimiä.",
  "MyTeamsTeamChannelPublicMessage": "Julkiset kanavat",
  "MyTeamsTeamChannelTypeMessage": "Yksityiset kanavat",
  "TeamChannelPickerFontIconFavoriteText": "Suosikki",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Yksityinen kanava",
  "TeamChannelPickerSugestionHeaderText": "Ehdotetut ryhmäkanavat",
  "TeamPickerButtonRemoveTitle": "poista",
  "TeamPickernoResultsFoundText": "Tiimejä ei löytynyt",
  "TeamPickerSugestionsHeaderText": "Ehdotetut tiimit",
  "TeamsChannelPickerButtonRemoveTitle": "poista",
  "TeamsChannelPickerNoresultsFoundText": "Kanavia ei löytynyt",
  "ViewMore": "Näytä lisää",
  "DynamicFormLoading": "Lataa...",
  "DynamicFormPleaseWait": "Ole hyvä ja odota...",
  "DynamicFormRequiredErrorMessage": "Et voi jättää tätä tyhjäksi.",
  "DynamicFormTermPanelTitle": "Valitse termi",
  "DynamicFormEnterURLPlaceholder": "URL-osoitteen syöttäminen",
  "DynamicFormEnterDescriptionPlaceholder": "Vaihtoehtoinen teksti",
  "DynamicFormDialogValidationErrorTitle": "Vahvistusvirhe",
  "DynamicFormDialogValidationErrorMessage": "Vahvistusvirheitä on, korjaa ne ennen tallentamista.",
  "DynamicFormNumberValueMustBeGreaterThan": "Arvon on oltava suurempi kuin {0}",
  "DynamicFormNumberValueMustBeBetween": "Tämän kentän arvon on oltava välillä {0} - {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Arvon on oltava pienempi kuin {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Käytä tätä sijaintia:",
  "ListItemCommentDIalogDeleteSubText": "Haluatko varmasti poistaa tämän kommentin?",
  "ListItemCommentsDialogDeleteTitle": "Vahvista poista kommentti",
  "ListItemCommentsLabel": "Kommentit",
  "ListItemCommentsNoCommentsLabel": "Kommentteja ei ole",
  "OrgAssetsLinkLabel": "Oma organisaatio",
  "MyTeamsMessageDontHaveTeams": "Sinulla ei ole yhtään tiimejä",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Kirjoita tagi, jonka haluat merkitä",
  "ModernTaxonomyPickerTreeTitle": "Valitse tunniste",
  "ModernTaxonomyPickerTreeTitleSingle": "Valitse tunniste",
  "ModernTaxonomyPickerTreeTitleMulti": "Valitse yksi tai useampi tunniste",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Lisää tunniste",
  "ModernTaxonomyPickerApplyButtonText": "Käytä",
  "ModernTaxonomyPickerCancelButtonText": "Peruuta",
  "ModernTaxonomyPickerLoadMoreText": "Lisätietoja",
  "ModernTaxonomyPickerRemoveButtonText": "Poista",
  "ModernTaxonomyPickerPanelCloseButtonText": "Sulje",
  "ModernTaxonomyPickerNoResultsFound": "Ei tuloksia",
  "ModernTaxonomyPickerSuggestionInLabel": "Tuumaa",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
