declare var define: any;

define([], () => {
  return {
    PeoplePickerGroupNotFound: "Groupe introuvable.",
    ListViewFilterLabel: "Filtrer",

    PeoplePickerSearchText: "Recherche d'utilisateurs",
    peoplePickerComponentTooltipMessage: "Sélecteur de personnes",
    peoplePickerComponentErrorMessage: "Champ obligatoire",
    peoplePickerSuggestionsHeaderText: "Personnes suggérées",
    genericNoResultsFoundText: "Aucun résultat trouvé",
    peoplePickerLoadingText: "Chargement",

    SiteBreadcrumbLabel: "Fil d'Ariane",
    ListViewGroupEmptyLabel: "Vide",
    WebPartTitlePlaceholder: "Titre du composant WebPart",
    WebPartTitleLabel: "Ajouter un titre",
    // DateTime: IDateTimeStrings;
    SendEmailTo: "Envoyer un email à {0}",
    StartChatWith: "Démarrer une discussion avec {0}",
    Contact: "Contact",
    UpdateProfile: "Mettre à jour votre profil",

    // Taxonomy picker
    TaxonomyPickerNoTerms: "L'ensemble de termes ne contient aucun terme",
    TaxonomyPickerExpandTitle: "Développer cet ensemble de termes",
    TaxonomyPickerMenuTermSet: "Menu pour l'ensemble de termes",
    TaxonomyPickerInLabel: "dans",
    TaxonomyPickerTermSetLabel: "Ensemble de termes",

    ListItemPickerSelectValue: "Sélectionnez une valeur",

    ListItemAttachmentsActionDeleteIconTitle: "Supprimer",
    ListItemAttachmentsactionDeleteTitle: "Supprimer",
    ListItemAttachmentsfileDeletedMsg: "Fichier {0} supprimé",
    ListItemAttachmentsfileDeleteError: "Erreur lors de la suppression du fichier : {0}, cause : {1}",
    ListItemAttachmentserrorLoadAttachments: "Erreur lors du chargement de la pièce jointe, cause : {0}",
    ListItemAttachmentsconfirmDelete: "Voulez-vous vraiment envoyer la pièce jointe {0} à la Corbeille du site ?",
    ListItemAttachmentsdialogTitle: "Pièce jointe",
    ListItemAttachmentsdialogOKbuttonLabel: "OK",
    ListItemAttachmentsdialogCancelButtonLabel: "Annuler",
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: "Supprimer",
    ListItemAttachmentsuploadAttachmentDialogTitle: "Ajouter une pièce jointe",
    ListItemAttachmentsuploadAttachmentButtonLabel: "Ajouter une pièce jointe",
    ListItemAttachmentsuploadAttachmentErrorMsg: "Le fichier {0} n'a pas pu être ajouté en tant que pièce jointe, cause : {1}",
    ListItemAttachmentsCommandBarAddAttachmentLabel: "Ajouter une pièce jointe",
    ListItemAttachmentsloadingMessage: "Téléchargement du fichier...",
    ListItemAttachmentslPlaceHolderIconText: "Pièce jointe",
    ListItemAttachmentslPlaceHolderDescription: "Ajouter des pièces jointes",
    ListItemAttachmentslPlaceHolderButtonLabel: "Ajouter",

    //Maps
    mapsErrorMessage: "Une erreur s'est produite lors du chargement de la carte",
    mapsLoadingText: "Chargement",
    mapsSearchButtonText: "Rechercher",
    mapsTitlePrefix: "Carte de",

    // RichText
    HeaderNormalText: "Texte normal",
    HeaderH2: "Titre 1",
    HeaderH3: "Titre 2",
    HeaderH4: "Titre 3",
    HeaderBlockQuote: "Citation",
    AlignLeft: "Aligner à gauche",
    AlignCenter: "Centrer",
    AlignRight: "Aligner à droite",
    AlignJustify: "Justifier",
    ListBullet: "Liste à puces",
    ListNumbered: "Liste numérotée",
    StyleTitle: "Style",
    BoldTitle: "Gras (Ctrl+B)",
    ItalicTitle: "Italique (Ctrl+I)",
    UnderlineTitle: "Souligné (Ctrl+U)",
    AlignTitle: "Alignement",
    ListTitle: "Liste",
    LinkTitle: "Lien hypertexte",
    MoreTitle: "Plus",
    FormattingPaneTitle: "Mise en forme du texte",
    CloseButton: "Fermer",
    InsertLinkTitle: "Insertion de lien",
    AddressFieldLabel: "Adresse",
    TextToDisplayLabel: "Texte à afficher",
    SaveButtonLabel: "Enregistrer",
    CancelButtonLabel: "Annuler",
    RemoveLinkLabel: "Supprimer le lien",
    ParagraphSectionTitle: "Paragraphe",
    HyperlinkSectionTitle: "Lien hypertexte",
    UndoTitle: "Annuler (Ctrl+Z)",
    RedoTitle: "Rétablir (Ctrl+Y)",
    ClearFormattingTitle: "Effacer toute la mise en forme",
    FontStyleTitle: "Style de police",
    FontSizeTitle: "Taille de police",
    StrikethroughTitle: "Barré",
    SuperscriptTitle: "Exposant",
    SubscriptTitle: "Indice",
    FontColorLabel: "Couleur de police",
    AutomaticFontColor: "Automatique",
    HighlightColorLabel: "Couleur de surlignage",
    NoColorHighlightColor: "Aucune couleur",
    IncreaseIndentTitle: "Augmenter le retrait",
    DecreaseIndentTitle: "Diminuer le retrait",
    ThemeColorsGroupName: "Couleurs du thème",
    HighlightColorsGroupName: "Couleurs de surlignage",
    StandardColorsGroupName: "Couleurs standards",
    ThemeColorDarker: "Thème plus foncé",
    ThemeColorDark: "Thème foncé",
    ThemeColorDarkAlt: "Couleur alternative du thème foncé",
    ThemeColorPrimary: "Première couleur du thème",
    ThemeColorSecondary: "Deuxième couleur du thème",
    ThemeColorTertiary: "Troisième couleur du thème",
    ThemeColorNeutralSecondary: "Couleur neutre secondaire",
    ThemeColorNeutralPrimaryAlt: "Alternative à la couleur neutre principale",
    ThemeColorNeutralPrimary: "Couleur neutre principale",
    ThemeColorNeutralDark: "Couleur neutre foncé",
    HighlightColorYellow: "Jaune",
    HighlightColorGreen: "Vert",
    HighlightColorAqua: "Cyan",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Bleu",
    HighlightColorRed: "Rouge",
    HighlightColorDarkblue: "Bleu foncé",
    HighlightColorTeal: "Bleu-vert",
    HighlightColorDarkgreen: "Vert foncé",
    HighlightColorPurple: "Violet",
    HighlightColorMaroon: "Marron",
    HighlightColorGold: "Or",
    HighlightColorDarkgrey: "Gris foncé",
    HighlightColorGrey: "Gris",
    HighlightColorBlack: "Noir",
    StandardColorDarkred:"Rouge foncé",
    StandardColorRed:"Rouge",
    StandardColorOrange:"Orange",
    StandardColorYellow:"Jaune",
    StandardColorLightgreen:"Vert clair",
    StandardColorGreen:"Vert",
    StandardColorLightblue:"Bleu clait",
    StandardColorBlue:"Bleu",
    StandardColorDarkblue:"Bleu foncé",
    StandardColorPurple:"Violet",

    // DateTime picker
    DatePickerMonthLongJanuary: "Janvier",
    DatePickerMonthShortJanuary: "Janv.",
    DatePickerMonthLongFebruary: "Février",
    DatePickerMonthShortFebruary: "Févr.",
    DatePickerMonthLongMarch: "Mars",
    DatePickerMonthShortMarch: "Mars",
    DatePickerMonthLongApril: "Avril",
    DatePickerMonthShortApril: "Avr.",
    DatePickerMonthLongMay: "Mai",
    DatePickerMonthShortMay: "Mai",
    DatePickerMonthLongJune: "Juin",
    DatePickerMonthShortJune: "Juin",
    DatePickerMonthLongJuly: "Juillet",
    DatePickerMonthShortJuly: "Juill.",
    DatePickerMonthLongAugust: "Août",
    DatePickerMonthShortAugust: "Août",
    DatePickerMonthLongSeptember: "Septembre",
    DatePickerMonthShortSeptember: "Sept.",
    DatePickerMonthLongOctober: "Octobre",
    DatePickerMonthShortOctober: "Oct.",
    DatePickerMonthLongNovember: "Novembre",
    DatePickerMonthShortNovember: "Nov.",
    DatePickerMonthLongDecember: "Décembre",
    DatePickerMonthShortDecember: "Déc.",
    DatePickerDayLongSunday: "Dimanche",
    DatePickerDayShortSunday: "Dim",
    DatePickerDayLongMonday: "Lundi",
    DatePickerDayShortMonday: "Lun",
    DatePickerDayLongTuesday: "Mardi",
    DatePickerDayShortTuesday: "Mar",
    DatePickerDayLongWednesday: "Mercredi",
    DatePickerDayShortWednesday: "Mer",
    DatePickerDayLongThursday: "Jeudi",
    DatePickerDayShortThursday: "Jeu",
    DatePickerDayLongFriday: "Vendredi",
    DatePickerDayShortFriday: "Ven",
    DatePickerDayLongSaturday: "Samedi",
    DatePickerDayShortSaturday: "Sam",
    DatePickerGoToToday: "Aujourd'hui",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Date",
    DateTimePickerTime: "Heure",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Valeur incorrecte pour l'heure",

    DateTime: {
      L_RelativeDateTime_AFewSecondsFuture: "Dans quelques secondes",
      L_RelativeDateTime_AFewSeconds: "Il y a quelques secondes",
      L_RelativeDateTime_AboutAMinuteFuture: "Dans environ une minute",
      L_RelativeDateTime_AboutAMinute: "Il y a environ une minute",
      L_RelativeDateTime_XMinutesFuture: "Dans {0} minute||Dans {0} minutes",
      L_RelativeDateTime_XMinutes: "Il y a {0} minute||Il y a {0} minutes",
      L_RelativeDateTime_XMinutesFutureIntervals: "1||2-",
      L_RelativeDateTime_XMinutesIntervals: "1||2-",
      L_RelativeDateTime_AboutAnHourFuture: "Dans environ une heure",
      L_RelativeDateTime_AboutAnHour: "Il y a environ une heure",
      L_RelativeDateTime_Tomorrow: "Demain",
      L_RelativeDateTime_Yesterday: "Hier",
      L_RelativeDateTime_TomorrowAndTime: "Demain à {0}",
      L_RelativeDateTime_YesterdayAndTime: "Hier à {0}",
      L_RelativeDateTime_XHoursFuture: "Dans {0} heure||Dans {0} heures",
      L_RelativeDateTime_XHours: "Il y a {0} heure||Il y a {0} heures",
      L_RelativeDateTime_XHoursFutureIntervals: "1||2-",
      L_RelativeDateTime_XHoursIntervals: "1||2-",
      L_RelativeDateTime_DayAndTime: "{0} à {1}",
      L_RelativeDateTime_XDaysFuture: "{0} jour à partir de maintenant || {0} jours à partir de maintenant",
      L_RelativeDateTime_XDays: "Il y a {0} jour||Il y a {0} jours",
      L_RelativeDateTime_XDaysFutureIntervals: "1||2-",
      L_RelativeDateTime_XDaysIntervals: "1||2-",
      L_RelativeDateTime_Today: "Aujourd'hui"
    },

    AddFileButtonLabel: "Add file",
    AddImageButtonLabel: "Add image",
    AriaCellValue: "{0} column, {1}",
    FilePickerCancelButtonLabel: "Cancel",
    CantValidateValidationMessage: "We couldn't verify this link. Please check the link and try again.",
    ChangeFileLinkLabel: "Change file",
    ChangeImageLinkLabel: "Change image",
    ChooseFileLinkLabel: "Choose file",
    ChooseImageLinkLabel: "Choose image",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    DocumentLibraries: "Document libraries",
    EditedByNamePlate: "edited by ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "File Picker",
    FileSizeField: "File Size",
    FolderAltText: "Folder",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "No",
    ProvidedValueIsInvalid: "Provided value is invalid",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    OneDriveRootFolderName: "Files",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Recent documents",
    RecentImagesHeader: "Recent images",
    RecentLinkLabel: "Recent",
    SearchBoxPlaceholder: "Web search",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    Selected: "selected",
    SharingField: "Sharing",
    SharingPrivate: "Private",
    SharingShared: "Shared",
    SiteLinkLabel: "Site",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Sorry, this function isn't implemented in this sample, because it would require a Bing API key.",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Upload file",
    UploadImageHeader: "Upload image",
    UploadLinkLabel: "Upload",
    WebSearchLinkLabel: "Web search",
    Yes: "Yes"
  };
});
