declare var define: any;

define([], () => {
  return {
  "SiteBreadcrumbLabel": "Fil d'Ariane",
  "ListViewGroupEmptyLabel": "Vide",
  "WebPartTitlePlaceholder": "Titre du composant WebPart",
  "WebPartTitleLabel": "Ajouter un titre",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Dans quelques secondes",
    "L_RelativeDateTime_AFewSeconds": "Il y a quelques secondes",
    "L_RelativeDateTime_AboutAMinuteFuture": "Dans environ une minute",
    "L_RelativeDateTime_AboutAMinute": "Il y a environ une minute",
    "L_RelativeDateTime_XMinutesFuture": "Dans {0} minute||Dans {0} minutes",
    "L_RelativeDateTime_XMinutes": "Il y a {0} minute||Il y a {0} minutes",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Dans environ une heure",
    "L_RelativeDateTime_AboutAnHour": "Il y a environ une heure",
    "L_RelativeDateTime_Tomorrow": "Demain",
    "L_RelativeDateTime_Yesterday": "Hier",
    "L_RelativeDateTime_TomorrowAndTime": "Demain à {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Hier à {0}",
    "L_RelativeDateTime_XHoursFuture": "Dans {0} heure||Dans {0} heures",
    "L_RelativeDateTime_XHours": "Il y a {0} heure||Il y a {0} heures",
    "L_RelativeDateTime_XHoursFutureIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_XHoursIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_DayAndTime": "{0} à {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} jour à partir de maintenant || {0} jours à partir de maintenant",
    "L_RelativeDateTime_XDays": "Il y a {0} jour||Il y a {0} jours",
    "L_RelativeDateTime_XDaysFutureIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_XDaysIntervals": "1 à 1 euro 2-",
    "L_RelativeDateTime_Today": "Aujourd'hui"
  },
  "SendEmailTo": "Envoyer un email à {0}",
  "StartChatWith": "Démarrer une discussion avec {0}",
  "Contact": "Contact",
  "UpdateProfile": "Mettre à jour votre profil",
  "TaxonomyPickerNoTerms": "L'ensemble de termes ne contient aucun terme",
  "TaxonomyPickerExpandTitle": "Développer cet ensemble de termes",
  "TaxonomyPickerMenuTermSet": "Menu pour l'ensemble de termes",
  "TaxonomyPickerInLabel": "dans",
  "TaxonomyPickerTermSetLabel": "Ensemble de termes",
  "peoplePickerComponentTooltipMessage": "Sélecteur de personnes",
  "peoplePickerComponentErrorMessage": "Champ obligatoire",
  "peoplePickerSuggestionsHeaderText": "Personnes suggérées",
  "peoplePickerLoadingText": "Chargement",
  "PeoplePickerSearchText": "Recherche d'utilisateurs",
  "PeoplePickerGroupNotFound": "Groupe introuvable.",
  "genericNoResultsFoundText": "Aucun résultat trouvé",
  "ListItemPickerSelectValue": "Sélectionnez une valeur",
  "ListItemAttachmentsActionDeleteIconTitle": "Supprimer",
  "ListItemAttachmentsactionDeleteTitle": "Supprimer",
  "ListItemAttachmentsfileDeletedMsg": "Fichier {0} supprimé",
  "ListItemAttachmentsfileDeleteError": "Erreur lors de la suppression du fichier : {0}, cause : {1}",
  "ListItemAttachmentserrorLoadAttachments": "Erreur lors du chargement de la pièce jointe, cause : {0}",
  "ListItemAttachmentsconfirmDelete": "Voulez-vous vraiment envoyer la pièce jointe {0} à la Corbeille du site ?",
  "ListItemAttachmentsdialogTitle": "Pièce jointe",
  "ListItemAttachmentsdialogOKbuttonLabel": "D'accord",
  "ListItemAttachmentsdialogCancelButtonLabel": "Annuler",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Supprimer",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Ajouter une pièce jointe",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Ajouter une pièce jointe",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Le fichier {0} n'a pas pu être ajouté en tant que pièce jointe, cause : {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Ajouter une pièce jointe",
  "ListItemAttachmentsloadingMessage": "Téléchargement du fichier...",
  "ListItemAttachmentslPlaceHolderIconText": "Pièce jointe",
  "ListItemAttachmentslPlaceHolderDescription": "Ajouter des pièces jointes",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Ajouter",
  "mapsErrorMessage": "Une erreur s'est produite lors du chargement de la carte",
  "mapsLoadingText": "Chargement",
  "mapsSearchButtonText": "Rechercher",
  "mapsTitlePrefix": "Carte de",
  "ListViewFilterLabel": "Filtrer",
  "HeaderNormalText": "Texte normal",
  "HeaderH2": "Titre 1",
  "HeaderH3": "Titre 2",
  "HeaderH4": "Titre 3",
  "HeaderBlockQuote": "Citation",
  "AlignLeft": "Aligner à gauche",
  "AlignCenter": "Centrer",
  "AlignRight": "Aligner à droite",
  "AlignJustify": "Justifier",
  "ListBullet": "Liste à puces",
  "ListNumbered": "Liste numérotée",
  "StyleTitle": "Style",
  "BoldTitle": "Gras (Ctrl+B)",
  "ItalicTitle": "Italique (Ctrl+I)",
  "UnderlineTitle": "Souligné (Ctrl+U)",
  "AlignTitle": "Alignement",
  "ListTitle": "Liste",
  "LinkTitle": "Lien hypertexte",
  "MoreTitle": "Plus",
  "FormattingPaneTitle": "Mise en forme du texte",
  "CloseButton": "Fermer",
  "InsertLinkTitle": "Insertion de lien",
  "AddressFieldLabel": "Adresse",
  "TextToDisplayLabel": "Texte à afficher",
  "SaveButtonLabel": "Enregistrer",
  "CancelButtonLabel": "Annuler",
  "RemoveLinkLabel": "Supprimer le lien",
  "ParagraphSectionTitle": "Paragraphe",
  "HyperlinkSectionTitle": "Lien hypertexte",
  "UndoTitle": "Annuler (Ctrl+Z)",
  "RedoTitle": "Rétablir (Ctrl+Y)",
  "ClearFormattingTitle": "Effacer toute la mise en forme",
  "FontStyleTitle": "Style de police",
  "FontSizeTitle": "Taille de police",
  "StrikethroughTitle": "Barré",
  "SuperscriptTitle": "Exposant",
  "SubscriptTitle": "Indice",
  "FontColorLabel": "Couleur de police",
  "AutomaticFontColor": "Automatique",
  "HighlightColorLabel": "Couleur de surlignage",
  "NoColorHighlightColor": "Aucune couleur",
  "IncreaseIndentTitle": "Augmenter le retrait",
  "DecreaseIndentTitle": "Diminuer le retrait",
  "ThemeColorsGroupName": "Couleurs du thème",
  "HighlightColorsGroupName": "Couleurs de surlignage",
  "StandardColorsGroupName": "Couleurs standards",
  "CustomColorsGroupName": "Couleurs personnalisées",
  "ThemeColorDarker": "Thème plus foncé",
  "ThemeColorDark": "Thème foncé",
  "ThemeColorDarkAlt": "Couleur alternative du thème foncé",
  "ThemeColorPrimary": "Première couleur du thème",
  "ThemeColorSecondary": "Deuxième couleur du thème",
  "ThemeColorTertiary": "Troisième couleur du thème",
  "ThemeColorNeutralSecondary": "Couleur neutre secondaire",
  "ThemeColorNeutralPrimaryAlt": "Alternative à la couleur neutre principale",
  "ThemeColorNeutralPrimary": "Couleur neutre principale",
  "ThemeColorNeutralDark": "Couleur neutre foncé",
  "HighlightColorYellow": "Jaune",
  "HighlightColorGreen": "Vert",
  "HighlightColorAqua": "Cyan",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Bleu",
  "HighlightColorRed": "Rouge",
  "HighlightColorDarkblue": "Bleu foncé",
  "HighlightColorTeal": "Bleu-vert",
  "HighlightColorDarkgreen": "Vert foncé",
  "HighlightColorPurple": "Violet",
  "HighlightColorMaroon": "Marron",
  "HighlightColorGold": "Or",
  "HighlightColorDarkgrey": "Gris foncé",
  "HighlightColorGrey": "Gris",
  "HighlightColorBlack": "Noir",
  "StandardColorDarkred": "Rouge foncé",
  "StandardColorRed": "Rouge",
  "StandardColorOrange": "Orange",
  "StandardColorYellow": "Jaune",
  "StandardColorLightgreen": "Vert clair",
  "StandardColorGreen": "Vert",
  "StandardColorLightblue": "Bleu clait",
  "StandardColorBlue": "Bleu",
  "StandardColorDarkblue": "Bleu foncé",
  "StandardColorPurple": "Violet",
  "DatePickerMonthLongJanuary": "Janvier",
  "DatePickerMonthShortJanuary": "Janv.",
  "DatePickerMonthLongFebruary": "Février",
  "DatePickerMonthShortFebruary": "Févr.",
  "DatePickerMonthLongMarch": "Mars",
  "DatePickerMonthShortMarch": "Mars",
  "DatePickerMonthLongApril": "Avril",
  "DatePickerMonthShortApril": "Avr.",
  "DatePickerMonthLongMay": "Mai",
  "DatePickerMonthShortMay": "Mai",
  "DatePickerMonthLongJune": "Juin",
  "DatePickerMonthShortJune": "Juin",
  "DatePickerMonthLongJuly": "Juillet",
  "DatePickerMonthShortJuly": "Juill.",
  "DatePickerMonthLongAugust": "Août",
  "DatePickerMonthShortAugust": "Août",
  "DatePickerMonthLongSeptember": "Septembre",
  "DatePickerMonthShortSeptember": "Sept.",
  "DatePickerMonthLongOctober": "Octobre",
  "DatePickerMonthShortOctober": "Oct.",
  "DatePickerMonthLongNovember": "Novembre",
  "DatePickerMonthShortNovember": "Nov.",
  "DatePickerMonthLongDecember": "Décembre",
  "DatePickerMonthShortDecember": "Déc.",
  "DatePickerDayLongSunday": "Dimanche",
  "DatePickerDayShortSunday": "Dim",
  "DatePickerDayLongMonday": "Lundi",
  "DatePickerDayShortMonday": "Lun",
  "DatePickerDayLongTuesday": "Mardi",
  "DatePickerDayShortTuesday": "Mar",
  "DatePickerDayLongWednesday": "Mercredi",
  "DatePickerDayShortWednesday": "Mer",
  "DatePickerDayLongThursday": "Jeudi",
  "DatePickerDayShortThursday": "Jeu",
  "DatePickerDayLongFriday": "Vendredi",
  "DatePickerDayShortFriday": "Ven",
  "DatePickerDayLongSaturday": "Samedi",
  "DatePickerDayShortSaturday": "Sam",
  "DatePickerGoToToday": "Aujourd'hui",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Date",
  "DateTimePickerTime": "Heure",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Valeur incorrecte pour l'heure",
  "AddFileButtonLabel": "Ajouter le fichier",
  "AddImageButtonLabel": "Ajouter de l'image",
  "AriaCellValue": "{0} colonne, {1}",
  "FilePickerCancelButtonLabel": "Annuler",
  "CantValidateValidationMessage": "Nous n'avons pas pu vérifier ce lien. S'il vous plaît vérifier le lien et essayer à nouveau.",
  "ChangeFileLinkLabel": "Modifier le fichier",
  "ChangeImageLinkLabel": "Changer l'image",
  "ChooseFileLinkLabel": "Choisissez le fichier",
  "ChooseImageLinkLabel": "Choisissez l'image",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Vous êtes responsable du respect des droits des autres, y compris le droit d'auteur.",
  "CreativeCommonsMessage": "Ces résultats sont étiquetés avec des licences Creative Commons. Examinez les licences pour vous assurer que vous vous conformez.",
  "DateFormat": "MM/DD/YYYY hh:mm A",
  "DocumentLabelTemplate": "{0}, Document, {1} modifié, édité par {2}, Private",
  "DocumentLibraries": "Bibliothèques de documents",
  "EditedByNamePlate": "édité par ",
  "EmptyFileSize": "0 octets",
  "FilePickerHeader": "Picker de fichiers",
  "FileSizeField": "Taille du fichier",
  "FolderAltText": "Dossier",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, Folder, Modified {1}, édité par {2}, {3} articles, Private",
  "FromLinkLinkLabel": "À partir d'un lien",
  "ImageAltText": ". image {0}",
  "ImageAriaLabelTemplate": ". image {0}",
  "ImageLayoutPlaceholderText": "Disposition",
  "ImageSizePlaceholderText": "Taille de l'image",
  "ItemChildCountField": "Nombre d'enfants d'article",
  "LayoutOptionAll": "Tous",
  "LayoutOptionSquare": "Carré",
  "LayoutOptionTall": "Grand",
  "LayoutOptionWide": "Large",
  "LearnMoreLink": "Pour en savoir plus.",
  "LicenseOptionAll": "Tous",
  "LicenseOptionAny": "Creative Commons uniquement",
  "LicensePlaceholderText": "Licence",
  "LinkFileInstructions": "Collez un lien vers un fichier dans OneDrive for Business ou SharePoint Online",
  "LinkHeader": "À partir d'un lien",
  "LinkImageInstructions": "Collez un lien vers une image dans OneDrive for Business ou SharePoint Online",
  "ListLayoutAriaLabel": "Afficher les options. {0} {1} .",
  "ListLayoutCompact": "Vue compacte",
  "ListLayoutCompactDescription": "Afficher les éléments et les détails dans une liste compacte",
  "ListLayoutList": "Afficher la liste",
  "ListLayoutListDescrition": "Afficher les éléments et les détails dans une liste",
  "ListLayoutTile": "Vue de tuile",
  "ListLayoutTileDescription": "Afficher les éléments avec aperçus de tuiles",
  "ListOptionsAlt": "Afficher les options. {0} sélectionnés .",
  "ListOptionsTitle": "Ouvrez le menu des options de vue",
  "Loading": "Chargement...",
  "ModifiedByField": "Modifié par",
  "ModifiedField": "Date modifiée",
  "NameField": "Nom",
  "No": "non",
  "ProvidedValueIsInvalid": "La valeur fournie est invalide",
  "NoExternalLinksValidationMessage": "Nous ne prenons en charge que les liens vers les fichiers de votre propre organisation.",
  "NoImageValidationMessage": "Ce n'est pas un lien vers un type de fichier que nous prenons en charge. Vous ne pouvez lier qu'à une image.",
  "NoRecentFiles": "Pas de fichiers récents",
  "NoRecentFilesDescription": "Essayez de sélectionner un fichier à partir de votre site ou téléchargez-en un à partir de votre appareil.",
  "NoResultsBadEnglish": "Aucun résultat n'a été trouvé. Essayez de modifier les options de filtre",
  "ODModifiedField": "Modifié",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, {2} modifié, édité par {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Cet article provient de votre site OneDrive. Les fichiers et dossiers dans OneDrive sont privés à moins que vous ne les partagiez. Avez-vous partagé ce fichier avec les membres de votre site afin qu'ils puissent le ccess?",
  "OneDriveConfirmDialogTitle": "Il suffit de vérifier ...",
  "OneDriveEmptyFolderAlt": "Dossier vide",
  "OneDriveEmptyFolderDescription": "Pour ajouter des fichiers, rendez-vous sur votre OneDrive. Vous pouvez également ajouter des fichiers à ce dossier à l'aide de l'application OneDrive pour votre ordinateur.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Ce dossier est vide",
  "OneDriveRootFolderName": "Fichiers",
  "OpenButtonLabel": "Ouvert",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Images et fichiers fournis par votre organisation",
  "PoweredByBing": "Propulsé par Bing",
  "RecentDocumentsHeader": "Documents récents",
  "RecentImagesHeader": "Images récentes",
  "RecentLinkLabel": "Récente",
  "SearchBoxPlaceholder": "Recherche sur le Web",
  "SearchResultAlt": "Résultat d'image pour {0}.",
  "SearchResultAriaLabel": "Appuyez sur entrez pour ouvrir la source d'image dans un nouvel onglet.",
  "Selected": "Sélectionné",
  "SharingField": "Partage",
  "SharingPrivate": "Privé",
  "SharingShared": "Partagé",
  "SiteLinkLabel": "Site",
  "SizeOptionAll": "Tous",
  "SizeOptionExtraLarge": "Extra Large",
  "SizeOptionLarge": "Grande",
  "SizeOptionMedium": "Moyen",
  "SizeOptionSmall": "Petit",
  "SizeUnit": [
    "Octets",
    "Ko",
    "Mb",
    "Go",
    "Tb",
    "Pb",
    "Eb",
    "Eg",
    "Yb"
  ],
  "SorryWebSearch": "Désolé, cette fonction n'est pas implémentée dans cet exemple, car elle nécessiterait une clé D'API Bing.",
  "SortedAscending": "Trié sain à l'autre de A à Z",
  "SortedDescending": "Triéz Z à A",
  "TypeAriaLabel": "Opérations de colonne pour le type de fichier, Appuyez sur pour trier sur le type de fichier",
  "UploadFileHeader": "Télécharger le fichier",
  "UploadImageHeader": "Télécharger l'image",
  "UploadLinkLabel": "Télécharger",
  "WebSearchLinkLabel": "Recherche sur le Web",
  "Yes": "Oui"
};
});