declare var define: any;

define([], () => {
  return {
  CalendarControlDayOfWeekSunday: "Sunday",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "found",
  worldMapLoadintText: "Loading map style…",
  worldMapLocationLabel: "location",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "name",
  worldMapSearchLocations: "Search locations...",
  worldMapTitle: "World Map",
  worldMapZoomContent: "Zoom in",
  worldMapZoomIn: "Zoom in",
  "Save": "Salva",
  "Cancel": "Annulla",
  "SiteBreadcrumbLabel": "Breadcrumb del sito web",
  "ListViewGroupEmptyLabel": "Vuoto",
  "WebPartTitlePlaceholder": "Titolo web part",
  "WebPartTitleLabel": "Aggiungere un titolo",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "In pochi secondi",
    "L_RelativeDateTime_AFewSeconds": "Pochi secondi fa",
    "L_RelativeDateTime_AboutAMinuteFuture": "In circa un minuto",
    "L_RelativeDateTime_AboutAMinute": "Circa un minuto fa",
    "L_RelativeDateTime_XMinutesFuture": "In {0} minuto In {0} minuti",
    "L_RelativeDateTime_XMinutes": "{0} minuti fa {0} minuti fa",
    "L_RelativeDateTime_XMinutesFutureIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_XMinutesIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "In circa un'ora",
    "L_RelativeDateTime_AboutAnHour": "Circa un'ora fa",
    "L_RelativeDateTime_Tomorrow": "Domani",
    "L_RelativeDateTime_Yesterday": "Ieri",
    "L_RelativeDateTime_TomorrowAndTime": "Domani al {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Ieri a {0}",
    "L_RelativeDateTime_XHoursFuture": "In {0} ora In {0} ore",
    "L_RelativeDateTime_XHours": "{0}'ora fa {0} ore fa",
    "L_RelativeDateTime_XHoursFutureIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_XHoursIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_DayAndTime": "{0} {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} giorno da adesso {0} giorni tra ora",
    "L_RelativeDateTime_XDays": "{0} giorno fa {0} giorni fa",
    "L_RelativeDateTime_XDaysFutureIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_XDaysIntervals": "N. 1 . . . . . . . . 2-",
    "L_RelativeDateTime_Today": "Oggi"
  },
  "SendEmailTo": "Inviare un messaggio di posta elettronica a {0}",
  "StartChatWith": "Avviare una chat con {0}",
  "Contact": "Contattare",
  "UpdateProfile": "Aggiornare il profilo",
  "TaxonomyPickerNoTerms": "Il set di termini non contiene termini",
  "TaxonomyPickerExpandTitle": "Espandi questo set di termini",
  "TaxonomyPickerMenuTermSet": "Menu per il set di termini",
  "TaxonomyPickerInLabel": "Pollici",
  "TaxonomyPickerTermSetLabel": "Set di termini",
  "TaxonomyPickerTermsNotFound": "Impossibile trovare i termini selezionati successivi nell'archivio termini: {0}",
  "TaxonomyPickerInvalidTerms": "Correggere i termini non validi: {0}",
  "peoplePickerComponentTooltipMessage": "Selezione utenti",
  "peoplePickerComponentErrorMessage": "Campo obbligatorio",
  "peoplePickerSuggestionsHeaderText": "Persone suggerite",
  "peoplePickerLoadingText": "Caricamento",
  "PeoplePickerSearchText": "Recupero degli utenti",
  "PeoplePickerGroupNotFound": "Impossibile trovare il gruppo.",
  "genericNoResultsFoundText": "Nessun risultato trovato",
  "ListItemPickerSelectValue": "Seleziona valore",
  "ListItemAttachmentsActionDeleteIconTitle": "Elimina",
  "ListItemAttachmentsactionDeleteTitle": "Elimina",
  "ListItemAttachmentsfileDeletedMsg": "Il file {0} eliminato",
  "ListItemAttachmentsfileDeleteError": "Errore nel file di eliminazione: {0}, motivo {1}",
  "ListItemAttachmentserrorLoadAttachments": "Errore durante il caricamento dell'allegato della voce dell'elenco, motivo: {0}",
  "ListItemAttachmentsconfirmDelete": "Sei sicuro di voler inviare l'allegato {0} al cestino del sito?",
  "ListItemAttachmentsdialogTitle": "Allegato voce di elenco",
  "ListItemAttachmentsdialogOKbuttonLabel": "Ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Annulla",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Elimina",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Aggiungi allegato",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Aggiungi allegato",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Il file non {0} allegato, motivo: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Aggiungi allegato",
  "ListItemAttachmentsloadingMessage": "Caricamento del file in corso...",
  "ListItemAttachmentslPlaceHolderIconText": "Allegato voce di elenco",
  "ListItemAttachmentslPlaceHolderDescription": "Si prega di aggiungi allegato",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Aggiungere",
  "mapsErrorMessage": "Si è verificato un errore durante il caricamento della mappa",
  "mapsLoadingText": "Caricamento",
  "mapsSearchButtonText": "Ricerca",
  "mapsTitlePrefix": "Mappa di",
  "ListViewFilterLabel": "Filtrare l'elenco",
  "HeaderNormalText": "Testo normale",
  "HeaderH2": "Titolo 2",
  "HeaderH3": "Titolo 3",
  "HeaderH4": "Titolo 4",
  "HeaderBlockQuote": "Quotazione pull",
  "AlignLeft": "Allinea a sinistra",
  "AlignCenter": "Centro",
  "AlignRight": "Allinea a destra",
  "AlignJustify": "Giustificare",
  "ListBullet": "Elenco puntato",
  "ListNumbered": "Elenco numerato",
  "StyleTitle": "Stile",
  "BoldTitle": "Grassetto (CTRL-B)",
  "ItalicTitle": "Corsivo (CTRL-I)",
  "UnderlineTitle": "Sottolineato (CTRL-U)",
  "AlignTitle": "Allineare",
  "ListTitle": "Elenco",
  "LinkTitle": "Collegamento ipertestuale",
  "ImageTitle": "Immagine",
  "MoreTitle": "Più",
  "FormattingPaneTitle": "Formattazione del testo",
  "CloseButton": "Chiudi",
  "InsertLinkTitle": "Inserisci collegamento",
  "InsertImageTitle": "Inserire un'immagine",
  "AddressFieldLabel": "Indirizzo",
  "TextToDisplayLabel": "Testo da visualizzare",
  "SaveButtonLabel": "Salvare",
  "CancelButtonLabel": "Annulla",
  "RemoveLinkLabel": "Rimuovi collegamento",
  "ParagraphSectionTitle": "Paragrafo",
  "HyperlinkSectionTitle": "Collegamento ipertestuale",
  "UndoTitle": "Annulla (CTRL-Z)",
  "RedoTitle": "Ripeti (CTRL-Y)",
  "ClearFormattingTitle": "Cancella tutta la formattazione",
  "FontStyleTitle": "Stile carattere",
  "FontSizeTitle": "Dimensione del carattere",
  "StrikethroughTitle": "Barrato",
  "SuperscriptTitle": "Apice",
  "SubscriptTitle": "Indice",
  "FontColorLabel": "Colore carattere",
  "AutomaticFontColor": "Automatico",
  "HighlightColorLabel": "Colore evidenziazione",
  "NoColorHighlightColor": "Nessun colore",
  "IncreaseIndentTitle": "Aumenta rientro",
  "DecreaseIndentTitle": "Riduci rientro",
  "ThemeColorsGroupName": "Colori tema",
  "HighlightColorsGroupName": "Evidenziare i colori",
  "StandardColorsGroupName": "Colori standard",
  "CustomColorsGroupName": "Colori personalizzati",
  "ThemeColorDarker": "Tema più scuro",
  "ThemeColorDark": "Tema scuro",
  "ThemeColorDarkAlt": "Tema scuro alternativo",
  "ThemeColorPrimary": "Tema primario",
  "ThemeColorSecondary": "Tema secondario",
  "ThemeColorTertiary": "Terziario neutro",
  "ThemeColorNeutralSecondary": "Secondario neutro",
  "ThemeColorNeutralPrimaryAlt": "Alternativa primaria neutra",
  "ThemeColorNeutralPrimary": "Primario neutro",
  "ThemeColorNeutralDark": "Scuro neutro",
  "HighlightColorYellow": "Giallo",
  "HighlightColorGreen": "Verde",
  "HighlightColorAqua": "Acqua",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Blu",
  "HighlightColorRed": "Rosso",
  "HighlightColorDarkblue": "Blu scuro",
  "HighlightColorTeal": "Color foglia di tè",
  "HighlightColorDarkgreen": "Verde scuro",
  "HighlightColorPurple": "Viola",
  "HighlightColorMaroon": "Marrone",
  "HighlightColorGold": "Oro",
  "HighlightColorDarkgrey": "Grigio scuro",
  "HighlightColorGrey": "Grigio",
  "HighlightColorBlack": "Nero",
  "StandardColorDarkred": "Rosso scuro",
  "StandardColorRed": "Rosso",
  "StandardColorOrange": "Arancione",
  "StandardColorYellow": "Giallo",
  "StandardColorLightgreen": "Verde chiaro",
  "StandardColorGreen": "Verde",
  "StandardColorLightblue": "Azzurro",
  "StandardColorBlue": "Blu",
  "StandardColorDarkblue": "Blu scuro",
  "StandardColorPurple": "Viola",
  "DatePickerMonthLongJanuary": "Gennaio",
  "DatePickerMonthShortJanuary": "Gen",
  "DatePickerMonthLongFebruary": "Febbraio",
  "DatePickerMonthShortFebruary": "Feb",
  "DatePickerMonthLongMarch": "Marzo",
  "DatePickerMonthShortMarch": "Mar",
  "DatePickerMonthLongApril": "Aprile",
  "DatePickerMonthShortApril": "Apr",
  "DatePickerMonthLongMay": "Maggio",
  "DatePickerMonthShortMay": "Mag",
  "DatePickerMonthLongJune": "Giugno",
  "DatePickerMonthShortJune": "Giu",
  "DatePickerMonthLongJuly": "Luglio",
  "DatePickerMonthShortJuly": "Lug",
  "DatePickerMonthLongAugust": "Agosto",
  "DatePickerMonthShortAugust": "Ago",
  "DatePickerMonthLongSeptember": "Settembre",
  "DatePickerMonthShortSeptember": "Set",
  "DatePickerMonthLongOctober": "Ottobre",
  "DatePickerMonthShortOctober": "Ott",
  "DatePickerMonthLongNovember": "Novembre",
  "DatePickerMonthShortNovember": "Nov",
  "DatePickerMonthLongDecember": "Dicembre",
  "DatePickerMonthShortDecember": "Dic",
  "DatePickerDayLongSunday": "Domenica",
  "DatePickerDayShortSunday": "Dom",
  "DatePickerDayLongMonday": "Lunedì",
  "DatePickerDayShortMonday": "Lun",
  "DatePickerDayLongTuesday": "Martedì",
  "DatePickerDayShortTuesday": "Mar",
  "DatePickerDayLongWednesday": "Mercoledì",
  "DatePickerDayShortWednesday": "Mer",
  "DatePickerDayLongThursday": "Giovedì",
  "DatePickerDayShortThursday": "Gio",
  "DatePickerDayLongFriday": "Venerdì",
  "DatePickerDayShortFriday": "Ven",
  "DatePickerDayLongSaturday": "Sabato",
  "DatePickerDayShortSaturday": "Sab",
  "DatePickerGoToToday": "Oggi",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Data",
  "DateTimePickerTime": "Tempo",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Valore orario errato",
  "DateTimePickerMinuteValueInvalid": "Valore minuti non corretto",
  "DateTimePickerSecondValueInvalid": "Valore secondi non corretto",
  "DateTimePickerTextErrorMessage": "Immettere una data valida",
  "AddFileButtonLabel": "Aggiungi file",
  "AddImageButtonLabel": "Aggiungi immagine",
  "AriaCellValue": "{0} colonna, {1}",
  "FilePickerCancelButtonLabel": "Annulla",
  "CantValidateValidationMessage": "Non è stato possibile verificare questo collegamento. Controllare il collegamento e riprovare.",
  "ChangeFileLinkLabel": "Cambia file",
  "ChangeImageLinkLabel": "Cambia immagine",
  "ChooseFileLinkLabel": "Scegli file",
  "ChooseImageLinkLabel": "Scegli immagine",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "L'utente è responsabile del rispetto dei diritti altrui, incluso il copyright.",
  "CreativeCommonsMessage": "Questi risultati sono contrassegnati con licenze Creative Commons. Esaminare le licenze per assicurarsi di rispettare.",
  "DateFormat": "GG/MM/AAAA hh:mm A",
  "DocumentLabelTemplate": "{0}, Documento, {1} modificato, a cura di {2}, Privato",
  "DocumentLibraries": "Raccolte documenti",
  "EditedByNamePlate": "a cura di ",
  "EmptyFileSize": "0 byte",
  "FilePickerHeader": "Selezione file",
  "FileSizeField": "Dimensioni file",
  "FolderAltText": "Cartella",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, Cartella, {1} modificato, modificato da {2}, elementi {3}, Privato",
  "FromLinkLinkLabel": "Da un collegamento",
  "ImageAltText": ". Immagine {0}",
  "ImageAriaLabelTemplate": ". Immagine {0}",
  "ImageLayoutPlaceholderText": "Impaginazione",
  "ImageSizePlaceholderText": "Dimensioni dell'immagine",
  "ItemChildCountField": "Conteggio figli elemento",
  "LayoutOptionAll": "Tutti",
  "LayoutOptionSquare": "Piazza",
  "LayoutOptionTall": "Alto",
  "LayoutOptionWide": "Ampia",
  "LearnMoreLink": "Ulteriori informazioni.",
  "LicenseOptionAll": "Tutti",
  "LicenseOptionAny": "Solo Creative Commons",
  "LicensePlaceholderText": "Licenza",
  "LinkFileInstructions": "Incollare un collegamento a un file in OneDrive for Business o SharePoint Online",
  "LinkHeader": "Da un collegamento",
  "LinkImageInstructions": "Incollare un collegamento a un'immagine in OneDrive for Business o SharePoint Online",
  "ListLayoutAriaLabel": "Opzioni di visualizzazione. {0} {1} .",
  "ListLayoutCompact": "Vista compatta",
  "ListLayoutCompactDescription": "Visualizzare elementi e dettagli in un elenco compatto",
  "ListLayoutList": "Visualizzazione elenco",
  "ListLayoutListDescrition": "Visualizzare elementi e dettagli in un elenco",
  "ListLayoutTile": "Visualizzazione affiancata",
  "ListLayoutTileDescription": "Visualizzare gli elementi con le anteprime dei riquadri",
  "ListOptionsAlt": "Opzioni di visualizzazione. {0} selezionato .",
  "ListOptionsTitle": "Aprire il menu delle opzioni di visualizzazione",
  "Loading": "Caricamento...",
  "ModifiedByField": "Modificato da",
  "ModifiedField": "Data di modifica",
  "NameField": "Nome",
  "No": "No",
  "ProvidedValueIsInvalid": "Il valore fornito non è valido",
  "NoExternalLinksValidationMessage": "Supportiamo solo il collegamento ai file nella tua organizzazione.",
  "NoImageValidationMessage": "Questo non è un link a un tipo di file che supportiamo. È possibile collegare solo un'immagine.",
  "NoRecentFiles": "Nessun file recente",
  "NoRecentFilesDescription": "Prova a selezionare un file dal tuo sito o a caricarne uno dal dispositivo.",
  "NoResultsBadEnglish": "Non viene trovato alcun risultato. Provare a modificare le opzioni di filtro",
  "ODModifiedField": "Volta",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, {2} modificato, modificato da {3}, {4} {5}",
  "OneDriveConfirmDialogBody": "Questo elemento proviene dal sito di OneDrive. I file e le cartelle in OneDrive sono privati a meno che non vengano condivisi. Hai condiviso questo file con i membri del tuo sito in modo che possano ccess esso?",
  "OneDriveConfirmDialogTitle": "Sto solo controllando...",
  "OneDriveEmptyFolderAlt": "Svuota cartella",
  "OneDriveEmptyFolderDescription": "Per aggiungere file, passare a OneDrive. È anche possibile aggiungere file a questa cartella usando l'app OneDrive per il computer.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Questa cartella è vuota",
  "OneDriveRootFolderName": "ﬁle",
  "OpenButtonLabel": "Apri",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Immagini e file forniti dall'organizzazione",
  "PoweredByBing": "Alimentato da Bing",
  "RecentDocumentsHeader": "Documenti recenti",
  "RecentImagesHeader": "Immagini recenti",
  "RecentLinkLabel": "Recente",
  "SearchBoxPlaceholder": "Ricerca sul Web",
  "SearchResultAlt": "Risultato dell'immagine per {0}.",
  "SearchResultAriaLabel": "Premere INVIO per aprire la sorgente dell'immagine in una nuova scheda.",
  "Selected": "Selezionato",
  "SharingField": "Condivisione",
  "SharingPrivate": "Privato",
  "SharingShared": "condiviso",
  "SiteLinkLabel": "Sito",
  "SizeOptionAll": "Tutti",
  "SizeOptionExtraLarge": "Extra Large",
  "SizeOptionLarge": "Grande",
  "SizeOptionMedium": "Medio",
  "SizeOptionSmall": "Piccolo",
  "SizeUnit": [
    "Byte",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Zb",
    "Yb"
  ],
  "SorryWebSearch": "Spiacenti, questa funzione non è implementata in questo esempio, perché richiederebbe una chiave API Bing.Softhis, this function isn't implemented in this sample, because it would require a Bing API key.",
  "SortedAscending": "Ordinato dalla A alla Z",
  "SortedDescending": "Ordinato dalla Z alla A",
  "TypeAriaLabel": "Operazioni sulle colonne per Tipo di file, Premere per ordinare in base al tipo di file",
  "UploadFileHeader": "Carica file",
  "UploadImageHeader": "Carica immagine",
  "UploadLinkLabel": "Caricare",
  "WebSearchLinkLabel": "Ricerca sul Web",
  "StockImagesLinkLabel": "Immagini Stock",
  "StockImagesHeader": "Immagini Stock",
  "Yes": "Sì",
  "NewFolderNamePlaceholder": "Immettere il nome della cartella",
  "FolderFilterBoxPlaceholder": "Filtrare le cartelle per nome",
  "FolderExplorerLoading": "Caricamento cartelle in file...",
  "FolderExplorerNoItems": "Questa cartella non dispone di sottocartelle.",
  "NewFolderIncorrectSymbolsError": "Immettere un nome che non includa nessuno di questi caratteri: \" * : < > ? /  |.",
  "SomethingWentWrong": "Qualcosa è andato storto",
  "SelectedLabel": "Selezionato",
  "SelectIcon": "Seleziona icona",
  "TreeViewExpandTitle": "Espandere questo elemento",
  "TreeViewCollapseTitle": "Comprimere questo elemento",
  "CollectionDataEmptyFields": "Non sono stati forniti campi per i dati di raccolta.",
  "CollectionDataEmptyValue": "Nessun dato nella raccolta.",
  "CollectionAddRowButtonLabel": "Aggiungere dati alla raccolta",
  "CollectionDeleteRowButtonLabel": "Eliminare la riga corrente",
  "CollectionSaveAndAddButtonLabel": "Aggiungere e salvare",
  "CollectionDataItemShowErrorsLabel": "Mostra errori di riga",
  "CollectionDataItemFieldRequiredLabel": "Il campo è obbligatorio.",
  "CollectionDataItemMissingFields": "La raccolta dei campi è vuota!",
  "InvalidUrlError": "L'URL fornito non è valido",
  "CollectionDataSearch": "Ricerca",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "caricamento dei team",
  "MyTeamsMessageError": "Qualcosa è andato storto durante il caricamento dei team, provare più tardi o aggiornare il browser",
  "MyTeamsNoTeamsMessage": "Non hai team",
  "MyTeamsTeamChannelPublicMessage": "Canali pubblici",
  "MyTeamsTeamChannelTypeMessage": "Canali privati",
  "TeamChannelPickerFontIconFavoriteText": "Favorito",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Canale privato",
  "TeamChannelPickerSugestionHeaderText": "Canali del team suggeriti",
  "TeamPickerButtonRemoveTitle": "togliere",
  "TeamPickernoResultsFoundText": "Nessuna squadra trovata",
  "TeamPickerSugestionsHeaderText": "Team suggeriti",
  "TeamsChannelPickerButtonRemoveTitle": "togliere",
  "TeamsChannelPickerNoresultsFoundText": "Nessun canale trovato",
  "ViewMore": "Guarda di più",
  "DynamicFormLoading": "Caricamento...",
  "DynamicFormPleaseWait": "Attendere prego...",
  "DynamicFormRequiredErrorMessage": "Non puoi lasciare tutto vuoto.",
  "DynamicFormTermPanelTitle": "Seleziona termine",
  "DynamicFormEnterURLPlaceholder": "Immettere un URL",
  "DynamicFormEnterDescriptionPlaceholder": "Testo alternativo",
  "DynamicFormDialogValidationErrorTitle": "Errori di validazione",
  "DynamicFormDialogValidationErrorMessage": "Sono presenti degli errori di validazione, si prega di correggerli prima di salvare le modifiche.",
  "DynamicFormNumberValueMustBeGreaterThan": "Il valore inserito deve essere maggiore di {0}",
  "DynamicFormNumberValueMustBeBetween": "Il valore inserito deve essere compreso tra {0} e {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Il valore inserito deve essere minore di {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Seleziona file",
  "DynamicFormRequiredFileMessage": "Il file è obbligatorio.",
  "customDisplayName": "Utilizzare questa posizione:",
  "ListItemCommentDIalogDeleteSubText": "Eliminare questo commento?",
  "ListItemCommentsDialogDeleteTitle": "Conferma eliminazione commento",
  "ListItemCommentsLabel": "Commenti",
  "ListItemCommentsNoCommentsLabel": "Non ci sono commenti",
  "OrgAssetsLinkLabel": "Tua organizzazione",
  "MyTeamsMessageDontHaveTeams": "Non hai alcun team",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Inserisci un termine che vuoi taggare",
  "ModernTaxonomyPickerTreeTitleSingle": "Seleziona un tag",
  "ModernTaxonomyPickerTreeTitleMulti": "Seleziona uno o più tag",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Aggiungi tag",
  "ModernTaxonomyPickerApplyButtonText": "Usa",
  "ModernTaxonomyPickerCancelButtonText": "Annulla",
  "ModernTaxonomyPickerLoadMoreText": "Ulteriori informazioni",
  "ModernTaxonomyPickerRemoveButtonText": "Elimina",
  "ModernTaxonomyPickerPanelCloseButtonText": "Chiudi",
  "ModernTaxonomyPickerNoResultsFound": "Nessun risultato trovato",
  "ModernTaxonomyPickerSuggestionInLabel": "Pollici",

  "ModernAudioPlay": "Riproduci",
  "ModernAudioPause": "Pausa",
  "ModernAudioIncVol": "Aumenta Volume",
  "ModernAudioDecVol": "Diminuisci Volume",
  "ModernAudioMute": "Muto",

  "ProgressStepsIndicatorNoSteps": "Nessuno step",

  "UploadFilesButtonLabel": "Aggiungi",
  "UpLoadFilesDeleteButtonLabel": "Rimuovi",
  "UpLoadFilesDragDropLabel": "Trascina e rilascia i file o utilizza il pulsante per aggiungere i file.",
  "UpLoadFilesSelectAllLabel": "Seleziona tutto",
  "UploadFilesUploadButtonLabel": "Carica",
};
});
