declare var define: any;

define([], () => {
  return {
  "SiteBreadcrumbLabel": "ウェブサイトの階層リンク",
  "ListViewGroupEmptyLabel": "空",
  "WebPartTitlePlaceholder": "Web パーツのタイトル",
  "WebPartTitleLabel": "タイトルを追加する",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "数秒で",
    "L_RelativeDateTime_AFewSeconds": "数秒前",
    "L_RelativeDateTime_AboutAMinuteFuture": "約1分で",
    "L_RelativeDateTime_AboutAMinute": "約1分前",
    "L_RelativeDateTime_XMinutesFuture": "{0}分||{0}分",
    "L_RelativeDateTime_XMinutes": "{0}分前||{0}分前",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
    "L_RelativeDateTime_XMinutesIntervals": "1||2-",
    "L_RelativeDateTime_AboutAnHourFuture": "約1時間で",
    "L_RelativeDateTime_AboutAnHour": "約1時間前",
    "L_RelativeDateTime_Tomorrow": "明日",
    "L_RelativeDateTime_Yesterday": "昨日",
    "L_RelativeDateTime_TomorrowAndTime": "明日の{0}",
    "L_RelativeDateTime_YesterdayAndTime": "昨日{0}で",
    "L_RelativeDateTime_XHoursFuture": "{0}時間内||{0}時間内",
    "L_RelativeDateTime_XHours": "{0}時間前||{0}時間前",
    "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
    "L_RelativeDateTime_XHoursIntervals": "1||2-",
    "L_RelativeDateTime_DayAndTime": "{1}の{0}",
    "L_RelativeDateTime_XDaysFuture": "{0}日から||{0}日後",
    "L_RelativeDateTime_XDays": "{0}日前||{0}日前",
    "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
    "L_RelativeDateTime_XDaysIntervals": "1||2-",
    "L_RelativeDateTime_Today": "本日は"
  },
  "SendEmailTo": "{0}に電子メールを送信する",
  "StartChatWith": "{0}とチャットを開始する",
  "Contact": "連絡先",
  "UpdateProfile": "プロフィールを更新する",
  "TaxonomyPickerNoTerms": "用語セットに用語が含まれていません",
  "TaxonomyPickerExpandTitle": "この用語セットを展開する",
  "TaxonomyPickerMenuTermSet": "用語セットのメニュー",
  "TaxonomyPickerInLabel": "インチ",
  "TaxonomyPickerTermSetLabel": "用語セット",
  "peoplePickerComponentTooltipMessage": "ユーザー選択ウィンドウ",
  "peoplePickerComponentErrorMessage": "必須フィールド",
  "peoplePickerSuggestionsHeaderText": "提案された人々",
  "peoplePickerLoadingText": "読み込み",
  "PeoplePickerSearchText": "ユーザーのフェッチ",
  "PeoplePickerGroupNotFound": "グループが見つかりませんでした。",
  "genericNoResultsFoundText": "結果が見つかりません",
  "ListItemPickerSelectValue": "値の選択",
  "ListItemAttachmentsActionDeleteIconTitle": "削除",
  "ListItemAttachmentsactionDeleteTitle": "削除",
  "ListItemAttachmentsfileDeletedMsg": "ファイル{0}削除されました",
  "ListItemAttachmentsfileDeleteError": "ファイルの削除中にエラーが発生しました: {0}、理由{1}",
  "ListItemAttachmentserrorLoadAttachments": "リスト アイテムの添付ファイルの読み込み中にエラー {0}が発生しました。",
  "ListItemAttachmentsconfirmDelete": "添付ファイルをサイトのごみ箱に{0}に送信しますか?",
  "ListItemAttachmentsdialogTitle": "リスト アイテムの添付ファイル",
  "ListItemAttachmentsdialogOKbuttonLabel": "わかりました",
  "ListItemAttachmentsdialogCancelButtonLabel": "キャンセル",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "削除",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "添付ファイルの追加",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "添付ファイルの追加",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "ファイル{0}添付されていない、理由:{1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "添付ファイルの追加",
  "ListItemAttachmentsloadingMessage": "ファイルをアップロードしています...",
  "ListItemAttachmentslPlaceHolderIconText": "リスト アイテムの添付ファイル",
  "ListItemAttachmentslPlaceHolderDescription": "添付ファイルを追加してください",
  "ListItemAttachmentslPlaceHolderButtonLabel": "追加",
  "mapsErrorMessage": "マップの読み込み中にエラーが発生しました",
  "mapsLoadingText": "読み込み",
  "mapsSearchButtonText": "検索",
  "mapsTitlePrefix": "地図",
  "ListViewFilterLabel": "リストをフィルター処理する",
  "HeaderNormalText": "標準テキスト",
  "HeaderH2": "見出し 1",
  "HeaderH3": "見出し 2",
  "HeaderH4": "見出し 3",
  "HeaderBlockQuote": "引用のプル",
  "AlignLeft": "左揃え",
  "AlignCenter": "センター",
  "AlignRight": "右揃え",
  "AlignJustify": "正当 化",
  "ListBullet": "箇条書き",
  "ListNumbered": "番号付きリスト",
  "StyleTitle": "スタイル",
  "BoldTitle": "太字 (Ctrl+B)",
  "ItalicTitle": "斜体 (Ctrl+I)",
  "UnderlineTitle": "下線 (Ctrl+U)",
  "AlignTitle": "配置",
  "ListTitle": "リスト",
  "LinkTitle": "ハイパーリンク",
  "MoreTitle": "もっとその",
  "FormattingPaneTitle": "テキストの書式設定",
  "CloseButton": "閉じる",
  "InsertLinkTitle": "リンクの挿入",
  "AddressFieldLabel": "アドレス",
  "TextToDisplayLabel": "表示するテキスト",
  "SaveButtonLabel": "保存",
  "CancelButtonLabel": "キャンセル",
  "RemoveLinkLabel": "リンクの削除",
  "ParagraphSectionTitle": "段落",
  "HyperlinkSectionTitle": "ハイパーリンク",
  "UndoTitle": "元に戻す (Ctrl+Z)",
  "RedoTitle": "やり直し (Ctrl+Y)",
  "ClearFormattingTitle": "すべての書式をクリアする",
  "FontStyleTitle": "フォント スタイル",
  "FontSizeTitle": "フォント サイズ",
  "StrikethroughTitle": "取り消し 線",
  "SuperscriptTitle": "上付き 文字",
  "SubscriptTitle": "添 字",
  "FontColorLabel": "フォントの色",
  "AutomaticFontColor": "自動",
  "HighlightColorLabel": "強調表示色",
  "NoColorHighlightColor": "色なし",
  "IncreaseIndentTitle": "インデントを増やす",
  "DecreaseIndentTitle": "インデントを減らす",
  "ThemeColorsGroupName": "テーマの色",
  "HighlightColorsGroupName": "ハイライト色",
  "StandardColorsGroupName": "標準色",
  "CustomColorsGroupName": "ユーザー設定の色",
  "ThemeColorDarker": "テーマが暗い",
  "ThemeColorDark": "テーマダーク",
  "ThemeColorDarkAlt": "テーマダークオルタナティブ",
  "ThemeColorPrimary": "テーマプライマリ",
  "ThemeColorSecondary": "テーマセカンダリ",
  "ThemeColorTertiary": "中立三次",
  "ThemeColorNeutralSecondary": "ニュートラルセカンダリ",
  "ThemeColorNeutralPrimaryAlt": "ニュートラルプライマリ代替",
  "ThemeColorNeutralPrimary": "ニュートラルプライマリ",
  "ThemeColorNeutralDark": "ニュートラルダーク",
  "HighlightColorYellow": "黄色",
  "HighlightColorGreen": "緑",
  "HighlightColorAqua": "アクア",
  "HighlightColorMagenta": "マゼンタ",
  "HighlightColorBlue": "青",
  "HighlightColorRed": "赤",
  "HighlightColorDarkblue": "ダークブルー",
  "HighlightColorTeal": "ティール",
  "HighlightColorDarkgreen": "濃い緑",
  "HighlightColorPurple": "紫",
  "HighlightColorMaroon": "マルーン",
  "HighlightColorGold": "金",
  "HighlightColorDarkgrey": "ダークグレー",
  "HighlightColorGrey": "灰色",
  "HighlightColorBlack": "黒",
  "StandardColorDarkred": "濃い赤",
  "StandardColorRed": "赤",
  "StandardColorOrange": "オレンジ",
  "StandardColorYellow": "黄色",
  "StandardColorLightgreen": "ライトグリーン",
  "StandardColorGreen": "緑",
  "StandardColorLightblue": "ライトブルー",
  "StandardColorBlue": "青",
  "StandardColorDarkblue": "ダークブルー",
  "StandardColorPurple": "紫",
  "DatePickerMonthLongJanuary": "月",
  "DatePickerMonthShortJanuary": "月",
  "DatePickerMonthLongFebruary": "2月",
  "DatePickerMonthShortFebruary": "Feb",
  "DatePickerMonthLongMarch": "3月",
  "DatePickerMonthShortMarch": "03 月",
  "DatePickerMonthLongApril": "4月",
  "DatePickerMonthShortApril": "Apr",
  "DatePickerMonthLongMay": "5月",
  "DatePickerMonthShortMay": "5月",
  "DatePickerMonthLongJune": "6 月",
  "DatePickerMonthShortJune": "6 月",
  "DatePickerMonthLongJuly": "7 月",
  "DatePickerMonthShortJuly": "7 月",
  "DatePickerMonthLongAugust": "8 月",
  "DatePickerMonthShortAugust": "8 月",
  "DatePickerMonthLongSeptember": "9 月",
  "DatePickerMonthShortSeptember": "セブン",
  "DatePickerMonthLongOctober": "10 月",
  "DatePickerMonthShortOctober": "10 月",
  "DatePickerMonthLongNovember": "11 月",
  "DatePickerMonthShortNovember": "11 月",
  "DatePickerMonthLongDecember": "12 月",
  "DatePickerMonthShortDecember": "12 月",
  "DatePickerDayLongSunday": "日曜日",
  "DatePickerDayShortSunday": "日",
  "DatePickerDayLongMonday": "月曜日",
  "DatePickerDayShortMonday": "私の",
  "DatePickerDayLongTuesday": "火曜日",
  "DatePickerDayShortTuesday": "火",
  "DatePickerDayLongWednesday": "水曜日",
  "DatePickerDayShortWednesday": "水",
  "DatePickerDayLongThursday": "木曜日",
  "DatePickerDayShortThursday": "木",
  "DatePickerDayLongFriday": "金曜日",
  "DatePickerDayShortFriday": "金",
  "DatePickerDayLongSaturday": "土曜日",
  "DatePickerDayShortSaturday": "土",
  "DatePickerGoToToday": "本日は",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "日付",
  "DateTimePickerTime": "時間",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "時間の値が正しくありません",
  "AddFileButtonLabel": "ファイルの追加",
  "AddImageButtonLabel": "画像の追加",
  "AriaCellValue": "{0}列, {1}",
  "FilePickerCancelButtonLabel": "キャンセル",
  "CantValidateValidationMessage": "このリンクを確認できませんでした。リンクを確認して、やり直してください。",
  "ChangeFileLinkLabel": "ファイルの変更",
  "ChangeImageLinkLabel": "画像の変更",
  "ChooseFileLinkLabel": "ファイルの選択",
  "ChooseImageLinkLabel": "画像の選択",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "おおとりは、著作権を含む他者の権利を尊重する責任を負います。",
  "CreativeCommonsMessage": "これらの結果には、クリエイティブ・コモンズ・ライセンスがタグ付けされます。ライセンスを確認して、準拠していることを確認します。",
  "DateFormat": "MM/DD/YYYY hh:mm A",
  "DocumentLabelTemplate": "{0}、ドキュメント、変更{1}、{2}、プライベートで編集",
  "DocumentLibraries": "ドキュメント ライブラリ",
  "EditedByNamePlate": "編集者",
  "EmptyFileSize": "0 バイト",
  "FilePickerHeader": "ファイル ピッカー",
  "FileSizeField": "ファイル サイズ",
  "FolderAltText": "フォルダー",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}、 フォルダ、変更{1}、{2}、{3} アイテム、プライベートで編集",
  "FromLinkLinkLabel": "リンクから",
  "ImageAltText": ".{0} イメージ",
  "ImageAriaLabelTemplate": ".{0} イメージ",
  "ImageLayoutPlaceholderText": "レイアウト",
  "ImageSizePlaceholderText": "画像サイズ",
  "ItemChildCountField": "アイテムの子数",
  "LayoutOptionAll": "すべての",
  "LayoutOptionSquare": "広場",
  "LayoutOptionTall": "背",
  "LayoutOptionWide": "広い",
  "LearnMoreLink": "詳細情報。",
  "LicenseOptionAll": "すべての",
  "LicenseOptionAny": "クリエイティブ・コモンズのみ",
  "LicensePlaceholderText": "ライセンス",
  "LinkFileInstructions": "ビジネスまたは SharePoint オンラインの OneDrive 内のファイルへのリンクを貼り付ける",
  "LinkHeader": "リンクから",
  "LinkImageInstructions": "ビジネスまたは SharePoint オンラインの OneDrive にイメージへのリンクを貼り付ける",
  "ListLayoutAriaLabel": "オプションを表示します。{0} {1} .",
  "ListLayoutCompact": "コンパクトビュー",
  "ListLayoutCompactDescription": "コンパクトなリストでアイテムと詳細を表示する",
  "ListLayoutList": "リスト ビュー",
  "ListLayoutListDescrition": "リスト内のアイテムと詳細を表示する",
  "ListLayoutTile": "タイル ビュー",
  "ListLayoutTileDescription": "タイル プレビューを使用してアイテムを表示する",
  "ListOptionsAlt": "オプションを表示します。{0}選択されます。",
  "ListOptionsTitle": "表示オプション メニューを開く",
  "Loading": "読み込み。。。",
  "ModifiedByField": "更新者",
  "ModifiedField": "更新日",
  "NameField": "名前",
  "No": "いいえ",
  "ProvidedValueIsInvalid": "指定された値が無効です",
  "NoExternalLinksValidationMessage": "お客様の組織内のファイルへのリンクのみがサポートされています。",
  "NoImageValidationMessage": "これは、サポートするファイルの種類へのリンクではありません。リンクできるのは画像だけです。",
  "NoRecentFiles": "最近使用したファイルはありません",
  "NoRecentFilesDescription": "サイトからファイルを選択するか、デバイスからファイルをアップロードしてみてください。",
  "NoResultsBadEnglish": "結果が見つかりません。フィルタ オプションを変更する",
  "ODModifiedField": "変更",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}、{1}、変更{2}、{3}、{4}、{5}編集",
  "OneDriveConfirmDialogBody": "このアイテムは OneDrive サイトからのもので、次のサイトから作成されます。OneDrive 内のファイルとフォルダーは、共有しない限りプライベートです。このファイルをサイト メンバと共有して、ユーザーが参照できるようにしますか?",
  "OneDriveConfirmDialogTitle": "ちょっと聞いてみただけです。。。",
  "OneDriveEmptyFolderAlt": "空のフォルダ",
  "OneDriveEmptyFolderDescription": "ファイルを追加するには、OneDrive に移動します。コンピューターの OneDrive アプリを使用して、このフォルダーにファイルを追加することもできます。",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "このフォルダは空です",
  "OneDriveRootFolderName": "ファイル",
  "OpenButtonLabel": "開く",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "組織が提供する画像とファイル",
  "PoweredByBing": "Bingを搭載",
  "RecentDocumentsHeader": "最近使用したドキュメント",
  "RecentImagesHeader": "最近の画像",
  "RecentLinkLabel": "最近",
  "SearchBoxPlaceholder": "ウェブ検索",
  "SearchResultAlt": "{0}のイメージ結果。",
  "SearchResultAriaLabel": "Enter キーを押して、イメージ ソースを新しいタブで開きます。",
  "Selected": "選択",
  "SharingField": "共有",
  "SharingPrivate": "プライベート",
  "SharingShared": "共有",
  "SiteLinkLabel": "サイト",
  "SizeOptionAll": "すべての",
  "SizeOptionExtraLarge": "特大",
  "SizeOptionLarge": "大きな",
  "SizeOptionMedium": "媒体",
  "SizeOptionSmall": "小さな",
  "SizeUnit": [
    "バイト",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "例えば",
    "Yb"
  ],
  "SorryWebSearch": "この関数は、Bing API キーを必要とするため、このサンプルでは実装されていません。",
  "SortedAscending": "並べ替え A ~ Z",
  "SortedDescending": "並べ替えられた Z から A",
  "TypeAriaLabel": "ファイルの種類の列操作、ファイルの種類で並べ替えるを押す",
  "UploadFileHeader": "ファイルのアップロード",
  "UploadImageHeader": "画像のアップロード",
  "UploadLinkLabel": "アップロード",
  "WebSearchLinkLabel": "ウェブ検索",
  "Yes": "はい",
  "SelectedLabel": "選択された",
  "SelectIcon": "アイコンの選択"
};
});