declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Svetainės navigacijos grandinė',

    'ListViewGroupEmptyLabel': 'Nenurodyta',

    'WebPartTitlePlaceholder': 'Puslapio dalies antraštė',
    'WebPartTitleLabel': 'Pridėti antraštę',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "po kelių sekundžių",
      "L_RelativeDateTime_AFewSeconds": "prieš kelias sekundes",
      "L_RelativeDateTime_AboutAMinuteFuture": "maždaug po minutės",
      "L_RelativeDateTime_AboutAMinute": "beveik prieš minutę",
      "L_RelativeDateTime_XMinutesFuture": "po {0} min.",
      "L_RelativeDateTime_XMinutes": "prieš {0} min.",
      "L_RelativeDateTime_XMinutesFutureIntervals": "0-",
      "L_RelativeDateTime_XMinutesIntervals": "0-",
      "L_RelativeDateTime_AboutAnHourFuture": "maždaug po valandos",
      "L_RelativeDateTime_AboutAnHour": "beveik prieš valandą",
      "L_RelativeDateTime_Tomorrow": "rytoj",
      "L_RelativeDateTime_Yesterday": "vakar",
      "L_RelativeDateTime_TomorrowAndTime": "rytoj, {0}",
      "L_RelativeDateTime_YesterdayAndTime": "vakar, {0}",
      "L_RelativeDateTime_XHoursFuture": "po {0} val.",
      "L_RelativeDateTime_XHours": "prieš {0} val.",
      "L_RelativeDateTime_XHoursFutureIntervals": "0-",
      "L_RelativeDateTime_XHoursIntervals": "0-",
      "L_RelativeDateTime_DayAndTime": "{0}, {1}",
      "L_RelativeDateTime_XDaysFuture": "po {0} d.",
      "L_RelativeDateTime_XDays": "prieš {0} d.",
      "L_RelativeDateTime_XDaysFutureIntervals": "0-",
      "L_RelativeDateTime_XDaysIntervals": "0-",
      "L_RelativeDateTime_Today": "šiandien"
    },
    "SendEmailTo": "Siųsti el. laišką {0}",
    "StartChatWith": "Pradėti pokalbį su {0}",
    "Contact": "Kontaktas",
    "UpdateProfile": "Atnaujinti profilį",

    "TaxonomyPickerNoTerms": "Terminų rinkinys tuščias",
    "TaxonomyPickerExpandTitle": "Išskleisti terminų rinkinį",
    "TaxonomyPickerMenuTermSet": "Terminų rinkinio meniu",
    "TaxonomyPickerInLabel": "",
    "TaxonomyPickerTermSetLabel": "Terminų rinkinys",

    peoplePickerComponentTooltipMessage: "Pasirinkite naudotojus",
    peoplePickerComponentErrorMessage: "Privalomas laukas",
    peoplePickerSuggestionsHeaderText: 'Pasiūlymai',
    peoplePickerLoadingText: 'Įkeliama',
    PeoplePickerSearchText: 'Ieškoma naudotojų',
    PeoplePickerGroupNotFound: "Grupės nepavyko rasti.",

    genericNoResultsFoundText: 'Rezultatų nėra',

    ListItemPickerSelectValue: 'Pasirinkite reikšmę',
    ListItemAttachmentsActionDeleteIconTitle: 'Naikinti',
    ListItemAttachmentsactionDeleteTitle: 'Naikinti',
    ListItemAttachmentsfileDeletedMsg: 'Failas „{0}“ panaikintas',
    ListItemAttachmentsfileDeleteError: 'Klaida naikinant failą „{0}“: {1}',
    ListItemAttachmentserrorLoadAttachments: 'Nepavyko įkelti elemento priedų infomacijos: {0}',
    ListItemAttachmentsconfirmDelete: 'Ar tikrai norite priedą „{0}“ siųsti į svetainės šiukšlinę?',
    ListItemAttachmentsdialogTitle: 'Elemento priedai',
    ListItemAttachmentsdialogOKbuttonLabel: 'Gerai',
    ListItemAttachmentsdialogCancelButtonLabel: 'Atšaukti',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Naikinti',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Įkelti priedą',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Įkelti priedą',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Failo „{0}“ įkelti nepavyko: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Įkelti priedą',
    ListItemAttachmentsloadingMessage: 'Failas siunčiamas...',
    ListItemAttachmentslPlaceHolderIconText: 'Elemento priedai',
    ListItemAttachmentslPlaceHolderDescription: 'Please Add Attachment',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Pridėti',

    mapsErrorMessage: 'Įkeliant žemėlapį įvyko klaida',
    mapsLoadingText: 'Įkeliama',
    mapsSearchButtonText: 'Paieška',
    mapsTitlePrefix: 'Žemėlapis',

    ListViewFilterLabel: "Filtruoti",

    HeaderNormalText: "Normal text",
    HeaderH2: "Heading 1",
    HeaderH3: "Heading 2",
    HeaderH4: "Heading 3",
    HeaderBlockQuote: "Pull quote",
    AlignLeft: "Align left",
    AlignCenter: "Center",
    AlignRight: "Align right",
    AlignJustify: "Justify",
    ListBullet: "Bulleted list",
    ListNumbered: "Numbered list",
    StyleTitle: "Style",
    BoldTitle: "Bold (Ctrl+B)",
    ItalicTitle: "Italic (Ctrl+I)",
    UnderlineTitle: "Underline (Ctrl+U)",
    AlignTitle: "Align",
    ListTitle: "List",
    LinkTitle: "Hyperlink",
    MoreTitle: "More",
    FormattingPaneTitle: "Text formatting",
    CloseButton: "Close",
    InsertLinkTitle: "Insert link",
    AddressFieldLabel: "Address",
    TextToDisplayLabel: "Text to display",
    SaveButtonLabel: "Save",
    CancelButtonLabel: "Cancel",
    RemoveLinkLabel: "Remove link",
    ParagraphSectionTitle: "Paragraph",
    HyperlinkSectionTitle: "Hyperlink",
    UndoTitle: "Undo (Ctrl+Z)",
    RedoTitle: "Redo (Ctrl+Y)",
    ClearFormattingTitle: "Clear all formatting",
    FontStyleTitle: "Font style",
    FontSizeTitle: "Font size",
    StrikethroughTitle: "Strikethrough",
    SuperscriptTitle: "Superscript",
    SubscriptTitle: "Subscript",
    FontColorLabel: "Font Color",
    AutomaticFontColor: "Automatic",
    HighlightColorLabel: "Highlight color",
    NoColorHighlightColor: "No color",
    IncreaseIndentTitle: "Increase indent",
    DecreaseIndentTitle: "Decrease indent",
    ThemeColorsGroupName: "Theme colors",
    HighlightColorsGroupName: "Highlight colors",
    StandardColorsGroupName: "Standard colors",
    ThemeColorDarker: "Theme darker",
    ThemeColorDark: "Theme dark",
    ThemeColorDarkAlt: "Theme dark alternate",
    ThemeColorPrimary: "Theme primary",
    ThemeColorSecondary: "Theme secondary",
    ThemeColorTertiary: "Neutral tertiary",
    ThemeColorNeutralSecondary: "Neutral secondary",
    ThemeColorNeutralPrimaryAlt: "Neutral primary alternate",
    ThemeColorNeutralPrimary: "Neutral primary",
    ThemeColorNeutralDark: "Neutral dark",
    HighlightColorYellow: "Yellow",
    HighlightColorGreen: "Green",
    HighlightColorAqua: "Aqua",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Blue",
    HighlightColorRed: "Red",
    HighlightColorDarkblue: "Dark blue",
    HighlightColorTeal: "Teal",
    HighlightColorDarkgreen: "Dark green",
    HighlightColorPurple: "Purple",
    HighlightColorMaroon: "Maroon",
    HighlightColorGold: "Gold",
    HighlightColorDarkgrey: "Dark grey",
    HighlightColorGrey: "Grey",
    HighlightColorBlack: "Black",
    StandardColorDarkred: "Dark red",
    StandardColorRed: "Red",
    StandardColorOrange: "Orange",
    StandardColorYellow: "Yellow",
    StandardColorLightgreen: "Light green",
    StandardColorGreen: "Green",
    StandardColorLightblue: "Light blue",
    StandardColorBlue: "Blue",
    StandardColorDarkblue: "Dark blue",
    StandardColorPurple: "Purple",

    DatePickerMonthLongJanuary: "sausis",
    DatePickerMonthShortJanuary: "saus.",
    DatePickerMonthLongFebruary: "vasaris",
    DatePickerMonthShortFebruary: "vas.",
    DatePickerMonthLongMarch: "kovas",
    DatePickerMonthShortMarch: "kov.",
    DatePickerMonthLongApril: "balandis",
    DatePickerMonthShortApril: "bal.",
    DatePickerMonthLongMay: "gegužė",
    DatePickerMonthShortMay: "geg.",
    DatePickerMonthLongJune: "birželis",
    DatePickerMonthShortJune: "birž.",
    DatePickerMonthLongJuly: "liepa",
    DatePickerMonthShortJuly: "liep.",
    DatePickerMonthLongAugust: "rugpjūtis",
    DatePickerMonthShortAugust: "rugp.",
    DatePickerMonthLongSeptember: "rugsėjis",
    DatePickerMonthShortSeptember: "rugs.",
    DatePickerMonthLongOctober: "spalis",
    DatePickerMonthShortOctober: "spal.",
    DatePickerMonthLongNovember: "lapkritis",
    DatePickerMonthShortNovember: "lapkr.",
    DatePickerMonthLongDecember: "gruodis",
    DatePickerMonthShortDecember: "gruod.",
    DatePickerDayLongSunday: "sekmadienis",
    DatePickerDayShortSunday: "sk",
    DatePickerDayLongMonday: "pirmadienis",
    DatePickerDayShortMonday: "pr",
    DatePickerDayLongTuesday: "antradienis",
    DatePickerDayShortTuesday: "an",
    DatePickerDayLongWednesday: "trečiadienis",
    DatePickerDayShortWednesday: "tr",
    DatePickerDayLongThursday: "ketvirtadienis",
    DatePickerDayShortThursday: "kt",
    DatePickerDayLongFriday: "penktadienis",
    DatePickerDayShortFriday: "pn",
    DatePickerDayLongSaturday: "šeštadienis",
    DatePickerDayShortSaturday: "št",
    DatePickerGoToToday: "šiandien",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Data",
    DateTimePickerTime: "Laikas",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Incorrect hour value"
  };
});
