declare var define: any;

define([], () => {
  return {
    PeoplePickerGroupNotFound: "Grupės nepavyko rasti.",
    ListViewFilterLabel: "Filtruoti",

    PeoplePickerSearchText: "Ieškoma naudotojų",
    peoplePickerComponentTooltipMessage: "Pasirinkite naudotojus",
    peoplePickerComponentErrorMessage: "Privalomas laukas",
    peoplePickerSuggestionsHeaderText: "Pasiūlymai",
    genericNoResultsFoundText: "Rezultatų nėra",
    peoplePickerLoadingText: "Įkeliama",

    SiteBreadcrumbLabel: "Svetainės navigacijos grandinė",
    ListViewGroupEmptyLabel: "Nenurodyta",
    WebPartTitlePlaceholder: "Puslapio dalies antraštė",
    WebPartTitleLabel: "Pridėti antraštę",
    // DateTime: IDateTimeStrings;
    SendEmailTo: "Siųsti el. laišką {0}",
    StartChatWith: "Pradėti pokalbį su {0}",
    Contact: "Kontaktas",
    UpdateProfile: "Atnaujinti profilį",

    // Taxonomy picker
    TaxonomyPickerNoTerms: "Terminų rinkinys tuščias",
    TaxonomyPickerExpandTitle: "Išskleisti terminų rinkinį",
    TaxonomyPickerMenuTermSet: "Terminų rinkinio meniu",
    TaxonomyPickerInLabel: "",
    TaxonomyPickerTermSetLabel: "Terminų rinkinys",

    ListItemPickerSelectValue: "Pasirinkite reikšmę",

    ListItemAttachmentsActionDeleteIconTitle: "Naikinti",
    ListItemAttachmentsactionDeleteTitle: "Naikinti",
    ListItemAttachmentsfileDeletedMsg: "Failas „{0}“ panaikintas",
    ListItemAttachmentsfileDeleteError: "Klaida naikinant failą „{0}“: {1}",
    ListItemAttachmentserrorLoadAttachments: "Nepavyko įkelti elemento priedų infomacijos: {0}",
    ListItemAttachmentsconfirmDelete: "Ar tikrai norite priedą „{0}“ siųsti į svetainės šiukšlinę?",
    ListItemAttachmentsdialogTitle: "Elemento priedai",
    ListItemAttachmentsdialogOKbuttonLabel: "Gerai",
    ListItemAttachmentsdialogCancelButtonLabel: "Atšaukti",
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: "Naikinti",
    ListItemAttachmentsuploadAttachmentDialogTitle: "Įkelti priedą",
    ListItemAttachmentsuploadAttachmentButtonLabel: "Įkelti priedą",
    ListItemAttachmentsuploadAttachmentErrorMsg: "Failo „{0}“ įkelti nepavyko: {1}",
    ListItemAttachmentsCommandBarAddAttachmentLabel: "Įkelti priedą",
    ListItemAttachmentsloadingMessage: "Failas siunčiamas...",
    ListItemAttachmentslPlaceHolderIconText: "Elemento priedai",
    ListItemAttachmentslPlaceHolderDescription: "Įkelkite elemento priedų",
    ListItemAttachmentslPlaceHolderButtonLabel: "Pridėti",

    //Maps
    mapsErrorMessage: "Įkeliant žemėlapį įvyko klaida",
    mapsLoadingText: "Įkeliama",
    mapsSearchButtonText: "Paieška",
    mapsTitlePrefix: "Žemėlapis",

    // RichText
    HeaderNormalText: "Paprastas tekstas",
    HeaderH2: "1 antraštė",
    HeaderH3: "2 antraštė",
    HeaderH4: "3 antraštė",
    HeaderBlockQuote: "Dėmesį atkreipianti citata",
    AlignLeft: "Lygiuoti kairėje",
    AlignCenter: "Centre",
    AlignRight: "Lygiuoti dešinėje",
    AlignJustify: "Abipusė lygiuotė",
    ListBullet: "Sąrašas su ženkleliais",
    ListNumbered: "Numeruotas sąrašas",
    StyleTitle: "Stilius",
    BoldTitle: "Paryškintasis (Ctrl+B)",
    ItalicTitle: "Pasvirasis (Ctrl+I)",
    UnderlineTitle: "Pabrauktasis (Ctrl+U)",
    AlignTitle: "Lygiuotė",
    ListTitle: "Sąrašas",
    LinkTitle: "Hipersaitas",
    MoreTitle: "Daugiau",
    FormattingPaneTitle: "Teksto formatavimas",
    CloseButton: "Uždaryti",
    InsertLinkTitle: "Įterpti saitą",
    AddressFieldLabel: "Adresas",
    TextToDisplayLabel: "Rodytinas tekstas",
    SaveButtonLabel: "Įrašyti",
    CancelButtonLabel: "Atšaukti",
    RemoveLinkLabel: "Šalinti saitą",
    ParagraphSectionTitle: "Pastraipa",
    HyperlinkSectionTitle: "Hipersaitas",
    UndoTitle: "Anuliuoti (Ctrl+Z)",
    RedoTitle: "Perdaryti (Ctrl+Y)",
    ClearFormattingTitle: "Valyti visą formatavimą",
    FontStyleTitle: "Šrifto stilius",
    FontSizeTitle: "Šrifto dydis",
    StrikethroughTitle: "Perbraukimas",
    SuperscriptTitle: "Viršutinis indeksas",
    SubscriptTitle: "Apatinis indeksas",
    FontColorLabel: "Šrifto spalva",
    AutomaticFontColor: "Automatinė",
    HighlightColorLabel: "Pažymėjimo spalva",
    NoColorHighlightColor: "Be spalvų",
    IncreaseIndentTitle: "Didinti įtrauką",
    DecreaseIndentTitle: "Mažinti įtrauką",
    ThemeColorsGroupName: "Temos spalvos",
    HighlightColorsGroupName: "Paryškinimo spalvos",
    StandardColorsGroupName: "Standartinės spalvos",
    ThemeColorDarker: "Tamsesnė tema",
    ThemeColorDark: "Tamsi tema",
    ThemeColorDarkAlt: "Alternatyvi tamsi tema",
    ThemeColorPrimary: "Pirminė tema",
    ThemeColorSecondary: "Antrinė tema",
    ThemeColorTertiary: "Tretinė tema",
    ThemeColorNeutralSecondary: "Neutrali antrinė",
    ThemeColorNeutralPrimaryAlt: "Alternatyvi neutrali pirminė",
    ThemeColorNeutralPrimary: "Neutrali pirminė",
    ThemeColorNeutralDark: "Neutrali tamsi",
    HighlightColorYellow: "Geltona",
    HighlightColorGreen: "Žalia",
    HighlightColorAqua: "Melsvai žalsva",
    HighlightColorMagenta: "Purpurinė",
    HighlightColorBlue: "Mėlyna",
    HighlightColorRed: "Raudona",
    HighlightColorDarkblue: "Tamsiai mėlyna",
    HighlightColorTeal: "Žalsvai mėlyna",
    HighlightColorDarkgreen: "Tamsiai žalia",
    HighlightColorPurple: "Violetinė",
    HighlightColorMaroon: "Kaštoninė",
    HighlightColorGold: "Auksas",
    HighlightColorDarkgrey: "Tamsiai pilka",
    HighlightColorGrey: "Pilka",
    HighlightColorBlack: "Juoda",
    StandardColorDarkred: "Tamsiai raudona",
    StandardColorRed: "Raudona",
    StandardColorOrange: "Oranžinė",
    StandardColorYellow: "Geltona",
    StandardColorLightgreen: "Šviesiai žalia",
    StandardColorGreen: "Žalia",
    StandardColorLightblue: "Šviesiai mėlyna",
    StandardColorBlue: "Mėlyna",
    StandardColorDarkblue: "Tamsiai mėlyna",
    StandardColorPurple: "Violetinė",

    // DateTime picker
    DatePickerMonthLongJanuary: "sausis",
    DatePickerMonthShortJanuary: "saus.",
    DatePickerMonthLongFebruary: "vasaris",
    DatePickerMonthShortFebruary: "vas.",
    DatePickerMonthLongMarch: "kovas",
    DatePickerMonthShortMarch: "kov.",
    DatePickerMonthLongApril: "balandis",
    DatePickerMonthShortApril: "bal.",
    DatePickerMonthLongMay: "gegužė",
    DatePickerMonthShortMay: "geg.",
    DatePickerMonthLongJune: "birželis",
    DatePickerMonthShortJune: "birž.",
    DatePickerMonthLongJuly: "liepa",
    DatePickerMonthShortJuly: "liep.",
    DatePickerMonthLongAugust: "rugpjūtis",
    DatePickerMonthShortAugust: "rugp.",
    DatePickerMonthLongSeptember: "rugsėjis",
    DatePickerMonthShortSeptember: "rugs.",
    DatePickerMonthLongOctober: "spalis",
    DatePickerMonthShortOctober: "spal.",
    DatePickerMonthLongNovember: "lapkritis",
    DatePickerMonthShortNovember: "lapkr.",
    DatePickerMonthLongDecember: "gruodis",
    DatePickerMonthShortDecember: "gruod.",
    DatePickerDayLongSunday: "sekmadienis",
    DatePickerDayShortSunday: "sk",
    DatePickerDayLongMonday: "pirmadienis",
    DatePickerDayShortMonday: "pr",
    DatePickerDayLongTuesday: "antradienis",
    DatePickerDayShortTuesday: "an",
    DatePickerDayLongWednesday: "trečiadienis",
    DatePickerDayShortWednesday: "tr",
    DatePickerDayLongThursday: "ketvirtadienis",
    DatePickerDayShortThursday: "kt",
    DatePickerDayLongFriday: "penktadienis",
    DatePickerDayShortFriday: "pn",
    DatePickerDayLongSaturday: "šeštadienis",
    DatePickerDayShortSaturday: "št",
    DatePickerGoToToday: "šiandien",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Data",
    DateTimePickerTime: "Laikas",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Netinkama laiko reikšmė",

    DateTime: {
      L_RelativeDateTime_AFewSecondsFuture: "po kelių sekundžių",
      L_RelativeDateTime_AFewSeconds: "prieš kelias sekundes",
      L_RelativeDateTime_AboutAMinuteFuture: "maždaug po minutės",
      L_RelativeDateTime_AboutAMinute: "beveik prieš minutę",
      L_RelativeDateTime_XMinutesFuture: "po {0} min.",
      L_RelativeDateTime_XMinutes: "prieš {0} min.",
      L_RelativeDateTime_XMinutesFutureIntervals: "0-",
      L_RelativeDateTime_XMinutesIntervals: "0-",
      L_RelativeDateTime_AboutAnHourFuture: "maždaug po valandos",
      L_RelativeDateTime_AboutAnHour: "beveik prieš valandą",
      L_RelativeDateTime_Tomorrow: "rytoj",
      L_RelativeDateTime_Yesterday: "vakar",
      L_RelativeDateTime_TomorrowAndTime: "rytoj, {0}",
      L_RelativeDateTime_YesterdayAndTime: "vakar, {0}",
      L_RelativeDateTime_XHoursFuture: "po {0} val.",
      L_RelativeDateTime_XHours: "prieš {0} val.",
      L_RelativeDateTime_XHoursFutureIntervals: "0-",
      L_RelativeDateTime_XHoursIntervals: "0-",
      L_RelativeDateTime_DayAndTime: "{0}, {1}",
      L_RelativeDateTime_XDaysFuture: "po {0} d.",
      L_RelativeDateTime_XDays: "prieš {0} d.",
      L_RelativeDateTime_XDaysFutureIntervals: "0-",
      L_RelativeDateTime_XDaysIntervals: "0-",
      L_RelativeDateTime_Today: "šiandien"
    },

    AddFileButtonLabel: "Add file",
    AddImageButtonLabel: "Add image",
    AriaCellValue: "{0} column, {1}",
    FilePickerCancelButtonLabel: "Cancel",
    CantValidateValidationMessage: "We couldn't verify this link. Please check the link and try again.",
    ChangeFileLinkLabel: "Change file",
    ChangeImageLinkLabel: "Change image",
    ChooseFileLinkLabel: "Choose file",
    ChooseImageLinkLabel: "Choose image",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    DocumentLibraries: "Document libraries",
    EditedByNamePlate: "edited by ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "File Picker",
    FileSizeField: "File Size",
    FolderAltText: "Folder",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "No",
    ProvidedValueIsInvalid: "Provided value is invalid",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    OneDriveRootFolderName: "Files",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Recent documents",
    RecentImagesHeader: "Recent images",
    RecentLinkLabel: "Recent",
    SearchBoxPlaceholder: "Web search",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    Selected: "selected",
    SharingField: "Sharing",
    SharingPrivate: "Private",
    SharingShared: "Shared",
    SiteLinkLabel: "Site",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Sorry, this function isn't implemented in this sample, because it would require a Bing API key.",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Upload file",
    UploadImageHeader: "Upload image",
    UploadLinkLabel: "Upload",
    WebSearchLinkLabel: "Web search",
    Yes: "Yes"
  };
});
