declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Website broodkruimelpad',

    'ListViewGroupEmptyLabel': 'Leeg',

    'WebPartTitlePlaceholder': 'Webonderdeel titel',
    'WebPartTitleLabel': 'Titel ingeven',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Over een paar seconden",
      "L_RelativeDateTime_AFewSeconds": "Een paar seconden geleden",
      "L_RelativeDateTime_AboutAMinuteFuture": "Over ongeveer een minuut",
      "L_RelativeDateTime_AboutAMinute": "Ongeveer een minuut geleden",
      "L_RelativeDateTime_XMinutesFuture": "In {0} minuut||In {0} minuten",
      "L_RelativeDateTime_XMinutes": "{0} minuut geleden||{0} minuten geleden",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "In ongeveer een uur",
      "L_RelativeDateTime_AboutAnHour": "Ongeveer een uur geleden",
      "L_RelativeDateTime_Tomorrow": "Morgen",
      "L_RelativeDateTime_Yesterday": "Gisteren",
      "L_RelativeDateTime_TomorrowAndTime": "Morgen om {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Gisteren om {0}",
      "L_RelativeDateTime_XHoursFuture": "In {0} uur||In {0} uur",
      "L_RelativeDateTime_XHours": "{0} uur geleden||{0} uur geleden",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} om {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dag vanaf nu||{0} dagen vanaf nu",
      "L_RelativeDateTime_XDays": "{0} dag geleden||{0} dagen geleden",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Vandaag"
    },
    "SendEmailTo": "Stuur een mail naar {0}",
    "StartChatWith": "Start een gesprek met {0}",
    "Contact": "Contacteer",
    "UpdateProfile": "Profiel aanpassen",

    "TaxonomyPickerNoTerms": "Termen set heeft geen termen beschikbaar",
    "TaxonomyPickerExpandTitle": "Vouw de termen set uit",
    "TaxonomyPickerMenuTermSet": "Menu van de termen set",
    "TaxonomyPickerInLabel": "in",
    "TaxonomyPickerTermSetLabel": "Termen set",

    peoplePickerComponentTooltipMessage: "Personen kiezen",
    peoplePickerComponentErrorMessage: "Verplicht veld",
    peoplePickerSuggestionsHeaderText: 'Voorgestelde personen',
    peoplePickerLoadingText: 'Laden',
    PeoplePickerSearchText: 'Personen worden opgehaald',
    PeoplePickerGroupNotFound: "Groep niet gevonden.",

    ListItemPickerSelectValue: 'Selecteer veld',

    ListItemAttachmentsActionDeleteIconTitle: 'Verwijderen',
    ListItemAttachmentsactionDeleteTitle: 'Verwijderen',
    ListItemAttachmentsfileDeletedMsg: 'Bestand {0} verwijderd',
    ListItemAttachmentsfileDeleteError: 'Probleem bij het verwijderen van het bestand: {0}, rede {1}',
    ListItemAttachmentserrorLoadAttachments: 'Probleem bij het laden van de bijlage, rede: {0}',
    ListItemAttachmentsconfirmDelete: 'Ben je zeker dat je het bestand {0} wilt verwijderen?',
    ListItemAttachmentsdialogTitle: 'Bijlage van lijstitem',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Annuleren',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Verwijderen',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Bijlage toevoegen',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Bijlage toevoegen',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Het bestand {0} kon niet toegevoegd worden, rede: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Bijlage toevoegen',
    ListItemAttachmentsloadingMessage: 'Bestand opladen ...',
    ListItemAttachmentslPlaceHolderIconText: 'Bijlage van lijstitem',
    ListItemAttachmentslPlaceHolderDescription: 'Voeg een bijlage toe',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Toevoegen',

    mapsErrorMessage: 'Er is een fout opgetreden bij het laden van de kaart',
    mapsLoadingText: 'Laden',
    mapsSearchButtonText: 'Zoeken',
    mapsTitlePrefix: 'Kaart van',

    genericNoResultsFoundText: 'Geen resultaten gevonden',

    ListViewFilterLabel: "Filter de lijst",

    DatePickerMonthLongJanuary: "Januari",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Februari",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Maart",
    DatePickerMonthShortMarch: "Maa",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Mei",
    DatePickerMonthShortMay: "Mei",
    DatePickerMonthLongJune: "Juni",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "Juli",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "Augustus",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sept",
    DatePickerMonthLongOctober: "Oktober",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Zondag",
    DatePickerDayShortSunday: "Zon",
    DatePickerDayLongMonday: "Maandag",
    DatePickerDayShortMonday: "Maa",
    DatePickerDayLongTuesday: "Dinsdag",
    DatePickerDayShortTuesday: "Din",
    DatePickerDayLongWednesday: "Woensdag",
    DatePickerDayShortWednesday: "Woe",
    DatePickerDayLongThursday: "Donderdag",
    DatePickerDayShortThursday: "Don",
    DatePickerDayLongFriday: "Vrijdag",
    DatePickerDayShortFriday: "Vri",
    DatePickerDayLongSaturday: "Zaterdag",
    DatePickerDayShortSaturday: "Zat",
    DatePickerGoToToday: "Vandaag",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Dag",
    DateTimePickerTime: "Tijd",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Foute uur waarde",

    AddFileButtonLabel: "Add file",
    AddImageButtonLabel: "Add image",
    AriaCellValue: "{0} column, {1}",
    FilePickerCancelButtonLabel: "Cancel",
    CantValidateValidationMessage: "We couldn't verify this link. Please check the link and try again.",
    ChangeFileLinkLabel: "Change file",
    ChangeImageLinkLabel: "Change image",
    ChooseFileLinkLabel: "Choose file",
    ChooseImageLinkLabel: "Choose image",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    DocumentLibraries: "Document libraries",
    EditedByNamePlate: "edited by ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "File Picker",
    FileSizeField: "File Size",
    FolderAltText: "Folder",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "No",
    ProvidedValueIsInvalid: "Provided value is invalid",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    OneDriveRootFolderName: "Files",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Recent documents",
    RecentImagesHeader: "Recent images",
    RecentLinkLabel: "Recent",
    SearchBoxPlaceholder: "Web search",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    Selected: "selected",
    SharingField: "Sharing",
    SharingPrivate: "Private",
    SharingShared: "Shared",
    SiteLinkLabel: "Site",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Sorry, this function isn't implemented in this sample, because it would require a Bing API key.",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Upload file",
    UploadImageHeader: "Upload image",
    UploadLinkLabel: "Upload",
    WebSearchLinkLabel: "Web search",
    Yes: "Yes"
  };
});
