declare var define: any;

define([], () => {
  return {
  TermSetNaviagtionErrorMessage: "Zestaw Terminów nie został znaleziony",
  TermSetNavigationNoTerms: "Brak zdefiniowanych terminów",
  "Save": "Zapisz",
  "Cancel": "Anuluj",
  "SiteBreadcrumbLabel": "Strona nawigacyjna",
  "ListViewGroupEmptyLabel": "Pusty",
  "WebPartTitlePlaceholder": "Tytuł składnika Web Part",
  "WebPartTitleLabel": "Dodawanie tytułu",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "W ciągu kilku sekund",
    "L_RelativeDateTime_AFewSeconds": "Kilka sekund temu",
    "L_RelativeDateTime_AboutAMinuteFuture": "W około minutę",
    "L_RelativeDateTime_AboutAMinute": "Około minuty temu",
    "L_RelativeDateTime_XMinutesFuture": "W {0} minutę||W {0} minut",
    "L_RelativeDateTime_XMinutes": "{0} minutę temu||{0} minut temu",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "W około godzinę",
    "L_RelativeDateTime_AboutAnHour": "Około godziny temu",
    "L_RelativeDateTime_Tomorrow": "Jutro",
    "L_RelativeDateTime_Yesterday": "Dokonana wczoraj",
    "L_RelativeDateTime_TomorrowAndTime": "Jutro w {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Wczoraj o {0}",
    "L_RelativeDateTime_XHoursFuture": "W {0} godzinę||W {0} godzinach",
    "L_RelativeDateTime_XHours": "{0} godzinę temu||{0} godzin temu",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} w {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} dzień od teraz||{0} dni od teraz",
    "L_RelativeDateTime_XDays": "{0} dzień temu||{0} dni temu",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Dziś"
  },
  "SendEmailTo": "Wyślij e-mail do {0}",
  "StartChatWith": "Rozpocznij czat z {0}",
  "Contact": "Kontakt",
  "UpdateProfile": "Aktualizowanie profilu",
  "TaxonomyPickerNoTerms": "Zestaw terminów nie zawiera żadnych terminów",
  "TaxonomyPickerExpandTitle": "Rozwiń ten zestaw Terminów",
  "TaxonomyPickerMenuTermSet": "Menu dla zestawu Terminów",
  "TaxonomyPickerInLabel": "Cala",
  "TaxonomyPickerTermSetLabel": "Zestaw Terminów",
  "TaxonomyPickerTermsNotFound": "Nie można znaleźć kolejnych wybranych terminów w magazynie terminów: {0}",
  "TaxonomyPickerInvalidTerms": "Napraw nieprawidłowe terminy: {0}",
  "peoplePickerComponentTooltipMessage": "Selektor osób",
  "peoplePickerComponentErrorMessage": "Pole wymagane",
  "peoplePickerSuggestionsHeaderText": "Sugerowani ludzie",
  "peoplePickerLoadingText": "Ładowanie",
  "PeoplePickerSearchText": "Pobieranie użytkowników",
  "PeoplePickerGroupNotFound": "Nie można odnaleźć grupy.",
  "genericNoResultsFoundText": "Nie znaleziono wyników",
  "ListItemPickerSelectValue": "Wybierz wartość",
  "ListItemAttachmentsActionDeleteIconTitle": "Usunąć",
  "ListItemAttachmentsactionDeleteTitle": "Usunąć",
  "ListItemAttachmentsfileDeletedMsg": "Usunięte {0} plików",
  "ListItemAttachmentsfileDeleteError": "Błąd podczas usuwania pliku: {0}, Przyczyna {1}",
  "ListItemAttachmentserrorLoadAttachments": "Błąd w załączniku elementu listy obciążenia, Przyczyna: {0}",
  "ListItemAttachmentsconfirmDelete": "Czy na pewno chcesz wysłać załącznik {0} do kosza witryny?",
  "ListItemAttachmentsdialogTitle": "Załącznik elementu listy",
  "ListItemAttachmentsdialogOKbuttonLabel": "Ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Anuluj",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Usuń",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Dodaj załącznik",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Dodaj załącznik",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Plik nie {0} dołączony, Przyczyna: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Dodaj załącznik",
  "ListItemAttachmentsloadingMessage": "Przesyłanie pliku...",
  "ListItemAttachmentslPlaceHolderIconText": "Załącznik elementu listy",
  "ListItemAttachmentslPlaceHolderDescription": "Proszę dodać załącznik",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Dodaj",
  "mapsErrorMessage": "Wystąpił błąd podczas ładowania mapy",
  "mapsLoadingText": "Ładowania",
  "mapsSearchButtonText": "Szukaj",
  "mapsTitlePrefix": "Mapa",
  "ListViewFilterLabel": "Filtrowanie listy",
  "HeaderNormalText": "Zwykły tekst",
  "HeaderH2": "Dział 2",
  "HeaderH3": "Dział 3",
  "HeaderH4": "Dział 4",
  "HeaderBlockQuote": "Wyróżniony cytat",
  "AlignLeft": "Wyrównaj do lewej",
  "AlignCenter": "Wyśrodkuj",
  "AlignRight": "Wyrównaj do prawej",
  "AlignJustify": "Wyjustuj",
  "ListBullet": "Lista punktowana",
  "ListNumbered": "Lista numerowana",
  "StyleTitle": "Styl",
  "BoldTitle": "Pogrubienie (Ctrl + B)",
  "ItalicTitle": "Kursywa (Ctrl + I)",
  "UnderlineTitle": "Podkreślenie (Ctrl + U)",
  "AlignTitle": "Wyrównaj",
  "ListTitle": "Listy",
  "LinkTitle": "Hiperłącze",
  "ImageTitle": "Obraz",
  "MoreTitle": "Więcej",
  "FormattingPaneTitle": "Formatowanie tekstu",
  "CloseButton": "Zamknij",
  "InsertLinkTitle": "Wstaw odnośnik",
  "InsertImageTitle": "Wstaw obraz",
  "AddressFieldLabel": "Adres",
  "TextToDisplayLabel": "Tekst do wyświetlenia",
  "SaveButtonLabel": "Zapisz",
  "CancelButtonLabel": "Anuluj",
  "RemoveLinkLabel": "Usuń łącze",
  "ParagraphSectionTitle": "Paragraf",
  "HyperlinkSectionTitle": "Hiperłącze",
  "UndoTitle": "Cofnij (Ctrl + Z)",
  "RedoTitle": "Powtórz (Ctrl + Y)",
  "ClearFormattingTitle": "Wyczyść całe formatowanie",
  "FontStyleTitle": "Styl czcionki",
  "FontSizeTitle": "Rozmiar czcionki",
  "StrikethroughTitle": "Przekreślenie",
  "SuperscriptTitle": "Indeks górny",
  "SubscriptTitle": "Indeks dolny",
  "FontColorLabel": "Kolor czcionki",
  "AutomaticFontColor": "Automatyczne",
  "HighlightColorLabel": "Kolor podświetlenia",
  "NoColorHighlightColor": "Brak koloru",
  "IncreaseIndentTitle": "Zwiększ wcięcie",
  "DecreaseIndentTitle": "Zmniejsz wcięcie",
  "ThemeColorsGroupName": "Kolory motywu",
  "HighlightColorsGroupName": "Wyróżnianie kolorów",
  "StandardColorsGroupName": "Kolory standardowe",
  "CustomColorsGroupName": "Kolory niestandardowe",
  "ThemeColorDarker": "Ciemniejsze motywy",
  "ThemeColorDark": "Temat ciemny",
  "ThemeColorDarkAlt": "Temat ciemny zastępca",
  "ThemeColorPrimary": "Temat podstawowy",
  "ThemeColorSecondary": "Motyw pomocniczy",
  "ThemeColorTertiary": "Neutralny trzeciorzędny",
  "ThemeColorNeutralSecondary": "Neutralny wtórny",
  "ThemeColorNeutralPrimaryAlt": "Neutralny podstawowy alternatywny",
  "ThemeColorNeutralPrimary": "Neutralny podstawowy",
  "ThemeColorNeutralDark": "Neutralny ciemny",
  "HighlightColorYellow": "Żółty",
  "HighlightColorGreen": "Zielony",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Niebieski",
  "HighlightColorRed": "Czerwony",
  "HighlightColorDarkblue": "Ciemnoniebieski",
  "HighlightColorTeal": "Teal",
  "HighlightColorDarkgreen": "Ciemnozielony",
  "HighlightColorPurple": "Fioletowy",
  "HighlightColorMaroon": "Bordowy",
  "HighlightColorGold": "Złoty",
  "HighlightColorDarkgrey": "Ciemnoszary",
  "HighlightColorGrey": "Szary",
  "HighlightColorBlack": "Czarny",
  "StandardColorDarkred": "Ciemnoczerwony",
  "StandardColorRed": "Czerwony",
  "StandardColorOrange": "Pomarańczowy",
  "StandardColorYellow": "Żółty",
  "StandardColorLightgreen": "Jasnozielony",
  "StandardColorGreen": "Zielony",
  "StandardColorLightblue": "Jasnoniebieski",
  "StandardColorBlue": "Niebieski",
  "StandardColorDarkblue": "Ciemnoniebieski",
  "StandardColorPurple": "Fioletowy",
  "DatePickerMonthLongJanuary": "Styczeń",
  "DatePickerMonthShortJanuary": "Sty",
  "DatePickerMonthLongFebruary": "Lut",
  "DatePickerMonthShortFebruary": "Luty",
  "DatePickerMonthLongMarch": "Mar",
  "DatePickerMonthShortMarch": "Marzec",
  "DatePickerMonthLongApril": "Kwiecień",
  "DatePickerMonthShortApril": "Kwi",
  "DatePickerMonthLongMay": "Maj",
  "DatePickerMonthShortMay": "Maj",
  "DatePickerMonthLongJune": "Czerwiec",
  "DatePickerMonthShortJune": "Cze",
  "DatePickerMonthLongJuly": "Lipiec",
  "DatePickerMonthShortJuly": "Lip",
  "DatePickerMonthLongAugust": "Sierpień",
  "DatePickerMonthShortAugust": "Sierpnia",
  "DatePickerMonthLongSeptember": "Wrzesień",
  "DatePickerMonthShortSeptember": "Wrz",
  "DatePickerMonthLongOctober": "Październik",
  "DatePickerMonthShortOctober": "Paź",
  "DatePickerMonthLongNovember": "Listopad",
  "DatePickerMonthShortNovember": "Lis",
  "DatePickerMonthLongDecember": "Grudzień",
  "DatePickerMonthShortDecember": "Gru",
  "DatePickerDayLongSunday": "Niedziela",
  "DatePickerDayShortSunday": "Nie",
  "DatePickerDayLongMonday": "Poniedziałek",
  "DatePickerDayShortMonday": "Pn",
  "DatePickerDayLongTuesday": "Wtorek",
  "DatePickerDayShortTuesday": "Wt",
  "DatePickerDayLongWednesday": "Środa",
  "DatePickerDayShortWednesday": "Śr",
  "DatePickerDayLongThursday": "Czwartek",
  "DatePickerDayShortThursday": "Czw",
  "DatePickerDayLongFriday": "Piątek",
  "DatePickerDayShortFriday": "Pt",
  "DatePickerDayLongSaturday": "Sobota",
  "DatePickerDayShortSaturday": "Sob",
  "DatePickerGoToToday": "Dziś",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Data",
  "DateTimePickerTime": "Czas",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Nieprawidłowa wartość godziny",
  "DateTimePickerMinuteValueInvalid": "Nieprawidłowa wartość minutowa",
  "DateTimePickerSecondValueInvalid": "Nieprawidłowa druga wartość",
  "DateTimePickerTextErrorMessage": "Podaj prawidłową datę",
  "AddFileButtonLabel": "Dodaj plik",
  "AddImageButtonLabel": "Dodaj obraz",
  "AriaCellValue": "kolumna {0} {1}",
  "FilePickerCancelButtonLabel": "Anuluj",
  "CantValidateValidationMessage": "Nie mogliśmy zweryfikować tego linku. Proszę sprawdzić link i spróbować ponownie.",
  "ChangeFileLinkLabel": "Zmień plik",
  "ChangeImageLinkLabel": "Zmiana obrazu",
  "ChooseFileLinkLabel": "Wybierz plik",
  "ChooseImageLinkLabel": "Wybierz obraz",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Użytkownik jest odpowiedzialny za poszanowanie praw innych osób, w tym praw autorskich.",
  "CreativeCommonsMessage": "Wyniki te są oznaczone licencjami Creative Commons. Zapoznaj się z licencjami, aby upewnić się, że są zgodne.",
  "DateFormat": "MM/DD/rrrr hh: mm A",
  "DocumentLabelTemplate": "{0}, dokument, zmodyfikowany {1}, edytowane przez {2}, prywatne",
  "DocumentLibraries": "Biblioteki dokumentów",
  "EditedByNamePlate": "edytowane przez ",
  "EmptyFileSize": "0 bajtów",
  "FilePickerHeader": "Selektor plików",
  "FileSizeField": "Rozmiar pliku",
  "FolderAltText": "Folder",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, folder, zmodyfikowany {1}, edytowane przez {2}, {3} elementy, prywatne",
  "FromLinkLinkLabel": "Z linku",
  "ImageAltText": ". {0} obraz",
  "ImageAriaLabelTemplate": ". {0} obraz",
  "ImageLayoutPlaceholderText": "Układ",
  "ImageSizePlaceholderText": "Rozmiar obrazu",
  "ItemChildCountField": "Liczba podrzędnych elementów",
  "LayoutOptionAll": "Wszystkie",
  "LayoutOptionSquare": "Kwadratowy",
  "LayoutOptionTall": "Wysoki",
  "LayoutOptionWide": "Szeroki",
  "LearnMoreLink": "Dowiedz się więcej.",
  "LicenseOptionAll": "Wszystkie",
  "LicenseOptionAny": "Tylko Creative Commons",
  "LicensePlaceholderText": "Licencji",
  "LinkFileInstructions": "Wklej łącze do pliku w OneDrive dla firmy lub SharePoint Online",
  "LinkHeader": "Z linku",
  "LinkImageInstructions": "Wklej łącze do obrazu w OneDrive dla firmy lub SharePoint Online",
  "ListLayoutAriaLabel": "Opcje widoku. {0} {1}.",
  "ListLayoutCompact": "Widok kompaktowy",
  "ListLayoutCompactDescription": "Wyświetlanie elementów i szczegółów na liście kompaktowej",
  "ListLayoutList": "Widok listy",
  "ListLayoutListDescrition": "Wyświetlanie elementów i szczegółów na liście",
  "ListLayoutTile": "Widok kafelków",
  "ListLayoutTileDescription": "Wyświetlanie elementów z podglądem kafelków",
  "ListOptionsAlt": "Opcje widoku. {0} zaznaczone.",
  "ListOptionsTitle": "Otwórz menu opcji widoku",
  "Loading": "Ładowania...",
  "ModifiedByField": "Zmodyfikowany przez",
  "ModifiedField": "Data modyfikacji",
  "NameField": "Nazwa",
  "No": "Nr",
  "ProvidedValueIsInvalid": "Podana wartość jest nieprawidłowa",
  "NoExternalLinksValidationMessage": "Obsłuż tylko łącza do plików w Twojej organizacji.",
  "NoImageValidationMessage": "Nie jest to łącze do typu pliku, który obsłuży. Można połączyć tylko z obrazem.",
  "NoRecentFiles": "Brak najnowszych plików",
  "NoRecentFilesDescription": "Spróbuj wybrać plik z witryny lub przesłać go z urządzenia.",
  "NoResultsBadEnglish": "Nie znaleziono żadnego wyniku. Spróbuj zmienić opcje filtru",
  "ODModifiedField": "Zmodyfikowano",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, zmodyfikowane {2}, edytowane przez {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Ten element jest z witryny OneDrive. Pliki i foldery w usłudze OneDrive są prywatne, chyba że są udostępniane. Czy udostępniony ten plik z członkami witryny, aby mogli go ostęp?",
  "OneDriveConfirmDialogTitle": "Wystarczy sprawdzić...",
  "OneDriveEmptyFolderAlt": "Pusty folder",
  "OneDriveEmptyFolderDescription": "Aby dodać pliki, przejdź do usługi OneDrive. Można również dodać pliki do tego folderu za pomocą aplikacji OneDrive na komputerze.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Ten folder jest pusty",
  "OneDriveRootFolderName": "Pliki",
  "OpenButtonLabel": "Otwórz",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Obrazy i pliki dostarczone przez organizację",
  "PoweredByBing": "Zasilany przez Bing",
  "RecentDocumentsHeader": "Ostatnie dokumenty",
  "RecentImagesHeader": "Ostatnie Zdjęcia",
  "RecentLinkLabel": "Ostatnie",
  "SearchBoxPlaceholder": "Wyszukiwanie w Internecie",
  "SearchResultAlt": "Wynik obrazu dla {0}.",
  "SearchResultAriaLabel": "Naciśnij ENTER, aby otworzyć źródło obrazu w nowej karcie.",
  "Selected": "Wybrane",
  "SharingField": "Udostępnianie",
  "SharingPrivate": "Prywatny",
  "SharingShared": "Udostępnionych",
  "SiteLinkLabel": "Witryny",
  "SizeOptionAll": "Wszystkie",
  "SizeOptionExtraLarge": "Bardzo duże",
  "SizeOptionLarge": "Duże",
  "SizeOptionMedium": "Średnie",
  "SizeOptionSmall": "Małe",
  "SizeUnit": [
    "Bajtów",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Np",
    "Yb"
  ],
  "SorryWebSearch": "Przepraszamy, ta funkcja nie jest zaimplementowana w tym przykładzie, ponieważ wymaga klucza interfejsu API usługi Bing.",
  "SortedAscending": "Sortowane od A do Z",
  "SortedDescending": "Sortowane od Z do A",
  "TypeAriaLabel": "Operacje kolumnowe dla typ pliku, naciśnij, aby posortować według typu pliku",
  "UploadFileHeader": "Prześlij plik",
  "UploadImageHeader": "Prześlij obraz",
  "UploadLinkLabel": "Przeslij",
  "WebSearchLinkLabel": "Wyszukiwanie w Internecie",
  "StockImagesLinkLabel": "Zdjęcia stockowe",
  "StockImagesHeader": "Zdjęcia stockowe",
  "Yes": "Tak",
  "NewFolderNamePlaceholder": "Wprowadź nazwę folderu",
  "FolderFilterBoxPlaceholder": "Filtrowanie folderów według nazwy",
  "FolderExplorerLoading": "Ładowanie folderów...",
  "FolderExplorerNoItems": "Ten folder nie ma żadnych podfolderów.",
  "NewFolderIncorrectSymbolsError": "Wpisz nazwę, która nie zawiera żadnego z następujących znaków: \" * : < > ? /  |.",
  "SomethingWentWrong": "Coś poszło nie tak",
  "SelectedLabel": "Wybrany",
  "SelectIcon": "Wybierz ikonę",
  "TreeViewExpandTitle": "Rozwiń ten element",
  "TreeViewCollapseTitle": "Zwiń ten element",
  "CollectionDataEmptyFields": "Nie podano żadnych pól dla danych kolekcji.",
  "CollectionDataEmptyValue": "Brak danych w Twojej kolekcji.",
  "CollectionAddRowButtonLabel": "Dodawanie danych do kolekcji",
  "CollectionDeleteRowButtonLabel": "Usuwanie bieżącego wiersza",
  "CollectionSaveAndAddButtonLabel": "Dodawanie i zapisywanie",
  "CollectionDataItemShowErrorsLabel": "Pokaż błędy wierszy",
  "CollectionDataItemFieldRequiredLabel": "Pole jest wymagane.",
  "CollectionDataItemMissingFields": "Kolekcja pól jest pusta!",
  "InvalidUrlError": "Podany adres URL jest nieprawidłowy",
  "CollectionDataSearch": "Szukaj",
  "CollectionDataMinimumUsersDefaultMessage": "Minimalna liczba użytkowników do wybrania to {0}",
  "MyTeamsLoadingMessage": "ładowanie zespołów",
  "MyTeamsMessageError": "Coś poszło nie tak podczas ładowania zespołów, spróbuj później lub odśwież przeglądarkę",
  "MyTeamsNoTeamsMessage": "Nie masz żadnych zespołów",
  "MyTeamsTeamChannelPublicMessage": "Kanały publiczne",
  "MyTeamsTeamChannelTypeMessage": "Kanały prywatne",
  "TeamChannelPickerFontIconFavoriteText": "Ulubiony",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Kanał prywatny",
  "TeamChannelPickerSugestionHeaderText": "Sugerowane kanały zespołu",
  "TeamPickerButtonRemoveTitle": "usuń",
  "TeamPickernoResultsFoundText": "Nie znaleziono zespołów",
  "TeamPickerSugestionsHeaderText": "Sugerowane zespoły",
  "TeamsChannelPickerButtonRemoveTitle": "usuń",
  "TeamsChannelPickerNoresultsFoundText": "Nie znaleziono kanałów",
  "ViewMore": "Zobacz więcej",
  "DynamicFormLoading": "Ładowanie...",
  "DynamicFormPleaseWait": "Czekaj...",
  "DynamicFormRequiredErrorMessage": "Nie możesz pozostawić tego pola pustego.",
  "DynamicFormTermPanelTitle": "Wybierz termin",
  "DynamicFormEnterURLPlaceholder": "Wpisz adres URL",
  "DynamicFormEnterDescriptionPlaceholder": "Tekst alternatywny",
  "DynamicFormDialogValidationErrorTitle": "Błąd weryfikacji",
  "DynamicFormDialogValidationErrorMessage": "Występują błędy sprawdzania poprawności, popraw je przed zapisaniem.",
  "DynamicFormNumberValueMustBeGreaterThan": "Wartość musi być większa niż {0}",
  "DynamicFormNumberValueMustBeBetween": "Wartość musi mieścić się w przedziale od {0} do {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Wartość musi być mniejsza niż {0}",
  "DynamicFormChooseFileLabel": "Plik",
  "DynamicFormChooseFileButtonText": "Wybierz plik",
  "DynamicFormRequiredFileMessage": "Plik jest wymagany",
  "customDisplayName": "Użyj tej lokalizacji:",
  "ListItemCommentDIalogDeleteSubText": "Czy na pewno chcesz usunąć ten komentarz?",
  "ListItemCommentsDialogDeleteTitle": "Potwierdź Usuń komentarz",
  "ListItemCommentsLabel": "Komentarze",
  "ListItemCommentsNoCommentsLabel": "Brak komentarzy",
  "OrgAssetsLinkLabel": "Twoja organizacja",
  "MyTeamsMessageDontHaveTeams": "Nie masz żadnych zaspołów",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Wprowadź termin, który chcesz oznaczyć",
  "ModernTaxonomyPickerTreeTitleSingle": "Wybierz tag",
  "ModernTaxonomyPickerTreeTitleMulti": "Wybierz jeden lub więcej tagów",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Dodaj tag",
  "ModernTaxonomyPickerApplyButtonText": "Zastosuj",
  "ModernTaxonomyPickerCancelButtonText": "Anuluj",
  "ModernTaxonomyPickerLoadMoreText": "Dowiedz się więcej",
  "ModernTaxonomyPickerRemoveButtonText": "Usuń",
  "ModernTaxonomyPickerPanelCloseButtonText": "Zamknij",
  "ModernTaxonomyPickerNoResultsFound": "Nie znaleziono wyników",
  "ModernTaxonomyPickerSuggestionInLabel": "w",

  "ModernAudioPlay": "Odtwórz",
  "ModernAudioPause": "Pauza",
  "ModernAudioIncVol": "Zwiększ głośność",
  "ModernAudioDecVol": "Zmniejsz głośność",
  "ModernAudioMute": "Wycisz",

  "ProgressStepsIndicatorNoSteps": "Brak kroków do wyświetlenia",

  "UploadFilesButtonLabel": "Dodaj",
  "UpLoadFilesDeleteButtonLabel": "Usuń",
  "UpLoadFilesDragDropLabel": "Przeciągnij i upuść pliki tutaj lub uzyj przycisku Dodaj",
  "UpLoadFilesSelectAllLabel": "Wybierz wszystkie",
  "UploadFilesUploadButtonLabel": "Prześlij",

  HoverReactionBarSearchEmojiPlaceholder: "Wyszukaj emoji",
  ImagePickderSelectLabel: "Wybierz obraz",
  ImagePickerDeleteImageLabel: "Usuń",
  ImagePickerSelectLabel: "Wybierz",
  ImagePickerCancelLabel: "Anuluj",
  ImagePickerPanelHeaderText: "Wybierz obraz by użyć jako miniaturę",
  ImagePickerSharePointTabLabel: "SharePoint",
  ImagePickerOneDriveTabLabel: "OnDrive",
  ImagePickerStockImagesTabLabel: "Zdjęcia stockowe",
  ImagePickerUploadTabLabel: "Prześlij",
  ImagePickerDragFilesAccpted: "Akceptowane formaty plików : .gif, .jpg, .jpeg, .png, .svg",
  ImagePickerDragFilesRejected: "Niektóre pliki będą odrzucone",
  ImagePickerDragFilesActive:"Upuść pliki tutaj...",
  ImagePickerDragDropText: "Przeciągnij i upuść pliki tutaj lub naciśnij by wybrać pliki, maksymalna liczba plików w jednej operacji to 10",
  ImagePickerUploadLocationLabel: "Lokalizacja przesyłania",
  ImagePickerUploadLocationOndriveLabel: "OneDrive",
  ImagePickerUploadLocationSharePointLabel: "Obecna witryna",
  ImagePickerRetryButtonLabel: "Powtórz",
  ImagePickerDeleteLabel: "Usuń",

  AppliedFiltersAriaLabel: "Zastosowane filtry",
  ClearAllFiltersTitle: "Wyczyść wszystkie filtry",
  ClearFilterTitle: "Wyczyść filtr",
  ClearAllFiltersText: "Wyczyść filtry",
  FilterOverflowAriaLabel: "Więcej",

  CalendarControlDayOfWeekSunday:  "Niedziela",
  CalendarControlDayOfWeekMonday: "Poniedziałek",
  CalendarControlDayOfWeekTuesday: "Wtorek",
  CalendarControlDayOfWeekWednesday: "Środa",
  CalendarControlDayOfWeekThursday: "Czwartek",
  CalendarControlDayOfWeekFriday: "Piątek",
  CalendarControlDayOfWeekSaturday: "Sobota",
  CalendarControlDetailsLabel: "Detale",

  CalendarControlViewMonthLabel: "Miesiąc",
  CalendarControlViewWeekLabel: "Tydzień",
  CalendarControlViewDayLabel: "Dzień",
  CalendarControlTodayLabel: "Dziś",
  CalendarControlPreviousLabel: "Wstecz",
  CalendarControlNextLabel: "Dalej",

  CalendarControlAttendeessLabel: "Uczestnicy",
  CalendarControlFullDaylabel: "Cały dzień",
};
});
