declare var define: any;

define([], () => {
  return {
'SiteBreadcrumbLabel':'Localização atual do site',
    'ListViewGroupEmptyLabel': 'Vazio',
    'WebPartTitlePlaceholder': 'Título da Web part',
    'WebPartTitleLabel': 'Adicione um título',
    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Em alguns segundos",
      "L_RelativeDateTime_AFewSeconds": "Alguns segundos atrás",
      "L_RelativeDateTime_AboutAMinuteFuture": "Em cerca de um minuto",
      "L_RelativeDateTime_AboutAMinute": "Cerca de um minuto atrás",
      "L_RelativeDateTime_XMinutesFuture": "Em {0} minuto || Em {0} minutos",
      "L_RelativeDateTime_XMinutes": "{0} minuto atrás || {0} minutos atrás",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1 || 2-",
      "L_RelativeDateTime_XMinutesIntervals": "1 || 2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Em cerca de uma hora",
      "L_RelativeDateTime_AboutAnHour": "Cerca de uma hora atrás",
      "L_RelativeDateTime_Tomorrow": "Amanhã",
      "L_RelativeDateTime_Yesterday": "Ontem",
      "L_RelativeDateTime_TomorrowAndTime": "Amanhã às {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Ontem às {0}",
      "L_RelativeDateTime_XHoursFuture": "Em {0} hora || Em {0} horas",
      "L_RelativeDateTime_XHours": "{0} hora atrás || {0} horas atrás",
      "L_RelativeDateTime_XHoursFutureIntervals": "1 || 2-",
      "L_RelativeDateTime_XHoursIntervals": "1 || 2-",
      "L_RelativeDateTime_DayAndTime": "{0} em {1}",
      "L_RelativeDateTime_XDaysFuture": "{0} dias a partir de agora || {0} dias a partir de agora",
      "L_RelativeDateTime_XDays": "{0} dia atrás || {0} dias atrás",
      "L_RelativeDateTime_XDaysFutureIntervals": "1 || 2-",
      "L_RelativeDateTime_XDaysIntervals": "1 || 2-",
      "L_RelativeDateTime_Today": "Hoje"
    },
    "SendEmailTo": "Envie um e-mail para {0}",
    "StartChatWith": "Inicie um bate-papo com {0}",
    "Contact": "Contato",
    "UpdateProfile": "Atualize seu perfil",

    "TaxonomyPickerNoTerms": "O conjunto de termos não contém quaisquer termos",
    "TaxonomyPickerExpandTitle": "Expandir este conjunto de termos",
    "TaxonomyPickerMenuTermSet": "Menu para conjunto de termos",
    "TaxonomyPickerInLabel": "no",
    "TaxonomyPickerTermSetLabel": "Conjunto de termos",
    "TaxonomyPickerTermsNotFound": "Os próximos termos selecionados não foram encontrados no repositório de termos: {0}",
    "TaxonomyPickerInvalidTerms": "Corrija os termos inválidos: {0}",

    peoplePickerComponentTooltipMessage: "Selecionador de Pessoas",
    peoplePickerComponentErrorMessage: "Campo obrigatório",
    peoplePickerSuggestionsHeaderText: 'Pessoas sugeridas',
    peoplePickerLoadingText: 'Carregando',
    PeoplePickerSearchText: 'Buscando usuários',
    PeoplePickerGroupNotFound: "Grupo não encontrado.",

    genericNoResultsFoundText: 'Nenhum resultado encontrado',

    ListItemPickerSelectValue: 'Selecione o valor',
    ListItemAttachmentsActionDeleteIconTitle: 'Excluir',
    ListItemAttachmentsactionDeleteTitle: 'Excluir',
    ListItemAttachmentsfileDeletedMsg: 'Arquivo {0} excluído',
    ListItemAttachmentsfileDeleteError: 'Erro ao excluir arquivo: {0}, motivo {1}',
    ListItemAttachmentserrorLoadAttachments: 'Erro ao carregar o anexo do item da lista, motivo: {0}',
    ListItemAttachmentsconfirmDelete: 'Tem certeza de que deseja enviar o anexo {0} para a lixeira do site?',
    ListItemAttachmentsdialogTitle: 'Anexo de item de lista',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Cancelar',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Excluir',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Juntar anexo',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Juntar anexo',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'O arquivo {0} não anexado, motivo: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Juntar anexo',
    ListItemAttachmentsloadingMessage: 'Enviando arquivo ...',
    ListItemAttachmentslPlaceHolderIconText: 'Anexo de item de lista',
    ListItemAttachmentslPlaceHolderDescription: 'Por favor, adicione anexo',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Adicionar',

    mapsErrorMessage: 'Ocorreu um erro ao carregar o mapa',
    mapsLoadingText: 'Carregando',
    mapsSearchButtonText: 'Procurar',
    mapsTitlePrefix: 'Mapa de',

    ListViewFilterLabel: "Filtre a lista",

    HeaderNormalText: "Texto normal",
    HeaderH2: "Cabeçalho 1",
    HeaderH3: "Título 2",
    HeaderH4: "Título 3",
    HeaderBlockQuote: "Puxar citação",
    AlignLeft: "Alinhar à esquerda",
    AlignCenter: "Centro",
    AlignRight: "Alinhar à direita",
    AlignJustify: "Justificar",
    ListBullet: "Lista com marcadores",
    ListNumbered: "Lista numerada",
    StyleTitle: "Estilo",
    BoldTitle: "Negrito (Ctrl + B)",
    ItalicTitle: "Itálico (Ctrl + I)",
    UnderlineTitle: "Sublinhado (Ctrl + U)",
    AlignTitle: "Alinhar",
    ListTitle: "Lista",
    LinkTitle: "Hyperlink",
    ImageTitle: "Imagem",
    MoreTitle: "Mais",
    FormattingPaneTitle: "Formatação de texto",
    CloseButton: "Fechar",
    InsertLinkTitle: "Inserir link",
    InsertImageTitle: "Inserir Imagem",
    AddressFieldLabel: "Endereço",
    TextToDisplayLabel: "Texto a ser exibido",
    SaveButtonLabel: "Salvar",
    CancelButtonLabel: "Cancelar",
    RemoveLinkLabel: "Remover link",
    ParagraphSectionTitle: "Parágrafo",
    HyperlinkSectionTitle: "Hyperlink",
    UndoTitle: "Desfazer (Ctrl + Z)",
    RedoTitle: "Refazer (Ctrl + Y)",
    ClearFormattingTitle: "Limpar toda a formatação",
    FontStyleTitle: "Estilo de fonte",
    FontSizeTitle: "Tamanho da fonte",
    StrikethroughTitle: "Tachado",
    SuperscriptTitle: "Sobrescrito",
    SubscriptTitle: "Subscrito",
    FontColorLabel: "Cor da fonte",
    AutomaticFontColor: "Automático",
    HighlightColorLabel: "Cor de destaque",
    NoColorHighlightColor: "Sem cor",
    IncreaseIndentTitle: "Aumentar recuo",
    DecreaseIndentTitle: "Recuar devagar",
    ThemeColorsGroupName: "Cores do tema",
    HighlightColorsGroupName: "Destacar cores",
    StandardColorsGroupName: "Cores padrão",
    CustomColorsGroupName: "Cores personalizadas",
    ThemeColorDarker: "Tema mais escuro",
    ThemeColorDark: "Tema escuro",
    ThemeColorDarkAlt: "Tema escuro alternativo",
    ThemeColorPrimary: "Tema principal",
    ThemeColorSecondary: "Tema secundário",
    ThemeColorTertiary: "Terciário neutro",
    ThemeColorNeutralSecondary: "Neutro secundário",
    ThemeColorNeutralPrimaryAlt: "Alternativo primário neutro",
    ThemeColorNeutralPrimary: "Neutro primário",
    ThemeColorNeutralDark: "Neutro escuro",
    HighlightColorYellow: "Amarelo",
    HighlightColorGreen: "Verde",
    HighlightColorAqua: "Aqua",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Azul",
    HighlightColorRed: "Vermelho",
    HighlightColorDarkblue: "Azul escuro",
    HighlightColorTeal: "Cerceta",
    HighlightColorDarkgreen: "Verde escuro",
    HighlightColorPurple: "Roxo",
    HighlightColorMaroon: "Marrom",
    HighlightColorGold: "Ouro",
    HighlightColorDarkgrey: "Cinza escuro",
    HighlightColorGrey: "Cinza",
    HighlightColorBlack: "Preto",
    StandardColorDarkred: "Vermelho escuro",
    StandardColorRed: "Vermelho",
    StandardColorOrange: "Laranja",
    StandardColorYellow: "Amarelo",
    StandardColorLightgreen: "Luz verde",
    StandardColorGreen: "Verde",
    StandardColorLightblue: "Azul claro",
    StandardColorBlue: "Azul",
    StandardColorDarkblue: "Azul escuro",
    StandardColorPurple: "Roxo",

    DatePickerMonthLongJanuary: "Janeiro",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Fevereiro",
    DatePickerMonthShortFebruary: "Fev",
    DatePickerMonthLongMarch: "Marcha",
    DatePickerMonthShortMarch: "Março",
    DatePickerMonthLongApril: "Abril",
    DatePickerMonthShortApril: "Abril",
    DatePickerMonthLongMay: "Maio",
    DatePickerMonthShortMay: "Maio",
    DatePickerMonthLongJune: "Junho",
    DatePickerMonthShortJune: "Junho",
    DatePickerMonthLongJuly: "Julho",
    DatePickerMonthShortJuly: "Julho",
    DatePickerMonthLongAugust: "Agosto",
    DatePickerMonthShortAugust: "Agosto",
    DatePickerMonthLongSeptember: "Setembro",
    DatePickerMonthShortSeptember: "Setembro",
    DatePickerMonthLongOctober: "Outubro",
    DatePickerMonthShortOctober: "Outubro",
    DatePickerMonthLongNovember: "Novembro",
    DatePickerMonthShortNovember: "Novembro",
    DatePickerMonthLongDecember: "Dezembro",
    DatePickerMonthShortDecember: "Dezembro",
    DatePickerDayLongSunday: "Domigo",
    DatePickerDayShortSunday: "Dom",
    DatePickerDayLongMonday: "Segunda-feira",
    DatePickerDayShortMonday: "Seg",
    DatePickerDayLongTuesday: "Terça-feira",
    DatePickerDayShortTuesday: "Ter",
    DatePickerDayLongWednesday: "Quarta-feira",
    DatePickerDayShortWednesday: "Qua",
    DatePickerDayLongThursday: "Quinta-feira",
    DatePickerDayShortThursday: "Qui",
    DatePickerDayLongFriday: "Sexta-feira",
    DatePickerDayShortFriday: "Sex",
    DatePickerDayLongSaturday: "Sábado",
    DatePickerDayShortSaturday: "Sáb",
    DatePickerGoToToday: "Hoje",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Data",
    DateTimePickerTime: "Tempo",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Valor de hora incorreto",
    DateTimePickerMinuteValueInvalid: "Valor de minuto incorreto",
    DateTimePickerSecondValueInvalid: "Segundo valor incorreto",

    AddFileButtonLabel: "Adicionar ficheiro",
    AddImageButtonLabel: "Adicionar imagem",
    AriaCellValue:  "{0} Coluna, {1}",
    FilePickerCancelButtonLabel: "Cancelar",
    CantValidateValidationMessage: "Não foi possível verificar este link. Verifique o link e tente novamente.",
    ChangeFileLinkLabel: "Alterar arquivo",
    ChangeImageLinkLabel: "Mudar imagem",
    ChooseFileLinkLabel: "Escolher arquivo",
    ChooseImageLinkLabel: "Escolha a imagem",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "Você é responsável por respeitar os direitos dos outros, incluindo direitos autorais.",
    CreativeCommonsMessage: "Esses resultados são marcados com licenças Creative Commons. Revise as licenças para garantir sua conformidade.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Documento, Modificado {1}, editado por {2}, Privado",
    DocumentLibraries: "Bibliotecas de documentos",
    EditedByNamePlate: "editado por ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "Seletor de arquivos",
    FileSizeField: "Tamanho do arquivo",
    FolderAltText: "Pasta",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Pasta, Modificado {1}, editado por {2}, {3} itens, Privado",
    FromLinkLinkLabel: "De um link",
    ImageAltText: ". {0} Imagem",
    ImageAriaLabelTemplate: ". {0} Imagem",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Tamanho da imagem",
    ItemChildCountField: "Contagem de itens filhos",
    LayoutOptionAll: "Tudo",
    LayoutOptionSquare: "Quadrado",
    LayoutOptionTall: "Alto",
    LayoutOptionWide: "Largo",
    LearnMoreLink: "Saber mais.",
    LicenseOptionAll: "Tudo",
    LicenseOptionAny: "Somente Creative Commons",
    LicensePlaceholderText: "Licença",
    LinkFileInstructions: "Cole um link para um arquivo no OneDrive for Business ou SharePoint Online",
    LinkHeader: "De um link",
    LinkImageInstructions: "Cole um link para uma imagem no OneDrive for Business ou no SharePoint Online",
    ListLayoutAriaLabel: "Ver opções. {0} {1}.",
    ListLayoutCompact: "Visualização compacta",
    ListLayoutCompactDescription: "Ver itens e detalhes em uma lista compacta",
    ListLayoutList: "Exibição de lista",
    ListLayoutListDescrition: "Ver itens e detalhes em uma lista",
    ListLayoutTile: "Vista lado a lado",
    ListLayoutTileDescription: "Ver itens com visualizações de blocos",
    ListOptionsAlt: "Opções de visualização. {0} selecionado.",
    ListOptionsTitle: "Abra o menu de opções de visualização",
    Loading: "Carregando...", 
    ModifiedByField:"Modificado por",
    ModifiedField: "Data modificada",
    NameField: "Nome",
    No: "Não",
    ProvidedValueIsInvalid: "O valor fornecido é inválido",
    NoExternalLinksValidationMessage: "Só suportamos links para arquivos em sua própria organização.",
    NoImageValidationMessage: "Este não é um link para um tipo de arquivo que suportamos. Você só pode criar um link para uma imagem.",
    NoRecentFiles: "Nenhum arquivo recente",
    NoRecentFilesDescription: "Tente selecionar um arquivo do seu site ou carregue um do seu dispositivo.",
    NoResultsBadEnglish: "*** Nenhum resultado encontrado. Tente alterar as opções de filtro",
    ODModifiedField: "Modificado",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modificado {2}, editado por {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "Este item é do seu site OneDrive. Arquivos e pastas no OneDrive são privados, a menos que você os compartilhe. Você compartilhou este arquivo com membros do seu site para que eles possam acessá-lo?",
    OneDriveConfirmDialogTitle: "Apenas checando...",
    OneDriveEmptyFolderAlt: "Pasta vazia",
    OneDriveEmptyFolderDescription: "Para adicionar arquivos, vá para seu OneDrive. Você também pode adicionar arquivos a esta pasta usando o aplicativo OneDrive para seu computador.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Esta pasta está vazia",
    OneDriveRootFolderName: "Arquivos",
    OpenButtonLabel: "Abrir",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Imagens e arquivos fornecidos por sua organização",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Documentos recentes",
    RecentImagesHeader: "Imagens recentes",
    RecentLinkLabel: "Recente",
    SearchBoxPlaceholder: "Pesquisa na internet",
    SearchResultAlt: "Resultado de imagem para {0}.",
    SearchResultAriaLabel: "Pressione Enter para abrir a fonte da imagem em uma nova guia.",
    Selected: "selecionado",
    SharingField: "Compartilhamento",
    SharingPrivate: "Privado",
    SharingShared: "Compartilhado",
    SiteLinkLabel: "Local",
    SizeOptionAll: "Tudo",
    SizeOptionExtraLarge: "Extra grande",
    SizeOptionLarge: "Grande",
    SizeOptionMedium: "Médio",
    SizeOptionSmall: "Pequena",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Desculpe, esta função não está implementada neste exemplo, porque exigiria uma chave de API do Bing.",
    SortedAscending: "Classificados de A a Z",
    SortedDescending: "Ordenado de Z a A",
    TypeAriaLabel: "Operações de coluna para tipo de arquivo, pressione para classificar por tipo de arquivo",
    UploadFileHeader: "Subir arquivo",
    UploadImageHeader: "Enviar Imagem",
    UploadLinkLabel: "Envio",
    WebSearchLinkLabel: "Pesquisa na internet",
    StockImagesLinkLabel: "Banco de imagens",
    StockImagesHeader: "Stock Images",
    Yes: "Sim",

    NewFolderNamePlaceholder: "Digite o nome da sua pasta",
    FolderFilterBoxPlaceholder: "Filtrar pastas por nome",
    FolderExplorerLoading: "Carregando pastas ...",
    FolderExplorerNoItems: "Esta pasta não possui subpastas.",
    NewFolderIncorrectSymbolsError:"Insira um nome que não inclua nenhum destes caracteres: \ *: <>? / \ |. ",
    SomethingWentWrong: "Algo deu errado",
    SelectedLabel: "Selecionado",
    SelectIcon: "Selecione o ícone",

    TreeViewExpandTitle: "Expanda este item",
    TreeViewCollapseTitle: "Recolher este item",

    CollectionDataEmptyFields: "Nenhum campo foi fornecido para os dados de coleta.",
    CollectionDataEmptyValue: "Não há dados em sua coleção.",
    CollectionAddRowButtonLabel: "Adicionar dados à coleção",
    CollectionDeleteRowButtonLabel: "Excluir a linha atual",
    CollectionSaveAndAddButtonLabel: "Adicionar e salvar",
    CollectionDataItemShowErrorsLabel: "Mostrar erros de linha",
    CollectionDataItemFieldRequiredLabel: "Campo é obrigatório.",
    CollectionDataItemMissingFields: "A coleção Fields está vazia!",
    InvalidUrlError: "O URL fornecido não é válido",
    CollectionDataSearch: "Procurar",

    ViewMore: "Veja mais"
};
});

