declare var define: any;

define([], () => {
  return {
  CalendarControlDayOfWeekSunday: "Domingo",
  TermSetNavigationErrorMessage: "TermSet não encontrado",
  TermSetNavigationNoTerms: "Nenhum termo definido",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "encontrado",
  worldMapLoadingText: "A carregar estilo do mapa…",
  worldMapLocationLabel: "localização",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "nome",
  worldMapSearchLocations: "Procurar localizações...",
  worldMapTitle: "Mapa Mundo",
  worldMapZoomContent: "Aproximar",
  worldMapZoomIn: "Aproximar",
  "Save": "Gravar",
  "Cancel": "Cancelar",
  "SiteBreadcrumbLabel": "Localização atual do site",
  "ListViewGroupEmptyLabel": "Vazio",
  "WebPartTitlePlaceholder": "Título da Web part",
  "WebPartTitleLabel": "Adicionar um título",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Em poucos segundos",
    "L_RelativeDateTime_AFewSeconds": "Há alguns segundos",
    "L_RelativeDateTime_AboutAMinuteFuture": "Em cerca de um minuto",
    "L_RelativeDateTime_AboutAMinute": "Cerca de um minuto atrás",
    "L_RelativeDateTime_XMinutesFuture": "Em {0} minuto || Em {0} minutos",
    "L_RelativeDateTime_XMinutes": "{0} minuto atrás|| {0} minutos atrás",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Em cerca de uma hora",
    "L_RelativeDateTime_AboutAnHour": "Cerca de uma hora atrás",
    "L_RelativeDateTime_Tomorrow": "Amanhã",
    "L_RelativeDateTime_Yesterday": "Ontem",
    "L_RelativeDateTime_TomorrowAndTime": "Amanhã às {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Ontem às {0}",
    "L_RelativeDateTime_XHoursFuture": "Em {0} hora || Em {0} horas",
    "L_RelativeDateTime_XHours": "{0} hora atrás|| {0} horas atrás",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} na {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} dia a partir de agora| | {0} dias a partir de agora",
    "L_RelativeDateTime_XDays": "{0} dia atrás|| {0} dias atrás",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Hoje"
  },
  "SendEmailTo": "Envie um e-mail para {0}",
  "StartChatWith": "Comece uma conversa com {0}",
  "Contact": "Contato",
  "UpdateProfile": "Atualize seu perfil",
  "TaxonomyPickerNoTerms": "O conjunto de termos não contém quaisquer termos",
  "TaxonomyPickerExpandTitle": "Expandir este conjunto de termos",
  "TaxonomyPickerMenuTermSet": "Menu para conjunto de termos",
  "TaxonomyPickerInLabel": "Em",
  "TaxonomyPickerTermSetLabel": "Conjunto de termos",
  "TaxonomyPickerTermsNotFound": "Os próximos termos selecionados não puderam ser encontrados no repositório de termos: {0}",
  "TaxonomyPickerInvalidTerms": "Por favor, corrija os prazos inválidos: {0}",
  "peoplePickerComponentTooltipMessage": "Selecionador de Pessoas",
  "peoplePickerComponentErrorMessage": "Campo necessário",
  "peoplePickerSuggestionsHeaderText": "Pessoas sugeridas",
  "peoplePickerLoadingText": "Carregando",
  "PeoplePickerSearchText": "Procurando utilizador",
  "PeoplePickerGroupNotFound": "O grupo não foi encontrado.",
  "genericNoResultsFoundText": "Não foram encontrados resultados",
  "ListItemPickerSelectValue": "Selecione valor",
  "ListItemAttachmentsActionDeleteIconTitle": "Excluir",
  "ListItemAttachmentsactionDeleteTitle": "Excluir",
  "ListItemAttachmentsfileDeletedMsg": "Arquivo {0} excluído",
  "ListItemAttachmentsfileDeleteError": "Erro ao excluir arquivo: {0}, motivo {1}",
  "ListItemAttachmentserrorLoadAttachments": "Erro ao carregar o anexo do item da lista, motivo: {0}",
  "ListItemAttachmentsconfirmDelete": "Tem certeza de que deseja enviar o anexo {0} para a lixeira do site?",
  "ListItemAttachmentsdialogTitle": "Anexo do item da lista",
  "ListItemAttachmentsdialogOKbuttonLabel": "OK",
  "ListItemAttachmentsdialogCancelButtonLabel": "Cancelar",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Excluir",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Adicionar anexo",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Adicionar anexo",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "O arquivo {0} não foi anexado, motivo: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Adicionar anexo",
  "ListItemAttachmentsloadingMessage": "Upload de arquivo ...",
  "ListItemAttachmentslPlaceHolderIconText": "Anexo do item da lista",
  "ListItemAttachmentslPlaceHolderDescription": "Por favor, adicione o anexo",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Adicionar",
  "mapsErrorMessage": "Houve um erro ao carregar o mapa",
  "mapsLoadingText": "Carregando",
  "mapsSearchButtonText": "Procurar",
  "mapsTitlePrefix": "Mapa de",
  "ListViewFilterLabel": "Filtrar a lista",
  "HeaderNormalText": "Texto normal",
  "HeaderH2": "Cabeçalho 2",
  "HeaderH3": "Título 3",
  "HeaderH4": "Título 4",
  "HeaderBlockQuote": "Puxar citação",
  "AlignLeft": "Alinhar à esquerda",
  "AlignCenter": "Centro",
  "AlignRight": "Alinhar à direita",
  "AlignJustify": "Justificar",
  "ListBullet": "Lista com marcadores",
  "ListNumbered": "Lista numerada",
  "StyleTitle": "Estilo",
  "BoldTitle": "Negrito (Ctrl+B)",
  "ItalicTitle": "Itálico (Ctrl+I)",
  "UnderlineTitle": "Sublinhado (Ctrl+U)",
  "AlignTitle": "Alinhar",
  "ListTitle": "Lista",
  "LinkTitle": "Hiperlink",
  "ImageTitle": "Imagem",
  "MoreTitle": "Mais",
  "FormattingPaneTitle": "Formatação de texto",
  "CloseButton": "Fechar",
  "InsertLinkTitle": "Inserir link",
  "InsertImageTitle": "Inserir imagem",
  "AddressFieldLabel": "Endereço",
  "TextToDisplayLabel": "Texto para exibir",
  "SaveButtonLabel": "Gravar",
  "CancelButtonLabel": "Cancelar",
  "RemoveLinkLabel": "Remover o link",
  "ParagraphSectionTitle": "Parágrafo",
  "HyperlinkSectionTitle": "Hiperlink",
  "UndoTitle": "Desfazer (Ctrl+Z)",
  "RedoTitle": "Refazer (Ctrl+Y)",
  "ClearFormattingTitle": "Limpar toda a formatação",
  "FontStyleTitle": "Estilo de fonte",
  "FontSizeTitle": "Tamanho da fonte",
  "StrikethroughTitle": "Tachado",
  "SuperscriptTitle": "Sobrescrito",
  "SubscriptTitle": "Subscrito",
  "FontColorLabel": "Cor da fonte",
  "AutomaticFontColor": "Automático",
  "HighlightColorLabel": "Cor de destaque",
  "NoColorHighlightColor": "Sem cor",
  "IncreaseIndentTitle": "Aumentar recuo",
  "DecreaseIndentTitle": "Diminuir recuo",
  "ThemeColorsGroupName": "Cores do tema",
  "HighlightColorsGroupName": "Destacar cores",
  "StandardColorsGroupName": "Cores padrão",
  "CustomColorsGroupName": "Cores personalizadas",
  "ThemeColorDarker": "Tema mais escuro",
  "ThemeColorDark": "Tema escuro",
  "ThemeColorDarkAlt": "Tema escuro alternativo",
  "ThemeColorPrimary": "Tema principal",
  "ThemeColorSecondary": "Tema secundário",
  "ThemeColorTertiary": "Terciário neutro",
  "ThemeColorNeutralSecondary": "Neutro secundário",
  "ThemeColorNeutralPrimaryAlt": "Alternativo primário neutro",
  "ThemeColorNeutralPrimary": "Neutro primário",
  "ThemeColorNeutralDark": "Neutro escuro",
  "HighlightColorYellow": "Amarelo",
  "HighlightColorGreen": "Verde",
  "HighlightColorAqua": "Azul turquesa",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Azul",
  "HighlightColorRed": "Vermelho",
  "HighlightColorDarkblue": "Azul escuro",
  "HighlightColorTeal": "Verde azulado",
  "HighlightColorDarkgreen": "Verde escuro",
  "HighlightColorPurple": "Roxo",
  "HighlightColorMaroon": "Marrom",
  "HighlightColorGold": "Ouro",
  "HighlightColorDarkgrey": "Cinza escuro",
  "HighlightColorGrey": "Cinza",
  "HighlightColorBlack": "Preto",
  "StandardColorDarkred": "Vermelho escuro",
  "StandardColorRed": "Vermelho",
  "StandardColorOrange": "Laranja",
  "StandardColorYellow": "Amarelo",
  "StandardColorLightgreen": "Verde claro",
  "StandardColorGreen": "Verde",
  "StandardColorLightblue": "Azul claro",
  "StandardColorBlue": "Azul",
  "StandardColorDarkblue": "Azul escuro",
  "StandardColorPurple": "Roxo",
  "DatePickerMonthLongJanuary": "Janeiro",
  "DatePickerMonthShortJanuary": "Jan",
  "DatePickerMonthLongFebruary": "Fevereiro",
  "DatePickerMonthShortFebruary": "Fev",
  "DatePickerMonthLongMarch": "Março",
  "DatePickerMonthShortMarch": "Mar",
  "DatePickerMonthLongApril": "Abril",
  "DatePickerMonthShortApril": "Abr",
  "DatePickerMonthLongMay": "Maio",
  "DatePickerMonthShortMay": "Mai",
  "DatePickerMonthLongJune": "Junho",
  "DatePickerMonthShortJune": "Jun",
  "DatePickerMonthLongJuly": "Julho",
  "DatePickerMonthShortJuly": "Jul",
  "DatePickerMonthLongAugust": "Agosto",
  "DatePickerMonthShortAugust": "Ago",
  "DatePickerMonthLongSeptember": "Setembro",
  "DatePickerMonthShortSeptember": "Set",
  "DatePickerMonthLongOctober": "Outubro",
  "DatePickerMonthShortOctober": "Out",
  "DatePickerMonthLongNovember": "Novembro",
  "DatePickerMonthShortNovember": "Nov",
  "DatePickerMonthLongDecember": "Dezembro",
  "DatePickerMonthShortDecember": "Dez",
  "DatePickerDayLongSunday": "Domingo",
  "DatePickerDayShortSunday": "Dom",
  "DatePickerDayLongMonday": "Segunda-feira",
  "DatePickerDayShortMonday": "Seg",
  "DatePickerDayLongTuesday": "Terça-feira",
  "DatePickerDayShortTuesday": "Ter",
  "DatePickerDayLongWednesday": "Quarta-feira",
  "DatePickerDayShortWednesday": "Qua",
  "DatePickerDayLongThursday": "Quinta-feira",
  "DatePickerDayShortThursday": "Qui",
  "DatePickerDayLongFriday": "Sexta-feira",
  "DatePickerDayShortFriday": "Sex",
  "DatePickerDayLongSaturday": "Sábado",
  "DatePickerDayShortSaturday": "Sáb",
  "DatePickerGoToToday": "Hoje",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Data",
  "DateTimePickerTime": "Tempo",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Valor de hora incorreto",
  "DateTimePickerMinuteValueInvalid": "Valor de minutos incorreto",
  "DateTimePickerSecondValueInvalid": "Valor de segundos incorreto",
  "DateTimePickerTextErrorMessage": "Por favor, insira uma data válida",
  "AddFileButtonLabel": "Adicionar arquivo",
  "AddImageButtonLabel": "Adicionar imagem",
  "AriaCellValue": "coluna {0}, {1}",
  "FilePickerCancelButtonLabel": "Cancelar",
  "CantValidateValidationMessage": "Não foi possível verificar este link. Verifique o link e tente novamente.",
  "ChangeFileLinkLabel": "Alterar arquivo",
  "ChangeImageLinkLabel": "Mudar imagem",
  "ChooseFileLinkLabel": "Escolher arquivo",
  "ChooseImageLinkLabel": "Escolher imagem",
  "CopyrightUrl": "https://www.microsoft.com/pt-pt/legal/copyright/default.aspx",
  "CopyrightWarning": "Você é responsável por respeitar os direitos dos outros, incluindo direitos autorais.",
  "CreativeCommonsMessage": "Esses resultados são marcados com licenças Creative Commons. Reveja as licenças para garantir sua conformidade.",
  "DateFormat": "MM/DD/YYYY hh: mm A",
  "DocumentLabelTemplate": "{0}, Documento, {1} Modificado, modificado por {2}, Privado",
  "DocumentLibraries": "Bibliotecas de documentos",
  "EditedByNamePlate": "modificado por ",
  "EmptyFileSize": "0 bytes",
  "FilePickerHeader": "Selecionador de arquivos",
  "FileSizeField": "Tamanho do arquivo",
  "FolderAltText": "Pasta",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, Pasta, {1} Modificado, modificado por {2}, {3} items, Privado",
  "FromLinkLinkLabel": "A partir de um link",
  "ImageAltText": ". Imagem {0}",
  "ImageAriaLabelTemplate": ". Imagem {0}",
  "ImageLayoutPlaceholderText": "Layout",
  "ImageSizePlaceholderText": "Tamanho da imagem",
  "ItemChildCountField": "Contagem de items filhos",
  "LayoutOptionAll": "Todos",
  "LayoutOptionSquare": "Quadrado",
  "LayoutOptionTall": "Alto",
  "LayoutOptionWide": "Larga",
  "LearnMoreLink": "Saber mais.",
  "LicenseOptionAll": "Todos",
  "LicenseOptionAny": "Somente Creative Commons",
  "LicensePlaceholderText": "Licença",
  "LinkFileInstructions": "Cole um link para um arquivo no OneDrive for Business ou no SharePoint Online",
  "LinkHeader": "A partir de um link",
  "LinkImageInstructions": "Cole um link para uma imagem no OneDrive for Business ou no SharePoint Online",
  "ListLayoutAriaLabel": "Ver opções. {0} {1} .",
  "ListLayoutCompact": "Vista compacta",
  "ListLayoutCompactDescription": "Ver items e detalhes em uma lista compacta",
  "ListLayoutList": "Vista de lista",
  "ListLayoutListDescrition": "Ver items e detalhes em uma lista",
  "ListLayoutTile": "Vista lado a lado",
  "ListLayoutTileDescription": "Ver items com visualizações de blocos",
  "ListOptionsAlt": "Opções de visualização. {0} selecionados .",
  "ListOptionsTitle": "Abra o menu de opções de visualização",
  "Loading": "Carregando...",
  "ModifiedByField": "Modificado por",
  "ModifiedField": "Data de modificação",
  "NameField": "Nome",
  "No": "Não",
  "ProvidedValueIsInvalid": "O valor fornecido é inválido",
  "NoExternalLinksValidationMessage": "Só são suportados links para arquivos da própria organização.",
  "NoImageValidationMessage": "Este não é um link para um tipo de arquivo suportado. Você só pode usar um link para uma imagem.",
  "NoRecentFiles": "Nenhum arquivo recente",
  "NoRecentFilesDescription": "Tente selecionar um arquivo do seu site ou carregue um do seu dispositivo.",
  "NoResultsBadEnglish": "Nenhum resultado encontrado. Tente alterar as opções de filtro",
  "ODModifiedField": "Modificado",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, Modificado {2}, modificado por {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Este item é do seu site OneDrive. Arquivos e pastas no OneDrive são privados, a menos que você os compartilhe. Você compartilhou este arquivo com os membros do seu site para que eles possam aceder?",
  "OneDriveConfirmDialogTitle": "Só verificando...",
  "OneDriveEmptyFolderAlt": "Pasta vazia",
  "OneDriveEmptyFolderDescription": "Para adicionar arquivos, aceda ao seu OneDrive. Você também pode adicionar arquivos a esta pasta usando o aplicativo OneDrive para o seu computador.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Esta pasta está vazia.",
  "OneDriveRootFolderName": "Arquivos",
  "OpenButtonLabel": "Abrir",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Imagens e arquivos fornecidos pela sua organização",
  "PoweredByBing": "Fornecido por Bing",
  "RecentDocumentsHeader": "Documentos recentes",
  "RecentImagesHeader": "Imagens recentes",
  "RecentLinkLabel": "Recente",
  "SearchBoxPlaceholder": "Pesquisa na internet",
  "SearchResultAlt": "Resultado de imagem para {0}.",
  "SearchResultAriaLabel": "Pressione Enter para abrir a imagem em uma nova aba.",
  "Selected": "Selecionado",
  "SharingField": "Compartilhando",
  "SharingPrivate": "Privado",
  "SharingShared": "Compartilhado",
  "SiteLinkLabel": "Site",
  "SizeOptionAll": "Todos",
  "SizeOptionExtraLarge": "Extra Grande",
  "SizeOptionLarge": "Grande",
  "SizeOptionMedium": "Médio",
  "SizeOptionSmall": "Pequeno",
  "SizeUnit": [
    "bytes",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Eg",
    "Yb"
  ],
  "SorryWebSearch": "Desculpe, esta função não está implementada neste exemplo, porque exigiria uma chave de API do Bing.",
  "SortedAscending": "Ordenado de A a Z",
  "SortedDescending": "Ordenado de Z a A",
  "TypeAriaLabel": "Operações de coluna para o tipo de arquivo, pressione para classificar no tipo de arquivo",
  "UploadFileHeader": "Carregar arquivo",
  "UploadImageHeader": "Carregar imagem",
  "UploadLinkLabel": "Carregar",
  "WebSearchLinkLabel": "Pesquisa na internet",
  "StockImagesLinkLabel": "Banco de imagens",
  "StockImagesHeader": "Banco de imagens",
  "Yes": "Sim",
  "NewFolderNamePlaceholder": "Insira o nome da sua pasta",
  "FolderFilterBoxPlaceholder": "Filtrar pastas por nome",
  "FolderExplorerLoading": "Carregando pastas ...",
  "FolderExplorerNoItems": "Esta pasta não possui sub-pastas.",
  "NewFolderIncorrectSymbolsError": "Por favor insira um nome que não inclua nenhum destes caracteres: \" * : < > ? /  |.",
  "SomethingWentWrong": "Algo correu mal.",
  "SelectedLabel": "Selecionado",
  "SelectIcon": "Selecionar ícone",
  "TreeViewExpandTitle": "Expandir este item",
  "TreeViewCollapseTitle": "Recolher este item",
  "CollectionDataEmptyFields": "Não foram fornecidos campos para a coleção de dados.",
  "CollectionDataEmptyValue": "Não há dados na sua coleção.",
  "CollectionAddRowButtonLabel": "Adicionar dados à coleção",
  "CollectionDeleteRowButtonLabel": "Eliminar a linha atual",
  "CollectionSaveAndAddButtonLabel": "Adicionar e gravar",
  "CollectionDataItemShowErrorsLabel": "Mostrar erros de linha",
  "CollectionDataItemFieldRequiredLabel": "O campo é necessário.",
  "CollectionDataItemMissingFields": "A coleção de campos está vazia!",
  "InvalidUrlError": "O URL fornecido não é válido",
  "CollectionDataSearch": "Pesquisar",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "carregando as suas equipas",
  "MyTeamsMessageError": "Algo correu mal ao carregar as suas equipas, por favor, tente mais tarde ou atualize o navegador",
  "MyTeamsNoTeamsMessage": "De momento não tem nenhuma equipa",
  "MyTeamsTeamChannelPublicMessage": "Canais Públicos",
  "MyTeamsTeamChannelTypeMessage": "Canais Privados",
  "TeamChannelPickerFontIconFavoriteText": "Favorito",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Canal Privado",
  "TeamChannelPickerSugestionHeaderText": "Canais de Equipa Sugeridos",
  "TeamPickerButtonRemoveTitle": "remover",
  "TeamPickernoResultsFoundText": "Nenhuma equipa encontrada",
  "TeamPickerSugestionsHeaderText": "Equipas Sugeridas",
  "TeamsChannelPickerButtonRemoveTitle": "remover",
  "TeamsChannelPickerNoresultsFoundText": "Não há canais encontrados",
  "ViewMore": "Ver mais",
  "DynamicFormLoading": "A carregar...",
  "DynamicFormPleaseWait": "Aguarde...",
  "DynamicFormRequiredErrorMessage": "Não pode deixar em branco.",
  "DynamicFormTermPanelTitle": "Selecione Termo",
  "DynamicFormEnterURLPlaceholder": "Insira um URL",
  "DynamicFormEnterDescriptionPlaceholder": "Texto alternativo",
  "DynamicFormDialogValidationErrorTitle": "Erro de validação",
  "DynamicFormDialogValidationErrorMessage": "Existem erros de validação, corrija-os antes de salvar.",
  "DynamicFormNumberValueMustBeGreaterThan": "O valor deve ser maior que {0}",
  "DynamicFormNumberValueMustBeBetween": "O valor deve estar entre {0} e {1}",
  "DynamicFormNumberValueMustBeLowerThan": "O valor deve ser inferior a {0}",
  "DynamicFormChooseFileLabel": "Ficheiro",
  "DynamicFormChooseFileButtonText": "Selecionar ficheiro",
  "DynamicFormRequiredFileMessage": "Ficheiro é necessário.",
  "customDisplayName": "Utilize este local:",
  "ListItemCommentDIalogDeleteSubText": "Tem a certeza que quer eliminar este comentário?",
  "ListItemCommentsDialogDeleteTitle": "Confirmar Eliminar Comentário",
  "ListItemCommentsLabel": "Comentários",
  "ListItemCommentsNoCommentsLabel": "Sem Comentários",
  "OrgAssetsLinkLabel": "Sua organização",
  "MyTeamsMessageDontHaveTeams": "De momento não tem nenhuma equipa",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Digite um termo que deseja marcar",
  "ModernTaxonomyPickerTreeTitleSingle": "Selecione uma etiqueta",
  "ModernTaxonomyPickerTreeTitleMulti": "Selecione um ou mais tags",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Adicionar tag",
  "ModernTaxonomyPickerApplyButtonText": "Aplicar",
  "ModernTaxonomyPickerCancelButtonText": "Cancelar",
  "ModernTaxonomyPickerLoadMoreText": "Carregar mais",
  "ModernTaxonomyPickerRemoveButtonText": "Remover",
  "ModernTaxonomyPickerPanelCloseButtonText": "Fechar",
  "ModernTaxonomyPickerNoResultsFound": "Nenhum resultado encontrado",
  "ModernTaxonomyPickerSuggestionInLabel": "Em",

   "ModernAudioPlay": "Play",
   "ModernAudioPause": "Pause",
   "ModernAudioIncVol": "Increase Volume",
   "ModernAudioDecVol": "Decrease Volume",
   "ModernAudioMute": "Mute",

   "ProgressStepsIndicatorNoSteps": "Nenhuma etapa definida",

   "UploadFilesButtonLabel": "Add",
   "UpLoadFilesDeleteButtonLabel": "Delete",
   "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
   "UpLoadFilesSelectAllLabel": "Select all",
   "UploadFilesUploadButtonLabel": "Carregar",
};
});
