declare var define: any;

define([], () => {
  return {
  CalendarControlDayOfWeekSunday: "Sunday",
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "found",
  worldMapLoadintText: "Loading map style…",
  worldMapLocationLabel: "location",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "name",
  worldMapSearchLocations: "Search locations...",
  worldMapTitle: "World Map",
  worldMapZoomContent: "Zoom in",
  worldMapZoomIn: "Zoom in",
  "Save": "Salva",
  "Cancel": "Anula",
  "SiteBreadcrumbLabel": "Site-ul breadcrumb",
  "ListViewGroupEmptyLabel": "Gol",
  "WebPartTitlePlaceholder": "Titlu parte Web",
  "WebPartTitleLabel": "Adăugarea unui titlu",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "În câteva secunde",
    "L_RelativeDateTime_AFewSeconds": "Acum câteva secunde",
    "L_RelativeDateTime_AboutAMinuteFuture": "În aproximativ un minut",
    "L_RelativeDateTime_AboutAMinute": "Acum un minut",
    "L_RelativeDateTime_XMinutesFuture": "În {0} minute||În {0} minute",
    "L_RelativeDateTime_XMinutes": "{0} minut în urmă||{0} minute în urmă",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Într-o oră",
    "L_RelativeDateTime_AboutAnHour": "Acum o oră",
    "L_RelativeDateTime_Tomorrow": "Mâine",
    "L_RelativeDateTime_Yesterday": "Făcută ieri",
    "L_RelativeDateTime_TomorrowAndTime": "Mâine la {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Ieri la {0}",
    "L_RelativeDateTime_XHoursFuture": "În {0} oră||În {0} ore",
    "L_RelativeDateTime_XHours": "{0} oră în urmă||{0} ore în urmă",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{0} la {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} zi de acum||{0} zile de acum",
    "L_RelativeDateTime_XDays": "{0} zi în urmă||{0} zile în urmă",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Astăzi"
  },
  "SendEmailTo": "Trimiteți un e-mail la {0}",
  "StartChatWith": "Începeți o conversație cu {0}",
  "Contact": "Contact",
  "UpdateProfile": "Actualizați-vă profilul",
  "TaxonomyPickerNoTerms": "Setul de termeni nu conține niciun",
  "TaxonomyPickerExpandTitle": "Extindeți acest set de termeni",
  "TaxonomyPickerMenuTermSet": "Meniu pentru set de termeni",
  "TaxonomyPickerInLabel": "In",
  "TaxonomyPickerTermSetLabel": "Set de termeni",
  "TaxonomyPickerTermsNotFound": "Următorul (următoarele) termen(e) selectat(e) nu a putut fi găsit(e) în depozitul de termeni: {0}",
  "TaxonomyPickerInvalidTerms": "Vă rugăm să remediați termenul ( termen) nevalid(e): {0}",
  "peoplePickerComponentTooltipMessage": "Selector persoane",
  "peoplePickerComponentErrorMessage": "Câmp obligatoriu",
  "peoplePickerSuggestionsHeaderText": "Persoane sugerate",
  "peoplePickerLoadingText": "Încărcare",
  "PeoplePickerSearchText": "Preluarea utilizatorilor",
  "PeoplePickerGroupNotFound": "Imposibil de găsit grupul.",
  "genericNoResultsFoundText": "Nu s-au găsit rezultate",
  "ListItemPickerSelectValue": "Selectare valoare",
  "ListItemAttachmentsActionDeleteIconTitle": "Şterge",
  "ListItemAttachmentsactionDeleteTitle": "Şterge",
  "ListItemAttachmentsfileDeletedMsg": "Fișier {0} șters",
  "ListItemAttachmentsfileDeleteError": "Eroare la ștergerea fișierului: {0}, motiv {1}",
  "ListItemAttachmentserrorLoadAttachments": "Eroare pe atașare element listă de încărcare, motiv: {0}",
  "ListItemAttachmentsconfirmDelete": "Sigur trimiteți atașarea {0} la Coșul de reciclare a site-ului?",
  "ListItemAttachmentsdialogTitle": "Atașare element listă",
  "ListItemAttachmentsdialogOKbuttonLabel": "ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Anula",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Şterge",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Adăugare atașare",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Adăugare atașare",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Fișierul nu {0} atașat, motiv: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Adăugare atașare",
  "ListItemAttachmentsloadingMessage": "Se încarcă fișierul...",
  "ListItemAttachmentslPlaceHolderIconText": "Atașare element listă",
  "ListItemAttachmentslPlaceHolderDescription": "Vă rugăm să adăugați atașament",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Adăugare",
  "mapsErrorMessage": "Eroare la încărcarea hărții",
  "mapsLoadingText": "Încărcare",
  "mapsSearchButtonText": "Căutaţi",
  "mapsTitlePrefix": "Harta",
  "ListViewFilterLabel": "Filtrați lista",
  "HeaderNormalText": "Text normal",
  "HeaderH2": "Titlul 2",
  "HeaderH3": "Titlu 3",
  "HeaderH4": "Rubrica 4",
  "HeaderBlockQuote": "Trage citat",
  "AlignLeft": "Aliniere la stânga",
  "AlignCenter": "Centrul",
  "AlignRight": "Aliniere la dreapta",
  "AlignJustify": "Justifica",
  "ListBullet": "Listă cu marcatori",
  "ListNumbered": "Listă numerotată",
  "StyleTitle": "Stil",
  "BoldTitle": "Bold (Ctrl + B)",
  "ItalicTitle": "Italic (Ctrl + I)",
  "UnderlineTitle": "Subliniere (Ctrl + U)",
  "AlignTitle": "Aliniaţi",
  "ListTitle": "Listă",
  "LinkTitle": "Hyperlink",
  "ImageTitle": "Imagine",
  "MoreTitle": "Mai multe",
  "FormattingPaneTitle": "Formatarea textului",
  "CloseButton": "Închide",
  "InsertLinkTitle": "Inserare legătură",
  "InsertImageTitle": "Inserare imagine",
  "AddressFieldLabel": "Adresa",
  "TextToDisplayLabel": "Text de afișat",
  "SaveButtonLabel": "Salva",
  "CancelButtonLabel": "Anula",
  "RemoveLinkLabel": "Eliminare legătură",
  "ParagraphSectionTitle": "Alineatul (",
  "HyperlinkSectionTitle": "Hyperlink",
  "UndoTitle": "Anulare (Ctrl + Z)",
  "RedoTitle": "Refacere (Ctrl + Y)",
  "ClearFormattingTitle": "Goliți toate formatele",
  "FontStyleTitle": "Stil font",
  "FontSizeTitle": "Dimensiune font",
  "StrikethroughTitle": "Tăiat",
  "SuperscriptTitle": "Exponent",
  "SubscriptTitle": "Indice",
  "FontColorLabel": "Culoare font",
  "AutomaticFontColor": "Automată",
  "HighlightColorLabel": "Evidențiere culoare",
  "NoColorHighlightColor": "Fără culoare",
  "IncreaseIndentTitle": "Mărire indent",
  "DecreaseIndentTitle": "Scădere indent",
  "ThemeColorsGroupName": "Culorile temei",
  "HighlightColorsGroupName": "Evidențiere culori",
  "StandardColorsGroupName": "Culori standard",
  "CustomColorsGroupName": "Culori particularizate",
  "ThemeColorDarker": "Tematica mai inchisa",
  "ThemeColorDark": "Temă întunecată",
  "ThemeColorDarkAlt": "Temă întuneric alternativ",
  "ThemeColorPrimary": "Tema primară",
  "ThemeColorSecondary": "Tematica secundar",
  "ThemeColorTertiary": "Terțiar neutru",
  "ThemeColorNeutralSecondary": "Secundar neutru",
  "ThemeColorNeutralPrimaryAlt": "Alternativ primar neutru",
  "ThemeColorNeutralPrimary": "Primar neutru",
  "ThemeColorNeutralDark": "Întuneric neutru",
  "HighlightColorYellow": "Galben",
  "HighlightColorGreen": "Verde",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Magenta",
  "HighlightColorBlue": "Albastru",
  "HighlightColorRed": "Roşu",
  "HighlightColorDarkblue": "Albastru închis",
  "HighlightColorTeal": "Teal",
  "HighlightColorDarkgreen": "Verde închis",
  "HighlightColorPurple": "Violet",
  "HighlightColorMaroon": "Maroon",
  "HighlightColorGold": "Aur",
  "HighlightColorDarkgrey": "Gri",
  "HighlightColorGrey": "Gri",
  "HighlightColorBlack": "Negru",
  "StandardColorDarkred": "Roșu închis",
  "StandardColorRed": "Roşu",
  "StandardColorOrange": "Portocaliu",
  "StandardColorYellow": "Galben",
  "StandardColorLightgreen": "Verde deschis",
  "StandardColorGreen": "Verde",
  "StandardColorLightblue": "Albastru deschis",
  "StandardColorBlue": "Albastru",
  "StandardColorDarkblue": "Albastru închis",
  "StandardColorPurple": "Violet",
  "DatePickerMonthLongJanuary": "Ianuarie",
  "DatePickerMonthShortJanuary": "Ianuarie",
  "DatePickerMonthLongFebruary": "Februarie",
  "DatePickerMonthShortFebruary": "Februarie",
  "DatePickerMonthLongMarch": "Martie",
  "DatePickerMonthShortMarch": "Mar",
  "DatePickerMonthLongApril": "Aprilie",
  "DatePickerMonthShortApril": "Apr",
  "DatePickerMonthLongMay": "Pot",
  "DatePickerMonthShortMay": "Pot",
  "DatePickerMonthLongJune": "Iunie",
  "DatePickerMonthShortJune": "Iun",
  "DatePickerMonthLongJuly": "Iulie",
  "DatePickerMonthShortJuly": "Iul",
  "DatePickerMonthLongAugust": "August",
  "DatePickerMonthShortAugust": "Aug",
  "DatePickerMonthLongSeptember": "Septembrie",
  "DatePickerMonthShortSeptember": "Şapte",
  "DatePickerMonthLongOctober": "Octombrie",
  "DatePickerMonthShortOctober": "Octombrie",
  "DatePickerMonthLongNovember": "Noiembrie",
  "DatePickerMonthShortNovember": "Noiembrie",
  "DatePickerMonthLongDecember": "Decembrie",
  "DatePickerMonthShortDecember": "Decembrie",
  "DatePickerDayLongSunday": "Duminică",
  "DatePickerDayShortSunday": "Dum",
  "DatePickerDayLongMonday": "Luni",
  "DatePickerDayShortMonday": "Meu",
  "DatePickerDayLongTuesday": "Marţi",
  "DatePickerDayShortTuesday": "Mar",
  "DatePickerDayLongWednesday": "Miercuri",
  "DatePickerDayShortWednesday": "Mier",
  "DatePickerDayLongThursday": "Joi",
  "DatePickerDayShortThursday": "Joi",
  "DatePickerDayLongFriday": "Vineri",
  "DatePickerDayShortFriday": "Vineri",
  "DatePickerDayLongSaturday": "Sâmbătă",
  "DatePickerDayShortSaturday": "Sâm",
  "DatePickerGoToToday": "Astăzi",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Data",
  "DateTimePickerTime": "Timp",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Valoare oră incorectă",
  "DateTimePickerMinuteValueInvalid": "Valoare incorectă a minutei",
  "DateTimePickerSecondValueInvalid": "A doua valoare incorectă",
  "DateTimePickerTextErrorMessage": "Vă rugăm să introduceți o dată validă",
  "AddFileButtonLabel": "Adăugare fișier",
  "AddImageButtonLabel": "Adăugare imagine",
  "AriaCellValue": "{0} coloană, {1}",
  "FilePickerCancelButtonLabel": "Anula",
  "CantValidateValidationMessage": "Nu am putut verifica acest link. Vă rugăm să verificați link-ul și încercați din nou.",
  "ChangeFileLinkLabel": "Modificare fișier",
  "ChangeImageLinkLabel": "Modificare imagine",
  "ChooseFileLinkLabel": "Alegere fișier",
  "ChooseImageLinkLabel": "Alege imaginea",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Sunteți responsabil pentru respectarea drepturilor celorlalți, inclusiv a dreptului de autor.",
  "CreativeCommonsMessage": "Aceste rezultate sunt etichetate cu licențe Creative Commons. Revizuiți licențele pentru a vă asigura că respectați.",
  "DateFormat": "MM/ZZ/AAAA hh: mm A",
  "DocumentLabelTemplate": "{0}, document, {1} modificat, editat de {2}, privat",
  "DocumentLibraries": "Biblioteci de documente",
  "EditedByNamePlate": "editat de ",
  "EmptyFileSize": "0 octeți",
  "FilePickerHeader": "Selector fișier",
  "FileSizeField": "Dimensiune fișier",
  "FolderAltText": "Folderul",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, pliant, {1} modificat, editat de {2}, articole {3}, privat",
  "FromLinkLinkLabel": "De la un link",
  "ImageAltText": ". {0} imagine",
  "ImageAriaLabelTemplate": ". {0} imagine",
  "ImageLayoutPlaceholderText": "Aspect",
  "ImageSizePlaceholderText": "Dimensiunea imaginii",
  "ItemChildCountField": "Contor copii articol",
  "LayoutOptionAll": "Toate",
  "LayoutOptionSquare": "Pătrat",
  "LayoutOptionTall": "Înalt",
  "LayoutOptionWide": "Largă",
  "LearnMoreLink": "află mai multe.",
  "LicenseOptionAll": "Toate",
  "LicenseOptionAny": "Creative Commons numai",
  "LicensePlaceholderText": "Licenţă",
  "LinkFileInstructions": "Lipiți un link la un fișier în OneDrive for Business sau SharePoint Online",
  "LinkHeader": "De la un link",
  "LinkImageInstructions": "Lipiți un link la o imagine în OneDrive for Business sau SharePoint Online",
  "ListLayoutAriaLabel": "Vizualizați opțiunile. {0} {1}.",
  "ListLayoutCompact": "Vizualizare compactă",
  "ListLayoutCompactDescription": "Vizualizarea elementelor și detaliilor într-o listă compactă",
  "ListLayoutList": "Vizualizare listă",
  "ListLayoutListDescrition": "Vizualizarea elementelor și detaliilor dintr-o listă",
  "ListLayoutTile": "Vizualizare dală",
  "ListLayoutTileDescription": "Vizualizarea elementelor cu examinări de țiglă",
  "ListOptionsAlt": "Vizualizați opțiunile. {0} selectată.",
  "ListOptionsTitle": "Deschiderea meniului opțiunilor de vizualizare",
  "Loading": "Încărcare...",
  "ModifiedByField": "Modificat de",
  "ModifiedField": "Data modificării",
  "NameField": "nume",
  "No": "nu",
  "ProvidedValueIsInvalid": "Valoarea furnizată nu este validă",
  "NoExternalLinksValidationMessage": "Sprijinim doar legarea la fișiere din propria organizație.",
  "NoImageValidationMessage": "Acest lucru nu este un link către un tip de fișier pe care îl sprijinim. Aveți posibilitatea să legați doar la o imagine.",
  "NoRecentFiles": "Fără fișiere recente",
  "NoRecentFilesDescription": "Încercați să selectați un fișier de pe site sau încărcați unul de pe dispozitiv.",
  "NoResultsBadEnglish": "Nu s-a găsit niciun rezultat. Încercați să modificați opțiunile de filtrare",
  "ODModifiedField": "Modificat",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, {2} modificat, editat de {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Acest element este de pe site-ul OneDrive. Fișierele și folderele din OneDrive sunt private dacă nu le partajați. Ați partajat acest fișier cu membrii site-ului dvs., astfel încât acestea să poată să-l ccess?",
  "OneDriveConfirmDialogTitle": "Doar de verificare...",
  "OneDriveEmptyFolderAlt": "Folder gol",
  "OneDriveEmptyFolderDescription": "Pentru a adăuga fișiere, accesați OneDrive. De asemenea, puteți adăuga fișiere la acest folder utilizând aplicația OneDrive pentru computer.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Acest folder este gol",
  "OneDriveRootFolderName": "Fişierele",
  "OpenButtonLabel": "Deschide",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Imagini și fișiere furnizate de organizația dvs.",
  "PoweredByBing": "Realizat de Bing",
  "RecentDocumentsHeader": "Documente recente",
  "RecentImagesHeader": "Imagini recente",
  "RecentLinkLabel": "Recentă",
  "SearchBoxPlaceholder": "Căutare pe web",
  "SearchResultAlt": "Rezultatul imaginii pentru {0}.",
  "SearchResultAriaLabel": "Apăsați Enter pentru a deschide sursa imaginii într-o filă nouă.",
  "Selected": "Selectat",
  "SharingField": "Partajare",
  "SharingPrivate": "Privat",
  "SharingShared": "Partajate",
  "SiteLinkLabel": "Site",
  "SizeOptionAll": "Toate",
  "SizeOptionExtraLarge": "Extra mare",
  "SizeOptionLarge": "Mare",
  "SizeOptionMedium": "Mediu",
  "SizeOptionSmall": "Mici",
  "SizeUnit": [
    "Octeţi",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Exemplu",
    "Yb"
  ],
  "SorryWebSearch": "Ne pare rău, această funcție nu este implementată în acest eșantion, deoarece ar necesita o cheie Bing API.",
  "SortedAscending": "Sortate la a la Z",
  "SortedDescending": "Sortare Z la A",
  "TypeAriaLabel": "Operațiuni de coloană pentru tipul de fișier, apăsați pentru a sorta pe tipul de fișier",
  "UploadFileHeader": "Încărcați fișierul",
  "UploadImageHeader": "Încărcați imaginea",
  "UploadLinkLabel": "Încărcaţi",
  "WebSearchLinkLabel": "Căutare pe web",
  "StockImagesLinkLabel": "Imagini stoc",
  "StockImagesHeader": "Imagini stoc",
  "Yes": "da",
  "NewFolderNamePlaceholder": "Introduceți numele folderului",
  "FolderFilterBoxPlaceholder": "Filtrarea folderelor după nume",
  "FolderExplorerLoading": "Încărcarea dosare...",
  "FolderExplorerNoItems": "Acest folder nu are subfoldere.",
  "NewFolderIncorrectSymbolsError": "Vă rugăm să introduceți un nume care nu include niciunul dintre aceste caractere: \" * : < > ? /  |.",
  "SomethingWentWrong": "Ceva nu a mers bine",
  "SelectedLabel": "Selectat",
  "SelectIcon": "Selectare pictogramă",
  "TreeViewExpandTitle": "Extindeți acest element",
  "TreeViewCollapseTitle": "Restrângerea acestui element",
  "CollectionDataEmptyFields": "Nu au fost furnizate câmpuri pentru datele de colectare.",
  "CollectionDataEmptyValue": "Nu există date în colecția dvs.",
  "CollectionAddRowButtonLabel": "Adăugarea datelor la colecție",
  "CollectionDeleteRowButtonLabel": "Ștergerea rândului curent",
  "CollectionSaveAndAddButtonLabel": "Adăugarea și salvarea",
  "CollectionDataItemShowErrorsLabel": "Afișarea erorilor de rând",
  "CollectionDataItemFieldRequiredLabel": "Câmpul este necesar.",
  "CollectionDataItemMissingFields": "Colecția de câmpuri este goală!",
  "InvalidUrlError": "ADRESA URL furnizată nu este validă",
  "CollectionDataSearch": "Căutare",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "încărcarea echipelor",
  "MyTeamsMessageError": "Ceva nu a mers bine în timp ce vă încărcați echipele, încercați mai târziu sau reîmprospătați browserul",
  "MyTeamsNoTeamsMessage": "Nu ai echipe",
  "MyTeamsTeamChannelPublicMessage": "Canale publice",
  "MyTeamsTeamChannelTypeMessage": "Canale private",
  "TeamChannelPickerFontIconFavoriteText": "Favorit",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Canal privat",
  "TeamChannelPickerSugestionHeaderText": "Canale de echipă sugerate",
  "TeamPickerButtonRemoveTitle": "depărta",
  "TeamPickernoResultsFoundText": "Nu s-au găsit echipe",
  "TeamPickerSugestionsHeaderText": "Echipe sugerate",
  "TeamsChannelPickerButtonRemoveTitle": "depărta",
  "TeamsChannelPickerNoresultsFoundText": "Nu s-au găsit canale",
  "ViewMore": "Vezi mai mult",
  "DynamicFormLoading": "Încărcare...",
  "DynamicFormPleaseWait": "Te rog să aştepţi...",
  "DynamicFormRequiredErrorMessage": "Nu poți lăsa acest gol.",
  "DynamicFormTermPanelTitle": "Selectați Termen",
  "DynamicFormEnterURLPlaceholder": "Introduceți o adresă URL",
  "DynamicFormEnterDescriptionPlaceholder": "Text alternativ",
  "DynamicFormDialogValidationErrorTitle": "Eroare de validatie",
  "DynamicFormDialogValidationErrorMessage": "Există erori de validare, remediați-le înainte de a salva.",
  "DynamicFormNumberValueMustBeGreaterThan": "Valoarea trebuie să fie mai mare decât {0}",
  "DynamicFormNumberValueMustBeBetween": "Valoarea trebuie să fie între {0} și {1}",
  "DynamicFormNumberValueMustBeLowerThan": "Valoarea trebuie să fie mai mică decât {0}",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Utilizați această locație:",
  "ListItemCommentDIalogDeleteSubText": "Sunteți sigur că doriți să ștergeți acest comentariu?",
  "ListItemCommentsDialogDeleteTitle": "Confirmați ștergerea comentariului",
  "ListItemCommentsLabel": "Comentarii",
  "ListItemCommentsNoCommentsLabel": "Nu există comentarii",
  "OrgAssetsLinkLabel": "Organizația dvs.",
  "MyTeamsMessageDontHaveTeams": "You don't have any teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Introduceți un termen pe care doriți să-l etichetați",
  "ModernTaxonomyPickerTreeTitleSingle": "Selectați o etichetă",
  "ModernTaxonomyPickerTreeTitleMulti": "Selectați una sau mai multe etichete",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Adaugă etichetă",
  "ModernTaxonomyPickerApplyButtonText": "Utilizați",
  "ModernTaxonomyPickerCancelButtonText": "Anulați",
  "ModernTaxonomyPickerLoadMoreText": "Aflați mai multe",
  "ModernTaxonomyPickerRemoveButtonText": "Ștergeți",
  "ModernTaxonomyPickerPanelCloseButtonText": "Închide",
  "ModernTaxonomyPickerNoResultsFound": "Nu s-au găsit rezultate",
  "ModernTaxonomyPickerSuggestionInLabel": "In",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
