declare var define: any;

define([], () => {
  return {
  "SiteBreadcrumbLabel": "Webová stránka breadcrumb",
  "ListViewGroupEmptyLabel": "Prázdne",
  "WebPartTitlePlaceholder": "Názov webovej časti",
  "WebPartTitleLabel": "Pridanie titulu",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Za niekoľko sekúnd",
    "L_RelativeDateTime_AFewSeconds": "Pred niekoľkými sekundami",
    "L_RelativeDateTime_AboutAMinuteFuture": "Asi za minútu",
    "L_RelativeDateTime_AboutAMinute": "Asi pred minútou",
    "L_RelativeDateTime_XMinutesFuture": "V {0} minute||Za {0} minút",
    "L_RelativeDateTime_XMinutes": "{0} pred minútou||{0} minútami",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
    "L_RelativeDateTime_XMinutesIntervals": "1||2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Asi za hodinu",
    "L_RelativeDateTime_AboutAnHour": "Asi pred hodinou",
    "L_RelativeDateTime_Tomorrow": "Zajtra",
    "L_RelativeDateTime_Yesterday": "Uskutočnená včera o",
    "L_RelativeDateTime_TomorrowAndTime": "Zajtra v {0}",
    "L_RelativeDateTime_YesterdayAndTime": "Včera na {0}",
    "L_RelativeDateTime_XHoursFuture": "Za {0} hodinu||V {0} hodín",
    "L_RelativeDateTime_XHours": "{0} pred hodinou||{0} hodín pred",
    "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
    "L_RelativeDateTime_XHoursIntervals": "1||2-",
    "L_RelativeDateTime_DayAndTime": "{0} zariadení {1}",
    "L_RelativeDateTime_XDaysFuture": "{0} deň od teraz||{0} dní od teraz",
    "L_RelativeDateTime_XDays": "{0} deň dozadu||{0} pred dňami",
    "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
    "L_RelativeDateTime_XDaysIntervals": "1||2-",
    "L_RelativeDateTime_Today": "Uskutočnená dnes o"
  },
  "SendEmailTo": "Pošlite e-mail na {0}",
  "StartChatWith": "Spustenie rozhovoru s {0}",
  "Contact": "Kontakt",
  "UpdateProfile": "Aktualizujte svoj profil",
  "TaxonomyPickerNoTerms": "Množina výrazov neobsahuje žiadne výrazy",
  "TaxonomyPickerExpandTitle": "Rozbaliť túto množinu výrazov",
  "TaxonomyPickerMenuTermSet": "Menu pre množinu výrazov",
  "TaxonomyPickerInLabel": "Palcov",
  "TaxonomyPickerTermSetLabel": "Množina výrazov",
  "peoplePickerComponentTooltipMessage": "Výber ľudí",
  "peoplePickerComponentErrorMessage": "Povinné pole",
  "peoplePickerSuggestionsHeaderText": "Navrhovaných ľudí",
  "peoplePickerLoadingText": "Nakládky",
  "PeoplePickerSearchText": "Načítavajú sa používatelia",
  "PeoplePickerGroupNotFound": "Skupina sa nenašla.",
  "genericNoResultsFoundText": "Nenašli sa žiadne výsledky",
  "ListItemPickerSelectValue": "Vybrať hodnotu",
  "ListItemAttachmentsActionDeleteIconTitle": "Odstrániť",
  "ListItemAttachmentsactionDeleteTitle": "Odstrániť",
  "ListItemAttachmentsfileDeletedMsg": "Súbor {0} odstránený",
  "ListItemAttachmentsfileDeleteError": "Chyba pri odstránení súboru: {0}, dôvod {1}",
  "ListItemAttachmentserrorLoadAttachments": "Chyba pri načítaní prílohy položky zoznamu, dôvod: {0}",
  "ListItemAttachmentsconfirmDelete": "Naozaj chcete odoslať prílohu {0} do Koša lokality?",
  "ListItemAttachmentsdialogTitle": "Príloha položky zoznamu",
  "ListItemAttachmentsdialogOKbuttonLabel": "ok",
  "ListItemAttachmentsdialogCancelButtonLabel": "Zrušiť",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Odstrániť",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Pridať prílohu",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Pridať prílohu",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Súbor {0} nie je priložený, dôvod: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Pridať prílohu",
  "ListItemAttachmentsloadingMessage": "Nahráva sa súbor...",
  "ListItemAttachmentslPlaceHolderIconText": "Príloha položky zoznamu",
  "ListItemAttachmentslPlaceHolderDescription": "Prosím, pridajte prílohu",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Pridať",
  "mapsErrorMessage": "Počas načítania mapy sa vyskytla chyba",
  "mapsLoadingText": "Nakládky",
  "mapsSearchButtonText": "Hľadať",
  "mapsTitlePrefix": "Mapa mesta",
  "ListViewFilterLabel": "Filtrovanie zoznamu",
  "HeaderNormalText": "Normálny text",
  "HeaderH2": "Okruh 1",
  "HeaderH3": "Okruh 2",
  "HeaderH4": "Okruh 3",
  "HeaderBlockQuote": "Pull Citácia",
  "AlignLeft": "Zarovnať doľava",
  "AlignCenter": "Centrum",
  "AlignRight": "Zarovnať doprava",
  "AlignJustify": "Odôvodniť",
  "ListBullet": "Zoznam s odrážkami",
  "ListNumbered": "Číslovaný zoznam",
  "StyleTitle": "Štýl",
  "BoldTitle": "Tučné (Ctrl + B)",
  "ItalicTitle": "Kurzíva (Ctrl + I)",
  "UnderlineTitle": "Podčiarknutie (Ctrl + U)",
  "AlignTitle": "Zarovnať",
  "ListTitle": "Zoznam",
  "LinkTitle": "Hypertextové prepojenie",
  "MoreTitle": "Viac",
  "FormattingPaneTitle": "Formátovanie textu",
  "CloseButton": "Zatvorte",
  "InsertLinkTitle": "Vložiť prepojenie",
  "AddressFieldLabel": "Adresu",
  "TextToDisplayLabel": "Text, ktorý sa má zobraziť",
  "SaveButtonLabel": "Uložiť",
  "CancelButtonLabel": "Zrušiť",
  "RemoveLinkLabel": "Odstrániť prepojenie",
  "ParagraphSectionTitle": "Odseku",
  "HyperlinkSectionTitle": "Hypertextové prepojenie",
  "UndoTitle": "Späť (Ctrl + Z)",
  "RedoTitle": "Znova (Ctrl + Y)",
  "ClearFormattingTitle": "Vymazať všetko formátovanie",
  "FontStyleTitle": "Štýl písma",
  "FontSizeTitle": "Veľkosť písma",
  "StrikethroughTitle": "Prečiarknutie",
  "SuperscriptTitle": "Horný index",
  "SubscriptTitle": "Dolný index",
  "FontColorLabel": "Farba písma",
  "AutomaticFontColor": "Automatické",
  "HighlightColorLabel": "Farba zvýraznenia",
  "NoColorHighlightColor": "Bez farby",
  "IncreaseIndentTitle": "Zväčšiť zarážku",
  "DecreaseIndentTitle": "Zmenšiť zarážku",
  "ThemeColorsGroupName": "Farby motívu",
  "HighlightColorsGroupName": "Zvýrazniť farby",
  "StandardColorsGroupName": "Štandardné farby",
  "CustomColorsGroupName": "Vlastné farby",
  "ThemeColorDarker": "Téma tmavšie",
  "ThemeColorDark": "Tematický motív",
  "ThemeColorDarkAlt": "Motív tmavý náhradník",
  "ThemeColorPrimary": "Téma primárne",
  "ThemeColorSecondary": "Téma sekundárne",
  "ThemeColorTertiary": "Neutrálne terciárne",
  "ThemeColorNeutralSecondary": "Neutrálne sekundárne",
  "ThemeColorNeutralPrimaryAlt": "Neutrálny primárny náhradník",
  "ThemeColorNeutralPrimary": "Neutrálne primárne",
  "ThemeColorNeutralDark": "Neutrálna tmavá",
  "HighlightColorYellow": "Žlté",
  "HighlightColorGreen": "Zelená",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Purpurová",
  "HighlightColorBlue": "Blue",
  "HighlightColorRed": "Červené",
  "HighlightColorDarkblue": "Tmavo modré",
  "HighlightColorTeal": "Teal",
  "HighlightColorDarkgreen": "Tmavozelená",
  "HighlightColorPurple": "Fialová",
  "HighlightColorMaroon": "Maroon",
  "HighlightColorGold": "Zlato",
  "HighlightColorDarkgrey": "Tmavošedá",
  "HighlightColorGrey": "Šedá",
  "HighlightColorBlack": "Čierna",
  "StandardColorDarkred": "Tmavo červená",
  "StandardColorRed": "Červené",
  "StandardColorOrange": "Oranžová",
  "StandardColorYellow": "Žlté",
  "StandardColorLightgreen": "Svetlozelená",
  "StandardColorGreen": "Zelená",
  "StandardColorLightblue": "Svetlo modrá",
  "StandardColorBlue": "Blue",
  "StandardColorDarkblue": "Tmavo modré",
  "StandardColorPurple": "Fialová",
  "DatePickerMonthLongJanuary": "Januári",
  "DatePickerMonthShortJanuary": "Január",
  "DatePickerMonthLongFebruary": "Februári",
  "DatePickerMonthShortFebruary": "Február",
  "DatePickerMonthLongMarch": "Marca",
  "DatePickerMonthShortMarch": "Mar",
  "DatePickerMonthLongApril": "Apríli",
  "DatePickerMonthShortApril": "Apríla",
  "DatePickerMonthLongMay": "Môže",
  "DatePickerMonthShortMay": "Môže",
  "DatePickerMonthLongJune": "Júni",
  "DatePickerMonthShortJune": "Júna",
  "DatePickerMonthLongJuly": "Júli",
  "DatePickerMonthShortJuly": "Júl",
  "DatePickerMonthLongAugust": "Auguste",
  "DatePickerMonthShortAugust": "Augusta",
  "DatePickerMonthLongSeptember": "Septembra",
  "DatePickerMonthShortSeptember": "Sedem",
  "DatePickerMonthLongOctober": "Októbri",
  "DatePickerMonthShortOctober": "Október",
  "DatePickerMonthLongNovember": "Novembri",
  "DatePickerMonthShortNovember": "Novembra",
  "DatePickerMonthLongDecember": "Decembri",
  "DatePickerMonthShortDecember": "Decembra",
  "DatePickerDayLongSunday": "Nedeľu",
  "DatePickerDayShortSunday": "Slnko",
  "DatePickerDayLongMonday": "Pondelok",
  "DatePickerDayShortMonday": "Môj",
  "DatePickerDayLongTuesday": "Utorok",
  "DatePickerDayShortTuesday": "Tue",
  "DatePickerDayLongWednesday": "Stredu",
  "DatePickerDayShortWednesday": "St",
  "DatePickerDayLongThursday": "Štvrtok",
  "DatePickerDayShortThursday": "Št",
  "DatePickerDayLongFriday": "Piatok",
  "DatePickerDayShortFriday": "Pi",
  "DatePickerDayLongSaturday": "Sobotu",
  "DatePickerDayShortSaturday": "Sedel",
  "DatePickerGoToToday": "Uskutočnená dnes o",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Dátum",
  "DateTimePickerTime": "Čas",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Nesprávna hodinová hodnota",
  "AddFileButtonLabel": "Pridať súbor",
  "AddImageButtonLabel": "Pridať obrázok",
  "AriaCellValue": "{0} stĺpci {1}",
  "FilePickerCancelButtonLabel": "Zrušiť",
  "CantValidateValidationMessage": "Nemohli sme overiť tento odkaz. Skontrolujte prosím odkaz a skúste to znova.",
  "ChangeFileLinkLabel": "Zmeniť súbor",
  "ChangeImageLinkLabel": "Zmeniť obrázok",
  "ChooseFileLinkLabel": "Vyberte súbor",
  "ChooseImageLinkLabel": "Vyberte obrázok",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Zodpovedáte za rešpektovanie práv ostatných, vrátane autorských práv.",
  "CreativeCommonsMessage": "Tieto výsledky sú označené licenciou Creative Commons. Skontrolujte licencie, aby ste zaistili súlad.",
  "DateFormat": "MM/DD/rrrr hh: mm A",
  "DocumentLabelTemplate": "{0}, dokument, upravený {1}, editovaný {2}, súkromný",
  "DocumentLibraries": "Knižnice dokumentov",
  "EditedByNamePlate": "editoval ",
  "EmptyFileSize": "0 bajtov",
  "FilePickerHeader": "Výber súboru",
  "FileSizeField": "Veľkosť súboru",
  "FolderAltText": "Priečinok",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, priečinok, upravený {1}, editovaný {2}, {3} položky, súkromné",
  "FromLinkLinkLabel": "Z odkazu",
  "ImageAltText": ". {0} obrázok",
  "ImageAriaLabelTemplate": ". {0} obrázok",
  "ImageLayoutPlaceholderText": "Rozloženie",
  "ImageSizePlaceholderText": "Veľkosť obrázka",
  "ItemChildCountField": "Počet podradených položiek tovaru",
  "LayoutOptionAll": "Všetky",
  "LayoutOptionSquare": "Námestie",
  "LayoutOptionTall": "Vysoký",
  "LayoutOptionWide": "Široký",
  "LearnMoreLink": "zistiť viac.",
  "LicenseOptionAll": "Všetky",
  "LicenseOptionAny": "Len Creative Commons",
  "LicensePlaceholderText": "Licencie",
  "LinkFileInstructions": "Prilepenie prepojenia na súbor v službe OneDrive for Business alebo SharePoint Online",
  "LinkHeader": "Z odkazu",
  "LinkImageInstructions": "Prilepenie prepojenia na obrázok v službe OneDrive for Business alebo SharePoint Online",
  "ListLayoutAriaLabel": "Možnosti zobrazenia. {0} {1}.",
  "ListLayoutCompact": "Kompaktný pohľad",
  "ListLayoutCompactDescription": "Zobrazenie položiek a podrobností v kompaktnom zozname",
  "ListLayoutList": "Zobrazenie zoznamu",
  "ListLayoutListDescrition": "Zobrazenie položiek a podrobností v zozname",
  "ListLayoutTile": "Zobrazenie dlaždíc",
  "ListLayoutTileDescription": "Zobrazenie položiek pomocou ukážok dlaždíc",
  "ListOptionsAlt": "Možnosti zobrazenia. {0} vybraté.",
  "ListOptionsTitle": "Otvorenie ponuky Zobraziť možnosti",
  "Loading": "Nakládky...",
  "ModifiedByField": "Upravený",
  "ModifiedField": "Dátum úpravy",
  "NameField": "meno",
  "No": "nie",
  "ProvidedValueIsInvalid": "Poskytnutá hodnota je neplatná",
  "NoExternalLinksValidationMessage": "Podporujeme len prepojenie na súbory vo vašej vlastnej organizácii.",
  "NoImageValidationMessage": "Toto nie je odkaz na typ súboru, ktorý podporujeme. Môžete odkazovať len na obrázok.",
  "NoRecentFiles": "Žiadne nedávne súbory",
  "NoRecentFilesDescription": "Skúste vybrať súbor z webu alebo ho nahrajte zo zariadenia.",
  "NoResultsBadEnglish": "Neexistuje žiadny výsledok nájdený. Pokúste sa zmeniť možnosti filtra",
  "ODModifiedField": "Upravené",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, upravené {2}, editované {3}, {4}, {5}",
  "OneDriveConfirmDialogBody": "Táto položka je z lokality OneDrive. Súbory a priečinky v službe OneDrive sú súkromné, pokiaľ ich nezdieľate. Zdieľali ste tento súbor s členmi vašej stránky, aby mohli rístup to?",
  "OneDriveConfirmDialogTitle": "Len kontrola...",
  "OneDriveEmptyFolderAlt": "Prázdny priečinok",
  "OneDriveEmptyFolderDescription": "Ak chcete pridať súbory, prejdite do svojho OneDrivu. Do tohto priečinka môžete pridať aj súbory pomocou aplikácie OneDrive pre váš počítač.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Tento priečinok je prázdny",
  "OneDriveRootFolderName": "Súbory",
  "OpenButtonLabel": "Otvoriť",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Obrázky a súbory, ktoré poskytuje vaša organizácia",
  "PoweredByBing": "Poháňané Bing",
  "RecentDocumentsHeader": "Nedávne dokumenty",
  "RecentImagesHeader": "Nedávne obrázky",
  "RecentLinkLabel": "Nedávne",
  "SearchBoxPlaceholder": "Vyhľadávanie na webe",
  "SearchResultAlt": "Výsledok obrázka pre {0}.",
  "SearchResultAriaLabel": "Stlačením klávesu Enter otvoríte zdroj obrazu na novej karte.",
  "Selected": "Vybrané",
  "SharingField": "Zdieľanie",
  "SharingPrivate": "Súkromné",
  "SharingShared": "Zdieľané",
  "SiteLinkLabel": "Stránky",
  "SizeOptionAll": "Všetky",
  "SizeOptionExtraLarge": "Extra veľká",
  "SizeOptionLarge": "Veľké",
  "SizeOptionMedium": "Stredné",
  "SizeOptionSmall": "Malé",
  "SizeUnit": [
    "Bajtov",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Napr",
    "YB"
  ],
  "SorryWebSearch": "Ospravedlňujeme sa, táto funkcia nie je implementovaná v tejto vzorke, pretože to by vyžadovalo Bing API kľúč.",
  "SortedAscending": "Zoradené do Z",
  "SortedDescending": "Zoradené Z na",
  "TypeAriaLabel": "Operácie stĺpcov pre typ súboru, stlačte na zoradenie na typ súboru",
  "UploadFileHeader": "Nahrať súbor",
  "UploadImageHeader": "Nahrať obrázok",
  "UploadLinkLabel": "Nahrať",
  "WebSearchLinkLabel": "Vyhľadávanie na webe",
  "Yes": "áno"
};
});