declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Menu',

    'ListViewGroupEmptyLabel': 'Prázdne',

    'WebPartTitlePlaceholder': 'Nadpis',
    'WebPartTitleLabel': 'Pridať nádpis',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Za pár sekúnd",
      "L_RelativeDateTime_AFewSeconds": "Pred pár sekundami",
      "L_RelativeDateTime_AboutAMinuteFuture": "Za minútku",
      "L_RelativeDateTime_AboutAMinute": "Pre minútou",
      "L_RelativeDateTime_XMinutesFuture": "Za {0} minútu||Za {0} minúty",
      "L_RelativeDateTime_XMinutes": "Pred {0} minútou||Pred {0} minútami",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Za hodinu",
      "L_RelativeDateTime_AboutAnHour": "Pred hodinou",
      "L_RelativeDateTime_Tomorrow": "Zajtra",
      "L_RelativeDateTime_Yesterday": "Včera",
      "L_RelativeDateTime_TomorrowAndTime": "Zajtra o {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Včera o {0}",
      "L_RelativeDateTime_XHoursFuture": "Za {0} hodinu||Za {0} hodín",
      "L_RelativeDateTime_XHours": "Pred {0} hodinou||Pred {0} hodinami",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} o {1}",
      "L_RelativeDateTime_XDaysFuture": "Za {0} deň||Za {0} dni",
      "L_RelativeDateTime_XDays": "Pred {0} dňom||Pred {0} dňami",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Dnes"
    },
    "SendEmailTo": "Poslať email na adresu {0}",
    "StartChatWith": "Začať chat s {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Aktualizovať profil",

    "TaxonomyPickerNoTerms": "Množina výrazov neobsahuje žiadny výraz",
    "TaxonomyPickerExpandTitle": "Rozbaliť množinu výrazov",
    "TaxonomyPickerMenuTermSet": "Menu pre množinu výrazov",
    "TaxonomyPickerInLabel": "v",
    "TaxonomyPickerTermSetLabel": "Množina výrazov",

    peoplePickerComponentTooltipMessage: "Výber osoby",
    peoplePickerComponentErrorMessage: "Povinný atribút",
    peoplePickerSuggestionsHeaderText: 'Navrhovaní ľudia',
    peoplePickerLoadingText: 'Nahrávanie',
    PeoplePickerSearchText: 'Načítavajú sa používatelia',
    PeoplePickerGroupNotFound: "Skupina sa nenašla.",

    genericNoResultsFoundText: 'Nenašli sa žiadne výsledky',

    ListItemPickerSelectValue: 'Vyberte hodnotu',
    ListItemAttachmentsActionDeleteIconTitle: 'Vymazať',
    ListItemAttachmentsactionDeleteTitle: 'Vymazať',
    ListItemAttachmentsfileDeletedMsg: 'Súbor {0} bol vymazaný',
    ListItemAttachmentsfileDeleteError: 'Chyba pri mazaní súboru: {0}, dôvod {1}',
    ListItemAttachmentserrorLoadAttachments: 'Chyba pri načítaní prílohy záznamu, dôvod: {0}',
    ListItemAttachmentsconfirmDelete: 'Ste si istý, že chcete prílohu {0} poslať do koša?',
    ListItemAttachmentsdialogTitle: 'Príloha záznamu',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Zrušiť',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Vymazať',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Pridať prílohu',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Pridať prílohu',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Súbor {0} nebol priložený, dôvod: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Pridať prílohu',
    ListItemAttachmentsloadingMessage: 'Nahrávanie súboru ...',
    ListItemAttachmentslPlaceHolderIconText: 'Príloha záznamu',
    ListItemAttachmentslPlaceHolderDescription: 'Prosím vložte prílohu',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Pridať',

    mapsErrorMessage: 'Vyskytla sa chyba pri nahrávaní mapy',
    mapsLoadingText: 'Nahrávanie',
    mapsSearchButtonText: 'Hľadať',
    mapsTitlePrefix: 'Mapa ',

    ListViewFilterLabel: "Filtrovať zoznam",

    HeaderNormalText: "Normálny text",
    HeaderH2: "Nádpis 1",
    HeaderH3: "Nádpis 2",
    HeaderH4: "Nádpis 3",
    HeaderBlockQuote: "Pull quote",
    AlignLeft: "Zarovnať vľavo",
    AlignCenter: "Zarovnať do stredu",
    AlignRight: "Zarovnať vpravo",
    AlignJustify: "Justify",
    ListBullet: "Bulleted list",
    ListNumbered: "Numbered list",
    StyleTitle: "Štýl",
    BoldTitle: "Bold (Ctrl+B)",
    ItalicTitle: "Italic (Ctrl+I)",
    UnderlineTitle: "Underline (Ctrl+U)",
    AlignTitle: "Align",
    ListTitle: "List",
    LinkTitle: "Hyperlink",
    MoreTitle: "More",
    FormattingPaneTitle: "Text formatting",
    CloseButton: "Close",
    InsertLinkTitle: "Insert link",
    AddressFieldLabel: "Address",
    TextToDisplayLabel: "Text to display",
    SaveButtonLabel: "Save",
    CancelButtonLabel: "Cancel",
    RemoveLinkLabel: "Remove link",
    ParagraphSectionTitle: "Paragraph",
    HyperlinkSectionTitle: "Hyperlink",
    UndoTitle: "Undo (Ctrl+Z)",
    RedoTitle: "Redo (Ctrl+Y)",
    ClearFormattingTitle: "Clear all formatting",
    FontStyleTitle: "Font style",
    FontSizeTitle: "Font size",
    StrikethroughTitle: "Strikethrough",
    SuperscriptTitle: "Superscript",
    SubscriptTitle: "Subscript",
    FontColorLabel: "Font Color",
    AutomaticFontColor: "Automatic",
    HighlightColorLabel: "Highlight color",
    NoColorHighlightColor: "No color",
    IncreaseIndentTitle: "Increase indent",
    DecreaseIndentTitle: "Decrease indent",
    ThemeColorsGroupName: "Theme colors",
    HighlightColorsGroupName: "Highlight colors",
    StandardColorsGroupName: "Standard colors",
    CustomColorsGroupName: "Custom Colors",
    ThemeColorDarker: "Theme darker",
    ThemeColorDark: "Theme dark",
    ThemeColorDarkAlt: "Theme dark alternate",
    ThemeColorPrimary: "Theme primary",
    ThemeColorSecondary: "Theme secondary",
    ThemeColorTertiary: "Neutral tertiary",
    ThemeColorNeutralSecondary: "Neutral secondary",
    ThemeColorNeutralPrimaryAlt: "Neutral primary alternate",
    ThemeColorNeutralPrimary: "Neutral primary",
    ThemeColorNeutralDark: "Neutral dark",
    HighlightColorYellow: "Yellow",
    HighlightColorGreen: "Green",
    HighlightColorAqua: "Aqua",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Blue",
    HighlightColorRed: "Red",
    HighlightColorDarkblue: "Dark blue",
    HighlightColorTeal: "Teal",
    HighlightColorDarkgreen: "Dark green",
    HighlightColorPurple: "Purple",
    HighlightColorMaroon: "Maroon",
    HighlightColorGold: "Gold",
    HighlightColorDarkgrey: "Dark grey",
    HighlightColorGrey: "Grey",
    HighlightColorBlack: "Black",
    StandardColorDarkred: "Dark red",
    StandardColorRed: "Red",
    StandardColorOrange: "Orange",
    StandardColorYellow: "Yellow",
    StandardColorLightgreen: "Light green",
    StandardColorGreen: "Green",
    StandardColorLightblue: "Light blue",
    StandardColorBlue: "Blue",
    StandardColorDarkblue: "Dark blue",
    StandardColorPurple: "Purple",

    DatePickerMonthLongJanuary: "Január",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Február",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Marec",
    DatePickerMonthShortMarch: "Mar",
    DatePickerMonthLongApril: "Apríl",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Máj",
    DatePickerMonthShortMay: "Máj",
    DatePickerMonthLongJune: "Jún",
    DatePickerMonthShortJune: "Jún",
    DatePickerMonthLongJuly: "Júl",
    DatePickerMonthShortJuly: "Júl",
    DatePickerMonthLongAugust: "August",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sept",
    DatePickerMonthLongOctober: "Október",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Nedeľa",
    DatePickerDayShortSunday: "Ned",
    DatePickerDayLongMonday: "Pondelok",
    DatePickerDayShortMonday: "Pon",
    DatePickerDayLongTuesday: "Utorok",
    DatePickerDayShortTuesday: "Uto",
    DatePickerDayLongWednesday: "Streda",
    DatePickerDayShortWednesday: "Str",
    DatePickerDayLongThursday: "Štvrtok",
    DatePickerDayShortThursday: "Štv",
    DatePickerDayLongFriday: "Piatok",
    DatePickerDayShortFriday: "Pia",
    DatePickerDayLongSaturday: "Sobota",
    DatePickerDayShortSaturday: "Sob",
    DatePickerGoToToday: "Dnes",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Dátum",
    DateTimePickerTime: "Čas",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Nesprávna hodnota hodín",

    AddFileButtonLabel: "Pridať súbor",
    AddImageButtonLabel: "Pridať obrázok",
    AriaCellValue: "{0} stĺpec, {1}",
    FilePickerCancelButtonLabel: "Zrušiť",
    CantValidateValidationMessage: "Nepodarilo sa overiť odkaz. Prosím skontrolujte odkaz a vyskšajte znova.",
    ChangeFileLinkLabel: "Zmeniť súbor",
    ChangeImageLinkLabel: "Zmeniť obrázok",
    ChooseFileLinkLabel: "Vybrať súbor",
    ChooseImageLinkLabel: "Vybrať obrázok",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, dokument, Upravený {1}, upravený {2}, Súkromný",
    DocumentLibraries: "Dokumentová knižnica",
    EditedByNamePlate: "upravené ",
    EmptyFileSize: "0 bajtov",
    FilePickerHeader: "Výber súboru",
    FileSizeField: "Veľkosť súboru",
    FolderAltText: "Priečinok",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "Nie",
    ProvidedValueIsInvalid: "Poskytnutá hodnota je neplatná",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Prázdny priečinok",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Tento priečinok je prázdny",
    OneDriveRootFolderName: "Súbory",
    OpenButtonLabel: "Otvoriť",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Obrázky a súbory organizácie.",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Posledné dokumenty",
    RecentImagesHeader: "Posledné obrázky",
    RecentLinkLabel: "Posledné",
    SearchBoxPlaceholder: "Hľadanie na internete",
    SearchResultAlt: "Obrázok výsledku pre {0}.",
    SearchResultAriaLabel: "Stlačte enter pre otvorenie obrázku v novej záložke.",
    Selected: "vybraný",
    SharingField: "Zdieľať",
    SharingPrivate: "Súkromné",
    SharingShared: "Zdieľané",
    SiteLinkLabel: "Stránka",
    SizeOptionAll: "Všetko",
    SizeOptionExtraLarge: "Exra Veľký",
    SizeOptionLarge: "Veľký",
    SizeOptionMedium: "Stredný",
    SizeOptionSmall: "Malý",
    SizeUnit: [
     "bajtov",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Ospravedlňujeme sa, táto funkcia nie je implementovaná.",
    SortedAscending: "Zoradené od A po Z",
    SortedDescending: "Zoradené od Z po A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Nahrať súbor",
    UploadImageHeader: "Nahrať obrázok",
    UploadLinkLabel: "Nahrať",
    WebSearchLinkLabel: "Hľadať na internte",
    Yes: "Áno"
  };
});