declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Brödsmulemeny',

    'ListViewGroupEmptyLabel': 'Tom',

    'WebPartTitlePlaceholder': 'Webbdelstitel',
    'WebPartTitleLabel': 'Ange titel',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Om några sekunder",
      "L_RelativeDateTime_AFewSeconds": "För några sekunder sedan",
      "L_RelativeDateTime_AboutAMinuteFuture": "Om ungefär en minut",
      "L_RelativeDateTime_AboutAMinute": "För ungefär en minut sedan",
      "L_RelativeDateTime_XMinutesFuture": "Om {0} minut||Om {0} minuter",
      "L_RelativeDateTime_XMinutes": "För {0} minut sedan||För {0} minuter sedan",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Om ungefär en timme",
      "L_RelativeDateTime_AboutAnHour": "För ungefär en timme sedan",
      "L_RelativeDateTime_Tomorrow": "Imorgon",
      "L_RelativeDateTime_Yesterday": "Igår",
      "L_RelativeDateTime_TomorrowAndTime": "Imorgon vid {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Igår vid {0}",
      "L_RelativeDateTime_XHoursFuture": "Om {0} timme||Om {0} timmar",
      "L_RelativeDateTime_XHours": "För {0} timme sedan||För {0} timmar sedan",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} at {1}",
      "L_RelativeDateTime_XDaysFuture": "Om {0} dag||Om {0} dagar",
      "L_RelativeDateTime_XDays": "För {0} dag sedan||För {0} dagar sedan",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Idag"
    },
    "SendEmailTo": "Skicka epost till {0}",
    "StartChatWith": "Börja en chat med {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Uppdatera din profil",

    "TaxonomyPickerNoTerms": "Termuppsättningen innehåller inga termer",
    "TaxonomyPickerExpandTitle": "Expandera termuppsättningen",
    "TaxonomyPickerMenuTermSet": "Meny för termuppsättning",
    "TaxonomyPickerInLabel": "I",
    "TaxonomyPickerTermSetLabel": "Termuppsättning",

    peoplePickerComponentTooltipMessage: "Personväljare",
    peoplePickerComponentErrorMessage: "Obligatoriskt fält",
    peoplePickerSuggestionsHeaderText: 'Föreslagna personer',
    peoplePickerLoadingText: 'Laddar',
    PeoplePickerSearchText: 'Hämtar användare',
    PeoplePickerGroupNotFound: "Gruppen kunde inte hittas.",

    genericNoResultsFoundText: 'Inga sökträffar',

    ListItemPickerSelectValue: 'Ange ett värde',
    ListItemAttachmentsActionDeleteIconTitle: 'Ta bort',
    ListItemAttachmentsactionDeleteTitle: 'Ta bort',
    ListItemAttachmentsfileDeletedMsg: 'Filen {0} raderades',
    ListItemAttachmentsfileDeleteError: 'Fel vid radering av fil: {0}, orsak {1}',
    ListItemAttachmentserrorLoadAttachments: 'Fel vid laddning av bilaga, orsak: {0}',
    ListItemAttachmentsconfirmDelete: 'Vill du verkligen flytta bilagan {0} till papperskorgen?',
    ListItemAttachmentsdialogTitle: 'Bilaga',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Avbryt',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Ta bort',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Lägg till bilaga',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Lägg till bilaga',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Filen {0} kunde inte bifogas, orsak: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Lägg till bilaga',
    ListItemAttachmentsloadingMessage: 'Laddar upp filen...',
    ListItemAttachmentslPlaceHolderIconText: 'Bilaga',
    ListItemAttachmentslPlaceHolderDescription: 'Lägg till en bilaga',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Lägg till',

    mapsErrorMessage: 'Ett fel uppstod vid laddning av kartan',
    mapsLoadingText: 'Laddar',
    mapsSearchButtonText: 'Sök',
    mapsTitlePrefix: 'Karta över',

    ListViewFilterLabel: "Filtrera listan",

    HeaderNormalText: "Normal text",
    HeaderH2: "Rubrik 1",
    HeaderH3: "Rubrik 2",
    HeaderH4: "Rubrik 3",
    HeaderBlockQuote: "Pull quote",
    AlignLeft: "Vänsterjustera",
    AlignCenter: "Centrera",
    AlignRight: "Högerjustera",
    AlignJustify: "Justify",
    ListBullet: "Punktlista",
    ListNumbered: "Numrerad lista",
    StyleTitle: "Style",
    BoldTitle: "Fet (Ctrl+B)",
    ItalicTitle: "Kursiv (Ctrl+I)",
    UnderlineTitle: "Understruken (Ctrl+U)",
    AlignTitle: "Justera",
    ListTitle: "Lista",
    LinkTitle: "Hyperlänk",
    MoreTitle: "Mer",
    FormattingPaneTitle: "Textformatering",
    CloseButton: "Stäng",
    InsertLinkTitle: "Infoga länk",
    AddressFieldLabel: "Adress",
    TextToDisplayLabel: "Visningstext",
    SaveButtonLabel: "Spara",
    CancelButtonLabel: "Avbryt",
    RemoveLinkLabel: "Ta bort länk",
    ParagraphSectionTitle: "Stycke",
    HyperlinkSectionTitle: "Hyperlänk",
    UndoTitle: "Ångra (Ctrl+Z)",
    RedoTitle: "Redo (Ctrl+Y)",
    ClearFormattingTitle: "Rensa all formatering",
    FontStyleTitle: "Font",
    FontSizeTitle: "Fontstorlek ",
    StrikethroughTitle: "Genomstruken",
    SuperscriptTitle: "Upphöjt",
    SubscriptTitle: "Nedsänkt",
    FontColorLabel: "Textfärg",
    AutomaticFontColor: "Automatisk",
    HighlightColorLabel: "Framhävd färg",
    NoColorHighlightColor: "Ingen färg",
    IncreaseIndentTitle: "Öka indentering",
    DecreaseIndentTitle: "Minska indentering",
    ThemeColorsGroupName: "Temafärger",
    HighlightColorsGroupName: "Framhävda färger",
    StandardColorsGroupName: "Standardfärger",
    ThemeColorDarker: "Mörkare tema",
    ThemeColorDark: "Mörkt tema",
    ThemeColorDarkAlt: "Mörkt alternativt tema",
    ThemeColorPrimary: "Primärt tema",
    ThemeColorSecondary: "Andrahandstema",
    ThemeColorTertiary: "Neutralt tredjeval",
    ThemeColorNeutralSecondary: "Neutralt andrahandsval",
    ThemeColorNeutralPrimaryAlt: "Neutralt primärt alternativ",
    ThemeColorNeutralPrimary: "Neutralt primärt",
    ThemeColorNeutralDark: "Neutralt mörkt",
    HighlightColorYellow: "Gul",
    HighlightColorGreen: "Grön",
    HighlightColorAqua: "Vatten",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Blå",
    HighlightColorRed: "Röd",
    HighlightColorDarkblue: "Mörkblå",
    HighlightColorTeal: "Beige",
    HighlightColorDarkgreen: "Mörkgrön",
    HighlightColorPurple: "Lila",
    HighlightColorMaroon: "Brun",
    HighlightColorGold: "Guld",
    HighlightColorDarkgrey: "Mörkgrå",
    HighlightColorGrey: "Grå",
    HighlightColorBlack: "Svart",
    StandardColorDarkred:"Mörkröd",
    StandardColorRed:"Röd",
    StandardColorOrange:"Orange",
    StandardColorYellow:"Gul",
    StandardColorLightgreen:"Ljusgrön",
    StandardColorGreen:"Grönn",
    StandardColorLightblue:"Ljusblå",
    StandardColorBlue:"Blå",
    StandardColorDarkblue:"Mörkblå",
    StandardColorPurple:"Lila",

    DatePickerMonthLongJanuary: "Januari",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Februari",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Mars",
    DatePickerMonthShortMarch: "Mar",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Maj",
    DatePickerMonthShortMay: "Maj",
    DatePickerMonthLongJune: "Juni",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "Juli",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "Augusti",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sep",
    DatePickerMonthLongOctober: "Oktober",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Söndag",
    DatePickerDayShortSunday: "Sön",
    DatePickerDayLongMonday: "Månday",
    DatePickerDayShortMonday: "Mån",
    DatePickerDayLongTuesday: "Tisday",
    DatePickerDayShortTuesday: "Tis",
    DatePickerDayLongWednesday: "Onsday",
    DatePickerDayShortWednesday: "Ons",
    DatePickerDayLongThursday: "Torsday",
    DatePickerDayShortThursday: "Tor",
    DatePickerDayLongFriday: "Fredag",
    DatePickerDayShortFriday: "Fre",
    DatePickerDayLongSaturday: "Lörday",
    DatePickerDayShortSaturday: "Lör",
    DatePickerGoToToday: "Idag",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Datum",
    DateTimePickerTime: "Tid",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Ogiltigt timvärde",

    AddFileButtonLabel: "Add file",
    AddImageButtonLabel: "Add image",
    AriaCellValue: "{0} column, {1}",
    FilePickerCancelButtonLabel: "Cancel",
    CantValidateValidationMessage: "We couldn't verify this link. Please check the link and try again.",
    ChangeFileLinkLabel: "Change file",
    ChangeImageLinkLabel: "Change image",
    ChooseFileLinkLabel: "Choose file",
    ChooseImageLinkLabel: "Choose image",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    DateFormat: "MM/DD/YYYY hh:mm A",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    DocumentLibraries: "Document libraries",
    EditedByNamePlate: "edited by ",
    EmptyFileSize: "0 bytes",
    FilePickerHeader: "File Picker",
    FileSizeField: "File Size",
    FolderAltText: "Folder",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FromLinkLinkLabel: "From a link",
    ImageAltText: ".{0} Image",
    ImageAriaLabelTemplate: ".{0} Image",
    ImageLayoutPlaceholderText: "Layout",
    ImageSizePlaceholderText: "Image size",
    ItemChildCountField: "Item Child Count",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LearnMoreLink: "Learn more.",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    LicensePlaceholderText: "License",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    LinkHeader: "From a link",
    LinkImageInstructions: "Paste a link to an image in OneDrive for Business or SharePoint Online",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescrition: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Loading: "Loading...",
    ModifiedByField: "Modified By",
    ModifiedField: "Date Modified",
    NameField: "Name",
    No: "No",
    ProvidedValueIsInvalid: "Provided value is invalid",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    NoImageValidationMessage: "This isn't a link to a file type we support. You can only link to an image.",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    ODModifiedField: "Modified",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    ODRowArialLabelTemplate: "{0}, {1}, Modified {2}, edited by {3}, {4}, {5}",
    OneDriveConfirmDialogBody: "This item is from your OneDrive site. Files and folders in OneDrive are private unless you share them. Have you shared this file with your site members so they can ccess it?",
    OneDriveConfirmDialogTitle: "Just checking...",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    OneDriveRootFolderName: "Files",
    OpenButtonLabel: "Open",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    PoweredByBing: "Powered by Bing",
    RecentDocumentsHeader: "Recent documents",
    RecentImagesHeader: "Recent images",
    RecentLinkLabel: "Recent",
    SearchBoxPlaceholder: "Web search",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    Selected: "selected",
    SharingField: "Sharing",
    SharingPrivate: "Private",
    SharingShared: "Shared",
    SiteLinkLabel: "Site",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    SizeUnit: [
     "bytes",
     "KB",
     "MB",
     "GB",
     "TB",
     "PB",
     "EB",
     "ZB",
     "YB"
    ],
    SorryWebSearch: "Sorry, this function isn't implemented in this sample, because it would require a Bing API key.",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    UploadFileHeader: "Upload file",
    UploadImageHeader: "Upload image",
    UploadLinkLabel: "Upload",
    WebSearchLinkLabel: "Web search",
    Yes: "Yes"
  };
});
