declare var define: any;

define([], () => {
  return {
    'SiteBreadcrumbLabel': 'Brödsmulemeny',

    'ListViewGroupEmptyLabel': 'Tom',

    'WebPartTitlePlaceholder': 'Webbdelstitel',
    'WebPartTitleLabel': 'Ange titel',

    "DateTime": {
      "L_RelativeDateTime_AFewSecondsFuture": "Om några sekunder",
      "L_RelativeDateTime_AFewSeconds": "För några sekunder sedan",
      "L_RelativeDateTime_AboutAMinuteFuture": "Om ungefär en minut",
      "L_RelativeDateTime_AboutAMinute": "För ungefär en minut sedan",
      "L_RelativeDateTime_XMinutesFuture": "Om {0} minut||Om {0} minuter",
      "L_RelativeDateTime_XMinutes": "För {0} minut sedan||För {0} minuter sedan",
      "L_RelativeDateTime_XMinutesFutureIntervals": "1||2-",
      "L_RelativeDateTime_XMinutesIntervals": "1||2-",
      "L_RelativeDateTime_AboutAnHourFuture": "Om ungefär en timme",
      "L_RelativeDateTime_AboutAnHour": "För ungefär en timme sedan",
      "L_RelativeDateTime_Tomorrow": "Imorgon",
      "L_RelativeDateTime_Yesterday": "Igår",
      "L_RelativeDateTime_TomorrowAndTime": "Imorgon vid {0}",
      "L_RelativeDateTime_YesterdayAndTime": "Igår vid {0}",
      "L_RelativeDateTime_XHoursFuture": "Om {0} timme||Om {0} timmar",
      "L_RelativeDateTime_XHours": "För {0} timme sedan||För {0} timmar sedan",
      "L_RelativeDateTime_XHoursFutureIntervals": "1||2-",
      "L_RelativeDateTime_XHoursIntervals": "1||2-",
      "L_RelativeDateTime_DayAndTime": "{0} at {1}",
      "L_RelativeDateTime_XDaysFuture": "Om {0} dag||Om {0} dagar",
      "L_RelativeDateTime_XDays": "För {0} dag sedan||För {0} dagar sedan",
      "L_RelativeDateTime_XDaysFutureIntervals": "1||2-",
      "L_RelativeDateTime_XDaysIntervals": "1||2-",
      "L_RelativeDateTime_Today": "Idag"
    },
    "SendEmailTo": "Skicka epost till {0}",
    "StartChatWith": "Börja en chat med {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Uppdatera din profil",

    "TaxonomyPickerNoTerms": "Termuppsättningen innehåller inga termer",
    "TaxonomyPickerExpandTitle": "Expandera termuppsättningen",
    "TaxonomyPickerMenuTermSet": "Meny för termuppsättning",
    "TaxonomyPickerInLabel": "I",
    "TaxonomyPickerTermSetLabel": "Termuppsättning",

    peoplePickerComponentTooltipMessage: "Personväljare",
    peoplePickerComponentErrorMessage: "Obligatoriskt fält",
    peoplePickerSuggestionsHeaderText: 'Föreslagna personer',
    peoplePickerLoadingText: 'Laddar',
    PeoplePickerSearchText: 'Hämtar användare',
    PeoplePickerGroupNotFound: "Gruppen kunde inte hittas.",

    genericNoResultsFoundText: 'Inga sökträffar',

    ListItemPickerSelectValue: 'Ange ett värde',
    ListItemAttachmentsActionDeleteIconTitle: 'Ta bort',
    ListItemAttachmentsactionDeleteTitle: 'Ta bort',
    ListItemAttachmentsfileDeletedMsg: 'Filen {0} raderades',
    ListItemAttachmentsfileDeleteError: 'Fel vid radering av fil: {0}, orsak {1}',
    ListItemAttachmentserrorLoadAttachments: 'Fel vid laddning av bilaga, orsak: {0}',
    ListItemAttachmentsconfirmDelete: 'Vill du verkligen flytta bilagan {0} till papperskorgen?',
    ListItemAttachmentsdialogTitle: 'Bilaga',
    ListItemAttachmentsdialogOKbuttonLabel: 'OK',
    ListItemAttachmentsdialogCancelButtonLabel: 'Avbryt',
    ListItemAttachmentsdialogOKbuttonLabelOnDelete: 'Ta bort',
    ListItemAttachmentsuploadAttachmentDialogTitle: 'Lägg till bilaga',
    ListItemAttachmentsuploadAttachmentButtonLabel: 'Lägg till bilaga',
    ListItemAttachmentsuploadAttachmentErrorMsg: 'Filen {0} kunde inte bifogas, orsak: {1}',
    ListItemAttachmentsCommandBarAddAttachmentLabel: 'Lägg till bilaga',
    ListItemAttachmentsloadingMessage: 'Laddar upp filen...',
    ListItemAttachmentslPlaceHolderIconText: 'Bilaga',
    ListItemAttachmentslPlaceHolderDescription: 'Lägg till en bilaga',
    ListItemAttachmentslPlaceHolderButtonLabel: 'Lägg till',

    mapsErrorMessage: 'Ett fel uppstod vid laddning av kartan',
    mapsLoadingText: 'Laddar',
    mapsSearchButtonText: 'Sök',
    mapsTitlePrefix: 'Karta över',

    ListViewFilterLabel: "Filtrera listan",

    HeaderNormalText: "Normal text",
    HeaderH2: "Rubrik 1",
    HeaderH3: "Rubrik 2",
    HeaderH4: "Rubrik 3",
    HeaderBlockQuote: "Pull quote",
    AlignLeft: "Vänsterjustera",
    AlignCenter: "Centrera",
    AlignRight: "Högerjustera",
    AlignJustify: "Justify",
    ListBullet: "Punktlista",
    ListNumbered: "Numrerad lista",
    StyleTitle: "Style",
    BoldTitle: "Fet (Ctrl+B)",
    ItalicTitle: "Kursiv (Ctrl+I)",
    UnderlineTitle: "Understruken (Ctrl+U)",
    AlignTitle: "Justera",
    ListTitle: "Lista",
    LinkTitle: "Hyperlänk",
    MoreTitle: "Mer",
    FormattingPaneTitle: "Textformatering",
    CloseButton: "Stäng",
    InsertLinkTitle: "Infoga länk",
    AddressFieldLabel: "Adress",
    TextToDisplayLabel: "Visningstext",
    SaveButtonLabel: "Spara",
    CancelButtonLabel: "Avbryt",
    RemoveLinkLabel: "Ta bort länk",
    ParagraphSectionTitle: "Stycke",
    HyperlinkSectionTitle: "Hyperlänk",
    UndoTitle: "Ångra (Ctrl+Z)",
    RedoTitle: "Redo (Ctrl+Y)",
    ClearFormattingTitle: "Rensa all formatering",
    FontStyleTitle: "Font",
    FontSizeTitle: "Fontstorlek ",
    StrikethroughTitle: "Genomstruken",
    SuperscriptTitle: "Upphöjt",
    SubscriptTitle: "Nedsänkt",
    FontColorLabel: "Textfärg",
    AutomaticFontColor: "Automatisk",
    HighlightColorLabel: "Framhävd färg",
    NoColorHighlightColor: "Ingen färg",
    IncreaseIndentTitle: "Öka indentering",
    DecreaseIndentTitle: "Minska indentering",
    ThemeColorsGroupName: "Temafärger",
    HighlightColorsGroupName: "Framhävda färger",
    StandardColorsGroupName: "Standardfärger",
    ThemeColorDarker: "Mörkare tema",
    ThemeColorDark: "Mörkt tema",
    ThemeColorDarkAlt: "Mörkt alternativt tema",
    ThemeColorPrimary: "Primärt tema",
    ThemeColorSecondary: "Andrahandstema",
    ThemeColorTertiary: "Neutralt tredjeval",
    ThemeColorNeutralSecondary: "Neutralt andrahandsval",
    ThemeColorNeutralPrimaryAlt: "Neutralt primärt alternativ",
    ThemeColorNeutralPrimary: "Neutralt primärt",
    ThemeColorNeutralDark: "Neutralt mörkt",
    HighlightColorYellow: "Gul",
    HighlightColorGreen: "Grön",
    HighlightColorAqua: "Vatten",
    HighlightColorMagenta: "Magenta",
    HighlightColorBlue: "Blå",
    HighlightColorRed: "Röd",
    HighlightColorDarkblue: "Mörkblå",
    HighlightColorTeal: "Beige",
    HighlightColorDarkgreen: "Mörkgrön",
    HighlightColorPurple: "Lila",
    HighlightColorMaroon: "Brun",
    HighlightColorGold: "Guld",
    HighlightColorDarkgrey: "Mörkgrå",
    HighlightColorGrey: "Grå",
    HighlightColorBlack: "Svart",
    StandardColorDarkred:"Mörkröd",
    StandardColorRed:"Röd",
    StandardColorOrange:"Orange",
    StandardColorYellow:"Gul",
    StandardColorLightgreen:"Ljusgrön",
    StandardColorGreen:"Grönn",
    StandardColorLightblue:"Ljusblå",
    StandardColorBlue:"Blå",
    StandardColorDarkblue:"Mörkblå",
    StandardColorPurple:"Lila",

    DatePickerMonthLongJanuary: "Januari",
    DatePickerMonthShortJanuary: "Jan",
    DatePickerMonthLongFebruary: "Februari",
    DatePickerMonthShortFebruary: "Feb",
    DatePickerMonthLongMarch: "Mars",
    DatePickerMonthShortMarch: "Mar",
    DatePickerMonthLongApril: "April",
    DatePickerMonthShortApril: "Apr",
    DatePickerMonthLongMay: "Maj",
    DatePickerMonthShortMay: "Maj",
    DatePickerMonthLongJune: "Juni",
    DatePickerMonthShortJune: "Jun",
    DatePickerMonthLongJuly: "Juli",
    DatePickerMonthShortJuly: "Jul",
    DatePickerMonthLongAugust: "Augusti",
    DatePickerMonthShortAugust: "Aug",
    DatePickerMonthLongSeptember: "September",
    DatePickerMonthShortSeptember: "Sep",
    DatePickerMonthLongOctober: "Oktober",
    DatePickerMonthShortOctober: "Okt",
    DatePickerMonthLongNovember: "November",
    DatePickerMonthShortNovember: "Nov",
    DatePickerMonthLongDecember: "December",
    DatePickerMonthShortDecember: "Dec",
    DatePickerDayLongSunday: "Söndag",
    DatePickerDayShortSunday: "Sön",
    DatePickerDayLongMonday: "Månday",
    DatePickerDayShortMonday: "Mån",
    DatePickerDayLongTuesday: "Tisday",
    DatePickerDayShortTuesday: "Tis",
    DatePickerDayLongWednesday: "Onsday",
    DatePickerDayShortWednesday: "Ons",
    DatePickerDayLongThursday: "Torsday",
    DatePickerDayShortThursday: "Tor",
    DatePickerDayLongFriday: "Fredag",
    DatePickerDayShortFriday: "Fre",
    DatePickerDayLongSaturday: "Lörday",
    DatePickerDayShortSaturday: "Lör",
    DatePickerGoToToday: "Idag",
    DatePickerIsRequiredErrorMessage: "",
    DatePickerInvalidInputErrorMessage: "",
    DatePickerIsOutOfBoundsErrorMessage: "",
    DateTimePickerDate: "Datum",
    DateTimePickerTime: "Tid",
    DateTimePickerTimeSeparator: ":",
    DateTimePickerHourValueInvalid: "Ogiltigt timvärde"
  };
});
