declare var define: any;

define([], () => {
  return {
  CalendarControlDayOfWeekSunday: "Sunday",
  TermSertNaviagtionErrorMessage: "TermSet not found",
  TermSetNavigationNoTerms: "No terms defined",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "found",
  worldMapLoadintText: "Loading map style…",
  worldMapLocationLabel: "location",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "name",
  worldMapSearchLocations: "Search locations...",
  worldMapTitle: "World Map",
  worldMapZoomContent: "Zoom in",
  worldMapZoomIn: "Zoom in",
  "Save": "Kurtarmak",
  "Cancel": "İptal",
  "SiteBreadcrumbLabel": "Web sitesi kırıntısı",
  "ListViewGroupEmptyLabel": "Boş",
  "WebPartTitlePlaceholder": "Web parçası başlığı",
  "WebPartTitleLabel": "Başlık ekleme",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "Birkaç saniye içinde",
    "L_RelativeDateTime_AFewSeconds": "Birkaç saniye önce",
    "L_RelativeDateTime_AboutAMinuteFuture": "Bir dakika içinde",
    "L_RelativeDateTime_AboutAMinute": "Yaklaşık bir dakika önce",
    "L_RelativeDateTime_XMinutesFuture": "{0} dakikada|| {0} dakikada",
    "L_RelativeDateTime_XMinutes": "{0} dakika önce|| {0} dakika önce",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XMinutesIntervals": "1|| 2-",
    "L_RelativeDateTime_AboutAnHourFuture": "Bir saat içinde",
    "L_RelativeDateTime_AboutAnHour": "Yaklaşık bir saat önce",
    "L_RelativeDateTime_Tomorrow": "Yarın",
    "L_RelativeDateTime_Yesterday": "Dün",
    "L_RelativeDateTime_TomorrowAndTime": "Yarın {0}'da",
    "L_RelativeDateTime_YesterdayAndTime": "Dün {0}'da",
    "L_RelativeDateTime_XHoursFuture": "{0} saat içinde|| {0} saat içinde",
    "L_RelativeDateTime_XHours": "{0} saat önce|| {0} saat önce",
    "L_RelativeDateTime_XHoursFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XHoursIntervals": "1|| 2-",
    "L_RelativeDateTime_DayAndTime": "{1}'de {0}",
    "L_RelativeDateTime_XDaysFuture": "{0} gün sonra|| {0} gün sonra",
    "L_RelativeDateTime_XDays": "{0} gün önce|| {0} gün önce",
    "L_RelativeDateTime_XDaysFutureIntervals": "1|| 2-",
    "L_RelativeDateTime_XDaysIntervals": "1|| 2-",
    "L_RelativeDateTime_Today": "Bugün"
  },
  "SendEmailTo": "{0}'a e-posta gönderme",
  "StartChatWith": "{0} ile sohbet başlatın",
  "Contact": "Iletişim",
  "UpdateProfile": "Profilinizi güncelleyin",
  "TaxonomyPickerNoTerms": "Terim kümesi herhangi bir koşul içermez",
  "TaxonomyPickerExpandTitle": "Bu Terim Kümesini Genişlet",
  "TaxonomyPickerMenuTermSet": "Dönem Seti Menüsü",
  "TaxonomyPickerInLabel": "Inç",
  "TaxonomyPickerTermSetLabel": "Dönem Seti",
  "TaxonomyPickerTermsNotFound": "Bir sonraki seçili terimler terim deposunda bulunamadı: {0}",
  "TaxonomyPickerInvalidTerms": "Lütfen geçersiz terimleri düzeltin): {0}",
  "peoplePickerComponentTooltipMessage": "İnsanlar Picker",
  "peoplePickerComponentErrorMessage": "Gerekli Alan",
  "peoplePickerSuggestionsHeaderText": "Önerilen Kişiler",
  "peoplePickerLoadingText": "Yükleme",
  "PeoplePickerSearchText": "Kullanıcıları alma",
  "PeoplePickerGroupNotFound": "Grup bulunamadı.",
  "genericNoResultsFoundText": "Sonuç bulunamadı",
  "ListItemPickerSelectValue": "Değer seçin",
  "ListItemAttachmentsActionDeleteIconTitle": "Silmek",
  "ListItemAttachmentsactionDeleteTitle": "Silmek",
  "ListItemAttachmentsfileDeletedMsg": "Dosya {0} silindi",
  "ListItemAttachmentsfileDeleteError": "Silme dosyasındaki hata: {0}, neden {1}",
  "ListItemAttachmentserrorLoadAttachments": "Yük listesi madde ekinde hata, neden: {0}",
  "ListItemAttachmentsconfirmDelete": "Eki {0} site geri dönüşüm kutusuna göndermek istediğinizden emin misiniz?",
  "ListItemAttachmentsdialogTitle": "Liste Öğesi Eki",
  "ListItemAttachmentsdialogOKbuttonLabel": "Tamam",
  "ListItemAttachmentsdialogCancelButtonLabel": "İptal",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "Silmek",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "Ek Ekle",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "Ek Ekle",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "Dosya {0} eklenmez, neden: {1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "Ek Ekle",
  "ListItemAttachmentsloadingMessage": "Dosya yükleme ...",
  "ListItemAttachmentslPlaceHolderIconText": "Liste Öğesi Eki",
  "ListItemAttachmentslPlaceHolderDescription": "Lütfen Ek Ekleyin",
  "ListItemAttachmentslPlaceHolderButtonLabel": "Ekle",
  "mapsErrorMessage": "Haritayı yüklerken bir hata oluştu",
  "mapsLoadingText": "Yükleme",
  "mapsSearchButtonText": "Arama",
  "mapsTitlePrefix": "Harita",
  "ListViewFilterLabel": "Listeye filtre uygulayın",
  "HeaderNormalText": "Normal metin",
  "HeaderH2": "Başlık 2",
  "HeaderH3": "Başlık 3",
  "HeaderH4": "Başlık 4",
  "HeaderBlockQuote": "Teklif çekme",
  "AlignLeft": "Sola hizala",
  "AlignCenter": "Merkezi",
  "AlignRight": "Sağa hizala",
  "AlignJustify": "Haklı",
  "ListBullet": "Madde işaretli liste",
  "ListNumbered": "Numaralı liste",
  "StyleTitle": "Stil",
  "BoldTitle": "Kalın (Ctrl+B)",
  "ItalicTitle": "Italik (Ctrl+I)",
  "UnderlineTitle": "Altı çizili (Ctrl+U)",
  "AlignTitle": "Hizalamak",
  "ListTitle": "Liste",
  "LinkTitle": "Köprü",
  "ImageTitle": "Resim",
  "MoreTitle": "-nda daha fazla",
  "FormattingPaneTitle": "Metin biçimlendirme",
  "CloseButton": "Yakın",
  "InsertLinkTitle": "Bağlantı ekle",
  "InsertImageTitle": "Resim ekle",
  "AddressFieldLabel": "Adres",
  "TextToDisplayLabel": "Görüntülenecek metin",
  "SaveButtonLabel": "Kaydetmek",
  "CancelButtonLabel": "İptal",
  "RemoveLinkLabel": "Bağlantıyı kaldırma",
  "ParagraphSectionTitle": "Paragraf",
  "HyperlinkSectionTitle": "Köprü",
  "UndoTitle": "Geri Ala(Ctrl+Z)",
  "RedoTitle": "Yeniden Yapma (Ctrl+Y)",
  "ClearFormattingTitle": "Tüm biçimlendirmeyi temizle",
  "FontStyleTitle": "Yazı tipi stili",
  "FontSizeTitle": "Yazı tipi boyutu",
  "StrikethroughTitle": "Üstü çizili",
  "SuperscriptTitle": "Üstsimge",
  "SubscriptTitle": "Altsimge",
  "FontColorLabel": "Yazı Tipi Rengi",
  "AutomaticFontColor": "Otomatik",
  "HighlightColorLabel": "Rengi vurgulama",
  "NoColorHighlightColor": "Renk yok",
  "IncreaseIndentTitle": "Girintiyi artırın",
  "DecreaseIndentTitle": "Girintiyi azaltma",
  "ThemeColorsGroupName": "Tema renkleri",
  "HighlightColorsGroupName": "Renkleri vurgulama",
  "StandardColorsGroupName": "Standart renkler",
  "CustomColorsGroupName": "Özel Renkler",
  "ThemeColorDarker": "Tema daha koyu",
  "ThemeColorDark": "Tema karanlık",
  "ThemeColorDarkAlt": "Tema karanlık alternatif",
  "ThemeColorPrimary": "Tema birincil",
  "ThemeColorSecondary": "Tema ikincil",
  "ThemeColorTertiary": "Nötr üçüncül",
  "ThemeColorNeutralSecondary": "Nötr ikincil",
  "ThemeColorNeutralPrimaryAlt": "Nötr birincil alternatif",
  "ThemeColorNeutralPrimary": "Nötr birincil",
  "ThemeColorNeutralDark": "Nötr karanlık",
  "HighlightColorYellow": "Sarı",
  "HighlightColorGreen": "Yeşil",
  "HighlightColorAqua": "Aqua",
  "HighlightColorMagenta": "Kırmızı",
  "HighlightColorBlue": "Mavi",
  "HighlightColorRed": "Kırmızı",
  "HighlightColorDarkblue": "Lacivert",
  "HighlightColorTeal": "Çamurcun",
  "HighlightColorDarkgreen": "Koyu yeşil",
  "HighlightColorPurple": "Mor",
  "HighlightColorMaroon": "Bordo",
  "HighlightColorGold": "Altın",
  "HighlightColorDarkgrey": "Koyu gri",
  "HighlightColorGrey": "Gri",
  "HighlightColorBlack": "Siyah",
  "StandardColorDarkred": "Koyu kırmızı",
  "StandardColorRed": "Kırmızı",
  "StandardColorOrange": "Turuncu",
  "StandardColorYellow": "Sarı",
  "StandardColorLightgreen": "Açık yeşil",
  "StandardColorGreen": "Yeşil",
  "StandardColorLightblue": "Açık mavi",
  "StandardColorBlue": "Mavi",
  "StandardColorDarkblue": "Lacivert",
  "StandardColorPurple": "Mor",
  "DatePickerMonthLongJanuary": "Ocak",
  "DatePickerMonthShortJanuary": "Ocak",
  "DatePickerMonthLongFebruary": "Şubat",
  "DatePickerMonthShortFebruary": "Şubat",
  "DatePickerMonthLongMarch": "Mart",
  "DatePickerMonthShortMarch": "Mart",
  "DatePickerMonthLongApril": "Nisan",
  "DatePickerMonthShortApril": "Nisan",
  "DatePickerMonthLongMay": "Olabilir",
  "DatePickerMonthShortMay": "Olabilir",
  "DatePickerMonthLongJune": "Haziran",
  "DatePickerMonthShortJune": "Haziran",
  "DatePickerMonthLongJuly": "Temmuz",
  "DatePickerMonthShortJuly": "Temmuz",
  "DatePickerMonthLongAugust": "Ağustos",
  "DatePickerMonthShortAugust": "Ağustos",
  "DatePickerMonthLongSeptember": "Eylül",
  "DatePickerMonthShortSeptember": "Yedi",
  "DatePickerMonthLongOctober": "Ekim",
  "DatePickerMonthShortOctober": "Ekim",
  "DatePickerMonthLongNovember": "Kasım",
  "DatePickerMonthShortNovember": "Kasım",
  "DatePickerMonthLongDecember": "Aralık",
  "DatePickerMonthShortDecember": "Aralık",
  "DatePickerDayLongSunday": "Pazar",
  "DatePickerDayShortSunday": "Güneş",
  "DatePickerDayLongMonday": "Pazartesi",
  "DatePickerDayShortMonday": "Benim",
  "DatePickerDayLongTuesday": "Salı",
  "DatePickerDayShortTuesday": "Sal",
  "DatePickerDayLongWednesday": "Çarşamba",
  "DatePickerDayShortWednesday": "Çrş",
  "DatePickerDayLongThursday": "Perşembe",
  "DatePickerDayShortThursday": "Perşembe",
  "DatePickerDayLongFriday": "Cuma",
  "DatePickerDayShortFriday": "Fri",
  "DatePickerDayLongSaturday": "Cumartesi",
  "DatePickerDayShortSaturday": "Cumartesi",
  "DatePickerGoToToday": "Bugün",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "Tarih",
  "DateTimePickerTime": "Zaman",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "Yanlış saat değeri",
  "DateTimePickerMinuteValueInvalid": "Yanlış dakika değeri",
  "DateTimePickerSecondValueInvalid": "Yanlış ikinci değer",
  "DateTimePickerTextErrorMessage": "Lütfen geçerli bir tarih girin",
  "AddFileButtonLabel": "Dosya ekleme",
  "AddImageButtonLabel": "Resim ekleme",
  "AriaCellValue": "{0} sütun, {1}",
  "FilePickerCancelButtonLabel": "İptal",
  "CantValidateValidationMessage": "Bu bağlantıyı doğrulayamadık. Lütfen bağlantıyı kontrol edin ve yeniden deneyin.",
  "ChangeFileLinkLabel": "Dosyayı değiştirme",
  "ChangeImageLinkLabel": "Görüntüyü değiştirme",
  "ChooseFileLinkLabel": "Dosyayı seçin",
  "ChooseImageLinkLabel": "Resmi seçin",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "Telif hakkı da dahil olmak üzere başkalarının haklarına saygı göstermeksizin sorumlusunuz.",
  "CreativeCommonsMessage": "Bu sonuçlar Creative Commons lisansları ile etiketlenir. Uymanızı sağlamak için lisansları gözden geçirin.",
  "DateFormat": "MM/DD/YYYY hh:mm A",
  "DocumentLabelTemplate": "{0}, Belge, Değiştirilmiş {1}, {2}, Özel",
  "DocumentLibraries": "Belge kitaplıkları",
  "EditedByNamePlate": "tarafından düzenlendi ",
  "EmptyFileSize": "0 bayt",
  "FilePickerHeader": "Dosya Seçici",
  "FileSizeField": "Dosya Boyutu",
  "FolderAltText": "Klasör",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}, Klasör, Modifiye {1}, {2}, {3} öğeleri, Özel tarafından düzenlenen",
  "FromLinkLinkLabel": "Bir bağlantıdan",
  "ImageAltText": ". {0} Görüntü",
  "ImageAriaLabelTemplate": ". {0} Görüntü",
  "ImageLayoutPlaceholderText": "Düzen",
  "ImageSizePlaceholderText": "Görüntü boyutu",
  "ItemChildCountField": "Öğe Çocuk Sayısı",
  "LayoutOptionAll": "Tüm",
  "LayoutOptionSquare": "Meydanı",
  "LayoutOptionTall": "Uzun",
  "LayoutOptionWide": "Geniş",
  "LearnMoreLink": "Daha fazla bilgi edinin.",
  "LicenseOptionAll": "Tüm",
  "LicenseOptionAny": "Yalnızca Creative Commons",
  "LicensePlaceholderText": "Lisans",
  "LinkFileInstructions": "OneDrive for Business veya SharePoint Online'da bir dosyaya bağlantı yapıştır",
  "LinkHeader": "Bir bağlantıdan",
  "LinkImageInstructions": "OneDrive for Business veya SharePoint Online'daki bir resme bağlantı yapıştır",
  "ListLayoutAriaLabel": "Seçenekleri görüntüleyin. {0} {1} .",
  "ListLayoutCompact": "Kompakt görünüm",
  "ListLayoutCompactDescription": "Öğeleri ve ayrıntıları kompakt bir listede görüntüleme",
  "ListLayoutList": "Liste görünümü",
  "ListLayoutListDescrition": "Öğeleri ve ayrıntıları listede görüntüleme",
  "ListLayoutTile": "Döşeme görünümü",
  "ListLayoutTileDescription": "Öğeleri döşeme önizlemeleriyle görüntüleme",
  "ListOptionsAlt": "Seçenekleri görüntüleyin. {0} seçilir.",
  "ListOptionsTitle": "Görünüm seçenekleri menüsünü açma",
  "Loading": "Yükleme...",
  "ModifiedByField": "Tarafından Modifiye",
  "ModifiedField": "Değiştirilen Tarih",
  "NameField": "Adı",
  "No": "№",
  "ProvidedValueIsInvalid": "Sağlanan değer geçersiz",
  "NoExternalLinksValidationMessage": "Yalnızca kendi kuruluşunuzdaki dosyalara bağlantı etmeyi destekliyoruz.",
  "NoImageValidationMessage": "Bu, desteklediğimiz bir dosya türüne bağlantı değildir. Yalnızca bir resme bağlantı kurabilirsiniz.",
  "NoRecentFiles": "Son dosya yok",
  "NoRecentFilesDescription": "Sitenizden bir dosya seçmeyi deneyin veya cihazınızdan bir dosya yükleyin.",
  "NoResultsBadEnglish": "Sonuç bulunamadı. Filtre seçeneklerini değiştirmeyi deneyin",
  "ODModifiedField": "Değiştirilmiş",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}, {1}, Modifiye {2}, {3}, {4}, {5} tarafından düzenlendi",
  "OneDriveConfirmDialogBody": "Bu öğe OneDrive sitenizden dir. OneDrive'daki dosya ve klasörler siz paylaşmadığınız sürece özeldir. Bu dosyayı site üyelerinizle paylaştınız mı?",
  "OneDriveConfirmDialogTitle": "Sadece kontrol ...",
  "OneDriveEmptyFolderAlt": "Boş klasör",
  "OneDriveEmptyFolderDescription": "Dosya eklemek için OneDrive'ınıza gidin. Ayrıca, bilgisayarınız için OneDrive uygulamasını kullanarak bu klasöre dosya ekleyebilirsiniz.",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "Bu klasör boş",
  "OneDriveRootFolderName": "Dosyaları",
  "OpenButtonLabel": "Açık",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "Kuruluşunuz tarafından sağlanan resimler ve dosyalar",
  "PoweredByBing": "Bing tarafından desteklenmektedir",
  "RecentDocumentsHeader": "Son belgeler",
  "RecentImagesHeader": "Son görüntüler",
  "RecentLinkLabel": "Son",
  "SearchBoxPlaceholder": "Web arama",
  "SearchResultAlt": "{0} için görüntü sonucu.",
  "SearchResultAriaLabel": "Yeni bir sekmede resim kaynağını açmak için enter tuşuna basın.",
  "Selected": "Seçili",
  "SharingField": "Paylaşım",
  "SharingPrivate": "Özel",
  "SharingShared": "Paylaşılan",
  "SiteLinkLabel": "Site",
  "SizeOptionAll": "Tüm",
  "SizeOptionExtraLarge": "Ekstra Büyük",
  "SizeOptionLarge": "Büyük",
  "SizeOptionMedium": "Orta",
  "SizeOptionSmall": "Küçük",
  "SizeUnit": [
    "Bayt",
    "Kb",
    "Mb",
    "Gb",
    "Tb",
    "Pb",
    "Eb",
    "Örneğin",
    "Yb"
  ],
  "SorryWebSearch": "Üzgünüz, bu işlev bu örnekte uygulanmaz, çünkü bir Bing API anahtarı gerektirir.",
  "SortedAscending": "A'dan Z'ye Sıralanmış",
  "SortedDescending": "Z'yi A'ya sıraladı",
  "TypeAriaLabel": "Dosya türü için sütun işlemleri, Dosya türünde sıralamak için basın",
  "UploadFileHeader": "Dosya yükle",
  "UploadImageHeader": "Resim yükle",
  "UploadLinkLabel": "Yüklemek",
  "WebSearchLinkLabel": "Web arama",
  "StockImagesLinkLabel": "Hazır fotoğraflar",
  "StockImagesHeader": "Hazır fotoğraflar",
  "Yes": "Evet",
  "NewFolderNamePlaceholder": "Klasör adınızı girin",
  "FolderFilterBoxPlaceholder": "Klasörleri ada göre filtreleme",
  "FolderExplorerLoading": "Klasörler yükleniyor...",
  "FolderExplorerNoItems": "Bu klasörde alt klasör yok.",
  "NewFolderIncorrectSymbolsError": "Lütfen bu karakterlerin hiçbirini içermeyen bir ad girin: \" * : < > ? /  |.",
  "SomethingWentWrong": "Bir şeyler ters gitti.",
  "SelectedLabel": "Seçili",
  "SelectIcon": "Simge seç",
  "TreeViewExpandTitle": "Bu öğeyi genişlet",
  "TreeViewCollapseTitle": "Bu öğeyi daralt",
  "CollectionDataEmptyFields": "Koleksiyon verileri için alan sağlanmadı.",
  "CollectionDataEmptyValue": "Koleksiyonunuzdaki veri yok.",
  "CollectionAddRowButtonLabel": "Koleksiyona veri ekleme",
  "CollectionDeleteRowButtonLabel": "Geçerli satırı silme",
  "CollectionSaveAndAddButtonLabel": "Ekleme ve kaydetme",
  "CollectionDataItemShowErrorsLabel": "Satır hatalarını göster",
  "CollectionDataItemFieldRequiredLabel": "Alan gereklidir.",
  "CollectionDataItemMissingFields": "Alanlar koleksiyonu boş!",
  "InvalidUrlError": "Sağlanan URL geçerli değil",
  "CollectionDataSearch": "Aramak",
  "CollectionDataMinimumUsersDefaultMessage": "Minimum number of users to be selected is {0}",
  "MyTeamsLoadingMessage": "ekiplerinizi yükleme",
  "MyTeamsMessageError": "Ekiplerinizi yüklerken bir şeyler ters gitti, lütfen daha sonra deneyin veya tarayıcıyı yenileyin",
  "MyTeamsNoTeamsMessage": "Hiç takımın yok.",
  "MyTeamsTeamChannelPublicMessage": "Genel Kanallar",
  "MyTeamsTeamChannelTypeMessage": "Özel Kanallar",
  "TeamChannelPickerFontIconFavoriteText": "Gözde",
  "TeamChannelPickerFontIconPrivateChannelTitle": "Özel Kanal",
  "TeamChannelPickerSugestionHeaderText": "Önerilen Ekip Kanalları",
  "TeamPickerButtonRemoveTitle": "kaldırmak",
  "TeamPickernoResultsFoundText": "Takım bulunamadı",
  "TeamPickerSugestionsHeaderText": "Önerilen Takımlar",
  "TeamsChannelPickerButtonRemoveTitle": "kaldırmak",
  "TeamsChannelPickerNoresultsFoundText": "Kanal bulunamadı",
  "ViewMore": "Daha fazla görüntüle",
  "DynamicFormLoading": "Yükleme...",
  "DynamicFormPleaseWait": "Lütfen bekleyin...",
  "DynamicFormRequiredErrorMessage": "Bunu boş bırakamazsın.",
  "DynamicFormTermPanelTitle": "Terim Seç",
  "DynamicFormEnterURLPlaceholder": "URL girme",
  "DynamicFormEnterDescriptionPlaceholder": "Alternatif metin",
  "DynamicFormDialogValidationErrorTitle": "Doğrulama Hatası",
  "DynamicFormDialogValidationErrorMessage": "Doğrulama hataları var, lütfen kaydetmeden önce düzeltin.",
  "DynamicFormNumberValueMustBeGreaterThan": "Değer, {0} değerinden büyük olmalıdır",
  "DynamicFormNumberValueMustBeBetween": "Değer, {0} ile {1} arasında olmalıdır",
  "DynamicFormNumberValueMustBeLowerThan": "Değer, {0} değerinden düşük olmalıdır",
  "DynamicFormChooseFileLabel": "File",
  "DynamicFormChooseFileButtonText": "Select file",
  "DynamicFormRequiredFileMessage": "File is required.",
  "customDisplayName": "Bu konumu kullan:",
  "ListItemCommentDIalogDeleteSubText": "Bu yorumu silmek istediğinizden emin misiniz?",
  "ListItemCommentsDialogDeleteTitle": "Açıklamayı Sil'i Onayla",
  "ListItemCommentsLabel": "Yorum",
  "ListItemCommentsNoCommentsLabel": "Yorum Yok",
  "OrgAssetsLinkLabel": "Kuruluşunuz",
  "MyTeamsMessageDontHaveTeams": "You don't have any teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "Etiketlemek istediğiniz bir terim girin",
  "ModernTaxonomyPickerTreeTitleSingle": "Bir etiket seçin",
  "ModernTaxonomyPickerTreeTitleMulti": "Bir veya daha fazla etiket seçin",
  "ModernTaxonomyPickerAddTagButtonTooltip": "Etiket Ekle",
  "ModernTaxonomyPickerApplyButtonText": "Kullan",
  "ModernTaxonomyPickerCancelButtonText": "İptal",
  "ModernTaxonomyPickerLoadMoreText": "Daha fazla bilgi edinin",
  "ModernTaxonomyPickerRemoveButtonText": "Sil",
  "ModernTaxonomyPickerPanelCloseButtonText": "Kapat",
  "ModernTaxonomyPickerNoResultsFound": "Sonuç bulunamadı",
  "ModernTaxonomyPickerSuggestionInLabel": "Inç",

  "ModernAudioPlay": "Play",
  "ModernAudioPause": "Pause",
  "ModernAudioIncVol": "Increase Volume",
  "ModernAudioDecVol": "Decrease Volume",
  "ModernAudioMute": "Mute",

  "ProgressStepsIndicatorNoSteps": "No steps",

  "UploadFilesButtonLabel": "Add",
  "UpLoadFilesDeleteButtonLabel": "Delete",
  "UpLoadFilesDragDropLabel": "Drag and Drop files or select Add File button",
  "UpLoadFilesSelectAllLabel": "Select all",
  "UploadFilesUploadButtonLabel": "Upload",
};
});
