declare var define: any;

define([], () => {
  return {
  CalendarControlDayOfWeekSunday: "Sunday",
  TermSertNaviagtionErrorMessage: "未发现术语集",
  TermSetNavigationNoTerms: "没有定义术语",
  worldMapCoord: "Coord:",
  worldMapE: "° E",
  worldMapFlag: "flag",
  worldMapFoundLabel: "found",
  worldMapLoadintText: "Loading map style…",
  worldMapLocationLabel: "location",
  worldMapN: "° N",
  worldMapResetMap: "Reset map",
  worldMapSearchField: "name",
  worldMapSearchLocations: "Search locations...",
  worldMapTitle: "World Map",
  worldMapZoomContent: "Zoom in",
  worldMapZoomIn: "Zoom in",
  "Save": "保存",
  "Cancel": "取消",
  "SiteBreadcrumbLabel": "网站导航",
  "ListViewGroupEmptyLabel": "空",
  "WebPartTitlePlaceholder": "Webpart标题",
  "WebPartTitleLabel": "添加标题",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "几秒钟内",
    "L_RelativeDateTime_AFewSeconds": "几秒钟前",
    "L_RelativeDateTime_AboutAMinuteFuture": "大约一分钟后",
    "L_RelativeDateTime_AboutAMinute": "大约一分钟前",
    "L_RelativeDateTime_XMinutesFuture": "{0}分钟内",
    "L_RelativeDateTime_XMinutes": "{0}分钟前",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1*2-",
    "L_RelativeDateTime_XMinutesIntervals": "1*2-",
    "L_RelativeDateTime_AboutAnHourFuture": "大约一小时后",
    "L_RelativeDateTime_AboutAnHour": "大约一小时前",
    "L_RelativeDateTime_Tomorrow": "明天",
    "L_RelativeDateTime_Yesterday": "昨天",
    "L_RelativeDateTime_TomorrowAndTime": "明天在{0}",
    "L_RelativeDateTime_YesterdayAndTime": "昨天在{0}",
    "L_RelativeDateTime_XHoursFuture": "{0}小时内",
    "L_RelativeDateTime_XHours": "{0}小时前",
    "L_RelativeDateTime_XHoursFutureIntervals": "1*2-",
    "L_RelativeDateTime_XHoursIntervals": "1*2-",
    "L_RelativeDateTime_DayAndTime": "{1}{0}",
    "L_RelativeDateTime_XDaysFuture": "{0}天后",
    "L_RelativeDateTime_XDays": "{0}天前",
    "L_RelativeDateTime_XDaysFutureIntervals": "1*2-",
    "L_RelativeDateTime_XDaysIntervals": "1*2-",
    "L_RelativeDateTime_Today": "今天"
  },
  "SendEmailTo": "向{0}发送电子邮件",
  "StartChatWith": "开始与{0}聊天",
  "Contact": "联系",
  "UpdateProfile": "更新您的个人资料",
  "TaxonomyPickerNoTerms": "术语集不包含任何术语",
  "TaxonomyPickerExpandTitle": "展开此术语集",
  "TaxonomyPickerMenuTermSet": "术语集的菜单",
  "TaxonomyPickerInLabel": "在",
  "TaxonomyPickerTermSetLabel": "术语集",
  "TaxonomyPickerTermsNotFound": "下一个选定的术语无法在术语商店中找到：{0}",
  "TaxonomyPickerInvalidTerms": "请修复无效术语：{0}",
  "peoplePickerComponentTooltipMessage": "人员选取器",
  "peoplePickerComponentErrorMessage": "必填字段",
  "peoplePickerSuggestionsHeaderText": "建议人员",
  "peoplePickerLoadingText": "加载",
  "PeoplePickerSearchText": "正在获取用户",
  "PeoplePickerGroupNotFound": "找不到组。",
  "genericNoResultsFoundText": "未找到结果",
  "ListItemPickerSelectValue": "选择值",
  "ListItemAttachmentsActionDeleteIconTitle": "删除",
  "ListItemAttachmentsactionDeleteTitle": "删除",
  "ListItemAttachmentsfileDeletedMsg": "文件{0}已删除",
  "ListItemAttachmentsfileDeleteError": "删除文件错误：{0}，原因{1}",
  "ListItemAttachmentserrorLoadAttachments": "加载列表附件错误，原因：{0}",
  "ListItemAttachmentsconfirmDelete": "是否确实要将附件{0}发送到站点回收站？",
  "ListItemAttachmentsdialogTitle": "列表项目附件",
  "ListItemAttachmentsdialogOKbuttonLabel": "好的",
  "ListItemAttachmentsdialogCancelButtonLabel": "取消",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "删除",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "添加附件",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "添加附件",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "文件{0}未附加，原因：{1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "添加附件",
  "ListItemAttachmentsloadingMessage": "正在上传文件...",
  "ListItemAttachmentslPlaceHolderIconText": "列表项目附件",
  "ListItemAttachmentslPlaceHolderDescription": "请添加附件",
  "ListItemAttachmentslPlaceHolderButtonLabel": "添加",
  "mapsErrorMessage": "加载地图时出错",
  "mapsLoadingText": "加载",
  "mapsSearchButtonText": "搜索",
  "mapsTitlePrefix": "地图",
  "ListViewFilterLabel": "筛选列表",
  "HeaderNormalText": "普通文本",
  "HeaderH2": "标题 2",
  "HeaderH3": "标题 3",
  "HeaderH4": "标题 4",
  "HeaderBlockQuote": "引用",
  "AlignLeft": "向左对齐",
  "AlignCenter": "居中对齐",
  "AlignRight": "向右对齐",
  "AlignJustify": "文本两端对齐",
  "ListBullet": "项目符号列表",
  "ListNumbered": "编号列表",
  "StyleTitle": "样式",
  "BoldTitle": "粗体（Ctrl+B）",
  "ItalicTitle": "斜体（Ctrl_I）",
  "UnderlineTitle": "下划线 （Ctrl+U）",
  "AlignTitle": "对齐",
  "ListTitle": "列表",
  "LinkTitle": "链接",
  "ImageTitle": "图像",
  "MoreTitle": "详细",
  "FormattingPaneTitle": "文本格式",
  "CloseButton": "关闭",
  "InsertLinkTitle": "插入链接",
  "InsertImageTitle": "插入图像",
  "AddressFieldLabel": "地址",
  "TextToDisplayLabel": "要显示的文本",
  "SaveButtonLabel": "保存",
  "CancelButtonLabel": "取消",
  "RemoveLinkLabel": "删除链接",
  "ParagraphSectionTitle": "段",
  "HyperlinkSectionTitle": "链接",
  "UndoTitle": "撤消（Ctrl+Z）",
  "RedoTitle": "重做（Ctrl+Y）",
  "ClearFormattingTitle": "清除所有格式",
  "FontStyleTitle": "字体样式",
  "FontSizeTitle": "字体大小",
  "StrikethroughTitle": "下划线",
  "SuperscriptTitle": "上标",
  "SubscriptTitle": "下标",
  "FontColorLabel": "字体颜色",
  "AutomaticFontColor": "自动",
  "HighlightColorLabel": "高亮显示颜色",
  "NoColorHighlightColor": "无颜色",
  "IncreaseIndentTitle": "增加缩进",
  "DecreaseIndentTitle": "减少缩进",
  "ThemeColorsGroupName": "主题颜色",
  "HighlightColorsGroupName": "突出显示颜色",
  "StandardColorsGroupName": "标准颜色",
  "CustomColorsGroupName": "自定义颜色",
  "ThemeColorDarker": "主题较暗",
  "ThemeColorDark": "主题深色",
  "ThemeColorDarkAlt": "主题深色备用色",
  "ThemeColorPrimary": "主题主色",
  "ThemeColorSecondary": "主题次色",
  "ThemeColorTertiary": "中性第三色",
  "ThemeColorNeutralSecondary": "中性次色",
  "ThemeColorNeutralPrimaryAlt": "中性备用色",
  "ThemeColorNeutralPrimary": "中性主色",
  "ThemeColorNeutralDark": "中性暗色调",
  "HighlightColorYellow": "黄色",
  "HighlightColorGreen": "绿色",
  "HighlightColorAqua": "水",
  "HighlightColorMagenta": "品红",
  "HighlightColorBlue": "蓝色",
  "HighlightColorRed": "红",
  "HighlightColorDarkblue": "深蓝色",
  "HighlightColorTeal": "青",
  "HighlightColorDarkgreen": "深绿色",
  "HighlightColorPurple": "紫色",
  "HighlightColorMaroon": "栗色",
  "HighlightColorGold": "黄金",
  "HighlightColorDarkgrey": "深灰色",
  "HighlightColorGrey": "灰色",
  "HighlightColorBlack": "黑",
  "StandardColorDarkred": "深红色",
  "StandardColorRed": "红",
  "StandardColorOrange": "橙",
  "StandardColorYellow": "黄色",
  "StandardColorLightgreen": "浅绿色",
  "StandardColorGreen": "绿色",
  "StandardColorLightblue": "浅蓝色",
  "StandardColorBlue": "蓝色",
  "StandardColorDarkblue": "深蓝色",
  "StandardColorPurple": "紫色",
  "DatePickerMonthLongJanuary": "一月",
  "DatePickerMonthShortJanuary": "1月",
  "DatePickerMonthLongFebruary": "二月",
  "DatePickerMonthShortFebruary": "2月",
  "DatePickerMonthLongMarch": "三月",
  "DatePickerMonthShortMarch": "3月",
  "DatePickerMonthLongApril": "四月",
  "DatePickerMonthShortApril": "4月",
  "DatePickerMonthLongMay": "五月",
  "DatePickerMonthShortMay": "5月",
  "DatePickerMonthLongJune": "六月",
  "DatePickerMonthShortJune": "6月",
  "DatePickerMonthLongJuly": "七月",
  "DatePickerMonthShortJuly": "7月",
  "DatePickerMonthLongAugust": "八月",
  "DatePickerMonthShortAugust": "8月",
  "DatePickerMonthLongSeptember": "九月",
  "DatePickerMonthShortSeptember": "9月",
  "DatePickerMonthLongOctober": "十月",
  "DatePickerMonthShortOctober": "10月",
  "DatePickerMonthLongNovember": "十一月",
  "DatePickerMonthShortNovember": "11月",
  "DatePickerMonthLongDecember": "十二月",
  "DatePickerMonthShortDecember": "12月",
  "DatePickerDayLongSunday": "星期天",
  "DatePickerDayShortSunday": "周日",
  "DatePickerDayLongMonday": "星期一",
  "DatePickerDayShortMonday": "周一",
  "DatePickerDayLongTuesday": "星期二",
  "DatePickerDayShortTuesday": "周二",
  "DatePickerDayLongWednesday": "星期三",
  "DatePickerDayShortWednesday": "周三",
  "DatePickerDayLongThursday": "星期四",
  "DatePickerDayShortThursday": "周四",
  "DatePickerDayLongFriday": "星期五",
  "DatePickerDayShortFriday": "周五",
  "DatePickerDayLongSaturday": "星期六",
  "DatePickerDayShortSaturday": "周六",
  "DatePickerGoToToday": "今天",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "日期",
  "DateTimePickerTime": "时间",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "小时数值不正确",
  "DateTimePickerMinuteValueInvalid": "分钟数值不正确",
  "DateTimePickerSecondValueInvalid": "秒数值不正确",
  "DateTimePickerTextErrorMessage": "请输入有效日期",
  "AddFileButtonLabel": "添加文件",
  "AddImageButtonLabel": "添加图像",
  "AriaCellValue": "{0}列，{1}",
  "FilePickerCancelButtonLabel": "取消",
  "CantValidateValidationMessage": "无法验证此链接。请检查链接，然后重试。",
  "ChangeFileLinkLabel": "更改文件",
  "ChangeImageLinkLabel": "更改图像",
  "ChooseFileLinkLabel": "选择文件",
  "ChooseImageLinkLabel": "选择图像",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "您有责任尊重他人的权利，包括版权。",
  "CreativeCommonsMessage": "这些结果带有知识共享许可证的标签。查看许可证以确保您遵守。",
  "DateFormat": "YYYY-MM-DD hh:mm A",
  "DocumentLabelTemplate": "{0}，文档，修改{1}，由{2}编辑，私有",
  "DocumentLibraries": "文档库",
  "EditedByNamePlate": "编辑者",
  "EmptyFileSize": "0 字节",
  "FilePickerHeader": "文件选取器",
  "FileSizeField": "文件大小",
  "FolderAltText": "文件夹",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}， 文件夹， 修改{1}， 编辑{2}， {3}项目， 私有",
  "FromLinkLinkLabel": "从链接",
  "ImageAltText": ".{0}图像",
  "ImageAriaLabelTemplate": ".{0}图像",
  "ImageLayoutPlaceholderText": "布局",
  "ImageSizePlaceholderText": "图像大小",
  "ItemChildCountField": "子项计数",
  "LayoutOptionAll": "所有",
  "LayoutOptionSquare": "正方形",
  "LayoutOptionTall": "高版",
  "LayoutOptionWide": "宽版",
  "LearnMoreLink": "了解更多信息。",
  "LicenseOptionAll": "所有",
  "LicenseOptionAny": "仅限知识共享",
  "LicensePlaceholderText": "许可证",
  "LinkFileInstructions": "在OneDrive for Business或者SharePoint Online中粘贴到文件的链接",
  "LinkHeader": "从链接",
  "LinkImageInstructions": "在OneDrive for Business或者SharePoint Online中粘贴图像链接",
  "ListLayoutAriaLabel": "查看选项。{0} {1} .",
  "ListLayoutCompact": "紧凑视图",
  "ListLayoutCompactDescription": "在紧凑列表中查看项目和详细信息",
  "ListLayoutList": "列表视图",
  "ListLayoutListDescrition": "查看列表中的项目和详细信息",
  "ListLayoutTile": "平铺视图",
  "ListLayoutTileDescription": "以平铺的方式查看子项",
  "ListOptionsAlt": "查看选项。{0}选中 。",
  "ListOptionsTitle": "打开视图选项菜单",
  "Loading": "加载。。。",
  "ModifiedByField": "修改者",
  "ModifiedField": "修改日期",
  "NameField": "名字",
  "No": "不",
  "ProvidedValueIsInvalid": "提供的值无效",
  "NoExternalLinksValidationMessage": "我们仅支持链接到您自己组织中的文件。",
  "NoImageValidationMessage": "这不是指向我们支持的文件类型的链接。您只能链接到图像。",
  "NoRecentFiles": "无最近文件",
  "NoRecentFilesDescription": "请尝试从您的网站中选择文件，或从设备上传文件。",
  "NoResultsBadEnglish": "未找到结果。尝试更改筛选器选项",
  "ODModifiedField": "变更",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}，{1}，修改{2}，由{3}、{4}、{5}编辑",
  "OneDriveConfirmDialogBody": "此项目来自您的 OneDrive 站点。OneDrive 中的文件和文件夹是私有的，除非您共享它们。您是否与您的网站成员共享此文件，以便他们可以成功？",
  "OneDriveConfirmDialogTitle": "只是检查...",
  "OneDriveEmptyFolderAlt": "空文件夹",
  "OneDriveEmptyFolderDescription": "要添加文件，请转到 OneDrive。您还可以使用计算机的 OneDrive 应用将文件添加到此文件夹。",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "此文件夹为空",
  "OneDriveRootFolderName": "文件",
  "OpenButtonLabel": "打开",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "组织提供的图像和文件",
  "PoweredByBing": "由必应支持",
  "RecentDocumentsHeader": "最近文档",
  "RecentImagesHeader": "最近的图像",
  "RecentLinkLabel": "最近",
  "SearchBoxPlaceholder": "网络搜索",
  "SearchResultAlt": "{0}的图像结果。",
  "SearchResultAriaLabel": "按 ENTER 以在新选项卡中打开图像源。",
  "Selected": "选择",
  "SharingField": "共享",
  "SharingPrivate": "私人",
  "SharingShared": "共享",
  "SiteLinkLabel": "网站",
  "SizeOptionAll": "所有",
  "SizeOptionExtraLarge": "特大",
  "SizeOptionLarge": "大",
  "SizeOptionMedium": "中",
  "SizeOptionSmall": "小",
  "SizeUnit": [
    "字节",
    "KB",
    "MB",
    "GB",
    "TB",
    "PB",
    "EB",
    "ZB",
    "YB"
  ],
  "SorryWebSearch": "很抱歉，此示例中未实现此功能，因为它需要必应 API 密钥。",
  "SortedAscending": "将 A 排序到 Z",
  "SortedDescending": "将 Z 排序到 A",
  "TypeAriaLabel": "文件类型的列操作，按 以对文件类型进行排序",
  "UploadFileHeader": "上传文件",
  "UploadImageHeader": "上传图片",
  "UploadLinkLabel": "上传",
  "WebSearchLinkLabel": "网络搜索",
  "StockImagesLinkLabel": "库存图片",
  "StockImagesHeader": "库存图片",
  "Yes": "是的",
  "NewFolderNamePlaceholder": "输入文件夹名称",
  "FolderFilterBoxPlaceholder": "按名称筛选文件夹",
  "FolderExplorerLoading": "加载文件夹...",
  "FolderExplorerNoItems": "此文件夹没有任何子项。",
  "NewFolderIncorrectSymbolsError": "请输入一个不包括这些字符的名称：\"* < >？/  |.",
  "SomethingWentWrong": "出错了",
  "SelectedLabel": "所选",
  "SelectIcon": "选择图标",
  "TreeViewExpandTitle": "扩展此项目",
  "TreeViewCollapseTitle": "折叠此项目",
  "CollectionDataEmptyFields": "没有为收集数据提供字段。",
  "CollectionDataEmptyValue": "您的收藏中没有数据。",
  "CollectionAddRowButtonLabel": "将数据添加到集合中",
  "CollectionDeleteRowButtonLabel": "删除当前行",
  "CollectionSaveAndAddButtonLabel": "添加和保存",
  "CollectionDataItemShowErrorsLabel": "显示行错误",
  "CollectionDataItemFieldRequiredLabel": "需要字段。",
  "CollectionDataItemMissingFields": "字段集合是空的！",
  "InvalidUrlError": "提供的 URL 无效",
  "CollectionDataSearch": "搜索",
  "CollectionDataMinimumUsersDefaultMessage": "至少要选{0}个用户",
  "MyTeamsLoadingMessage": "加载您的团队",
  "MyTeamsMessageError": "加载团队时出了问题，请稍后尝试或刷新浏览器",
  "MyTeamsNoTeamsMessage": "你没有任何团队",
  "MyTeamsTeamChannelPublicMessage": "公共频道",
  "MyTeamsTeamChannelTypeMessage": "私人频道",
  "TeamChannelPickerFontIconFavoriteText": "喜欢",
  "TeamChannelPickerFontIconPrivateChannelTitle": "私人频道",
  "TeamChannelPickerSugestionHeaderText": "推荐的团队频道",
  "TeamPickerButtonRemoveTitle": "删除",
  "TeamPickernoResultsFoundText": "未找到团队",
  "TeamPickerSugestionsHeaderText": "推荐的团队",
  "TeamsChannelPickerButtonRemoveTitle": "删除",
  "TeamsChannelPickerNoresultsFoundText": "未找到频道",
  "ViewMore": "查看更多",
  "DynamicFormLoading": "装载。。。",
  "DynamicFormPleaseWait": "请稍候。。。",
  "DynamicFormRequiredErrorMessage": "不能为空",
  "DynamicFormTermPanelTitle": "选择期限",
  "DynamicFormEnterURLPlaceholder": "输入网址",
  "DynamicFormEnterDescriptionPlaceholder": "备选文本",
  "DynamicFormDialogValidationErrorTitle": "验证错误",
  "DynamicFormDialogValidationErrorMessage": "存在验证错误，请在保存之前修复它们。",
  "DynamicFormNumberValueMustBeGreaterThan": "值必须大于 {0}",
  "DynamicFormNumberValueMustBeBetween": "值必须介于 {0} 和 {1} 之间",
  "DynamicFormNumberValueMustBeLowerThan": "值必须小于 {0}",
  "DynamicFormChooseFileLabel": "文件",
  "DynamicFormChooseFileButtonText": "选择文件",
  "DynamicFormRequiredFileMessage": "文件是必填项",
  "customDisplayName": "使用此位置：",
  "ListItemCommentDIalogDeleteSubText": "您确定要删除此评论吗？",
  "ListItemCommentsDialogDeleteTitle": "确认删除评论",
  "ListItemCommentsLabel": "评论",
  "ListItemCommentsNoCommentsLabel": "没有评论",
  "OrgAssetsLinkLabel": "您的组织",
  "MyTeamsMessageDontHaveTeams": "你没有任何teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "输入您要标记的术语",
  "ModernTaxonomyPickerTreeTitleSingle": "选择一个标签",
  "ModernTaxonomyPickerTreeTitleMulti": "选择一个或多个标签",
  "ModernTaxonomyPickerAddTagButtonTooltip": "添加标签",
  "ModernTaxonomyPickerApplyButtonText": "使用",
  "ModernTaxonomyPickerCancelButtonText": "取消",
  "ModernTaxonomyPickerLoadMoreText": "了解更多",
  "ModernTaxonomyPickerRemoveButtonText": "删除",
  "ModernTaxonomyPickerPanelCloseButtonText": "关闭",
  "ModernTaxonomyPickerNoResultsFound": "未找到结果",
  "ModernTaxonomyPickerSuggestionInLabel": "在",

  "ModernAudioPlay": "播放",
  "ModernAudioPause": "暂停",
  "ModernAudioIncVol": "提高音量",
  "ModernAudioDecVol": "降低音量",
  "ModernAudioMute": "静音",

  "ProgressStepsIndicatorNoSteps": "没有步骤",

  "UploadFilesButtonLabel": "添加",
  "UpLoadFilesDeleteButtonLabel": "删除",
  "UpLoadFilesDragDropLabel": "拖拽文件或者选择使用文件上传按钮",
  "UpLoadFilesSelectAllLabel": "全选",
  "UploadFilesUploadButtonLabel": "上传",
};
});
