declare var define: any;

define([], () => {
  return {
 CalendarControlDayOfWeekSunday: "Sunday",
 worldMapCoord: "Coord:",
 worldMapE: "° E",
 worldMapFlag: "flag",
 worldMapFoundLabel: "found",
 worldMapLoadintText: "Loading map style…",
 worldMapLocationLabel: "location",
 worldMapN: "° N",
 worldMapResetMap: "Reset map",
 worldMapSearchField: "name",
 worldMapSearchLocations: "Search locations...",
 worldMapTitle: "World Map",
 worldMapZoomContent: "Zoom in",
 worldMapZoomIn: "Zoom in",
 "TermSertNaviagtionErrorMessage": "未發現術語集",
  "TermSetNavigationNoTerms": "沒有定義術語",
  "Save": "儲存",
  "Cancel": "取消",
  "SiteBreadcrumbLabel": "網站導覽",
  "ListViewGroupEmptyLabel": "空",
  "WebPartTitlePlaceholder": "Webpart標題",
  "WebPartTitleLabel": "新增標題",
  "DateTime": {
    "L_RelativeDateTime_AFewSecondsFuture": "幾秒鐘內",
    "L_RelativeDateTime_AFewSeconds": "幾秒鐘前",
    "L_RelativeDateTime_AboutAMinuteFuture": "大約一分鐘後",
    "L_RelativeDateTime_AboutAMinute": "大約一分鐘前",
    "L_RelativeDateTime_XMinutesFuture": "{0}分鐘內",
    "L_RelativeDateTime_XMinutes": "{0}分鐘前",
    "L_RelativeDateTime_XMinutesFutureIntervals": "1*2-",
    "L_RelativeDateTime_XMinutesIntervals": "1*2-",
    "L_RelativeDateTime_AboutAnHourFuture": "大約一小時後",
    "L_RelativeDateTime_AboutAnHour": "大約一小時前",
    "L_RelativeDateTime_Tomorrow": "明天",
    "L_RelativeDateTime_Yesterday": "昨天",
    "L_RelativeDateTime_TomorrowAndTime": "明天在{0}",
    "L_RelativeDateTime_YesterdayAndTime": "昨天在{0}",
    "L_RelativeDateTime_XHoursFuture": "{0}小時內",
    "L_RelativeDateTime_XHours": "{0}小時前",
    "L_RelativeDateTime_XHoursFutureIntervals": "1*2-",
    "L_RelativeDateTime_XHoursIntervals": "1*2-",
    "L_RelativeDateTime_DayAndTime": "{1}{0}",
    "L_RelativeDateTime_XDaysFuture": "{0}天後",
    "L_RelativeDateTime_XDays": "{0}天前",
    "L_RelativeDateTime_XDaysFutureIntervals": "1*2-",
    "L_RelativeDateTime_XDaysIntervals": "1*2-",
    "L_RelativeDateTime_Today": "今天"
  },
  "SendEmailTo": "向{0}發送電子郵件",
  "StartChatWith": "開始與{0}聊天",
  "Contact": "聯絡",
  "UpdateProfile": "更新您的個人資料",
  "TaxonomyPickerNoTerms": "術語集不包含任何術語",
  "TaxonomyPickerExpandTitle": "展開此術語集",
  "TaxonomyPickerMenuTermSet": "術語集的選單",
  "TaxonomyPickerInLabel": "在",
  "TaxonomyPickerTermSetLabel": "術語集",
  "TaxonomyPickerTermsNotFound": "下一個選定的術語無法在術語商店中找到：{0}",
  "TaxonomyPickerInvalidTerms": "請修復無效術語：{0}",
  "peoplePickerComponentTooltipMessage": "人員選取器",
  "peoplePickerComponentErrorMessage": "必填欄位",
  "peoplePickerSuggestionsHeaderText": "建議人員",
  "peoplePickerLoadingText": "載入中",
  "PeoplePickerSearchText": "正在獲取使用者",
  "PeoplePickerGroupNotFound": "找不到群組。",
  "genericNoResultsFoundText": "未找到結果",
  "ListItemPickerSelectValue": "選擇值",
  "ListItemAttachmentsActionDeleteIconTitle": "刪除",
  "ListItemAttachmentsactionDeleteTitle": "刪除",
  "ListItemAttachmentsfileDeletedMsg": "檔案{0}已刪除",
  "ListItemAttachmentsfileDeleteError": "刪除檔案錯誤：{0}，原因{1}",
  "ListItemAttachmentserrorLoadAttachments": "載入列表附件錯誤，原因：{0}",
  "ListItemAttachmentsconfirmDelete": "是否確實要將附件{0}發送到網站回收桶？",
  "ListItemAttachmentsdialogTitle": "列表項目附件",
  "ListItemAttachmentsdialogOKbuttonLabel": "好的",
  "ListItemAttachmentsdialogCancelButtonLabel": "取消",
  "ListItemAttachmentsdialogOKbuttonLabelOnDelete": "刪除",
  "ListItemAttachmentsuploadAttachmentDialogTitle": "新增附件",
  "ListItemAttachmentsuploadAttachmentButtonLabel": "新增附件",
  "ListItemAttachmentsuploadAttachmentErrorMsg": "檔案{0}未附加，原因：{1}",
  "ListItemAttachmentsCommandBarAddAttachmentLabel": "新增附件",
  "ListItemAttachmentsloadingMessage": "正在上傳檔案...",
  "ListItemAttachmentslPlaceHolderIconText": "列表項目附件",
  "ListItemAttachmentslPlaceHolderDescription": "請新增附件",
  "ListItemAttachmentslPlaceHolderButtonLabel": "新增",
  "mapsErrorMessage": "載入地圖時出錯",
  "mapsLoadingText": "載入中",
  "mapsSearchButtonText": "搜尋",
  "mapsTitlePrefix": "地圖",
  "ListViewFilterLabel": "篩選列表",
  "HeaderNormalText": "普通文字",
  "HeaderH2": "標題 2",
  "HeaderH3": "標題 3",
  "HeaderH4": "標題 4",
  "HeaderBlockQuote": "引用",
  "AlignLeft": "向左對齊",
  "AlignCenter": "置中對齊",
  "AlignRight": "向右對齊",
  "AlignJustify": "文字兩端對齊",
  "ListBullet": "項目符號列表",
  "ListNumbered": "編號列表",
  "StyleTitle": "樣式",
  "BoldTitle": "粗體（Ctrl+B）",
  "ItalicTitle": "斜體（Ctrl+I）",
  "UnderlineTitle": "底線 （Ctrl+U）",
  "AlignTitle": "對齊",
  "ListTitle": "列表",
  "LinkTitle": "連結",
  "ImageTitle": "圖像",
  "MoreTitle": "詳細",
  "FormattingPaneTitle": "文字格式",
  "CloseButton": "關閉",
  "InsertLinkTitle": "插入連結",
  "InsertImageTitle": "插入圖像",
  "AddressFieldLabel": "地址",
  "TextToDisplayLabel": "要顯示的文字",
  "SaveButtonLabel": "儲存",
  "CancelButtonLabel": "取消",
  "RemoveLinkLabel": "刪除連結",
  "ParagraphSectionTitle": "段落",
  "HyperlinkSectionTitle": "連結",
  "UndoTitle": "復原（Ctrl+Z）",
  "RedoTitle": "重做（Ctrl+Y）",
  "ClearFormattingTitle": "清除所有格式",
  "FontStyleTitle": "字型樣式",
  "FontSizeTitle": "字型大小",
  "StrikethroughTitle": "刪除線",
  "SuperscriptTitle": "上標",
  "SubscriptTitle": "下標",
  "FontColorLabel": "字型顏色",
  "AutomaticFontColor": "自動",
  "HighlightColorLabel": "醒目提示顏色",
  "NoColorHighlightColor": "無顏色",
  "IncreaseIndentTitle": "增加縮排",
  "DecreaseIndentTitle": "減少縮排",
  "ThemeColorsGroupName": "主題顏色",
  "HighlightColorsGroupName": "醒目提示顏色",
  "StandardColorsGroupName": "標準顏色",
  "CustomColorsGroupName": "自訂顏色",
  "ThemeColorDarker": "主題較暗",
  "ThemeColorDark": "主題深色",
  "ThemeColorDarkAlt": "主題深色替代色",
  "ThemeColorPrimary": "主題主色",
  "ThemeColorSecondary": "主題次色",
  "ThemeColorTertiary": "中性第三色",
  "ThemeColorNeutralSecondary": "中性次色",
  "ThemeColorNeutralPrimaryAlt": "中性替代色",
  "ThemeColorNeutralPrimary": "中性主色",
  "ThemeColorNeutralDark": "中性暗色調",
  "HighlightColorYellow": "黃色",
  "HighlightColorGreen": "綠色",
  "HighlightColorAqua": "水色",
  "HighlightColorMagenta": "洋紅",
  "HighlightColorBlue": "藍色",
  "HighlightColorRed": "紅色",
  "HighlightColorDarkblue": "深藍色",
  "HighlightColorTeal": "藍綠色",
  "HighlightColorDarkgreen": "深綠色",
  "HighlightColorPurple": "紫色",
  "HighlightColorMaroon": "栗色",
  "HighlightColorGold": "金色",
  "HighlightColorDarkgrey": "深灰色",
  "HighlightColorGrey": "灰色",
  "HighlightColorBlack": "黑色",
  "StandardColorDarkred": "深紅色",
  "StandardColorRed": "紅色",
  "StandardColorOrange": "橙色",
  "StandardColorYellow": "黃色",
  "StandardColorLightgreen": "淺綠色",
  "StandardColorGreen": "綠色",
  "StandardColorLightblue": "淺藍色",
  "StandardColorBlue": "藍色",
  "StandardColorDarkblue": "深藍色",
  "StandardColorPurple": "紫色",
  "DatePickerMonthLongJanuary": "一月",
  "DatePickerMonthShortJanuary": "1月",
  "DatePickerMonthLongFebruary": "二月",
  "DatePickerMonthShortFebruary": "2月",
  "DatePickerMonthLongMarch": "三月",
  "DatePickerMonthShortMarch": "3月",
  "DatePickerMonthLongApril": "四月",
  "DatePickerMonthShortApril": "4月",
  "DatePickerMonthLongMay": "五月",
  "DatePickerMonthShortMay": "5月",
  "DatePickerMonthLongJune": "六月",
  "DatePickerMonthShortJune": "6月",
  "DatePickerMonthLongJuly": "七月",
  "DatePickerMonthShortJuly": "7月",
  "DatePickerMonthLongAugust": "八月",
  "DatePickerMonthShortAugust": "8月",
  "DatePickerMonthLongSeptember": "九月",
  "DatePickerMonthShortSeptember": "9月",
  "DatePickerMonthLongOctober": "十月",
  "DatePickerMonthShortOctober": "10月",
  "DatePickerMonthLongNovember": "十一月",
  "DatePickerMonthShortNovember": "11月",
  "DatePickerMonthLongDecember": "十二月",
  "DatePickerMonthShortDecember": "12月",
  "DatePickerDayLongSunday": "星期日",
  "DatePickerDayShortSunday": "週日",
  "DatePickerDayLongMonday": "星期一",
  "DatePickerDayShortMonday": "週一",
  "DatePickerDayLongTuesday": "星期二",
  "DatePickerDayShortTuesday": "週二",
  "DatePickerDayLongWednesday": "星期三",
  "DatePickerDayShortWednesday": "週三",
  "DatePickerDayLongThursday": "星期四",
  "DatePickerDayShortThursday": "週四",
  "DatePickerDayLongFriday": "星期五",
  "DatePickerDayShortFriday": "週五",
  "DatePickerDayLongSaturday": "星期六",
  "DatePickerDayShortSaturday": "週六",
  "DatePickerGoToToday": "今天",
  "DatePickerIsRequiredErrorMessage": "",
  "DatePickerInvalidInputErrorMessage": "",
  "DatePickerIsOutOfBoundsErrorMessage": "",
  "DateTimePickerDate": "日期",
  "DateTimePickerTime": "時間",
  "DateTimePickerTimeSeparator": ":",
  "DateTimePickerHourValueInvalid": "小時數值不正確",
  "DateTimePickerMinuteValueInvalid": "分鐘數值不正確",
  "DateTimePickerSecondValueInvalid": "秒數值不正確",
  "DateTimePickerTextErrorMessage": "請輸入有效日期",
  "AddFileButtonLabel": "新增檔案",
  "AddImageButtonLabel": "新增圖像",
  "AriaCellValue": "{0}列，{1}",
  "FilePickerCancelButtonLabel": "取消",
  "CantValidateValidationMessage": "無法驗證此連結。請檢查連結，然後重試。",
  "ChangeFileLinkLabel": "變更檔案",
  "ChangeImageLinkLabel": "變更圖像",
  "ChooseFileLinkLabel": "選擇檔案",
  "ChooseImageLinkLabel": "選擇圖像",
  "CopyrightUrl": "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
  "CopyrightWarning": "您有責任尊重他人的權利，包括版權。",
  "CreativeCommonsMessage": "這些結果帶有知識共享許可證的標籤。查看許可證以確保您遵守。",
  "DateFormat": "YYYY-MM-DD hh:mm A",
  "DocumentLabelTemplate": "{0}，文件，修改{1}，由{2}編輯，私有",
  "DocumentLibraries": "文件庫",
  "EditedByNamePlate": "編輯者",
  "EmptyFileSize": "0 位元組",
  "FilePickerHeader": "文件選取器",
  "FileSizeField": "文件大小",
  "FolderAltText": "資料夾",
  "FolderBackPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
  "FolderFrontPlate": "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
  "FolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
  "FolderLabelTemplate": "{0}， 資料夾， 修改{1}， 編輯{2}， {3}項目， 私有",
  "FromLinkLinkLabel": "從連結",
  "ImageAltText": ".{0}圖像",
  "ImageAriaLabelTemplate": ".{0}圖像",
  "ImageLayoutPlaceholderText": "版面配置",
  "ImageSizePlaceholderText": "圖像大小",
  "ItemChildCountField": "子項計數",
  "LayoutOptionAll": "所有",
  "LayoutOptionSquare": "正方形",
  "LayoutOptionTall": "高版",
  "LayoutOptionWide": "寬版",
  "LearnMoreLink": "了解更多資訊。",
  "LicenseOptionAll": "所有",
  "LicenseOptionAny": "僅限知識共享",
  "LicensePlaceholderText": "許可證",
  "LinkFileInstructions": "在OneDrive for Business或者SharePoint Online中貼上到文件的連結",
  "LinkHeader": "從連結",
  "LinkImageInstructions": "在OneDrive for Business或者SharePoint Online中貼上圖像連結",
  "ListLayoutAriaLabel": "查看選項。{0} {1} .",
  "ListLayoutCompact": "緊湊視圖",
  "ListLayoutCompactDescription": "在緊湊列表中查看項目和詳細資訊",
  "ListLayoutList": "列表視圖",
  "ListLayoutListDescrition": "查看列表中的項目和詳細資訊",
  "ListLayoutTile": "平鋪視圖",
  "ListLayoutTileDescription": "以平鋪的方式查看子項",
  "ListOptionsAlt": "查看選項。{0}選中 。",
  "ListOptionsTitle": "打開視圖選項選單",
  "Loading": "載入中...",
  "ModifiedByField": "修改者",
  "ModifiedField": "修改日期",
  "NameField": "名字",
  "No": "否",
  "ProvidedValueIsInvalid": "提供的值無效",
  "NoExternalLinksValidationMessage": "我們僅支援連結到您自己組織中的文件。",
  "NoImageValidationMessage": "這不是指向我們支援的文件類型的連結。您只能連結到圖像。",
  "NoRecentFiles": "無最近文件",
  "NoRecentFilesDescription": "請嘗試從您的網站中選擇文件，或從設備上傳文件。",
  "NoResultsBadEnglish": "未找到結果。嘗試更改篩選器選項",
  "ODModifiedField": "變更",
  "ODPhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
  "ODRowArialLabelTemplate": "{0}，{1}，修改{2}，由{3}、{4}、{5}編輯",
  "OneDriveConfirmDialogBody": "此專案來自您的 OneDrive 網站。OneDrive 中的檔和資料夾是私有的，除非您共用它們。您是否與您的網站成員共用此檔，以便他們可以成功？",
  "OneDriveConfirmDialogTitle": "只是檢查...",
  "OneDriveEmptyFolderAlt": "空資料夾",
  "OneDriveEmptyFolderDescription": "要添加文件，請轉到 OneDrive。您還可以使用計算機的 OneDrive 應用將文件添加到此資料夾。",
  "OneDriveEmptyFolderIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
  "OneDriveEmptyFolderTitle": "此資料夾為空",
  "OneDriveRootFolderName": "文件",
  "OpenButtonLabel": "打開",
  "PhotoIconUrl": "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
  "OrgAssetsTabLabel": "組織提供的圖像和文件",
  "PoweredByBing": "由必應支持",
  "RecentDocumentsHeader": "最近文件",
  "RecentImagesHeader": "最近的圖像",
  "RecentLinkLabel": "最近",
  "SearchBoxPlaceholder": "網絡搜索",
  "SearchResultAlt": "{0}的圖像結果。",
  "SearchResultAriaLabel": "按 ENTER 以在新選項卡中打開圖像源。",
  "Selected": "選擇",
  "SharingField": "共享",
  "SharingPrivate": "私人",
  "SharingShared": "共享",
  "SiteLinkLabel": "網站",
  "SizeOptionAll": "所有",
  "SizeOptionExtraLarge": "特大",
  "SizeOptionLarge": "大",
  "SizeOptionMedium": "中",
  "SizeOptionSmall": "小",
  "SizeUnit": [
    "位元組",
    "KB",
    "MB",
    "GB",
    "TB",
    "PB",
    "EB",
    "ZB",
    "YB"
  ],
  "SorryWebSearch": "很抱歉，此示例中未實現此功能，因為它需要必應 API 密鑰。",
  "SortedAscending": "將 A 排序到 Z",
  "SortedDescending": "將 Z 排序到 A",
  "TypeAriaLabel": "文件類型的列操作，按 以對文件類型進行排序",
  "UploadFileHeader": "上傳文件",
  "UploadImageHeader": "上傳圖片",
  "UploadLinkLabel": "上傳",
  "WebSearchLinkLabel": "網絡搜索",
  "StockImagesLinkLabel": "庫存圖片",
  "StockImagesHeader": "庫存圖片",
  "Yes": "是的",
  "NewFolderNamePlaceholder": "輸入資料夾名稱",
  "FolderFilterBoxPlaceholder": "按名稱篩選資料夾",
  "FolderExplorerLoading": "載入資料夾...",
  "FolderExplorerNoItems": "此資料夾沒有任何子項。",
  "NewFolderIncorrectSymbolsError": "請輸入一個不包括這些字符的名稱：\\\"* < >？/ \n.",
  "SomethingWentWrong": "出錯了",
  "SelectedLabel": "所選",
  "SelectIcon": "選擇圖標",
  "TreeViewExpandTitle": "展開此項目",
  "TreeViewCollapseTitle": "折疊此項目",
  "CollectionDataEmptyFields": "沒有為收集數據提供字段。",
  "CollectionDataEmptyValue": "您的收藏中沒有數據。",
  "CollectionAddRowButtonLabel": "將數據添加到集合中",
  "CollectionDeleteRowButtonLabel": "刪除當前行",
  "CollectionSaveAndAddButtonLabel": "添加和保存",
  "CollectionDataItemShowErrorsLabel": "顯示行錯誤",
  "CollectionDataItemFieldRequiredLabel": "需要字段。",
  "CollectionDataItemMissingFields": "字段集合是空的！",
  "InvalidUrlError": "提供的 URL 無效",
  "CollectionDataSearch": "搜索",
  "CollectionDataMinimumUsersDefaultMessage": "至少要選{0}個用戶",
  "MyTeamsLoadingMessage": "載入您的團隊",
  "MyTeamsMessageError": "載入團隊時出了問題，請稍後嘗試或刷新瀏覽器",
  "MyTeamsNoTeamsMessage": "你沒有任何團隊",
  "MyTeamsTeamChannelPublicMessage": "公共頻道",
  "MyTeamsTeamChannelTypeMessage": "私人頻道",
  "TeamChannelPickerFontIconFavoriteText": "喜歡",
  "TeamChannelPickerFontIconPrivateChannelTitle": "私人頻道",
  "TeamChannelPickerSugestionHeaderText": "推薦的團隊頻道",
  "TeamPickerButtonRemoveTitle": "刪除",
  "TeamPickernoResultsFoundText": "未找到團隊",
  "TeamPickerSugestionsHeaderText": "推薦的團隊",
  "TeamsChannelPickerButtonRemoveTitle": "刪除",
  "TeamsChannelPickerNoresultsFoundText": "未找到頻道",
  "ViewMore": "查看更多",
  "DynamicFormLoading": "裝載中...",
  "DynamicFormPleaseWait": "請稍候...",
  "DynamicFormRequiredErrorMessage": "不能為空",
  "DynamicFormTermPanelTitle": "選擇期限",
  "DynamicFormEnterURLPlaceholder": "輸入網址",
  "DynamicFormEnterDescriptionPlaceholder": "備選文本",
  "DynamicFormDialogValidationErrorTitle": "驗證錯誤",
  "DynamicFormDialogValidationErrorMessage": "存在驗證錯誤，請在保存之前修復它們。",
  "DynamicFormNumberValueMustBeGreaterThan": "值必須大於 {0}",
  "DynamicFormNumberValueMustBeBetween": "值必須介於 {0} 和 {1} 之間",
  "DynamicFormNumberValueMustBeLowerThan": "值必須小於 {0}",
  "DynamicFormChooseFileLabel": "文件",
  "DynamicFormChooseFileButtonText": "選擇文件",
  "DynamicFormRequiredFileMessage": "文件是必填項",
  "customDisplayName": "使用此位置：",
  "ListItemCommentDIalogDeleteSubText": "您確定要刪除此評論嗎？",
  "ListItemCommentsDialogDeleteTitle": "確認刪除評論",
  "ListItemCommentsLabel": "評論",
  "ListItemCommentsNoCommentsLabel": "沒有評論",
  "OrgAssetsLinkLabel": "您的組織",
  "MyTeamsMessageDontHaveTeams": "你沒有任何teams",
  "ModernTaxonomyPickerDefaultPlaceHolder": "輸入您要標記的術語",
  "ModernTaxonomyPickerTreeTitleSingle": "選擇一個標籤",
  "ModernTaxonomyPickerTreeTitleMulti": "選擇一個或多個標籤",
  "ModernTaxonomyPickerAddTagButtonTooltip": "添加標籤",
  "ModernTaxonomyPickerApplyButtonText": "使用",
  "ModernTaxonomyPickerCancelButtonText": "取消",
  "ModernTaxonomyPickerLoadMoreText": "了解更多",
  "ModernTaxonomyPickerRemoveButtonText": "刪除",
  "ModernTaxonomyPickerPanelCloseButtonText": "關閉",
  "ModernTaxonomyPickerNoResultsFound": "未找到結果",
  "ModernTaxonomyPickerSuggestionInLabel": "在",

  "ModernAudioPlay": "播放",
  "ModernAudioPause": "暫停",
  "ModernAudioIncVol": "提高音量",
  "ModernAudioDecVol": "降低音量",
  "ModernAudioMute": "靜音",

  "ProgressStepsIndicatorNoSteps": "沒有步驟",

  "UploadFilesButtonLabel": "添加",
  "UpLoadFilesDeleteButtonLabel": "刪除",
  "UpLoadFilesDragDropLabel": "拖拽文件或者選擇使用文件上傳按鈕",
  "UpLoadFilesSelectAllLabel": "全選",
  "UploadFilesUploadButtonLabel": "上傳"
};
});
