import { ImageSize } from "../../../FileTypeIcon";
import { IProgressAction } from "../../../Progress";
import { IFilePickerResult } from "../../../FilePicker";
import { ITag } from "office-ui-fabric-react";
import { ITermInfo, ITermSetInfo, ITermStoreInfo } from "@pnp/sp/taxonomy";

export interface IControlsTestState {
  imgSize: ImageSize;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  items: any[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  initialValues: any[];
  iFrameDialogOpened?: boolean;
  iFramePanelOpened?: boolean;
  authorEmails: string[];
  selectedList: string;
  progressActions: IProgressAction[];
  currentProgressActionIndex?: number;
  dateTimeValue: Date;
  richTextValue: string;
  currentCarouselElement: JSX.Element;
  canMovePrev: boolean;
  canMoveNext: boolean;
  comboBoxListItemPickerListId: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  comboBoxListItemPickerIds: any[];
  filePickerResult?: IFilePickerResult[];
  treeViewSelectedKeys?: string[];
  showAnimatedDialog?: boolean;
  showCustomisedAnimatedDialog?: boolean;
  showSuccessDialog?: boolean;
  showErrorDialog?: boolean;
  selectedTeam: ITag[];
  selectedTeamChannels: ITag[];
  filePickerDefaultFolderAbsolutePath?: string;
  errorMessage?: string;
  termPanelIsOpen?: boolean;
  actionTermId?: string;
  clickedActionTerm?: ITermInfo;
  selectedFilters?: string[];
  termStoreInfo: ITermStoreInfo;
  termSetInfo: ITermSetInfo;
  testTerms: ITermInfo[];

  isWebPartTitleDivVisible: boolean;
  isDynamicFormDivVisible: boolean;
  isTeamsDivVisible: boolean;
  isAccessibleAccordionDivVisible: boolean;
  isTaxonomyPickerDivVisible: boolean;
  isDateTimePickerDivVisible: boolean;
  isRichTextDivVisible: boolean;
  isPlaceholderDivVisible: boolean;
  isPeoplePickerDivVisible: boolean;
  isDragDropFilesDivVisible: boolean;
  isListViewDivVisible: boolean;
  isChartControlDivVisible: boolean;
  isMapDivVisible: boolean;
  isModernAudioDivVisible: boolean;
  isFileTypeIconDivVisible: boolean;
  isSecurityTrimmedControlDivVisible: boolean;
  isSitePickerDivVisible: boolean;
  isListPickerDivVisible: boolean;
  isListItemCommentsDivVisible: boolean;
  isFieldPickerDivVisible: boolean;
  isIconPickerDivVisible: boolean;
  isComboBoxListItemPickerDivVisible: boolean;
  isIFrameDialogDivVisible: boolean;
  isIFramePanelDivVisible: boolean;
  isFolderPickerDivVisible: boolean;
  isCarouselDivVisible: boolean;
  isSiteBreadcrumbDivVisible: boolean;
  isFilePickerDivVisible: boolean;
  isProgressDivVisible: boolean;
  isGridLayoutDivVisible: boolean;
  isFolderExplorerDivVisible: boolean;
  isTreeViewDivVisible: boolean;
  isPaginationDivVisible: boolean;
  isFieldCollectionDataDivVisible: boolean;
  isDashboardDivVisible: boolean;
  isToolbarDivVisible: boolean;
  isAnimatedDialogDivVisible: boolean;
  isLocationPickerDivVisible: boolean;
  isModernTaxonomyPickerDivVisible: boolean;
  isAdaptiveCardHostDivVisible: boolean;
  isVariantThemeProviderDivVisible: boolean;
  isEnhancedThemeProviderDivVisible: boolean;
  isAdaptiveCardDesignerHostDivVisible: boolean;
  isTaxonomyTreeDivVisible: boolean;
  isTestControlDivVisible: boolean;
  isUploadFilesDivVisible: boolean;
  toggleAll: boolean;
  showAllFilters: boolean;
  isViewPickerDivVisible: boolean;
}
