require("./FileBrowser.module.css");
var styles = {
    filePicker: 'filePicker_f1a66f2f',
    tabsContainer: 'tabsContainer_f1a66f2f',
    tabContainer: 'tabContainer_f1a66f2f',
    nav: 'nav_f1a66f2f',
    tabHeaderContainer: 'tabHeaderContainer_f1a66f2f',
    breadcrumbNav: 'breadcrumbNav_f1a66f2f',
    breadcrumbNavItem: 'breadcrumbNavItem_f1a66f2f',
    tab: 'tab_f1a66f2f',
    tabOffset: 'tabOffset_f1a66f2f',
    tabFiles: 'tabFiles_f1a66f2f',
    scrollablePaneWrapper: 'scrollablePaneWrapper_f1a66f2f',
    actionButtonsContainer: 'actionButtonsContainer_f1a66f2f',
    actionButtons: 'actionButtons_f1a66f2f',
    actionButton: 'actionButton_f1a66f2f',
    tabHeader: 'tabHeader_f1a66f2f',
    selectedTab: 'selectedTab_f1a66f2f',
    header: 'header_f1a66f2f',
    xlg: 'xlg_f1a66f2f',
    xxlg: 'xxlg_f1a66f2f',
    xxxlg: 'xxxlg_f1a66f2f',
    xxxxlg: 'xxxxlg_f1a66f2f',
    itemPickerTopBar: 'itemPickerTopBar_f1a66f2f',
    commandBarNoChevron: 'commandBarNoChevron_f1a66f2f',
    fileItem: 'fileItem_f1a66f2f',
    folderItem: 'folderItem_f1a66f2f',
    fileTypeIcon: 'fileTypeIcon_f1a66f2f',
    fileTypeIconIcon: 'fileTypeIconIcon_f1a66f2f',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_f1a66f2f',
    iconColumnHeader: 'iconColumnHeader_f1a66f2f',
    fileRow: 'fileRow_f1a66f2f',
    folderRow: 'folderRow_f1a66f2f',
    emptyFolder: 'emptyFolder_f1a66f2f',
    emptyFolderImage: 'emptyFolderImage_f1a66f2f',
    emptyFolderImageTag: 'emptyFolderImageTag_f1a66f2f',
    emptyFolderTitle: 'emptyFolderTitle_f1a66f2f',
    emptyFolderSubText: 'emptyFolderSubText_f1a66f2f',
    emptyFolderMobile: 'emptyFolderMobile_f1a66f2f',
    emptyFolderPc: 'emptyFolderPc_f1a66f2f',
    emptyFolderIcon: 'emptyFolderIcon_f1a66f2f'
};
export default styles;
//# sourceMappingURL=FileBrowser.module.scss.js.map