require("./StockImages.module.css");
var styles = {
    filePicker: 'filePicker_9ac6d3d1',
    tabsContainer: 'tabsContainer_9ac6d3d1',
    tabContainer: 'tabContainer_9ac6d3d1',
    nav: 'nav_9ac6d3d1',
    tabHeaderContainer: 'tabHeaderContainer_9ac6d3d1',
    breadcrumbNav: 'breadcrumbNav_9ac6d3d1',
    breadcrumbNavItem: 'breadcrumbNavItem_9ac6d3d1',
    tab: 'tab_9ac6d3d1',
    tabOffset: 'tabOffset_9ac6d3d1',
    tabFiles: 'tabFiles_9ac6d3d1',
    scrollablePaneWrapper: 'scrollablePaneWrapper_9ac6d3d1',
    actionButtonsContainer: 'actionButtonsContainer_9ac6d3d1',
    actionButtons: 'actionButtons_9ac6d3d1',
    actionButton: 'actionButton_9ac6d3d1',
    tabHeader: 'tabHeader_9ac6d3d1',
    selectedTab: 'selectedTab_9ac6d3d1',
    header: 'header_9ac6d3d1',
    xlg: 'xlg_9ac6d3d1',
    xxlg: 'xxlg_9ac6d3d1',
    xxxlg: 'xxxlg_9ac6d3d1',
    xxxxlg: 'xxxxlg_9ac6d3d1',
    itemPickerTopBar: 'itemPickerTopBar_9ac6d3d1',
    commandBarNoChevron: 'commandBarNoChevron_9ac6d3d1',
    fileItem: 'fileItem_9ac6d3d1',
    folderItem: 'folderItem_9ac6d3d1',
    fileTypeIcon: 'fileTypeIcon_9ac6d3d1',
    fileTypeIconIcon: 'fileTypeIconIcon_9ac6d3d1',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_9ac6d3d1',
    iconColumnHeader: 'iconColumnHeader_9ac6d3d1',
    fileRow: 'fileRow_9ac6d3d1',
    folderRow: 'folderRow_9ac6d3d1',
    emptyFolder: 'emptyFolder_9ac6d3d1',
    emptyFolderImage: 'emptyFolderImage_9ac6d3d1',
    emptyFolderImageTag: 'emptyFolderImageTag_9ac6d3d1',
    emptyFolderTitle: 'emptyFolderTitle_9ac6d3d1',
    emptyFolderSubText: 'emptyFolderSubText_9ac6d3d1',
    emptyFolderMobile: 'emptyFolderMobile_9ac6d3d1',
    emptyFolderPc: 'emptyFolderPc_9ac6d3d1',
    emptyFolderIcon: 'emptyFolderIcon_9ac6d3d1',
    stockImagesPickerContainer: 'stockImagesPickerContainer_9ac6d3d1',
    stockImagesPicker: 'stockImagesPicker_9ac6d3d1'
};
export default styles;
//# sourceMappingURL=StockImages.module.scss.js.map