name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'

    - name: Install npm dependencies
      run: npm i

    - name: Update version number for telemetry
      run: npm run versionUpdater

    - name: Create/update the missing localization keys
      run: npm run localization

    - name: Run build
      run: npm run build

    - name: Publish release
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
